### ISSUE TITLE
Particles textures are glitched in the Nether

### ISSUE THREAD

**Issue by DeadPigman17** [OreCruncher/DynamicSurroundings#104]
DynamicSurroundings-1.11.2-3.4.5.2.jar

1.11.2 - 13.20.0.2228 (Recommended version)

All particles' textures are glitched in the nether: 
  Without Dynamic Surroundings: 
  ![2017-06-03_18 36 40](https://cloud.githubusercontent.com/assets/22800252/26755480/57c48b52-488e-11e7-8616-d30ced362b8a.png)

  With Dynamic Surroundings:
  ![2017-06-03_18 45 17](https://cloud.githubusercontent.com/assets/22800252/26755482/67dc379c-488e-11e7-9bcf-c17a1de6dcb9.png)

**Comment by OreCruncher** [comment]
Any resource packs installed?  What other mods do you have installed?

**Comment by DeadPigman17** [comment]
You're right, it's an conflict with another mod i have installed. I'll figure out what mod it's causing this conflict and I'll report it.

**Comment by OreCruncher** [comment]
OK.  If you could keep me informed as to what you find I would appreciate it.

**Comment by DeadPigman17** [comment]
My bad, it was another mod's conflict, not Dynamic Surroundings'

**Comment by OreCruncher** [comment]
OK.  Going to close the issue.  Let me know if you find any other strangeness. :)
