### ISSUE TITLE
Polar Lights Not Synchronized for Each Client (dedicated server)

### ISSUE THREAD

**Issue by kenijey** [OreCruncher/DynamicSurroundings#105]
*Mod Version:* DynamicSurroundings-1.11.2-3.4.5.2

*Forge Version:* 2312

*Description:*
this is what my friend see 
![123](https://cloud.githubusercontent.com/assets/24831406/26761468/b17a52a8-4938-11e7-979c-d596ee04b8d4.png)
and this is what i see
![2017-06-04_15 16 39](https://cloud.githubusercontent.com/assets/24831406/26761477/e3a6c676-4938-11e7-8a87-4ab6a09fd063.png)
we are playing on a dedicated server which has dynamic surroundings installed.

**Comment by kenijey** [comment]
aaand ah, i saw the polar lights after 5 mins.

**Comment by OreCruncher** [comment]
They don't sync across clients anymore.  The borealis is 100% client side.  Also they fade in/out.  Other thing to check is that both of you were standing in a polar biome.  It's possible that you could have been standing in one, and your friend next to you could have been in a beach biome.

**Comment by kenijey** [comment]
hmm :/

**Comment by OreCruncher** [comment]
Let me clarify a bit.  Though the server does not generate the aurora data, the clients do use the current Minecraft day information to set the RNG seed for the aurora.  The net effect is that all clients should see the same style of aurora because of the seed.  (It works similar to the world seed for Minecraft.)

**Comment by kenijey** [comment]
yes i understood, and i remember the changelog that tells aurora thing is free from the server now bla bla. but it would be beauty if it be synchronized with client. nvm...
