### ISSUE TITLE
3.4.5.3 wont start on 1.11 while it marked as compatible

### ISSUE THREAD

**Issue by Xottab-DUTY** [OreCruncher/DynamicSurroundings#108]
*Mod Version:*
3.4.5.3
*Forge Version:*
Forge 1.11 - 13.19.1.2199

*Description:*
https://minecraft.curseforge.com/projects/dynamic-surroundings/files/2430134
This version is marked on CurseForge as 1.11 compatible, but in reality it asks for 1.11.2 and won't start.
Added later:
Found it is not compatible since 3.4.0.0

**Comment by OreCruncher** [comment]
Hmmm....ok.  Was wondering what it was going to break.  Support for < 1.11.2 was "as is".  Do you have a log of the issue - may be an easy tweak.

**Comment by Xottab-DUTY** [comment]
Just a bunch of warnings from FML, like:
`Dangerous alternative prefix `dsurround` for name......`
And this screenshot of what is actually happen when I try to install the mod:
https://yadi.sk/i/LtetqQID3K3tos

**Comment by OreCruncher** [comment]
Pushed v3.4.5.4 that contains a fix for this.  Had to explicitly set a MC version so it would load.

**Comment by Xottab-DUTY** [comment]
Thanks!
