### ISSUE TITLE
[Enhancement] Support Minecraft 1.12

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/DynamicSurroundings#109]
Before someone decides to make an entry I thought I would. :)  It may be a bit before I get to it.  I need to do some more things with the 1.10/1.11 versions, and I think it would be a good idea for the Forge version for 1.12 to bake a bit.

**Comment by xAlicatt** [comment]
Eagerly awaiting this! :D

**Comment by OreCruncher** [comment]
Pushed 1.12-3.4.5.7 to CurseForge!
