### ISSUE TITLE
Crashed When Join to Dedicated Server

### ISSUE THREAD

**Issue by kenijey** [OreCruncher/DynamicSurroundings#114]
*Mod Version:*
3.4.5.4
*Forge Version:*
2315

*Link to crash log (if applicable):*
[crash-2017-06-20_12.43.13-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/1087718/crash-2017-06-20_12.43.13-client.txt)

*Description:*
i just tried to join my dedicated server which has DS installed too.

**Comment by kenijey** [comment]
uhm, sorry if i shouldn't install DS to the server side.

**Comment by OreCruncher** [comment]
No, this is a client side thing.  Did you adjust any other mods in the pack besides DS?

**Comment by kenijey** [comment]
uhm i dunno, but it happened 1 time.

**Comment by OreCruncher** [comment]
OK.  This is a timing issue.  I could see how it could happen sporadically.  I will be adding some defensive code for the next dot release.

**Comment by kenijey** [comment]
thanks, get luck with

**Comment by OreCruncher** [comment]
Pushed v3.4.5.5 with a fix.

**Comment by kenijey** [comment]
hey orecruncher, we are still waiting for your awesome mod for 1.12 :D how much it will take? we really miss it

**Comment by OreCruncher** [comment]
lol.  I haven't pulled in a 1.12 sandbox yet.  Plan to take a peek this weekend.

**Comment by kenijey** [comment]
ahhh we can't wait :D
