### ISSUE TITLE
Crash Index out of Bounds

### ISSUE THREAD

**Issue by Darkere** [OreCruncher/DynamicSurroundings#116]
*Mod Version:* 3.4.5.5

*Forge Version:* 13.20.0.2315

*Link to crash log (if applicable):* 
https://pastebin.com/pgUatb6J

*Description:*
Looks to me like it might be easy to find. If it's not I might have to test without 100's of mods installed.

**Comment by OreCruncher** [comment]
Yeah.  Have to hot fix this one.  Will have an update later today.

**Comment by OreCruncher** [comment]
Pushed v3.4.5.6 with a fix.
