### ISSUE TITLE
Crash with Water Particles [1.11.2]

### ISSUE THREAD

**Issue by LukaPix** [OreCruncher/DynamicSurroundings#119]
*Mod Version:* 3.4.5.5

*Forge Version:* 13.20.0.2315

*Link to crash log (if applicable):* [https://1drv.ms/u/s!An8Z2izmI8NLgpJXeX6bLEml4Rbxaw](https://1drv.ms/u/s!An8Z2izmI8NLgpJXeX6bLEml4Rbxaw
)

*Description:* Game crashes if flowing water is somewhere in my loaded Chunks

**Comment by OreCruncher** [comment]
Update to v3.4.5.6.
