### ISSUE TITLE
Screen goes white/gray in certain areas

### ISSUE THREAD

**Issue by aelfwyne** [OreCruncher/DynamicSurroundings#123]
*Mod Version:* 1.11.2-3.4.5.6

*Forge Version:* 2386

*Link to crash log (if applicable):* no crash

*Description:*

When I tested this, it was working fine. But once I'd been playing a while and was mining, there area areas that when I walk into them, the screen goes COMPLETELY white/gray. If I walk back out of the areas, graphics return. Walk back in, blank again. Areas are larger than one chunk. Rebooted both client and server, no resolution. Disabled the mod, and graphics back to normal.

Btw, I said gray/white, but once I go back to look it's more of sky blue. It's darker if I don't have night vision on but still blank.

![2017-07-05_03 50 06](https://user-images.githubusercontent.com/1447876/27856892-2eccf012-6135-11e7-8470-cecadc2c8e61.png)

**Comment by OreCruncher** [comment]
Modpack, and what biome?

**Comment by aelfwyne** [comment]
My own modpack, Craftorium Alpha. Has been uploaded here if you need to see the dependency list. Biome is BiomesOPlenty Coniferous Forest.

**Comment by OreCruncher** [comment]
I wonder if there is a biome nearby that has fog from BoP

**Comment by aelfwyne** [comment]
There's not any of the biomes (such as wasteland) near where I'm having the issues. However, I do have Optifine installed. With Optifine disabled, things work. So on the Fog issue, I turned off Fog in Optifine and everything re-appeared.

So the bug appears to be related to FOG being enabled in Optifine... Turning it off is an OK workaround but would like to see a fix of some kind as Optifine is pretty much a requirement due to how laggy modded minecraft can be without it.

**Comment by OreCruncher** [comment]
Fog handling in Minecraft is a pain.  If you have more than one mod trying to manipulate fog you can get strange things like this.  If you have OptiFine, BoP, AND Dynamic Surroundings installed at the same time you will get what you experienced.  I added a way to disable all fog processing in DS because of this issue.  Not much I can do beyond that.

**Comment by OreCruncher** [comment]
For reference [#62]

**Comment by Piccot1214** [comment]
I tested BoP, OptiFine, DS combo.
DS version 1.11.2-3.4.6.0
BoP version 1.11.2-6.2.0.2267
OptiFine version 1.11.2 HD U C3

BoP+OptiFine+DS = incorrect fog.
BoP+OptiFine = correct fog.

I turned off all fog option in DS. but incorrect. Fog correct is when I uninstall DS.

**Comment by OreCruncher** [comment]
I made some fog changes and tested them with the latest BoP and OptiFine for 1.12.2 and fog rendered fine.  I am going to mark fixed for v3.4.9.1.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.1 with fog compat changes with BoP.
