### ISSUE TITLE
[1.12] Client crash - late SoundEvent registration

### ISSUE THREAD

**Issue by kenijey** [OreCruncher/DynamicSurroundings#126]
*Mod Version:* DynamicSurroundings-1.12-3.4.5.7

*Forge Version:* 2397

*Link to crash log (if applicable):* 
[crash-2017-07-06_17.44.48-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/1128210/crash-2017-07-06_17.44.48-client.txt)

*Description:*
i was in server, and it crashed instantly. (not server, client)
and i didn't install DS to the server side, did i make correct? sorry if im not

**Comment by kenijey** [comment]
hey ah, it happens if i jump.

**Comment by kenijey** [comment]
and no, not about the server side. it crashes everytime i jump. :/

**Comment by OreCruncher** [comment]
OK.  I have to do more code rearranging.  Despite what the Forge guys say it is never an easy migration to a newer version.  They keep changing things around. :\

**Comment by kenijey** [comment]
okay no worry we are waiting :)

**Comment by OreCruncher** [comment]
What's funny is that I don't experience the problem on my system.

**Comment by kenijey** [comment]
really?

**Comment by OreCruncher** [comment]
Yep.  Try out this JAR and let me know if it fixes: https://github.com/OreCruncher/DynamicSurroundings/releases/tag/v3.4.6.0T1

**Comment by kenijey** [comment]
i will. give me a little bit time

**Comment by kenijey** [comment]
and ah, should i install DS on server side? need answer for this

**Comment by kenijey** [comment]
ahhh yes, that version works with no crash. thank you.

**Comment by OreCruncher** [comment]
Gonna leave open until I post an official build.

**Comment by OreCruncher** [comment]
Fix pushed to CurseForge.
