### ISSUE TITLE
Client Crash 1.12

### ISSUE THREAD

**Issue by sofifreak** [OreCruncher/DynamicSurroundings#128]
1.12-3.4.5.7

1.12 - 14.21.1.2400

[crash-2017-07-07_20.39.04-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/1131996/crash-2017-07-07_20.39.04-client.txt)

Crash immediately after login.

**Comment by OreCruncher** [comment]
Dupe of [#126]
