### ISSUE TITLE
[1.11.x/1.12] Mod makes snow look like rain. (Tough As Nails Incompatibility)

### ISSUE THREAD

**Issue by axeladalidez78** [OreCruncher/DynamicSurroundings#129]
Mod Version: DynamicSurroundings-1.12-3.4.5.7

Forge Version: 2404

Description: 
So, I think it has to do with tough as nails. I'm in a biome, in which is supposed to snow, not naturally, but because toughasnails has made it winter, it snows there.
But the precipitation is rain (texture and sound) but snow appears in the ground
The first one hasn't got dynamicsurroundings but the second one does.

![2017-07-11_14 54 58](https://user-images.githubusercontent.com/6802783/28069344-6e1d714c-6649-11e7-862b-d7b34b9feb3e.png)
![2017-07-11_15 00 14](https://user-images.githubusercontent.com/6802783/28069418-b0ce9aac-6649-11e7-8e5e-7037ae5a3873.png)

**Comment by OreCruncher** [comment]
Fix pushed to CurseForge.
