### ISSUE TITLE
[1.12] Spurious sound effects at high altitude

### ISSUE THREAD

**Issue by PeterN** [OreCruncher/DynamicSurroundings#130]
Mod Version: 1.12-3.4.5.7

Forge Version: 1.12-14.21.1.2406

Link to crash log (if applicable): N/A

Description: When at high altitude (~ 105+) I can hear spurious sound effects (zombies, flowing water, etc) that seem like they may come from underground.

**Comment by OreCruncher** [comment]
I can't duplicate the issue.  What modpack are you using?

**Comment by PeterN** [comment]
Sorry, worked out it's the transition from "cave" to "surface" which just behaves oddly on tall buildings.

**Comment by OreCruncher** [comment]
Do you have any type of biome modifying mods?

**Comment by PeterN** [comment]
No, I've been using only this mod. The biome in question is swamp which I suppose has lots of ambient noises.

**Comment by OreCruncher** [comment]
@PeterN I haven't been able to duplicate the problem.  As for "tall buildings" at what height are you experiencing the issue?

**Comment by OreCruncher** [comment]
Are you still having issues?  If so try the latest 1.12 build.  I made more changes to registrations and what not so it may affect.

**Comment by TheQKnight** [comment]
having the same issue in the latest 1.12 release

**Comment by OreCruncher** [comment]
Latest as in the BETA I just posted today?  Is your pack available somewhere?

**Comment by TheQKnight** [comment]
yes, the one you posted today. My modpack is the Quantumverse, but I am currently testing an unreleased version. If you want to reproduce it, I recommend downloading the "Floating castle server spawn" map and standing in the spawn area. Its really loud there.

**Comment by OreCruncher** [comment]
Can you provide a link to the map?

**Comment by OreCruncher** [comment]
@TheQKnight *Ping*  I am finishing up the next BETA and would like to get a fix in for this, assuming it is something on my end.  Still not able to repro independently.  [CreativeMD posted a fix](https://minecraft.curseforge.com/projects/ambientsounds?gameCategorySlug=mc-mods&projectID=254284) for Ambient Sounds related to sound channel config which may address the problem.

**Comment by TheQKnight** [comment]
yes, sorry for not responding. I lost the thread for a while. I fixed the issue when I disabled the ambient sounds ocean and high up sounds. Thanks

**Comment by OreCruncher** [comment]
Good to hear.  Let me know if you encounter any more weirdness.

**Comment by OreCruncher** [comment]
Closing.  If the issue crops up or persists let me know.
