### ISSUE TITLE
[Compile] Mandatory jar signatures

### ISSUE THREAD

**Issue by Ristovski** [OreCruncher/DynamicSurroundings#134]
It appears that the `jarSign` step is now mandatory when running `build` which can be a bit annoying for people who don't have a keystore setup (it fails without it).

I advise making the `jarSign` reverse-depend on `build` so you can still sign the jars but running only `build` just won't sign them.

This way, you will still be able to sign your jars when you want (`gradle jarSign`) and others who compile from source can normally build DS (`gradle build`).

_PS: I hope but am not sure if you can make `jarSign` depend on `build`._

**Comment by OreCruncher** [comment]
I will take a look.  It looks to be a straight forward tweak, but I am a real gradle noob so anything it possible. :)

**Comment by OreCruncher** [comment]
Posted JARs to CurseForge, though this really doesn't have anything to do with that. :)
