### ISSUE TITLE
Fatally Missing Blocks when client doesn't install Dynamic Surroundings

### ISSUE THREAD

**Issue by budgej** [OreCruncher/DynamicSurroundings#135]
*Mod Version:* 1.12-3.4.6.2

*Forge Version:* 2443

*Description:*  You may have intended this, but I haven't read about it anywhere.  In version 3.4.6.1, my clients could choose not to install Dynamic Surroundings and still connect to my server.  In 3.4.6.2, there appear to be new mappings which are required on the client.  Upon downgrading back to 3.4.6.1, my server listed the following mappings in its log:

https://pastebin.com/NZseM8Ak

**Comment by OreCruncher** [comment]
These are sound registrations, not blocks, so it is nothing serious.  Despite what the Forge guys say there are some pitfalls migrating from 1.11 to 1.12, specifically the sound registry.  What happens in 1.12 is that the sound registry on the server will sync with attached clients overriding whatever it may think.  In my BETA 3.4.6.1 I did not register the sound events on the server so when the sounds sync'd up all the DS specific registrations would disappear on the client.  Starting with 3.4.6.2 I did do the registration.  When you moved back to 3.4.6.1 there was sound registry information in your world save that did not match with the server's registry and what you see is the result.

Now, my question is:  you have DS installed on the server, but yet your clients could attach without?  If this was the case I would be surprised if it worked.

**Comment by budgej** [comment]
Yes, my clients can connect to the server without installing Dynamic Surroundings.  I had assumed it was an intended feature.  Since it is not, I will stay on 3.4.6.1 for now.  Thank you for the response!

**Comment by OreCruncher** [comment]
I have to check into this.  Reason is that the server will push stuff to the clients and I am surprised that the clients don't die.  Just to note I didn't do anything to the client <-> server connection in 3.4.6.2 vs. 3.4.6.1.  Only thing I could think of is the registry sync (which DS has no control over) may be doing it.

**Comment by budgej** [comment]
No problem.  There's always at least one weirdo who likes the bug you fixed.  I'll be that guy here.

https://xkcd.com/1172/

**Comment by OreCruncher** [comment]
lol

**Comment by OreCruncher** [comment]
Going to close out for now.  If you come across any other issues let me know.  Thanks!
