### ISSUE TITLE
Loud Eagle sound that happens way too often.

### ISSUE THREAD

**Issue by DrakeEldridge** [OreCruncher/DynamicSurroundings#137]
*Mod Version: DynamicSurroundings-1.11.2-3.4.6.1

*Forge Version: forge-1.11.2-13.20.1.2393-universal

*Description: There is this eagle sound, like a loud squawking. Happens way too often and too loud. I can't find the option for it in the config.

**Comment by OreCruncher** [comment]
What biome are you in?  And based on your description it can be the Crow, Eagle, or Red Tailed Hawk.  If you go to the "Individual Sound Configuration" GUI in the Forge GUI Config system you can find each of those in the list.  Click "Play" to give em a listen to see which one it is.

**Comment by DrakeEldridge** [comment]
looked through all the dsurround: files in the 'individual sound configuration' and couldn't see an eagle or red tailed hawk option.

**Comment by DrakeEldridge** [comment]
and i know its not the crow. im in just plains biome

**Comment by OreCruncher** [comment]
Look for the sound "dsurround:raptor".  Is the sound a single screech, or does it have multiple chirp like sounds?

**Comment by DrakeEldridge** [comment]
well it plays every like, 3 minutes or so, and its loud so its kinda annoying when ur trying to relax and this single screech plays. Will try the raptor sound. And maybe once every 10-15 minutes. its just one of those noises that u dont want to hear too much

**Comment by DrakeEldridge** [comment]
Ok so it is the raptor one. But there r two sounds for the raptor. Screech, and the nice chirping. The chirping one is nice, dont mind that one playing as often as it does. But the screech seems to be the one that is used way too often.

**Comment by OreCruncher** [comment]
OK - the screech is the red tailed hawk.  I can tweak the weight so it doesn't play as often as compared to the other.

**Comment by OreCruncher** [comment]
Plan - reduce the frequency of play of the red tailed hawk as compared to other raptor sound clips.  I am also adding a clip for the Red Shouldered Hawk - sounds pretty nice.  The combo should reduce what you are experiencing quite a bit assuming the gods of random favor you. :)

**Comment by DrakeEldridge** [comment]
lol well I hope they do favor me. Will test it when the next version is out.

**Comment by OreCruncher** [comment]
Pushed v3.4.7.0 to CurseForge that has an additional raptor sound and reduces the frequency of the red tailed hawk sound.
