### ISSUE TITLE
1.12 - Sound System crash and then a CTD

### ISSUE THREAD

**Issue by Seth0067** [OreCruncher/DynamicSurroundings#138]
*Mod Version:*
1.12-3.4.6.3

*Forge Version:*
14.21.1.2424

*Link to crash log (if applicable):*
https://pastebin.com/Y0xf8fQD

*Description:*
sound system crashed and attempted to restart, then a CTD happened.  (player was travelling in boat at the time)

**Comment by OreCruncher** [comment]
Pushed v3.4.7.0 to CurseForge that has additional defensive code for this situation.
