### ISSUE TITLE
[Bug?] No weather cycling/rain at all

### ISSUE THREAD

**Issue by Whiskey-Sunshine** [OreCruncher/DynamicSurroundings#147]
*Mod Version:* 1.12-3.4.7.0

*Forge Version:* forge1.12-14.21.1.2424

*Link to crash log (if applicable):* No crash involved, nothing shows in logs regarding weather or errors with DS

*Description:* Early on when I first installed the mod, the weather cycled as expected; After some time, I played around with the commands, specifically using the /ds setmin rain command to bump the minimum intensity a bit higher, as I wanted a somewhat more rainy experience. Later on, I reset the biome configurations with /ds reset, and since that point, the weather does not cycle. When the rain timer hits 0, it instantly resets the timer and the weather doesn't change at all, remaining clear at all times. Tested over 24+ hours of time. Not entirely sure what's going on, but I'm not sure of how to fix it without removing and re-adding the mod and config.

**Comment by Whiskey-Sunshine** [comment]
Y'know. I really should have looked harder at my options. I turned weather off while working on a creative building world and never changed it back. Disregard this, I feel wicked stupid.

**Comment by OreCruncher** [comment]
lol - no worries.  I would rather have false reports than not know.  Thanks!
