### ISSUE TITLE
forcing weather to always be on?

### ISSUE THREAD

**Issue by resinate** [OreCruncher/DynamicSurroundings#148]
is there set of configs to use to enable always rain/snow?

**Comment by OreCruncher** [comment]
@resinate Honestly I never thought about this.  You could try manipulating the rain configuration properties so that the inactive time is 1 (1 tick) and the active time is a really really large number.

**Comment by OreCruncher** [comment]
@resinate Have you had a chance to tweak the settings to see if you can get permanent rain?

**Comment by OreCruncher** [comment]
Pushed a BETA of v3.5 to CurseForge.  Note that the new version has a library dependency on OreLib (another library mod I made).  Make sure you read the release notes prior to upgrade.
