### ISSUE TITLE
Wearing diamond armor sounds like walking on gravel or something

### ISSUE THREAD

**Issue by Kawaxte** [OreCruncher/DynamicSurroundings#149]
*Mod Version:* 3.4.7.0

*Forge Version:* 14.21.1.2443

*Link to crash log (if applicable):*

*Description:*
When i wear diamond armor and walk or run around it sounds like i'm on gravel or something similar.

**Comment by OreCruncher** [comment]
It's actually a modification of the ice sound.  The sound is generated because armor sounds are enabled.  Wearing different types of armor will give different sounds.
