### ISSUE TITLE
ava.util.concurrent.ExecutionException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by ProsperCraft** [OreCruncher/DynamicSurroundings#153]
*Mod Version:*
DynamicSurroundings-1.12-3.4.7.1

*Forge Version:*
1.12.1 2474

*Link to crash log (if applicable):*
Client console.
https://gist.github.com/ProsperCraft/9298553c2f35608b5d29fb39077260e4

Full forge log - 
https://gist.github.com/ProsperCraft/a56c79e1546e736712b7b89ba6a330c3/raw/66a980a92781849baea19459872dba8aa19a9644/gistfile1.txt

*Description:*
CME? NPE in client log when connecting to a server with wrong versions of a couple mods.

**Comment by OreCruncher** [comment]
Pushed build to CurseForge with fixes.

**Comment by ProsperCraft** [comment]
Thank you.
