### ISSUE TITLE
Player sound effects lag slightly behind the player's position

### ISSUE THREAD

**Issue by mezz** [OreCruncher/DynamicSurroundings#154]
*Mod Version:*
1.12-3.4.7.0

*Forge Version:*
14.22.1.2478

*Description:*
When making a player sound like drawing my sword, the sound is not exactly at my position.

This is most noticeable with headphones, when you are strafing.
If I look forward, strafe right, and draw my sword, the sound comes from the left where I was just standing previously. The opposite happens if I strafe the other way. Footsteps are also affected.

Something about the sound coming from the wrong place is subtly unsettling to me, in an otherwise very nice experience with the mod. It took me a while to pinpoint what exactly felt wrong about it.

**Comment by OreCruncher** [comment]
The attenuation type for the hotbar sounds are LINEAR.  Going to change to NONE which should fix those sounds.

As for footsteps I don't experience what you are describing RE: strafing, though I don't doubt what you are experiencing.  One thing that comes to mind is that sound processing occurs once a tick, and what may be happening is that visually the player entity has moved (interpolation) but the sound plays at a location just to the left/right which gives the sense of disconnect.  I will need to contemplate the best way to address - setting attenuation to NONE may "fix" it but could also cause some other problems.

**Comment by OreCruncher** [comment]
@mezz Can you give this test build a try to see if addresses the issues you are experiencing? https://github.com/OreCruncher/DynamicSurroundings/releases/tag/v3.4.7.2T1

**Comment by mezz** [comment]
Thanks, I think it may have improved.
I notice that the sound lingers in one spot and does not follow the player. So if I am strafing, the sword sound becomes more distant over time until it finishes playing.

**Comment by OreCruncher** [comment]
That is weird.  Reason is that with the test JAR the sound would have no attenuation.  I am going to do some more fiddling.  I have some additional tricks. :)

**Comment by OreCruncher** [comment]
OK - give this one a whirl. https://github.com/OreCruncher/DynamicSurroundings/releases/tag/v3.4.7.2T2

It should fix the L/R for item switching while strafing.  How do the footsteps sound?

**Comment by mezz** [comment]
Player sounds appear to be dead center all the time now, which is much more comfortable.
Thank you!

**Comment by OreCruncher** [comment]
Pushed version to CurseForge with fixes.
