### ISSUE TITLE
Keybindings keep resetting

### ISSUE THREAD

**Issue by Ash70** [OreCruncher/DynamicSurroundings#155]
*Mod Version:*
1.12 - 3.4.7.1.

*Forge Version:*
2474

*Description:*
The keybindings (e.g. setting light level to F7) reset to default values when quitting the game and restarting it.

**Comment by OreCruncher** [comment]
That is weird since DS doesn't manage keybindings.  What about other keybindings - do they stick or change?

**Comment by Ash70** [comment]
No, other keybindings 'stick' like normal. I just tried it in a new instance with only Dynamic Surroundings, and there it also happens.
Something else I just notice;, is that the keybindings do not show up in the list (options > controls) when I am not in a world. So going to controls from the main menu does not allow me to set the keybindings, I can only do this with Esc inside a world.
I also updated to latest forge (2479) but this didn't help either.

**Comment by OreCruncher** [comment]
Post the dsurround.cfg file.  Need to take a look at the configs.

**Comment by Ash70** [comment]
[Config](https://pastebin.com/FCheX8Ke)

**Comment by OreCruncher** [comment]
Are you stuck on 1.12.1, or would it be possible for you to test out in 1.12 using 2443?

**Comment by Ash70** [comment]
np.
In that case it works as it should. I can change keys from main menu, and key settings persist.

**Comment by OreCruncher** [comment]
OK - sounds like a Forge compat issue.  Wee!

**Comment by Ash70** [comment]
Oops sorry, wrong button. Good luck finding that one :-(

**Comment by Mansarde** [comment]
@OreCruncher Thx for the fix!
Can confirm that the key-bindings can be set before loading a map now and that they don't reset after a client restart.

But it seems the *presets* keyhandler still has the old bahviour.
Just FYI.

**Comment by OreCruncher** [comment]
OK - thanks!

**Comment by OreCruncher** [comment]
Pushed version to CurseForge with fix.
