### ISSUE TITLE
[Question] Turn off biome sounds in specific biomes

### ISSUE THREAD

**Issue by Nullga** [OreCruncher/DynamicSurroundings#156]
*Mod Version:*
1.11.2-3.4.7.1
*Forge Version:*
1.11.2-13.20.1.2429

*Description:*
Hi. I'm playing Advanced Rocketry and your mod and struggling with setting configs to turn off all biome sounds while in AR's Moon biome. As default DS plays in the Moon sounds corresponding to Plains biome? not sure which one is. Birds are singing and crickets chirping all around, yeah that's weird to me if in the Moon. Anyway [here](https://pastebin.com/8M8Nn3tN) is my external config. When I test to change one of sounds at higher volumes it works immediately by executing /ds reload command so I assume "biomes" should be set correctly but I should be doing wrong in "sounds" section. I appreciate if you can advise me. Thanks.

**Comment by OreCruncher** [comment]
Try this:
```
{
	"biomes": [
		{
			"conditions": "MATCH('(?i)(.*moon.*)', biome.name)",
			"_comment": "Advanced Rocketry Moon",
			"soundReset": true,
			"sounds": [
			]
		}
}
```

This should reset the sound list for all biomes that contain the word "moon".

**Comment by Nullga** [comment]
Though I had to add ']' near the end, it works PERFECTLY! Also now I understand how soundReset works. Thanks a lot!

**Comment by OreCruncher** [comment]
Glad to help.  BTW, when you are done with the config for AdvRocketry I would be interested in folding it into the DS repository.  Providing support for the mod is on my list of things to do but time always runs short.

**Comment by Nullga** [comment]
I'm actually working on this for a server where I'm on. The server currently has two dimensions Moon and Space for now. However I will submit a config whenever I'm done a bit more detailed work related to AdvRocketry :)
