### ISSUE TITLE
Constant durr when player is damaged

### ISSUE THREAD

**Issue by Katrix-** [OreCruncher/DynamicSurroundings#16]
In the latest update sounds changed a bit. Now all I'm hearing is a constant durr whenever the player is damaged. Tested with only DynamicSurroundings.

**Comment by OreCruncher** [comment]
@Katrix Confirmed.  To suppress the heartbeat and tummy grumble you can set the hurt and hunger thresholds under "Player Effects" to 0.

**Comment by OreCruncher** [comment]
@Katrix- Build with the fix posted.  Thanks!
