### ISSUE TITLE
1.10.2 Client side on server

### ISSUE THREAD

**Issue by Tototi1** [OreCruncher/DynamicSurroundings#162]
*Mod Version:*
3.4.7.1
*Forge Version:*
12.18.3.2281

*Link to crash log (if applicable):*
I have no crash log, i have log
-[20:29:26] [Thread-25/ERROR]: Source 'ade54521-d935-4a72-937a-88903d6829b5' not found in method 'play'
[20:29:39] [Thread-25/ERROR]: Error in class 'LibraryLWJGLOpenAL'
[22:06:15] [Client thread/INFO]: Unmuting sounds
[22:06:19] [Client thread/INFO]: Muting sounds

*Description:*
I have lag in my game, every two seconds !
My sound system crash and restart all the time.

**Comment by OreCruncher** [comment]
See #152.  The crash is occuring in the sound library that Minecraft uses.  In general your chances of experiencing the problem increase with client side lag.  You can disable the restart behavior if it is too bothersome.  Side effect is that you will no longer get streaming sounds.

**Comment by OreCruncher** [comment]
Will be committing changes to make the sound engine restart stuff a thing of the past.

**Comment by OreCruncher** [comment]
Pushed v3.4.8.0 with fixes.
