### ISSUE TITLE
[suggestion] Keybind to force-restart sound engine

### ISSUE THREAD

**Issue by ParadoxBomb** [OreCruncher/DynamicSurroundings#163]
After having the sound engine get stuck looping the background cricket sounds and all other sounds be muted (for unknown reasons, will post an issue if I can reproduce it), I was wondering if there was any possibility to include a force-restart of sound engine keybind. It would be useful for those edge cases that haven't been fixed yet, and it would only affect the client it's installed on.

**Comment by OreCruncher** [comment]
Going to be committing some changes to make sound engine restart unnecessary.  When that gets posted this issue will be closed since it would no longer be needed.

**Comment by OreCruncher** [comment]
Pushed v3.4.8.0 with fixes.
