### ISSUE TITLE
Light Levels not showing on blocks

### ISSUE THREAD

**Issue by iain-davis** [OreCruncher/DynamicSurroundings#165]
*Mod Version: 1.12.2-3.4.7.2

*Forge Version: 14.21.1.2443

*Link to crash log (if applicable):*

*Description: On the server I'm playing on, I had been using the light levels for a couple of days and it was working well. But now, when I press the L key (the key I have bound to light levels) Dynamic Surroundings says that it is turning on the light levels, but the numbers don't actually appear. Sometimes, they do appear (seemingly on their own, but I may have left the setting on, even though it isn't working) later for a little while.

At first, I thought maybe I'd messed up my configuration somehow, but I created a new profile in twitch and didn't copy over any of my configuration and the problem was still occurring. Also, it appears that the problem is only on the server, I tried in single player briefly and it seems to be working there. The server owner hasn't specifically turned off the light levels feature...

My guess is something else is getting in the way but we're uncertain as to what it would be. I'm include a list of mods in the pack, on the off-chance you'll spot something relevant:

JourneyMap (by techbrew)
Chameleon (by jaquadro)
Storage Drawers (by jaquadro)
Mantle (by mDiyo)
Tinkers Construct (by mDiyo)
BiblioCraft (by JDSinclair)
Refined Storage (by raoulvdberge)
AutoRegLib (by Vazkii)
Psi (by Vazkii)
Roots (by elucent)
Astral Sorcery (by HellFirePvP)
ViesCraft - Airships! (by Viesis_Gaming)
Dynamic Surroundings (by OreCruncher)
Immersive Engineering (by BluSunrize)
Immersive Petroleum (by theFlaxbeard)
Immersive Tech (by ferroo2000)
Farseek (by delvr)
Streams (by delvr)
Akashic Tome (by Vazkii)
MalisisCore (by Ordinastie)
MalisisDoors (by Ordinastie)
MalisisBlocks (by Ordinastie)
Wearable Backpacks (by koppeh)
ZeroCore (by ZeroNoRyouki)
Extreme Reactors (by ZeroNoRyouki)
Morpheus (by Quetzi)
Gentle Harvest (by BEQOsNtDi6xRDGzqIAT7)
ArchitectureCraft - ElytraDev Version (by darkevilmac)
MrCrayfish's Furniture Mod (by Mr_Crayfish)
Just Enough Items (JEI) (by mezz)
Hwyla (by TehNut)
WanionLib (by WanionCane)
UniDict (by WanionCane)
Soartex Fanver - Vanilla (by SoartexFanver)
Persistence (by ChesterChair)
Roguelike Dungeons (by Greymerk)
IvToolkit (by Ivorforce)
Recurrent Complex (by Ivorforce)
ForgeEndertech (by EnderLanky)
Advanced Hook Launchers (by EnderLanky)
Traverse (by ProfessorProspector)
Biomes O' Plenty (by Glitchfiend)
Inventory Tweaks (by Kobata)
SanLib (by SanAndreasP)
Corail Tombstone (by Corail31)
Pam's HarvestCraft (by MatrexsVigil)

**Comment by OreCruncher** [comment]
Light levels are purely client side - no server side interactions.  And to be clear OptiFine is not involved?

**Comment by iain-davis** [comment]
I don't have OptiFine.

**Comment by OreCruncher** [comment]
I've been looking at this and haven't been able to figure out anything specific.  Only thing I can think of is that the render state was funky when my logic is executed.  This sometimes happens when multiple mods in your pack interoperate.  I will be posting a BETA in the next couple days that changes out the light level hud functions so things may just start working.

**Comment by OreCruncher** [comment]
Pushed v3.4.8.5 with changes.
