### ISSUE TITLE
1.12.2 (Error in server log)

### ISSUE THREAD

**Issue by Endmateria** [OreCruncher/DynamicSurroundings#166]
DynamicSurroundings-1.12.2-3.4.7.2.jar (latest)

Forge 1.12.2 - 14.23.0.2493 (latest)

Error log (does not crash server): https://gist.github.com/Endmateria/8f4a7fca7157fa82641dfa008f1327d1#file-fml-junk-earlystartup-log

An error shows up in the server startup log.  Removed all other mods, error still shows up.  See code line 328

**Comment by OreCruncher** [comment]
This is the same as the one reported in [#187].  Going to close this one out since the other defect has data related to the fix.  Thanks for reporting!
