### ISSUE TITLE
Sandstorm in BoP Cold Desert

### ISSUE THREAD

**Issue by ElvenChaos** [OreCruncher/DynamicSurroundings#168]
*Mod Version:* 1.12.2-3.4.7.2

*Forge Version:* 2495

*Link to crash log (if applicable):* Image Reference: https://ibb.co/cHGpow (sorry for the menu, despite taking the screenshot without it open, when I paste it menus anyway.)

*Description:* I had DynSurr, BoP, and Geographicraft installed and was messing around when this occured. In the cold desert biome from BoP, it evidently doesn't rain or snow, but instead rages with a sandstorm.

**Comment by OreCruncher** [comment]
Looking at this and the config has it set correctly.  In a BoP Cold Desert there should be desert dust, but the dust color should be white.  If you still have the client log can you post it?

**Comment by ElvenChaos** [comment]
I don't have the client log for that anymore, I had a windows-breaking problem with windows due to it's inability to handle updates properly and had to reinstall windows. I've recently been remaking the 1.12 pack I was working on, so I'll try to reproduce the issue again.

**Comment by OreCruncher** [comment]
One thing that I noticed which is what you are probably referring to.  The fog itself is a whitish color, but the dust particles themselves render as a brownish/yellow color.  It's been on my list for a while to have the actual dust particles match the dust fog color.  In fact I am working on that now.  These changes should be in the next BETA so you may want to hold off on trying to "repro" until you have that build.

**Comment by ElvenChaos** [comment]
Well I just reproduced the issue, but I think you just saved me from trying to upload it all :P. The dust particles are the same as in my earlier screenshot, and looks like regular sand particles I would expect in a regular desert. Thanks for getting back to me on this issue, it was much appreciated :D!

**Comment by OreCruncher** [comment]
Posted v3.4.8.2 with fix.
