### ISSUE TITLE
Noticing some wonkiness with rendering

### ISSUE THREAD

**Issue by Sunconure11** [OreCruncher/DynamicSurroundings#169]
*Mod Version:*

1.12.2-3.4.7.2

*Forge Version:*

14.23.0.2501

*Link to crash log (if applicable):*

*Description:*

![screenshot 2017-10-03 09 12 14](https://user-images.githubusercontent.com/5614902/31126858-12926c06-a81b-11e7-9140-4f1c318a48a7.png)
![screenshot 2017-10-03 09 13 49](https://user-images.githubusercontent.com/5614902/31126904-3657d0a4-a81b-11e7-8bdf-420f75076009.png)

Notes: Albedo is installed, not sure if that has any effect on this. Hardcore Darkness is installed too. I also have Zombie Awareness installed.

**Comment by OreCruncher** [comment]
Disable albedo and see if it disappears. :)  If it does it would be an albedo problem I think.  DS responds to lighting events from albedo so it can do the rendering.  DS doesn't do the rendering.

**Comment by Sunconure11** [comment]
I can confirm it's albedo.

**Comment by Sunconure11** [comment]
I can confirm with 100% certainty it's an albedo issue. I'd advise updating against the latest build of it. Removing Hardcore Darkness did not end the issue.

**Comment by Sunconure11** [comment]
Sorry if I'm bugging you @OreCruncher, but any news on this?

**Comment by OreCruncher** [comment]
It's an Albedo issue I would think.  DS just supplies light point information to Albedo and it does its's magic.  I am assuming that this is Elucents version of Albedo correct?

**Comment by Sunconure11** [comment]
It appears an installation with just albedo + dynamic surroundings still causes the issue to an extent.

![screenshot 2017-10-13 00 30 33](https://user-images.githubusercontent.com/5614902/31530353-dc203d7a-afad-11e7-8b68-e67675c5d9b3.png)

Forge version used is 14.23.0.2512

**Comment by WolfieWaffle** [comment]
I'm getting white squares for the splash particles on waterfalls, unsure if its related but thought I might mention.

**Comment by OreCruncher** [comment]
Yep.  Noticed the same thing.  While the client is active, disable Albedo, run  the game a little bit, and re-enable.  It usually "fixes" until it goes wonky again.

**Comment by OreCruncher** [comment]
I made a fix for the latest version of Albedo that I fixes this issue.  Should be in the next BETA.

**Comment by OreCruncher** [comment]
Posted v3.4.8.2 with fix.

**Comment by Sunconure11** [comment]
![screenshot 2018-01-15 06 59 26](https://user-images.githubusercontent.com/5614902/34941484-ecc3263e-f9c1-11e7-9689-15ea98b4185e.png)

Footsteps are fixed, but I get this when holding an item.

**Comment by OreCruncher** [comment]
Not seeing an issue.  Where should I be looking in the picture?

**Comment by Sunconure11** [comment]
![screenshot 2018-01-15 07 03 56](https://user-images.githubusercontent.com/5614902/34941567-47730f22-f9c2-11e7-86d7-b83418c45222.png)
Notice the strange, fog-like overlay on my hand? It's the same as in some of my posts.

**Comment by OreCruncher** [comment]
Ah!  OK.  Strange that I don't see it on my end.  Your modpack posted somewhere?

**Comment by Sunconure11** [comment]
So far, I'm working on an update for it, that includes Albedo, but I'll link it. Just beware, it's beefy.

https://minecraft.curseforge.com/projects/compitum-magia

**Comment by OreCruncher** [comment]
How much memory should I allocate?

**Comment by Sunconure11** [comment]
4, if not, try 6.

**Comment by OreCruncher** [comment]
lol.  Gave it 8 and it almost used all of it during init.  The pack is a beast.

**Comment by Sunconure11** [comment]
Blame The Betweenlands probably lol. I noticed memory usage increased more when I added that.

**Comment by OreCruncher** [comment]
Saw the problem and then it appeared to correct itself. :\  This is going to be a fun one.

**Comment by Sunconure11** [comment]
I noticed that too. I was in my discord channel, talking to some people, and forgot I had MC open. Then I checked, and the issue was gone.

**Comment by OreCruncher** [comment]
OK.  Did a simple thing.  I removed DS from the pack and left Albedo in.  The problem still occurred.  Removed Albedo, problem went away.  Added Albedo back, and the problem came back.  It looks like the issue is with Albedo or one of the other mods is interacting with Albedo in strange ways.

While researching I came across this: https://github.com/MinecraftForge/MinecraftForge/issues/1637.  Doesn't point a finger or recommend a fix.  Just points out that this may be a bit more difficult to narrow in on.

**Comment by Sunconure11** [comment]
Look into Blood Moon, it changes the fog color when a blood moon occurs. I'm working on a maintenance-related update, due to the beefiness of the pack, to help reduce a bit of lag, and some issues with its associated server.

Basically, think of anything that does any weird special effects. Hardcore Darkness should also be looked into.
