### ISSUE TITLE
No sound in game after 15-20 minute play

### ISSUE THREAD

**Issue by GordonHollow** [OreCruncher/DynamicSurroundings#17]
> [12:29:59] [Thread-34/ERROR]: Error in class 'CodecJOrbis'
> [12:29:59] [Thread-34/ERROR]: Unable to acquire inputstream in method 'initialize'.
> [12:29:59] [Thread-34/WARN]: ERROR MESSAGE:
> [12:29:59] [Thread-34/INFO]: minecraft:sounds/random.anvil_use.ogg
> [12:29:59] [Thread-34/WARN]: STACK TRACE:
> [12:29:59] [Thread-34/INFO]: net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68)
> [12:29:59] [Thread-34/INFO]: net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65)
> [12:29:59] [Thread-34/INFO]: net.minecraft.client.audio.SoundManager$2$1.getInputStream(SoundManager.java:496)
> [12:29:59] [Thread-34/INFO]: paulscode.sound.codecs.CodecJOrbis.initialize(CodecJOrbis.java:281)
> [12:29:59] [Thread-34/INFO]: paulscode.sound.libraries.SourceLWJGLOpenAL.play(SourceLWJGLOpenAL.java:616)
> [12:29:59] [Thread-34/INFO]: paulscode.sound.Library.play(Library.java:706)
> [12:29:59] [Thread-34/INFO]: paulscode.sound.Library.play(Library.java:675)
> [12:29:59] [Thread-34/INFO]: paulscode.sound.SoundSystem.CommandPlay(SoundSystem.java:2076)
> [12:29:59] [Thread-34/INFO]: paulscode.sound.SoundSystem.CommandQueue(SoundSystem.java:2599)
> [12:29:59] [Thread-34/INFO]: paulscode.sound.CommandThread.run(CommandThread.java:121)
> [12:29:59] [Thread-34/ERROR]: Error in class 'SourceLWJGL OpenAL'
> [12:29:59] [Thread-34/ERROR]: Audio Format null in method 'play'
> [12:29:59] [Thread-34/ERROR]: Error in class 'CodecJOrbis'
> [12:29:59] [Thread-34/ERROR]: Unable to acquire inputstream in method 'initialize'.
> [12:29:59] [Thread-34/WARN]: ERROR MESSAGE:
> [12:29:59] [Thread-34/INFO]: minecraft:sounds/random.anvil_use.ogg
> [12:29:59] [Thread-34/WARN]: STACK TRACE:
> [12:29:59] [Thread-34/INFO]: net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68)
> [12:29:59] [Thread-34/INFO]: net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65)
> [12:29:59] [Thread-34/INFO]: net.minecraft.client.audio.SoundManager$2$1.getInputStream(SoundManager.java:496)
> [12:29:59] [Thread-34/INFO]: paulscode.sound.codecs.CodecJOrbis.initialize(CodecJOrbis.java:281)
> [12:29:59] [Thread-34/INFO]: paulscode.sound.libraries.SourceLWJGLOpenAL.play(SourceLWJGLOpenAL.java:616)
> [12:29:59] [Thread-34/INFO]: paulscode.sound.Library.play(Library.java:706)
> [12:29:59] [Thread-34/INFO]: paulscode.sound.Library.play(Library.java:675)
> [12:29:59] [Thread-34/INFO]: paulscode.sound.SoundSystem.CommandPlay(SoundSystem.java:2076)
> [12:29:59] [Thread-34/INFO]: paulscode.sound.SoundSystem.CommandQueue(SoundSystem.java:2599)
> [12:29:59] [Thread-34/INFO]: paulscode.sound.CommandThread.run(CommandThread.java:121)
> [12:29:59] [Thread-34/ERROR]: Error in class 'SourceLWJGL OpenAL'
> [12:29:59] [Thread-34/ERROR]: Audio Format null in method 'play'

Last version of DynamicSurroundings, Minecraft 1.10.2
Without DynSurroundings - no problem

**Comment by OreCruncher** [comment]
Toward the begging of the log look for a line that looks like:

`[21:02:47] [Client thread/INFO] [dsurround/dsurround]: Sound channels: 112 normal, 16 streaming (total avail: 255)
`

Let me know what it says.

**Comment by GordonHollow** [comment]
[12:00:51] [Thread-15/INFO] [dsurround]: Checking for newer mod version
> [12:00:51] [Client thread/INFO] [dsurround]: Sound channels: 112 normal, 16 streaming (total avail: 255)
> [12:00:51] [Thread-15/INFO] [dsurround]: Dynamic Surroundings version [3.1.3BETA] is the same or newer than the current version [3.1.3BETA]

Thats all

**Comment by OreCruncher** [comment]
Was there a lot of sound activity at the time?

**Comment by GordonHollow** [comment]
Hmmm, no i started new world and no have machines thats do a lot of sound
Just NPC village, normal level of sounds

**Comment by OreCruncher** [comment]
Were you using an anvil at the time?

**Comment by GordonHollow** [comment]
Its the most strange of logs - there is no anvil in loaded chunks
I don't craft it and NPC-village have no anvil too

**Comment by OreCruncher** [comment]
Yeah, its wierd.  This line has a smell to it:

`[12:29:59] [Thread-34/INFO]: minecraft:sounds/random.anvil_use.ogg`

That period between 'random' and 'anvil' is suspicious.  I would have expected to see it be a '/'.  I think the period is throwing it off, so when the sound system calls back into the Minecraft resource manager it cannot find that resource and throws an exception.  If this is the case, I have to wonder what is triggering that sound.

**Comment by OreCruncher** [comment]
@GordonHollow If you could can you block the 'minecraft:block.anvil.use' sound?  Goal is to see if it can get past the 15-20 mins.  You can configure that in the Minecraft GUI by going to the mod options.  Dynamic Surroundings has a button for Block Sounds.  Scroll down that list to find it.

**Comment by GordonHollow** [comment]
No, it "." there in log - random.anvil_use.ogg - no period "/"
Maybe some mods that add another anvil have this fail in code
But there is no anvil around anyway

**Comment by GordonHollow** [comment]
I try to block it, if this sound showed in the list of sounds

**Comment by OreCruncher** [comment]
Looked in the 1.10.2 sounds.json in my config and it looks correct:

`
  "block.anvil.use": {
    "sounds": [
      "random/anvil_use"
    ],
    "subtitle": "subtitles.block.anvil.use"
  },
`

What modpack are you using?

**Comment by GordonHollow** [comment]
The New Frontier modpack + many mods adding to this modpack by me
I block this sound and playing, need more time to prove that all good

**Comment by GordonHollow** [comment]
All works good with this blocked sound

**Comment by OreCruncher** [comment]
Cool.

**Comment by OreCruncher** [comment]
Not sure of the origin of the problem.  Dynamic Surroundings does not use the Anvil sounds.  Going to keep open to see if there is something I can log if/when something like this happens.

**Comment by GordonHollow** [comment]
Okay, if something strange with sound happen again, log will be there.

**Comment by OreCruncher** [comment]
Do you have any resource packs loaded?

**Comment by GordonHollow** [comment]
Faithfull x32 Modded edition

There is no sounds in this resourcepack, only textures and models

**Comment by OreCruncher** [comment]
Ok.  Normally if there is a bad sound configuration you would see something like this in the Minecraft log:
`
[09:31:55] [Client thread/WARN]: Invalid sounds.json
java.lang.NullPointerException
	at net.minecraft.client.audio.SoundHandler.func_110549_a(SourceFile:82) [bzw.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122) [bxi.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:446) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[09:31:55] [Client thread/WARN]: File minecraft:sounds/cloth1.ogg does not exist, cannot add it to event inventorypets:cloth1
[09:31:55] [Client thread/WARN]: File minecraft:sounds/wood1.ogg does not exist, cannot add it to event inventorypets:wood1
`
This is from the New Frontier modpack without any additions.  During startup Minecraft caught two issues and made sure it wouldn't be a problem during operation.  However, it appears that something is sneaking by.  May be one of your add on mods that isn't in the pack by default.

**Comment by GordonHollow** [comment]
It happen again!
With blocked anvil.use sound

Logs the same as 1st message, nothing new in this log

**Comment by OreCruncher** [comment]
OK.  In terms of blocking the sound I found a bug in the event handling that will be fixed in the next BETA.  It may be the sound is getting past the blocking logic.  Also, I changed how Dynamic Surroundings interacts with the Minecraft sound engine so if DS is somehow the culprit it may fix it.  I should have this release wrapped up in a couple days.

**Comment by OreCruncher** [comment]
@GordonHollow Just pushed a 3.2.0.0 version to CurseForge.  Check out that version and let me know if it works any better for you.

**Comment by GordonHollow** [comment]
DynamicSurroundings-1.10.2-3.2.1.1
All works fine =)

**Comment by OreCruncher** [comment]
Good to hear.  Going to close the issue.  If you find anything else let me know.  Thanks!
