### ISSUE TITLE
Not compatible with Aether II

### ISSUE THREAD

**Issue by amed12345** [OreCruncher/DynamicSurroundings#170]
*Mod Version:*
1.7.10-1.0.5.7
*Forge Version:*
10.13.4.1614 (1.7.10)

*Link to crash log (if applicable):*
https://gist.github.com/amed12345/8b5067a4cd35b52f35506838834f3860
*Description:*
Happens when I try to enter Aether II trough the portal.
Im not sure but I think it has a problem with the step sound. Without Dynamic Surroundings the problem doesn't occur.
It also doesnt work with twilight forest

**Comment by amed12345** [comment]
oh yeah, twilight forest also doesn't work

**Comment by amed12345** [comment]
whateveeeeeer its working on the newest mod version, sorryyyyyyyyy xdd

**Comment by OreCruncher** [comment]
Heh.  Sometimes you just can't explain it.  I presume that things are still working for you?

**Comment by OreCruncher** [comment]
Going to close the issue out as addressed.  Let me know if you have any further issues. :)
