### ISSUE TITLE
1.12.2-3.4.7.2 crashes client when connecting to dedicated server

### ISSUE THREAD

**Issue by kreezxil** [OreCruncher/DynamicSurroundings#171]
*Mod Version:*
1.12.2-3.4.7.2

*Forge Version:*
14.23.0.2512

*Link to crash log (if applicable):*
https://pastebin.com/UXRz60ie

*Description:*
crashes client when connecting to dedicated server

**Comment by OreCruncher** [comment]
How often does the crash occur?

**Comment by kreezxil** [comment]
I did it 3 times in a row ... so, every time.

**Comment by OreCruncher** [comment]
OK.  Appears to be a timing issue.  These sometimes crop up when something changes in the timing sequence of startup.

**Comment by OreCruncher** [comment]
Pushed v3.4.8.0 with fixes.
