### ISSUE TITLE
[java.lang.ThreadGroup:uncaughtException:1052]: at com.jcraft.jorbis.Block.(Block.java:55)

### ISSUE THREAD

**Issue by Raycoms** [OreCruncher/DynamicSurroundings#176]
*Mod Version:*
Minecraft 1.12.2
*Forge Version:*
forge-1.12.2-14.23.0.2515-universal.jar
spongeforge-1.12.2-2503-7.0.0-BETA-2706.jar

Everytime I join our server I get this one here:

[B#353] Exception in thread "Thread-581" [01:18:33] [Thread-581/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[B#353] [01:18:33] [Thread-581/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at com.jcraft.jorbis.Block.(Block.java:55)
[B#353] [01:18:33] [Thread-581/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at paulscode.sound.codecs.CodecJOrbis.initialize(CodecJOrbis.java:252)
[B#353] [01:18:33] [Thread-581/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at paulscode.sound.libraries.SourceLWJGLOpenAL.preLoad(SourceLWJGLOpenAL.java:687)
[B#353] [01:18:33] [Thread-581/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at paulscode.sound.Source.stream(Source.java:928)
[B#353] [01:18:33] [Thread-581/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at paulscode.sound.StreamThread.run(StreamThread.java:129)
Besides that my log is full of:

[B#353] [01:26:15] [Thread-1067/ERROR]: Error in class 'LibraryLWJGLOpenAL'
[B#353] [01:26:15] [Thread-1067/ERROR]: Source '3fe6147b-39e9-49ba-bbea-8905e9a3b05b' not found in method 'play'
Not sure if that is related though.

**Comment by OreCruncher** [comment]
Just saw this in my debugger w/the latest 1.10.2 Forge version.  Me thinks something changed with Forge.

**Comment by OreCruncher** [comment]
No.  I think this is the classic sound engine crash but in a different form.  I have a set of changes going in that should address.

**Comment by OreCruncher** [comment]
Pushed v3.4.8.0 with fixes.
