### ISSUE TITLE
Auroras on the ground

### ISSUE THREAD

**Issue by Aegeis** [OreCruncher/DynamicSurroundings#178]
*Mod Version:*1.12.2-3.4.7.2

*Forge Version:*14.21.1.2415

*Description:* Everytime an aurora is loaded, it's at the ground level. Can't find a way to get them to appear in the sky instead

**Comment by OreCruncher** [comment]
They spawn at the edge of the map with the base of the aurora being at ground level and extending to the sky.  They no longer hover as a band in the sky like in earlier versions.  If this is not what you are seeing please provide a screenshot.

**Comment by OreCruncher** [comment]
Plan on doing some fancy things with auroras.  In the process I think I will revert some of the aurora rendering behavior back.

**Comment by OreCruncher** [comment]
In the v3.4.8.4 release the auroras will again appear as bands in the sky rather than at view distance.  There will not be any options to tune actual placement.  Those will be in a later release when I decide the final form of auroras.

**Comment by OreCruncher** [comment]
Pushed v3.4.8.4 to CurseForge.
