### ISSUE TITLE
Custom config not working.

### ISSUE THREAD

**Issue by yellow961** [OreCruncher/DynamicSurroundings#179]
*Mod Version:* 1.12.2-3.4.7.2

*Forge Version:* 14.23.0.2500

Hey. I have the biomes o plenty mod installed, but i'm creating a custom map and wanting to use the "outback" biome in one of the areas for its grass colour. My problem is that the outback gets the dust storms in it when I would much rather it rain. I tried following the config settings but it hasn't seemed to work.

![capture dsurround](https://user-images.githubusercontent.com/33276677/32262979-c00b1762-bf2b-11e7-8572-f1da6d7f9c93.PNG)
![capture outback](https://user-images.githubusercontent.com/33276677/32262983-c3c6c860-bf2b-11e7-8b1c-2d7281cd4cdf.PNG)
![2017-11-01_17 41 51](https://user-images.githubusercontent.com/33276677/32263033-0de79cbc-bf2c-11e7-90e0-e4c2decbd4be.png)

**Comment by OreCruncher** [comment]
Do something like [this](https://github.com/OreCruncher/DynamicSurroundings/blob/master/src/main/resources/assets/dsurround/data/biomesoplenty.json#L4).  Note that the name is case sensitive.

**Comment by yellow961** [comment]
Thanks. Either I didn't have the biome name capitalised like I should have or this was the problem.. either way it's solved now so cheers

**Comment by OreCruncher** [comment]
Closing the issue as solved.  Any further questions or problems let me know.
