### ISSUE TITLE
Exception in server tick loop - Agricraft + DynSur compatibility problem

### ISSUE THREAD

**Issue by Snipe13051** [OreCruncher/DynamicSurroundings#18]
I posted the crash file over here: 
http://www.minecraftforum.net/forums/support/modded-client-support/2778061-1-10-2-self-modded-crash-exception-in-server-tick#c2

If i should paste the code here, feel free to tell me and i will do.

**Comment by OreCruncher** [comment]
Fix will be in 3.1.4.0.  For some reason the entity villager that Agricraft adds doesn't have an internal name.

**Comment by OreCruncher** [comment]
Release with fix now on CurseForge.
