### ISSUE TITLE
Dynamic Surroundings , Footsteps not working with Sound Physics 1.12.2

### ISSUE THREAD

**Issue by Tsoccerguy3** [OreCruncher/DynamicSurroundings#182]
*Mod Version:*
1.12.2
*Forge Version:*
forge-1.12.2-14.23.0.2544

*Link to crash log (if applicable):*
No crash
*Description:*
Footsteps seem to be muted not working
https://github.com/daipenger/Sound-Physics/issues/23

**Comment by T4ge** [comment]
Can confirm, seems to be the case for me too.
Dynamic Surroundings 1.12.2-3.4.7.2
forge-1.12.2-14.23.1.2559

**Comment by OreCruncher** [comment]
To be clear Sound Physics isn't really supported - it does some strange things behind DSs back to make the sounds mute or volume really low.  I personally use Sound Filters.

**Comment by OreCruncher** [comment]
Putting in a hax to make the footstep sound attenuation LINEAR instead of NONE if SF is loaded.  Not sure exactly what SF is doing with my sounds.

**Comment by OreCruncher** [comment]
Pushed v3.4.8.5 with changes.

**Comment by KaelaniRevyruun** [comment]
Uh... This bug is back with ds 3.6.1.0 :'D It's kind of annoying to have all other sounds working but not footsteps >.<
