### ISSUE TITLE
[1.7.10]IC2 has no sound when DynamicSurroundings installed

### ISSUE THREAD

**Issue by TataTawa** [OreCruncher/DynamicSurroundings#184]
*Mod Version:*
1.5.0.12
*Forge Version:*
1.7.10.1614

**Comment by TataTawa** [comment]
and log warns : IC2 Audio unavailble

**Comment by OreCruncher** [comment]
Think this is due to sound engine crash handling.  I am backporting some of the changes I am making in the newer builds to the 1.7.10 release.

**Comment by OreCruncher** [comment]
Pushed v1.0.6.0 with fixes.

**Comment by TataTawa** [comment]
no, DynamicSurrounding 1.0.6.0(1.7.10) doesn't fix the issue.
IC2 still logs "IC2 audio unavailable" and all IC2 sounds mute.

Also see this issue
[https://github.com/Aroma1997/CompactWindmills/issues/45](url)

**Comment by OreCruncher** [comment]
Dynamic Surroundings derives from SoundManager so the field lookup in IC2 must be doing something strange.  The field it is looking for is still there.

**Comment by TataTawa** [comment]
IC2 getDeclaredField only get SoundManagerReplacement's Fields, It cannot get SoundManager's fields. So the best fix is use (if, superclass etc ) in IC2

**Comment by OreCruncher** [comment]
Yep, or somehow refers to SoundManager.class for getting the field instead.
