### ISSUE TITLE
No footstep sounds in twilight forest

### ISSUE THREAD

**Issue by vivagabe** [OreCruncher/DynamicSurroundings#189]
*Mod Version: 1.12.2-3.4.7.2

*Forge Version: 2562

*Link to crash log (if applicable): none

*Description: Cannot hear footsteps while walking around twilight forest.

**Comment by OreCruncher** [comment]
Would you happen to have a client side log available for this particular issue?

**Comment by OreCruncher** [comment]
@vivagabe With my latest sandbox changes I can loaded up the latest available for Twilight Forest and I do get footsteps.  There was a problem with sea level (determining if a player is underground) and I have to provide some config for that.  I will be pushing out a BETA within the week and I would like you to try that to see if the problem you are experiencing goes away.  Some of the sandbox changes I am making have to do with ASM and it is possible there may be some conflicts with the current posted build.

**Comment by OreCruncher** [comment]
@vivagabe Just noticed that the cicadas queue up quite a number of sounds.  Just wandering around I had over 140+ cicada sound instances playing.  This consumes the bulk of the sound channels which would trigger the footstep sounds not to play.

**Comment by OreCruncher** [comment]
Pushed v3.4.8.0 with fixes.
