### ISSUE TITLE
Lots of Crashing with IC2 Mods Around.

### ISSUE THREAD

**Issue by Quest79** [OreCruncher/DynamicSurroundings#196]
DynamicSurroundings-1.10.2-3.4.7.2.jar

**See Crash Reports**

[crash-2017-12-25_15.10.02-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/1586248/crash-2017-12-25_15.10.02-client.txt)
[crash-2017-12-25_15.19.02-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/1586249/crash-2017-12-25_15.19.02-client.txt)
[crash-2017-12-25_15.46.34-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/1586250/crash-2017-12-25_15.46.34-client.txt)

*Description:*
Just interacting with random things. IC2 stuff, enchanting tables, even just standing around. Disappointing. Playing AOE modpack.

**Comment by OreCruncher** [comment]
Though I haven't trapped in a debugger I suspect that IC2 does not like the underlying Minecraft sound library being restarted from underneath it.  Try disabling Dynamic Surroundings sound engine restart to see if the crash goes away.  As a side effect streaming sounds (Minecraft music and DS biome sounds) will stop playing if PaulsCode throws a fit.

I am currently working on integrating some ASM CreativeMD came up with to address the underlying issue in PaulsCode.  Once I have that complete this sound engine restart stuff will be a thing of the past.

**Comment by OreCruncher** [comment]
Pushed v3.4.8.0 with fixes.
