### ISSUE TITLE
[Request] Fog in the morning

### ISSUE THREAD

**Issue by Ash70** [OreCruncher/DynamicSurroundings#198]
This was/is a feature in TFC and I'm missing it; so here's hoping you like it ;)
Have the fog distance slowly decrease just after sunrise, and then slowly bring it back well(!) before noon to emulate early morning fog.

**Comment by OreCruncher** [comment]
@Ash70 TFC?

**Comment by Ash70** [comment]
@OreCruncher [TerraFirmaCraft](http://terrafirmacraft.com/);  a mod from 1.7.10

**Comment by OreCruncher** [comment]
I have a version of morning fog going into the 3.4.9.1 release.

**Comment by Ash70** [comment]
Wow, thank you. :)

**Comment by darchitectlp** [comment]
Seriously, morning fog was one of my favorite things in TFC. So awesome that you added it, OreCruncher. This is one of the best mods out there!

**Comment by OreCruncher** [comment]
Check out the [last image on the page](https://minecraft.curseforge.com/projects/dynamic-surroundings/images#).  I never played TFC so I am not sure how it compares.

**Comment by Ash70** [comment]
Looks good to me. Can't wait to test it out.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.1 with the enhancement.

**Comment by Ash70** [comment]
I love it. For me there is no need for additional options/configs.
Thank you so much!
