### ISSUE TITLE
Natura Support

### ISSUE THREAD

**Issue by kenijey** [OreCruncher/DynamicSurroundings#199]
Can you add Natura support please? :D for example Tiger Leaves don't have extra leave thing. they're only cubes.
using latest DS and Natura, Forge 2585 on MC 1.12.2

**Comment by OreCruncher** [comment]
They must have changed how their leaf blocks are registered and handled. :\

**Comment by kenijey** [comment]
I really really guessed that! I was a bit sure about DS would work fine with Natura, there should be something wrong with my modpack, weirdly. xD
Thanks for quick reply, will try that very soon(probably tomorrow)

**Comment by kenijey** [comment]
![sfdf](https://user-images.githubusercontent.com/24831406/34734800-2b0e488a-f57e-11e7-8aa2-bb130522f78c.PNG)
by the way, i couldnt pass into it. passable leaves mod is installed, i can pass all other leaves but this one. it's so weird. maybe  we need help from @alexbegt ? :D

**Comment by OreCruncher** [comment]
Looks like the config is correct.  Have your removed passable leaves to see if the problem goes away?

**Comment by kenijey** [comment]
if you mean DS's extra leaves as the problem, i tried it right now, no. i deleted passable leaves mod, still theres no extra leaves from DS.

**Comment by kenijey** [comment]
this is what i dont expect from passable leaves mod or natura :D 
![xd](https://user-images.githubusercontent.com/24831406/34735314-12171256-f580-11e7-8722-80e72189b034.png)

**Comment by kenijey** [comment]
oh my god, i'm soooo sorry, OreCruncher. I'm really stupid. I conflicted Dynamic Surroundings and Better Foliage mods... I can't believe this...

**Comment by OreCruncher** [comment]
Lol.  Do like I do - get more caffeine. :)  Of course, it could make things worse. :))

**Comment by kenijey** [comment]
yeah, i let it be fixed :D i'm happy 
https://github.com/progwml6/Natura/issues/424#issuecomment-356462605
