### ISSUE TITLE
sound engine crashing in Aether Legacy

### ISSUE THREAD

**Issue by SimulatorSia** [OreCruncher/DynamicSurroundings#200]
*Mod Version:*3.4.8.1

*Forge Version:*14.23.1.2582

*Link to crash log (if applicable):* (no crash report)

*Description:*Everytime I go in the Aether from Aether legacy mod, the music starts playing, they like 10 seconds into it the sound engine crashes everytime and stops the music and all sounds until it reboots.

**Comment by OreCruncher** [comment]
Need a client log.

**Comment by SimulatorSia** [comment]
where would I find the client log?

**Comment by OreCruncher** [comment]
In your modpack install directory under the logs folder.  Look for the file fml-client-latest.log.  It should have what I am looking for assuming the last client session had the issue you are speaking of.

**Comment by SimulatorSia** [comment]
I can't get it to crash again since I updated forge, I hope I didn't waste your time but I think it's fixed <3

**Comment by OreCruncher** [comment]
No worries.  I would rather hear about problems than not. :)  Thanks!
