### ISSUE TITLE
Footprints Render Solid On Translucent Blocks

### ISSUE THREAD

**Issue by InsomniaKitten** [OreCruncher/DynamicSurroundings#202]
Footprints render solid when created on the surface of a translucent block.
This can be reproduced using vanilla's ice block.

**Mod version:** [3.4.8.1](https://minecraft.curseforge.com/projects/dynamic-surroundings/files/2517428)
**Forge version:** [1.12.2-14.23.1.2585](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.1.2585/forge-1.12.2-14.23.1.2585-changelog.txt)

**Comment by OreCruncher** [comment]
Yeah.... Particle interaction with a translucent surface.  Should be fun.

**Comment by OreCruncher** [comment]
With the fix the footprint will be very light on the surface of the ice block.  It will be more visible if there are light colored blocks under the ice block (such as wool), or when viewed at an angle with the side open to air.  Big thing is that it will not render dark. :)

**Comment by OreCruncher** [comment]
Posted v3.4.8.2 with fix.
