### ISSUE TITLE
Unexpected crash with the potion GUI

### ISSUE THREAD

**Issue by Sunconure11** [OreCruncher/DynamicSurroundings#209]
*Mod Version:*

1.12.2-3.4.8.2

*Forge Version:*

14.23.1.2589

*Link to crash log (if applicable):*

https://pastebin.com/N0hg3JJg

*Description:*

Seemingly happened randomly. IDK what caused it.

**Comment by Sunconure11** [comment]
... derp, didn't see it was resolved.

**Comment by OreCruncher** [comment]
Yep. :)  What was funny is that someone EMAILed me the issue, and just after I ran into it using your pack.  It's in Github and will be in the next BETA drop.  Related to this do you know if those sprout mobs give buffs to the player?  Each time my client crashed was in an area with a sprout nearby.

**Comment by Sunconure11** [comment]
The sprouts from roots? They don't IIRC. Support Creepers give buffs to other mobs though. Also, dungeon tactics is in the pack, which has plants that give you buffs or debuffs if you step on them.

**Comment by OreCruncher** [comment]
Dungeon Tactics.... I think that's it.  I will have to test further.  Reason I ask is that it looks like the potion effect entry is busted thus causing the NPE.  Need to confirm that is what is going on.
