### ISSUE TITLE
Splashing water colour

### ISSUE THREAD

**Issue by MeinKraft** [OreCruncher/DynamicSurroundings#212]
*Mod Version:*

DynamicSurroundings-1.12.2-3.4.8.3.jar

*Forge Version:*

14.23.1.2589

*Link to crash log (if applicable):*

*Description:*
Am i right in thinking your mod adds splashing effects when water falls from height onto other water?  if so I'm in a wasteland biome generated by Biomes of Plenty. The water is green yet the splash particles are blue. They should be green also?

Is this something you could fix? Splash particles based on colour of the water?

**Comment by OreCruncher** [comment]
I been noticing the same thing.  I will have to dig into it to see what I can do.  I think it would be possible.

**Comment by OreCruncher** [comment]
Pushed v3.4.8.4 to CurseForge.

**Comment by MeinKraft** [comment]
Hi  thank you for the extremely fast response, but...

these were the splash effects I was  trying to explain - see they are blue, this photo is taken with DynamicSurroundings-1.12.2-3.4.8.4

[](http://ni750123-2.web11.nitrado.hosting/gfdgfds.jpg)

**Comment by OreCruncher** [comment]
That is weird.  Should be colorized.  I will take a look.

**Comment by OreCruncher** [comment]
Try this jar and let me know how it looks: https://github.com/OreCruncher/DynamicSurroundings/releases/tag/v3.4.8.5T

This is from my current sandbox and the splash particles are rendering correctly in BoP biome that has tinted water.

**Comment by MeinKraft** [comment]
just tried it - particles are still blue - Im gonna try it just biomes o'plenty and DynamicSurroundings mods installed

**Comment by MeinKraft** [comment]
by George hes done it !

Perfect.

Thank you

**Comment by OreCruncher** [comment]
No problem.  I was working on Albedo compat and came across some interesting gems in the process. :)  BTW, do you use Albedo?

**Comment by MeinKraft** [comment]
Never even heard of it until now - but it seems it can add some very nice colour effects

**Comment by OreCruncher** [comment]
Just by itself it modifies MC lighting to improve it.  But yes, other mods out there take advantage of it to do lighting effects.  For example DS puts a glow around fireflies, and when you hold a lit item, like a torch, it will case a light halo around the player.

**Comment by MeinKraft** [comment]
I'm gonna have to try that now, lol

**Comment by MeinKraft** [comment]
I like the albedo torches mod, coloured torches should be a Minecraft Vanilla thing
