### ISSUE TITLE
Auroras and Astral Sorcery

### ISSUE THREAD

**Issue by ElvenChaos** [OreCruncher/DynamicSurroundings#213]
*Mod Version:* 3.4.8.3

*Forge Version:* 2589

*Description:*
Default Astral Sorcery sky rendering removes auroras from being visible at all. Is there a way to make auroras compatible with Astral Sorcery default sky rendering?

While enabling AS weak rendering allows auroras to appear, the resulting constellations in the sky as rendered weirdly.

**Comment by OreCruncher** [comment]
This I knew about.  Unfortunately some mods want to own the sky.  I am making some enhancements to auroras and I will see if I can convince the mods to get along. :)

**Comment by OreCruncher** [comment]
Pushed v3.4.8.5 with changes.
