### ISSUE TITLE
Auroras and Extended Days

### ISSUE THREAD

**Issue by ElvenChaos** [OreCruncher/DynamicSurroundings#214]
*Mod Version:* 3.4.8.3

*Forge Version:* 2589

*Description:*
Having auroras as well as the special sky rendering from [Extended Days](https://minecraft.curseforge.com/projects/extended-days) causes the auroras to rapidly flicker, and eventually produce GL errors.

Disabling ED special rendering provides a workaround for the problem, at the expense of not having the special rendering.

Issue is available at the ED github here: https://github.com/SilentChaos512/ExtendedDays/issues/12

**Comment by OreCruncher** [comment]
I will have to look at that.  I do some interesting things to get the sky rendered hooked for auroras and there may be a conflict because ED and DS are fighting over the sky renderer (the flicker being caused by the back and forth).

**Comment by OreCruncher** [comment]
Looks to be addressed with the change I made for [#213].

**Comment by OreCruncher** [comment]
Pushed v3.4.8.5 with changes.
