### ISSUE TITLE
[1.12.2] Footstep/Weapon swap noise goes hyperspeed in multiplayer

### ISSUE THREAD

**Issue by MafooHamhead** [OreCruncher/DynamicSurroundings#215]
*Mod Version:* **1.12.2-3.4.8.3**

*Forge Version:* **14.23.1.2589**

*Link to crash log (if applicable):* **N/A**

*Description:* **When you're in a server by yourself, everything is fine. A friend joins and the noise when you walk on blocks and swap weapons goes super sonic speed. Sounds repeat themselves at a super fast rate.**

Downgraded to version **1.12.2-3.4.8.1** of your mod and the issue is now gone.

**Comment by OreCruncher** [comment]
Pushed v3.4.8.4 to CurseForge.
