### ISSUE TITLE
[Feature Request] Random Things Rain Shield patch

### ISSUE THREAD

**Issue by swyrl** [OreCruncher/DynamicSurroundings#217]
DS 1.12.2-3.4.8.1
Forge 14.23.1.2587

Due to both Random Things and Dynamic Surroundings tweaking the same class (the vanilla class dealing with rain), installing Dynamic Surroundings renders the Rain Shield non-functional. (Obviously, I can fix this by disabling the rain ASM tweaks in DS, but that also gets rid of things like desert storms, which I'd like to keep.)

Thus, my (non-urgent) feature request is a patch that checks with randomthings' shield list before displaying rain sound/visuals client-side.

(The normal functionality of the rain shield is that, when placed, it will make an area around it free of rain particles and sounds.)

**Comment by OreCruncher** [comment]
I'll take a look.  It appears to be something straightforward to handle.

**Comment by OreCruncher** [comment]
Pushed v3.4.8.5 with changes.
