### ISSUE TITLE
crashing with optifine

### ISSUE THREAD

**Issue by MeinKraft** [OreCruncher/DynamicSurroundings#219]
*Mod Version:*
DynamicSurroundings-1.12.2-3.4.8.5
*Forge Version:*
1.12.2600

*Link to crash log (if applicable):*
no crash log generated

*Description:*
just 2 mods running, DS and Optifine_1.12.2_HD_U_C8, also fails with the latest Optifine 1.12 preview

Seems to crash during PostInitialization. Sometimes Java crashes and Forge is stuck with PostInitialization Dynamic Surroundings on screen, other times quits back to MC Launcher

the DS 3.4.8.5 you gave me to test (for the colour water splashing) works fine, only this latest update fails

**Comment by OreCruncher** [comment]
Need the crash report.  I fixed several optifine related issues before release.

**Comment by MeinKraft** [comment]
there isnt a crash report, sorry

**Comment by OreCruncher** [comment]
I used the same optifine version you have in my test and it works.  I presume if you remove optifine it works?

**Comment by OreCruncher** [comment]
Understand.  In my case I just have 2 additional mods.  What video card do you have?

**Comment by MeinKraft** [comment]
gtx 980 ti

**Comment by OreCruncher** [comment]
lol.  same as mine.  Well, this is going to be fun.

**Comment by MeinKraft** [comment]
[forge](http://ni750123-2.web11.nitrado.hosting/Image2.jpg)

thats the best i can do,  I did do a java update couple days ago,

**Comment by OreCruncher** [comment]
What launcher are you using?

**Comment by MeinKraft** [comment]
the standard minecraft launcher

**Comment by OreCruncher** [comment]
OK - that could be a potential difference.  I am using MultiMC.

**Comment by MeinKraft** [comment]
im using java 64 bit version  1.8.0_161-b12  its weird.

**Comment by OreCruncher** [comment]
Try this JAR: https://github.com/OreCruncher/DynamicSurroundings/releases/tag/v3.4.8.6T

**Comment by MeinKraft** [comment]
So the client starts, as soon as i hit F7 (my Light Level keybind) Minecraft crashes back to launcher screen

No crash report

**Comment by OreCruncher** [comment]
OK - narrows in on the specific piece of code.  The main question is why.  Like everything modded it doesn't make sense at the moment.

**Comment by Andyghandi** [comment]
![dynamic surrounds potential crash](https://user-images.githubusercontent.com/25442543/35283876-a7346d96-0059-11e8-885f-fd8779e7c5a1.png)

Also Happens to me, Using forge 1594-1601. I would assume its the same reason.

**Comment by OreCruncher** [comment]
Yep.  Optifine is doing something weird with one of the builtin classes.  The irony is that it works on my system.  I've been making blind changes and adding additonal logging in hopes of narrowing it down.  I will have a test jar available in an hour or so if you are game to try it out.

**Comment by MeinKraft** [comment]
Im always game to do some testing but wont be home for another 8 hours.

**Comment by Andyghandi** [comment]
I was first using 1594 as jei needed it as a part of Its latest update. Then tested with 1600 and 1601 with twitch launcher and same thing hapened. I didnt know where to look because there's nothing in the log. But yeah this could be on optifine. However you are doing a really great job on fixing crashes, there is many and you are really doing a great and fast job fixing them. Loving this mod too much to not include it in my modpack.

**Comment by OreCruncher** [comment]
Reuploaded a v3.4.9.0 JAR for 1.12.2.  Give it a shot.  If the HUD display funny or it crashes I will need the client log.  And yes, the problem is being caused by OptiFine.  It's messing with the texture classes of Minecraft in ways that don't seem natural. :)

@Andyghandi It's still not clear to me which versions of Forge you are using.  You mention 1600 - do you mean 2600? :)

**Comment by Andyghandi** [comment]
14.23.1.2600, My bad. I will try Your test jar combined in my pack and see how it goes.

**Comment by Andyghandi** [comment]
Test Jar works fine for me, Launcher boots up properly and I cant come across any bug after 20 min of gameplay. Awesome!

**Comment by OreCruncher** [comment]
Try turning on the light level HUD.

**Comment by Andyghandi** [comment]
Yeah that causes the game to freeze. Showing Green, yellow, red light levels on the ground but full of symbols and not as it is supposed to be. I have Light level overlay reloaded installed which Im using so Im my case im good. Nothing showing up in crash log though when freezing.

**Comment by OreCruncher** [comment]
Anything in the client log?

**Comment by Andyghandi** [comment]
Only thing showing in client log is "Server running behind, skipping 1344 ticks" last 5 mins multiple times and thats not related to the crash.

**Comment by OreCruncher** [comment]
Since Framebuffers are unreliable with OptiFine/shaders I put back some of the legacy code for light level rendering.  Specifically, if OptiFine is installed or Framebuffers are disabled the rendering logic will revert to the classic drawstring method.

**Comment by xerberus333** [comment]
Hey, I'm not sure if this is related:

[Light Level Overlay Jank](https://imgur.com/AIAyu21)

Should I make a new issue?

**Comment by OreCruncher** [comment]
No - I am pretty sure its the same issue.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.0 with fixes.
