### ISSUE TITLE
Modded Tools compatibility

### ISSUE THREAD

**Issue by lukiono** [OreCruncher/DynamicSurroundings#22]
Hey,

it would be a great feature when custom tools like the ones from tinkers construct could be written to the config by the player / modpack creator itself. so the swing and bow sounds can also be heared on other modded tools.

kind regards

**Comment by OreCruncher** [comment]
This was put in recently.  It's not on the Wiki yet. :)

**Comment by lukiono** [comment]
wow, you're very fast. =D

thanks for the information. so i will wait for the wiki then =)

**Comment by OreCruncher** [comment]
:)  You can see how its done looking here: https://github.com/OreCruncher/DynamicSurroundings/blob/master/src/main/resources/assets/dsurround/data/mcp.json#L576

**Comment by lukiono** [comment]
so, i can write it later in the config or do i need to recompile itself?

**Comment by OreCruncher** [comment]
If you are looking at making a pull request for the mod, the information would need to go into the tconstruct.json file.  This is the one that gets processed when Tinkers is loaded.  If you want to test out without recompiling then you can create an external json with the tweaks.  That can be found [here](https://github.com/OreCruncher/DynamicSurroundings/wiki/Tutorial:-Configuration-Files).

**Comment by lukiono** [comment]
so this tconstruct.json example would be correct?
http://paste.ee/p/uHYQh

**Comment by OreCruncher** [comment]
For the Json file you would have to enclose it all within another set of { } but yes it looks correct.

**Comment by lukiono** [comment]
thank you for the help =)

**Comment by OreCruncher** [comment]
If you get it working and don't want to do a pull request you can send me the changes?  This was on my to-do list but I haven't got there yet.

**Comment by lukiono** [comment]
yes, i will send it. but at the moment i have problems to find the correct id's for the tconstruct tools...

"slimeknights.tconstruct.tools.tools.hatchet" was the latest try but;
"slimeknights.tconstruct.tools.hatchet"
"slimeknights.tconstruct.items.hatchet"

and the same without slimeknights and minecraft and without both didnt worked yet... 

i bet it is a simple thinking error on my side ^^

**Comment by lukiono** [comment]
Yes, it was a simple error... 

https://www.dropbox.com/s/0fvwzqnbvgmqgx5/tconstruct.json?dl=1 

there you go. ive excluded the crossbow because the pull sound also plays when you shot with it. if you want to test it then add the following before longbow;
"slimeknights.tconstruct.tools.ranged.item.CrossBow",

**Comment by OreCruncher** [comment]
Excellent!  I will fold it in for the next BETA drop.  Thanks!

**Comment by OreCruncher** [comment]
Pushed release with this update to CurseForge.
