### ISSUE TITLE
Frog Croaks Ignore Configuration File

### ISSUE THREAD

**Issue by jurichmitchell** [OreCruncher/DynamicSurroundings#220]
DynamicSurroundings-1.12.2-3.4.8.5

1.12.2-forge1.12.2-14.23.1.2598

No crash.

Frog croaks are still audible in the Swampland biome even though "Enable Biomes Sounds" is set to false in the config file.

**Comment by OreCruncher** [comment]
Because they are block effects, not biome effects. :)  You can block the sound under the Individual Sound Configuration options in the mod config GUI.

**Comment by jurichmitchell** [comment]
AWESOME! Thanks. Case closed haha!

**Comment by OreCruncher** [comment]
If only all the issues were this easy. :D
