### ISSUE TITLE
ConcurrentModificationException happened at SoundManagerReplacement.java:240

### ISSUE THREAD

**Issue by PrinceOfAmber** [OreCruncher/DynamicSurroundings#221]
*Mod Version:* DynamicSurroundings-1.12.2-3.4.8.5.jar

*Forge Version:*14.23.1.2601

*Link to crash log (if applicable):* https://pastebin.com/sHmeQHwc

*Description:* I was just in a cave near a skeleton grinder so lots of mobs were dying

**Comment by OreCruncher** [comment]
This is an existing bug in the Minecraft code.  It happens on occasion.  How frequently is it occurring for you?

**Comment by OreCruncher** [comment]
I made some code changes to guard the state of the SoundManager.  Not entirely sure it will address this particular issue but it would help with cross side sound submission.  I posted a v3.4.9.0 to CurseForge.  Give that one a whirl.
