### ISSUE TITLE
crashes on startup

### ISSUE THREAD

**Issue by SpeedrunnerG55** [OreCruncher/DynamicSurroundings#225]
DynamicSurroundings-1.7.10-1.0.6.0.

forge 10.13.4.1614

https://hastebin.com/sokewicuta.vbs

crashes on startup

**Comment by OreCruncher** [comment]
Not seeing anything related to DS in that trace.  Looks to be a Forge issue of some sort.

**Comment by SpeedrunnerG55** [comment]
it only happens when I had that mod installed https://hastebin.com/asatonikem.vbs here is a log of it when I only have it in the mod folder so I know its isolated.

**Comment by OreCruncher** [comment]
Cool. :)
