### ISSUE TITLE
Game crash fatal error

### ISSUE THREAD

**Issue by mando222** [OreCruncher/DynamicSurroundings#228]
*Mod Version:*
1.12.2-3.4.7.2

*Forge Version:*
forge-14.23.2.2611

*Link to crash log (if applicable):*
full log: https://gist.github.com/mando222/86b7f9158296c2cd303a28f6bb4e5c41
*Description:*
This seemed to be related to #162 but not 100% sure.  These log entries are a constant and repeating thing even when not causing a crash.  I am still not 100% convinced this was the root of the crash but it is an issue. 

Game crashed and on reload in the log there was 
```
[21:24:35] [Thread-11/ERROR]: Source '8befe5ea-86a0-445d-be83-54ea03f54de7' not found in method 'play'
[21:24:36] [Thread-11/ERROR]: Error in class 'LibraryLWJGLOpenAL'
```

**Comment by OreCruncher** [comment]
Nothing in the log indicating a sound engine crash.  The above error you state above is possible though I would expect it to be rare.  There are some interesting timing loopholes between the PaulsCode processing thread and the Minecraft processing thread.

Try the latest BETA.  I put in some fixes for PaulsCode to address the crash, and additional logic to close down the timing loopholes I know of.

**Comment by OreCruncher** [comment]
@mando222 Have you had a chance to try out the latest BETA?

**Comment by mando222** [comment]
Yeah just been testing.  It looks to be resolved in the BETA.  Thanks for the quick resolution!

**Comment by OreCruncher** [comment]
Cool!  Let me know if you run into any other issues.
