### ISSUE TITLE
v1.10.2-3.2.0.0 hanging on startup after version check fail

### ISSUE THREAD

**Issue by gmalone** [OreCruncher/DynamicSurroundings#23]
Hi any thoughts on this?  Installed the update.  First run works!  But subsequent runs, for some reason, hang on this error:

DynamicSurroundings-1.10.2-3.2.0.0.jar
```

[09:19:18] [Forge Version Check/INFO] [ForgeVersionCheck]: [dsurround] Starting version check at https://raw.githubusercontent.com/OreCruncher/DynamicSurroundings/master/version.json
[09:19:18] [Forge Version Check/INFO] [ForgeVersionCheck]: [dsurround] Found status: UP_TO_DATE Target: null
```

**Comment by OreCruncher** [comment]
It's not an error.  The status is found up to date and as such there isn't an update target.  If the mod version were behind the Target would indicate what the new version is.  BTW, this is the Forge version check routines that is doing this.

**Comment by OreCruncher** [comment]
@gmalone Any more info on the hang?  I notice that with MultiMC it has a pretty long delay during/after initializing the sound engine.  That's not Dynamic Surroundings. :)

**Comment by gmalone** [comment]
Thanks for following up with me on that. It turned out that it was not
Dynamic surroundings causing the problem. It was what was loading right
after it. So all is well my friend. Thanks. I love the plug-in!

**Comment by OreCruncher** [comment]
Glad you like it.  Going to close this issue then.  If you find anything else be sure to let me know.
