### ISSUE TITLE
random crash game

### ISSUE THREAD

**Issue by KiraLinux** [OreCruncher/DynamicSurroundings#232]
DynamicSurroundings-1.12.2-3.4.9.2

1.12.2-forge1.12.2-14.23.1.2607

[fml-client.zip](https://github.com/OreCruncher/DynamicSurroundings/files/1700799/fml-client.zip)

I can not describe
the game flies out in rare cases

**Comment by OreCruncher** [comment]
Was something happening like changing dimensions or dying?

**Comment by OreCruncher** [comment]
I think I know what the issue is.  Made a fix for it

**Comment by OreCruncher** [comment]
Pushed v3.4.9.3 with a fix.
