### ISSUE TITLE
crash when climbing ladders straight down

### ISSUE THREAD

**Issue by LiEyWe** [OreCruncher/DynamicSurroundings#233]
*Mod Version:*
1.12.2-3.4.9.0

*Forge Version:*
14.23.2.2611

*Link to crash log (if applicable):*
https://paste.ee/p/CvyWn

*Description:*
when I climb ladders straight down, I get the crash linked above. I have quark installed, maybe it has to do something with quark's feature of climing down ladders faster?

**Comment by OreCruncher** [comment]
Does it always happen when climbing down the ladder?  Or just sometimes?

**Comment by LiEyWe** [comment]
Just sometimes when climbing down.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.3 with a fix.
