### ISSUE TITLE
Crash when teleported to my base

### ISSUE THREAD

**Issue by Diamond45123** [OreCruncher/DynamicSurroundings#235]
*Mod Version:* Latest version for 1.11.2

*Forge Version:* 2563

*Link to crash log (if applicable):*
https://pastebin.com/AiTmmvMa
*Description:*
Game crashed when I teleported to my base, I guess It's an issue in the newest version of Dynamic Surroundings mod.

**Comment by Diamond45123** [comment]
To be more specific i think it's a conflict with galactic craft.

**Comment by OreCruncher** [comment]
The crash is down in the chunk code when DS is trying to get biome information.  Do you happen to know if the chunk was loaded, or if the chunk had to be loaded?

**Comment by Diamond45123** [comment]
The base was chunk-loaded, and my dimension was overworld, I had some GC machines and a tier 1 rocket.. maybe a bug trying to render it or something like that?

**Comment by OreCruncher** [comment]
Based on the call stack it looks like the chunk info in the chunk object was incomplete somehow and triggered the exception.  I am adding some defensive code to detect and mitigate the problem.  The changes should be in the next BETA (likely later today).

**Comment by OreCruncher** [comment]
Pushed v3.4.9.3 with some defensive code changes to address this.  Let me know if you have further problems.
