### ISSUE TITLE
Missing item swap sound for axe, pickaxe, tools...

### ISSUE THREAD

**Issue by MrDj200** [OreCruncher/DynamicSurroundings#236]
Hey, is there a way to manually restart the Sound engine?
Sometimes it crashes without the auto restart (mainly when disconnecting from a server).

I tried the /ds reload, but it seems that is something different ^^.

The only way I know of right now is to restart the game entirely(which takes a looong time with modded mc as you know :D)

-Dj

**Comment by OreCruncher** [comment]
Is there a problem with DS?  As for manual restart the you can use the built in debug of Minecraft for reloading resources: F3+T.  It may take a bit since it reloads textures and what not, but it does reinit the sound engine.

**Comment by MrDj200** [comment]
Yeah, I tried that aswell (sry forgot I used that before), however the Sound is Stuttering after that, so I still have to restart the game in the end.

**Comment by OreCruncher** [comment]
Do you have a client log with the problem (disconnecting from server and sounds stuttering)?

**Comment by MrDj200** [comment]
There is one just spammed with
`[04:23:48] [main/INFO] [dsurround/]: Unmuting sounds`
want me to Upload the whole thing, or do you mean another client log?

**Comment by OreCruncher** [comment]
The client lastest log.  Can paste it to pastebin to make things easy.  And that spam can happen when the sound engine isn't available for some reason, like doing an F3+T and the Minecraft window loses focus.

**Comment by MrDj200** [comment]
It'll be hard to reproduce, but I'll try. 
Don't know when it happens, as it is pretty random

**Comment by MrDj200** [comment]
I got an old log file though, don't know if it has the text of the "client-latest.log" in though, I'll upload it anyway, maybe It'll help:

https://gist.github.com/MrDj200/6c32e5bf18b375c52eeb32281c66024e  (pastebin didn't want it, sry :D)

**Comment by OreCruncher** [comment]
Which version minecraft/ds?

**Comment by MrDj200** [comment]
MC: 1.12.2
DS: 3.4.7.2

**Comment by OreCruncher** [comment]
OK.  Try using the latest BETA.  In v3.4.8.0 I got rid of sound engine restart and replaced with ASM patches that CreativeMD had.  Works much better, and makes IC2 happy.  IC2 doesn't like having the sound engine restarted from under it.

**Comment by MrDj200** [comment]
I assume it is Client Only, and the server doesn't care, even if it has the "old" version installed?

**Comment by OreCruncher** [comment]
I haven't tried it specifically, but in theory that is the case.  When I coded all the changes in the latest BETA the client should ignore what it doesn't care about.  And as a bonus it only talks with the server to route a sound for item crafting so it is more friendly to the server.

**Comment by MrDj200** [comment]
Ok, so I guess I'll take the newest Beta "3.4.9.2" ?

**Comment by OreCruncher** [comment]
Yep.  Or you can wait a day or 2.  Plan on posting another one.

**Comment by MrDj200** [comment]
I'll try this Beta, and let you know of any Problems ^^

**Comment by MrDj200** [comment]
Hmm, I've got a problem where some of my Tools don't have the equip sound.
They are TC tools, but the Vanilla axe for example doesn't have one either.

See here: [YT Link](https://youtu.be/rcki0dNav7s)

**Comment by OreCruncher** [comment]
Yep, that is a problem.  I can duplicate it.  Will work on it.  Just when I thought things were settling down. :)

**Comment by MrDj200** [comment]
They never do, I'm still a beginner programmer, but that is something I already know :P

**Comment by OreCruncher** [comment]
Fixed.  Pretty easy one at that.  Will be in the next beta. :)

**Comment by OreCruncher** [comment]
Pushed v3.4.9.3 with a fix for item swamp sounds.
