### ISSUE TITLE
Gray dust? particles emitted during rapid direction change also emitted when flying which seems to make no sense

### ISSUE THREAD

**Issue by asiekierka** [OreCruncher/DynamicSurroundings#237]
*Mod Version:* 1.12.2-3.4.9.2

*Forge Version:* 14.23.1.2604

*Description:*

Gray dust? particles emitted during rapid direction change are also emitted when flying. I imagine them as pertaining to ground, though, which makes them look awkward when flying. Is this intentional behaviour or not?

**Comment by OreCruncher** [comment]
You in a cold biome?  It could be breath particles.

**Comment by asiekierka** [comment]
...Oh.

Sorry, I'm stupid.

**Comment by OreCruncher** [comment]
lol - no worries.  The first time I was flying with the breath particles I thought the same thing, and I put the darn code in myself.
