### ISSUE TITLE
Crash using Dynamic Surrondings and Vanilla Tweaks

### ISSUE THREAD

**Issue by vpontin** [OreCruncher/DynamicSurroundings#238]
Random crash while walking on the map...

Crash-log: https://gist.github.com/vpontin/8c3e0621ef01ca6b1e153d6ebca0c75e

Using MC 1.12.2, Forge 14.23.2.2613, VanillaTweaks 1.2.5 and DynamicSurrondings 3.4.9.2

Also reported on VT side, https://github.com/strikerrocker/VanillaTweaks/issues/24

**Comment by OreCruncher** [comment]
I will take a look.  I suspect it isn't me.

**Comment by OreCruncher** [comment]
Note these changes are in attempt to fend off a capability provider reporting that an EntityItem has an Emoji capability when it clearly does not.

**Comment by vpontin** [comment]
Well, i will close this, but i hope @strikerrocker will proper fix his side too!

**Comment by OreCruncher** [comment]
The change I just put in for DS should mitigate this particular issue with VT, but there may be others.  But yes, ideally the code change would happen in VT.  May run into other compatibility issues.

**Comment by vpontin** [comment]
Reopened since https://github.com/strikerrocker/VanillaTweaks/issues/24 was too and i think only when striker make the proper fix this issue could be closed.

**Comment by OreCruncher** [comment]
If you want. :)

**Comment by vpontin** [comment]
Closed the issue in https://github.com/strikerrocker/VanillaTweaks/commit/82039bec4e5eadc7400143a85e3975563ac0ce78
