### ISSUE TITLE
[SUGGESTION] Unmute eerie cave ambience sounds

### ISSUE THREAD

**Issue by Aleszp** [OreCruncher/DynamicSurroundings#240]
Hi!
Since Minecraft 15w44b cave ambience sounds ( [YT example](https://www.youtube.com/watch?v=LwcgG7ZYlFE) ) are not working (they play too far away to be heard). While Mojang adds new samples, this bug still wasn't fixed ([MC-91803](https://bugs.mojang.com/browse/MC-91803), they keep marking it as fixed, but still it doesn't work and is remarked as unresolved when somebody points it out).

As Dynamic Surroundings adds a lot of its own sounds (and messes a bit with sound system) wouldn't re-adding those sounds enhance player's experience (especially that mod seems to be about enhancing ambience by both visual and audio means)?

//OT: Big kudos to you OreCruncher for reimplementing void-fog and adding morning fog (it's awesome :D). Also big kudos for mod as a whole :D, you're doing an awesome job, DS is on my list of must-have mods ;)//

**Comment by OreCruncher** [comment]
I added code to supply cave ambiance.  The logic is not like MC logic.  Specifically, when the sound event can trigger I generate a random point around the player rather than some convoluted logic involving viewed chunks.  (The MC logic in 1.7.10 made more sense because it was server side and sent the sound event to players in range.  With the later versions of MC it is a client side operation and I think they took that 1.7.10 server logic and put it client side.  Geez.)

**Comment by Aleszp** [comment]
> The MC logic in 1.7.10 made more sense because it was server side and sent the sound event to players in range. With the later versions of MC it is a client side operation and I think they took that 1.7.10 server logic and put it client side. Geez.

Well... now it explains why it stopped working after 1.7.10... I guess that in client they checked not nearest chunks, but all loaded by client chunks (I guess it, because of where the sounds play).
And it really don't make sense... before everyone heard those noises simultaneously... now it's like "What was that? o_O" "Dunno, only you've heard it".

(For a moment I thought that maybe they broke it on purpose while removing voidfog in the same update, to make Minecraft less creepy, more "friendly".)

**Comment by OreCruncher** [comment]
Yep.  Unfortunately I don't have it where the sound can coordinate across clients since it is purely client side code.  The ambient timer is tied to the client tick and that can vary between clients.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.4 to CurseForge.
