### ISSUE TITLE
Foosteps Not Respecting Movement Speed

### ISSUE THREAD

**Issue by InsomniaKitten** [OreCruncher/DynamicSurroundings#241]
From what I can gather, your custom footstep sounds seem to always play at a constant rate regardless of how fast the player is actually moving. In vanilla, footstep frequency changes relative to the player's current movement speed. This is most noticeable with my WIP mod [Roam](https://github.com/SleeplessDevelopment/Roam), where I change the player's movement speed based on the material they are walking on. I merely multiply their x and z motion by a modifier, so I assume vanilla determines the footstep frequency from motion too. I'm not sure where it is handled so unfortunately, I cannot refer you to the code.

**Mod version:** [1.12.2-3.4.9.3](https://minecraft.curseforge.com/projects/dynamic-surroundings/files/2529271)

EDIT: Okay I may have misheard whilst testing, and I am completely wrong about this. You do seem to change footstep frequency based on movement speed, my bad. >.< Feel free to close this

**Comment by OreCruncher** [comment]
That would be strange.  I notice it when debugging.  The start of detecting velocity is found [here](https://github.com/OreCruncher/DynamicSurroundings/blob/master/src/main/java/org/blockartistry/DynSurround/client/footsteps/system/Generator.java#L182).  The main method for determining if it is a WALK or RUN is [here](https://github.com/OreCruncher/DynamicSurroundings/blob/master/src/main/java/org/blockartistry/DynSurround/client/footsteps/system/Generator.java#L311).
