### ISSUE TITLE
Ghost step (server)

### ISSUE THREAD

**Issue by SimulatorSia** [OreCruncher/DynamicSurroundings#242]
*Mod Version:* 3.4.9.3

*Forge Version:* 14.23.1.2555

I still _hear_ ghost steps in this modpack I have, I put in the latest version of dynamic surroundings and sometimes I go for an hour without any ghost steps but now they won't stop, day and night and very loud. When no one is moving they're there. It sometimes plays the metal step sound and sometimes the stone step sound. Only those two, never dirt or wood or any others.

**Comment by OreCruncher** [comment]
I think it's your pack.  You have it posted somewhere?  Also, enable DS debugging.  When the problem happens again, hit F3 to bring up the debug screen and take a screenshot.  I would like to take a look at the info there.

**Comment by SimulatorSia** [comment]
I can recreate it!!! It happens on multiplayer and singleplayer, with mods and without any mods. When you move a villager in a minecart, then break the minecart. Stepping comes from the block where the villager was standing when you broke the minecart. I figured it out because once I broke the block he was standing on, the loud constant step sounds stopped.

**Comment by OreCruncher** [comment]
What block was the villager on?  I set up a small rail loop and got a villager in the cart.  During it's travels I break the cart and the villager lands on the ground.  I don't get any extra footsteps.

**Comment by OreCruncher** [comment]
Also, try [this JAR](https://github.com/OreCruncher/DynamicSurroundings/releases/tag/v3.4.9.4T2) to see if it happens.

**Comment by OreCruncher** [comment]
Ah!  I think I got it to do it.  Now to dig into it.

**Comment by OreCruncher** [comment]
I updated the test JAR with a tweak.  Let me know if it fixes on your end.

**Comment by SimulatorSia** [comment]
*Testing it out as soon as I get to my computer*
It's really funny how we take such tiny glitches so seriously. It's such a weird circumstance to cause a minor glitch but it reminds me of this
https://www.youtube.com/watch?v=Lg73GKm7GgI
(it's hilarious)

**Comment by OreCruncher** [comment]
Funny video.  Since the mod's focus is on sound/sight it makes sense to track these little things down.  For me this particular issue I only saw ONCE.  I wasn't able to duplicate again.  My theory is that either: a) the mob is trying to walk while inside of the minecart, or b) the data state in the entity object is changing such that it looks like it is walking.  Either way I added a check a into the footstep logic to test whether the mob is riding something, and if so just don't process footsteps.

**Comment by SimulatorSia** [comment]
With the test jar. I can't recreate the footstep sound with a villager. And the villager was standing on natura eucalyptus wood the very first time. The second time in creative he was standing on stone bricks after I recreated it. I tried again on stone bricks after downloading the test jar and no sound.

**Comment by OreCruncher** [comment]
Good to hear!  I'm going to mark fixed for next BETA.  If for some reason it happens again let me know.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.4 to CurseForge.
