### ISSUE TITLE
[Mod Support] Twilight Forest

### ISSUE THREAD

**Issue by tyra314** [OreCruncher/DynamicSurroundings#244]
I really like the fireflies with albedo, however, they seem to be missing in the twilight forest. It would be great if fireflies would spawn the whole day in the twilight forest, as this dimension doesn't have a day-night cycle.

**Comment by OreCruncher** [comment]
Twlight Forest support is on my list of things to work on.  I can certainly look at this.

**Comment by tyra314** [comment]
Love you man. Can't wait to see the fireflies :D

**Comment by OreCruncher** [comment]
Pushed v3.4.9.5 to CurseForge.
