### ISSUE TITLE
Fresh Install Crash

### ISSUE THREAD

**Issue by socalguy562** [OreCruncher/DynamicSurroundings#247]
*Mod Version:* 1.12.2-3.4.9.4

*Forge Version:* 1.12.2

*Link to crash log (if applicable):*
[fml-client-latest.log](https://github.com/OreCruncher/DynamicSurroundings/files/1734297/fml-client-latest.log)
*Description:*
![capture](https://user-images.githubusercontent.com/36579031/36347047-032bfd38-1402-11e8-8b69-49dbb65888c8.PNG)

**Comment by socalguy562** [comment]
I updated to the 64 version of java and allocated more memory and still the same issues. If I delete the mod game is fine. It's the first one I'm trying to install.

**Comment by 23Link89** [comment]
Your attached file isn't a crash log, it's a forge log. Please instead of going to your log folder, go to your crash-reports folder and send that file instead via attaching or pastebin

**Comment by OreCruncher** [comment]
You are trying to run the 1.7.10 version of Dynamic Surroundings in a 1.12.2 Minecraft install.  The line "Examining for coremod candidacy DynamicSurroundings-1.7.10-1.0.6.0.jar" gives it away. :)  Make sure you  have the correct version.  The JAR name should be "DynamicSurroundings-1.12.2-3.4.9.4.jar".  My official upload of that version can be found [here](https://minecraft.curseforge.com/projects/dynamic-surroundings/files/2532273).

**Comment by socalguy562** [comment]
Thank you for the quick responses. I was downloading the green button download instead of the latest. Thanks for the help.
