### ISSUE TITLE
[REQUEST] Custom altitude for elevation haze 

### ISSUE THREAD

**Issue by Cre8or** [OreCruncher/DynamicSurroundings#248]
*Mod Version:* 3.4.9.4

*Forge Version:* 12.18.3.2511

*Link to crash log (if applicable):* n/a

*Description:*

Using Optifine, it is possible to change the cloud height to much higher altitudes. This is, ofcourse, a purely cosmetic change, but one that is useful for some Biomes O Plenty worlds that have Alps or Crag biomes (which can reach all the way up to the world's building height limit).

Using Dynamic Surroundings, it is possible (especially with the latest alpha version) to have elevation haze, which complements the Minecraft clouds splendidly. However, it does not take the modified cloud height into account.

A simple fix for this issue would be a slider (or number input) in the elevation haze settings to specify an offset to the default cloud height, to once again make the haze altitude match the clouds altitude.

**Comment by OreCruncher** [comment]
Dynamic Surroundings bases cloud height based on what the world provider says.  Sometimes a mod implements what it thinks cloud height is but doesn't tell the rest of the universe, like in this case.  What you can do is create an external configuration file that redefines cloud height for your dimensions.  You can find that information [here](https://github.com/OreCruncher/DynamicSurroundings/wiki/Tutorial:-Configuration-Files).  The pertinent section is related to dimension configuration.

**Comment by OreCruncher** [comment]
Oops.

**Comment by Cre8or** [comment]
Thanks for the heads up, I didn't know your mod was this flexible - just made a config to fix the cloud height, worked like a charm. Keep up the good work!

**Comment by OreCruncher** [comment]
No worries.  :)  Glad you have your issue resolved.
