### ISSUE TITLE
java.lang.NullPointerException: Ticking entity

### ISSUE THREAD

**Issue by Hypsellis** [OreCruncher/DynamicSurroundings#25]
I got this crash while walking on the world, I don't know what caused it. http://pastebin.com/mp
I had already reported this issue to Immersive Engineering devs, but it seems the problem come from Dynamic Surroundings. https://github.com/BluSunrize/ImmersiveEngineering/issues/1846

**Comment by Hypsellis** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/1846#issuecomment-271757969

**Comment by OreCruncher** [comment]
@Hypsellis Are you able to jump and get the jump sound?

**Comment by Hypsellis** [comment]
I don't know, I get the crash before.

**Comment by OreCruncher** [comment]
@Hypsellis Can you try Forge 2185?  It is the latest recommended build.

**Comment by Hypsellis** [comment]
It's the one I use.

**Comment by OreCruncher** [comment]
@Hypsellis OK - I think I know what the problem is.  Going to work on getting it tested.  I expect to have a build posted tomorrow.

**Comment by OreCruncher** [comment]
3.2.1.1 pushed to CurseForge.
