### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Nexusdog** [OreCruncher/DynamicSurroundings#256]
MC/F 1.12.2/2618

Accidentally pressed F8, & although it said successfully reloaded sounds there were none - exited the game & got met with 'an unexpected crash has occurred' message at main menu.

https://pastebin.com/XTnNnyBB

**Comment by OreCruncher** [comment]
And? :)  The stack trace indicates it's AmbientSounds. :)  @CreativeMD - this one appears to be yours.

**Comment by CreativeMD** [comment]
Yeah, i will try to fix it, but it might be a good idea to report this issue here: https://github.com/CreativeMD/AmbientSounds

**Comment by OreCruncher** [comment]
@Nexusdog Looks like CreativeMD posted a fix for AmbientSounds.  I'm going to close this issue out.  If the problem persists create an issue at the AmbientSounds repo linked above.

**Comment by Nexusdog** [comment]
My apologies guys, I had a stab at what the issues was & what the likely cause was. :-/
