### ISSUE TITLE
[Bug] Client Crash

### ISSUE THREAD

**Issue by iamtpage** [OreCruncher/DynamicSurroundings#257]
*Mod Version:* DynamicSurroundings-1.12.2-3.4.9.4.jar

*Forge Version:* forge-1.12.2-14.23.2.2611-universal

*Link to crash log (if applicable):* https://gist.github.com/iamtpage/b467312196f7135e2585dce18a476386

*Description:* Minecraft boots up, and when I go to join my server, the client crashes and the crash log above is produced. I resolved the issue by disabling DynamicSurroundings

**Comment by OreCruncher** [comment]
Thanks!  Another situation where the player entity starts getting update ticks before the game fully initializes. :\  Have to love Forge modding. :)

**Comment by OreCruncher** [comment]
Pushed v3.4.9.5 to CurseForge.
