### ISSUE TITLE
Crash with Advanced Rocketry while in space

### ISSUE THREAD

**Issue by EnderMelody** [OreCruncher/DynamicSurroundings#259]
Mod version: 1.10.2-3.4.7.2

Forge Version: 12.18.3.2511

Link to crash log (if applicable): no normal crash log but a pid was created: https://pastebin.com/EdDfKVc0

Description: As far as I can tell it only crashes when I am at a space station from Advanced Rocketry. I can be in the dimension for a long time without problems, but sometimes it crashes. This time it crashed after about 2 minutes. It never creates a crash report and just closes minecraft.

Modlist: https://pastebin.com/YfPXiGDR

**Comment by OreCruncher** [comment]
That is a hard JVM crash.  It looks to be an older version of 1.8 Java.  Try updating to the latest.

**Comment by EnderMelody** [comment]
Sorry, I've been busy. Ill try that when I get the chance and see if it works.

**Comment by OreCruncher** [comment]
@EnderMelody Have you had a chance to check it out?

**Comment by EnderMelody** [comment]
I have not had time to try updating, but last time i played it didnt have any problems so I there is no way for me to tell if it will happen again. If it does happen again I will try updating and tell you if it fixes it. Thanks for continuing to make mods!

**Comment by OreCruncher** [comment]
I am going to close this issue out as addressed.  If you have further issues let me know.
