### ISSUE TITLE
Friend encountering crashes with this mod

### ISSUE THREAD

**Issue by Sunconure11** [OreCruncher/DynamicSurroundings#265]
https://pastebin.com/gKxPRx1G

**Comment by OreCruncher** [comment]
Think this is the same as [#264].

**Comment by OreCruncher** [comment]
Try this JAR out.  Its a sandbox build is going to be close to what I publish this weekend: https://github.com/OreCruncher/DynamicSurroundings/releases/tag/1.12.2-3.4.9.6T4.  This should fix 264 as well.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.6 to CurseForge with fixes.
