### ISSUE TITLE
Better Support for Other Mods' Tools and Armour

### ISSUE THREAD

**Issue by TechnoMysterio** [OreCruncher/DynamicSurroundings#272]
As a general improvement for the mod, supporting other mods' tools and armour so that they gain appropriate sounds would be good. I've noticed that a lot of mods already have json files in Dynamic Surroundings' jar file for footsteps and ambient sounds in them, but they don't have support for said mods' tools and armour. 

A few highlights of tools/armour sets from already supported mods with missing sounds I noticed:

Astral Sorcery's mantle armours and rock crystal tools
Blood Magic's Bound Tools and Armour, Sentient Armour (Sentient Tools already have sounds), and the dagger of sacrifice
Ceramic's Clay Armour
Embers' Clockwork Tools and Ashen Armour
Ice and Fire's Silver Armour/Tools, Dragon Bone Armour/Tools, Disguise Armour
NetherEx's many tools and armour sets
Tinkers' Construct does have a lot of tool types already supported, but many tools like the Frying Pan and Hammer don't have sounds
Tough as Nails' Wool Armour/Jelly Armour

And here are a few fairly popular mods without current support:

Better With Mods has Soul Steel Armour
Botania, most of its weapons and tools automatically gain sounds, but its armours don't
Immersive Engineering has Faraday Armour, Mining Drill, Revolver, Chemthrower and the Railgun
Random Things has a few helmets, boots and tools
Tinkers' Complement has Manyullyn Armour and a few new tool types

Better support for mods like this would be excellent, as it seems rather weird how standard iron armour makes more noise than Steel Plate armour in modpacks.

**Comment by OreCruncher** [comment]
Armor/weapon support is rather intensive to support so when I work on a given mods config I visit those things.  However, if mods use the same classes that Minecraft does (i.e. derive from ItemTool, etc.) DS can infer armor/item sounds and does so.  In fact there are a lot of mods that do this and do not require specific config support. :)

BTW, if you are savvy enough I do accept pull requests for mod config updates. :D

**Comment by TechnoMysterio** [comment]
I have made a json files for a few mods, but I don't know how to use GitHub very well. Would uploading them in a zip file be OK? If so, any preferred/not-preferred sites?

**Comment by OreCruncher** [comment]
No preference, but don't like using sites that serve up ads.  Reason is those places are haven for malware.

**Comment by TechnoMysterio** [comment]
These files are probably missing one or two things, and I may create/rewrite some in the future, but this should be a good start anyway. Hope MEGA's ok with you:

https://mega.nz/#!5DwxkBgB!7d9yQzvLi-gPrnw48Ek354cRHsyCTqbIe4Jz91KqyNU

**Comment by OreCruncher** [comment]
Yep - Megas fine.  I will take a look at them.  Thanks!

**Comment by TechnoMysterio** [comment]
No problem, I missed out on Tough As Nails' Armours, as it's a bit hard to apply sounds to jelly/wool armour when you've got a choice between leather, metal, other metal and crystal... is slime well known for being particularly metallic?

**Comment by OreCruncher** [comment]
We would have to ask the TConstruct guys since they are the slime experts. :)

**Comment by TechnoMysterio** [comment]
Yeah, I always found it a bit weird how much slime related stuff is in Tinkers'. I feel they may enjoy it a little too much somehow... ew...

**Comment by TechnoMysterio** [comment]
Well, I figured I didn't have much else to do, so I wrote some more compat files and updated a few others. Download here:

https://mega.nz/#!IT4mRbKI!0GKme8IMmwk2lkrHU_ZaaX5owXPHy1chMl54d4ZLRtg

I must admit that I haven't tested them, but I have checked them carefully and I've passed them through jsonlint, so hopefully that's enough.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.7 to CurseForge.
