### ISSUE TITLE
Crash with Sound Engine

### ISSUE THREAD

**Issue by BrisingrAerowing** [OreCruncher/DynamicSurroundings#273]
*Mod Version:* 3.4.9.6

*Forge Version:* 2623

*Link to crash log (if applicable):* [Crash Log](https://gist.github.com/BrisingrAerowing/311cd816ba73af4b079a28bf38b62e11)

*Description:* Game startup crash.

**Comment by OreCruncher** [comment]
Was Forge complaining about a mod dependency issue at the time of the crash?

**Comment by BrisingrAerowing** [comment]
No. Reverting to 3.4.9.5 fixed it.

**Comment by OreCruncher** [comment]
The prior version didn't have this particular issue because it is new code that is being triggered.  Would you happen to have the client log available?  I want understand the context around the crash a bit better.

**Comment by BrisingrAerowing** [comment]
I should. Let me check and find the log.

**Comment by BrisingrAerowing** [comment]
And now it loads perfectly fine. I changed nothing other than the DS version. 😕 Gah. Errors like this are the bane of my existence as a programmer.

**Comment by OreCruncher** [comment]
It's the particular nature of this issue.  It appears timing related.  The only time I have seen this issue in development is when Forge fails a mods dependency check.  I suspect, though, that there may be mod interactions that alter the startup timing which triggers the problem.  Regardless it is going to be fixed for the next BETA. :)  Thanks!
