### ISSUE TITLE
Crash on bootup related to Solar

### ISSUE THREAD

**Issue by Sunconure11** [OreCruncher/DynamicSurroundings#274]
*Mod Version:*

DynamicSurroundings-1.12.2-3.4.9.6

*Forge Version:*

14.23.2.2624

*Link to crash log (if applicable):*

https://pastebin.com/3YPvms6c

*Description:*

This crash is preventing me from loading my game.

**Comment by Sunconure11** [comment]
I believe it to be connected to @ArekkuusuJerii's Solar.

**Comment by OreCruncher** [comment]
I have seen this problem under other circumstances, like when Forge detects a mod dependency failure and reports it.  This JAR address that issue and should address the one here: https://github.com/OreCruncher/DynamicSurroundings/releases/tag/1.12.2-3.4.9.7T4

**Comment by OreCruncher** [comment]
Pushed v3.4.9.7 to CurseForge.
