### ISSUE TITLE
weird client crash (when leaving modpack server)

### ISSUE THREAD

**Issue by SimulatorSia** [OreCruncher/DynamicSurroundings#275]
*Mod Version:* 3.4.9.5

*Forge Version:* 2611

<details>
  <summary>Spoiler</summary>
  ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.4-1.12.2-anarchy.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.0-core.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  MMFMLCorePlugin (MultiMine-1.12.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.5.jar)
  LoadingPlugin (Quark-r1.4-122.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 3/7/18 2:05 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at org.blockartistry.DynSurround.client.handlers.EnvironStateHandler.process(EnvironStateHandler.java:381)
	at org.blockartistry.DynSurround.client.handlers.EffectManager.onTick(EffectManager.java:148)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1137_EffectManager_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.11.6
	Java Version: 1.8.0_162, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2085368736 bytes (1988 MB) / 3348627456 bytes (3193 MB) up to 4772593664 bytes (4551 MB)
	LaunchWrapper: 36 active transformer(s)
          - Transformer: net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
          - Transformer: $wrapper.atomicstryker.multimine.common.fmlmagic.MMTransformer
          - Transformer: $wrapper.vazkii.quark.base.asm.ClassTransformer
          - Transformer: $wrapper.thebetweenlands.core.TheBetweenlandsClassTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: guichaguri.betterfps.transformers.PatcherTransformer
          - Transformer: guichaguri.betterfps.transformers.MathTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.AccessTransformer
          - Transformer: pl.asie.foamfix.coremod.FoamFixAT
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemBlockTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemBlockSpecialTransformer
          - Transformer: $wrapper.pl.asie.foamfix.coremod.FoamFixTransformer
          - Transformer: $wrapper.invtweaks.forge.asm.ContainerTransformer
          - Transformer: $wrapper.org.blockartistry.DynSurround.asm.Transformer
          - Transformer: $wrapper.com.tterrag.blur.BlurTransformer
          - Transformer: $wrapper.team.chisel.ctm.client.asm.CTMTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.TerminalTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 3 total; -Xmx5120m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 Optifine OptiFine_1.12.2_HD_U_C8 71 mods loaded, 71 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                  | Source                                        | Signature                                |
	|:------ |:------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft           | 1.12.2                   | minecraft.jar                                 | None                                     |
	| UCHIJA | mcp                 | 9.42                     | minecraft.jar                                 | None                                     |
	| UCHIJA | FML                 | 8.0.99.99                | forge-1.12.2-14.23.2.2611.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge               | 14.23.2.2611             | forge-1.12.2-14.23.2.2611.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | foamfixcore         | 7.7.4                    | minecraft.jar                                 | None                                     |
	| UCHIJA | jei                 | 4.8.5.157                | jei_1.12.2-4.8.5.157.jar                      | None                                     |
	| UCHIJA | abyssalcraft        | 1.9.4.4                  | AbyssalCraft-1.12.2-1.9.4.4.jar               | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCHIJA | quark               | r1.4-122                 | Quark-r1.4-122.jar                            | None                                     |
	| UCHIJA | autoreglib          | 1.3-15                   | AutoRegLib-1.3-15.jar                         | None                                     |
	| UCHIJA | battletowers        | 1.6.1                    | BattleTowers-1.12.2.jar                       | None                                     |
	| UCHIJA | bibliocraft         | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar             | None                                     |
	| UCHIJA | biomesoplenty       | 7.0.1.2315               | BiomesOPlenty-1.12.2-7.0.1.2315-universal.jar | None                                     |
	| UCHIJA | blockdrops          | 1.4.0                    | blockdrops-1.12.2-1.4.0.jar                   | None                                     |
	| UCHIJA | blur                | 1.0.4-14                 | Blur-1.0.4-14.jar                             | None                                     |
	| UCHIJA | chiselsandbits      | 14.14                    | chiselsandbits-14.14.jar                      | None                                     |
	| UCHIJA | ichunutil           | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                    | None                                     |
	| UCHIJA | ftbl                | 4.2.5                    | FTBLib-4.2.5.jar                              | None                                     |
	| UCHIJA | ftbu                | 4.2.4                    | FTBUtilities-4.2.4.jar                        | None                                     |
	| UCHIJA | carryon             | 1.7.2                    | CarryOn MC1.12.2 v1.7.2.jar                   | None                                     |
	| UCHIJA | chameleon           | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| UCHIJA | chococraft          | 0.9.1.52                 | chococraft_1.12.1-0.9.1.52.jar                | None                                     |
	| UCHIJA | ctm                 | MC1.12-0.2.3.12          | CTM-MC1.12-0.2.3.12.jar                       | None                                     |
	| UCHIJA | dimdoors            | 3.0.7-b-1                | Dimdoors-3.0.7-b-1.233.jar                    | None                                     |
	| UCHIJA | dldungeonsjdg       | 1.11.1                   | DoomlikeDungeons-1.11.1-MC1.12.2.jar          | None                                     |
	| UCHIJA | dungeontactics      | DT-0.14.2                | DungeonTactics-1.12.2-0.14.2.jar              | None                                     |
	| UCHIJA | dsurround           | 3.4.9.5                  | DynamicSurroundings-1.12.2-3.4.9.5.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJA | presets             | 3.4.9.5                  | DynamicSurroundings-1.12.2-3.4.9.5.jar        | None                                     |
	| UCHIJA | erebus              | 1.0.19                   | Erebus-1.0.19.jar                             | None                                     |
	| UCHIJA | foamfix             | 0.9.4-1.12.2             | foamfix-0.9.4-1.12.2-anarchy.jar              | None                                     |
	| UCHIJA | gottschcore         | 1.2.0                    | GottschCore-mc1.12.2-f14.23.1.2555-v1.2.0.jar | None                                     |
	| UCHIJA | gravestone          | 1.10.1                   | gravestone-1.10.1.jar                         | None                                     |
	| UCHIJA | harshencastle       | 0.13.1                   | HarshenCastle-0.13.1.jar                      | None                                     |
	| UCHIJA | placebo             | 1.2.0                    | Placebo-1.12.2-1.2.0.jar                      | None                                     |
	| UCHIJA | hexxitgear          | 2.7.0                    | Hexxit Gear-1.12.2-2.7.0.jar                  | None                                     |
	| UCHIJA | infernalmobs        | 1.7.5                    | InfernalMobs-1.12.2.jar                       | None                                     |
	| UCHIJA | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJA | ironchest           | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar               | None                                     |
	| UCHIJA | itemzoom            | 1.10                     | itemzoom_1.12.1-1.10.jar                      | None                                     |
	| UCHIJA | jehc                | 1.3.1                    | jehc-1.12-1.3.1.jar                           | None                                     |
	| UCHIJA | jepb                | 1.2.1                    | jepb-1.12-1.2.1.jar                           | None                                     |
	| UCHIJA | journeymap          | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| UCHIJA | jrftl               | 1.1                      | JRFTL[1.12.2]-1.1.jar                         | None                                     |
	| UCHIJA | jeresources         | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar       | None                                     |
	| UCHIJA | magma_monsters      | 0.3.0                    | MagmaMonsters-0.3.0.jar                       | None                                     |
	| UCHIJA | malisiscore         | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                  | None                                     |
	| UCHIJA | malisisblocks       | 1.12.2-6.1.0             | malisisblocks-1.12.2-6.1.0.jar                | None                                     |
	| UCHIJA | malisisdoors        | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| UCHIJA | mantle              | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                      | None                                     |
	| UCHIJA | modnametooltip      | 1.10.0                   | modnametooltip_1.12.2-1.10.0.jar              | None                                     |
	| UCHIJA | morebeautifulplates | 1.12.2-1.0.3             | morebeautifulplates-1.12.2-1.0.3.jar          | None                                     |
	| UCHIJA | multimine           | 1.5.8                    | MultiMine-1.12.2.jar                          | None                                     |
	| UCHIJA | natura              | 1.12.2-4.3.2.42          | natura-1.12.2-4.3.2.42.jar                    | None                                     |
	| UCHIJA | neat                | 1.4-15                   | Neat 1.4-15.jar                               | None                                     |
	| UCHIJA | nex                 | 2.1.14.15                | NetherEx-1.12-2.1.14.15.jar                   | None                                     |
	| UCHIJA | nofov               | 1.0.1                    | NoFov-MC1.12-1.0.1.jar                        | None                                     |
	| UCHIJA | oretweaker          | 1.0.2-1.12.0             | Ore Tweaker-1.0.2-1.12.0.jar                  | None                                     |
	| UCHIJA | tconstruct          | 1.12.2-2.9.1.65          | TConstruct-1.12.2-2.9.1.65.jar                | None                                     |
	| UCHIJA | xreliquary          | 1.12.2-1.3.4.742         | Reliquary-1.12.2-1.3.4.742.jar                | None                                     |
	| UCHIJA | roguelike           | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |
	| UCHIJA | ruins               | 16.9                     | Ruins-1.12.jar                                | None                                     |
	| UCHIJA | secretroomsmod      | 5.3.2                    | secretroomsmod-1.12.2-5.3.2.jar               | None                                     |
	| UCHIJA | shatter             | 7.0.0                    | Shatter-Mod-1.12.2.jar                        | None                                   |
	| UCHIJA | soulshardstow       | 1.12-2.7.4-53            | SoulShards-TOW-1.12-2.7.4-53.jar              | None                                     |
	| UCHIJA | storagedrawers      | 1.12-5.2.5               | StorageDrawers-1.12.2-5.3.4.jar               | None                                     |
	| UCHIJA | thebetweenlands     | 3.3.0                    | TheBetweenlands-3.3.0-universal.jar           | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UCHIJA | theoneprobe         | 1.4.19                   | theoneprobe-1.12-1.4.19.jar                   | None                                     |
	| UCHIJA | toroquest           | 1.12.2-5.2               | toroquest-1.12.2-5.2.jar                      | None                                     |
	| UCHIJA | treechopper         | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar                  | None                                     |
	| UCHIJA | twilightforest      | 3.6.345                  | twilightforest-1.12.2-3.6.345-universal.jar   | None                                     |

	Loaded coremods (and transformers): 
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.4-1.12.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.0-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
BlurPlugin (Blur-1.0.4-14.jar)
  com.tterrag.blur.BlurTransformer
MMFMLCorePlugin (MultiMine-1.12.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.5.jar)
  org.blockartistry.DynSurround.asm.Transformer
LoadingPlugin (Quark-r1.4-122.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1 ATI-10.0.52' Renderer: 'ATI Radeon HD 4670 OpenGL Engine'
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Launched Version: forge-14.23.2.2611
	LWJGL: 2.9.2
	OpenGL: ATI Radeon HD 4670 OpenGL Engine GL version 2.1 ATI-10.0.52, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
	Type: Client (map_client.txt)
	Resource Packs: Modded Resources, Faithful 1.12.2-rv4, Sims Custom pack
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3 CPU 540 @ 3.07GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C8
	Render Distance Chunks: 10
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 ATI-10.0.52
	OpenGlRenderer: ATI Radeon HD 4670 OpenGL Engine
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4
</details>

Description: Using latest Hexxit modpack (sorry I know it's very large and difficult to narrow down) and when ever I leave this public server to go to the main menu it crashes reliably every time with this same crash, I've tried removing Dynamic Surroundings and the crash goes away. Adding it back also makes it crash when leaving again.
https://minecraft.curseforge.com/projects/hexxit-updated

**Comment by OreCruncher** [comment]
I think this problem is already fixed in my sandbox.  Give this test JAR a try: https://github.com/OreCruncher/DynamicSurroundings/releases/tag/1.12.2-3.4.9.7T4

**Comment by OreCruncher** [comment]
Pushed v3.4.9.7 to CurseForge.

**Comment by SimulatorSia** [comment]
yay no crash<3<3<3<3
