### ISSUE TITLE
[Mod Support] - Cosmetic Armor Reworked.

### ISSUE THREAD

**Issue by Z-Tunic** [OreCruncher/DynamicSurroundings#277]
This mod... when added allows players to wear a second set of armor for show while keeping the effects of their worn armor. Like for example... having the look of Diamond Armor on your character while your actual armor is Terrasteel Armor.

Was curious if it was possible to have the Armor Sounds work from Armors worn in the Cosmetic Armor slots, like... overriding the sounds from the actual armor you are using.

For example... the sounds from Cosmetic Diamond Armor being heard instead of the Terrasteel Armor sounds since the Diamond Armor overrides your Terrasteel Armor.

Currently at the moment your actual armor plays the sounds instead of what's worn in the Cosmetic Armor slot, as it remains mute even if no actual armor was worn.

Dunno if possible but would be a neat thing.

**Comment by OreCruncher** [comment]
Took a look at potential support and decided to not do this for the 3.4.9.x release.  Will take a look again for v3.5.x.x.

**Comment by OreCruncher** [comment]
Pushed a BETA of v3.5 to CurseForge.  Note that the new version has a library dependency on OreLib (another library mod I made).  Make sure you read the release notes prior to upgrade.
