### ISSUE TITLE
Weather isn't in sync with Tough As Nails Seasons

### ISSUE THREAD

**Issue by NitroxydeX** [OreCruncher/DynamicSurroundings#278]
*Mod Version:*
3.4.7.2
*Forge Version:*
14.23.2.2611

*Description:*
In #129 it was stated that this problem is already fixed but in the latest Release non-Beta version it's not working. It still shows Rain instead of snow when the season is winter.

Changelog of the new beta versions didn't stated anything related to Tough As Nails-fixes. So I think it's not fixed right now.

**Comment by OreCruncher** [comment]
Have you tried a latest BETA?

**Comment by NitroxydeX** [comment]
Like I stated: No. I've read through the changelogs of all last Beta Builds on Curse and nothing was stated related to Tough As Nails.

**Comment by OreCruncher** [comment]
Wasn't too clear that on whether you tried it or not.  Regardless, what version of TaN are you using?

**Comment by NitroxydeX** [comment]
TaN is 3.1.0.84 - it's the release version

**Comment by OreCruncher** [comment]
Appears they changed some math.  Need to make some tweaks.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.8 to CurseForge.

**Comment by NitroxydeX** [comment]
Thanks for the heads up.
