### ISSUE TITLE
Desert biome keeps switching fog colour

### ISSUE THREAD

**Issue by nytak619** [OreCruncher/DynamicSurroundings#279]
*Mod Version:*
1.12.2-3.4.9.7.
*Forge Version:*
14.23.2.2613

*Link to crash log (if applicable):*

*Description:*
When in desert biome, yellow fog is replaced by blue fog for a milisecond or so.

**Comment by OreCruncher** [comment]
Several qestions:
* What modpack?
* What other biomes are near by (within 20 blocks)?  (If you can get inside the desert where there aren't any other biomes it would be easier.)
* Is it raining, early morning, late evening, etc?

**Comment by nytak619** [comment]
- StatusEffecthud, Ambient Sounds, Dynamic surroundings, Better HUD, SoundFilters
- Can't tell, seed is "-8989846162228293929" without the " - Large biomes
- Midday, no rain.
- No potion
- When moving

**Comment by OreCruncher** [comment]
To help with the "what biomes are nearby" do you know if you are at the edge of the desert region?  Reason I ask is that the logic "averages" the colors of all the biomes in a 20 block square radius around the player position.  The flashing is more than likely due to the fact that some of the biomes in that area are reporting "no fog color" for that block column.

**Comment by nytak619** [comment]
![2018-03-09_19 23 10](https://user-images.githubusercontent.com/36439652/37217810-9ea120c2-23cf-11e8-8171-cf6422d02deb.png)
![2018-03-09_19 24 19](https://user-images.githubusercontent.com/36439652/37217811-9ebf1ba4-23cf-11e8-8856-2c7409679632.png)
Managed to take a screenshot for a second after bunch of screens. Thats how it looks for a second.

Dont see if its chunk loading.

**Comment by OreCruncher** [comment]
Ok.  [Made a test JAR based on some theories](https://github.com/OreCruncher/DynamicSurroundings/releases/tag/1.12.2-3.4.9.8T4).  Can you test it out to see if the problem goes away?

**Comment by nytak619** [comment]
No it wasn't boosted, I also tried it while walking but found it annoying, so reported it.

Cannot seem to replicate it in the jar you've sent

**Comment by OreCruncher** [comment]
Cool.  This was a good find. :)  Fix will be in the next build posted to CurseForge (maybe tomorrow).

**Comment by OreCruncher** [comment]
Pushed v3.4.9.8 to CurseForge.
