### ISSUE TITLE
High Pitched Screech at High Elevations

### ISSUE THREAD

**Issue by Selim042** [OreCruncher/DynamicSurroundings#28]
I'm guessing my range of hearing is greater than who may have tested this particular sound, but at high elevations, along with the wind effect, I can hear a high pitch constant screech.

**Comment by OreCruncher** [comment]
What mod version?

**Comment by Selim042** [comment]
Version 3.2.1.1, biome didn't seem to matter, I tried in deep ocean, swamp, and plains.  The noise seemed to start a bit below the build limit.

**Comment by OreCruncher** [comment]
@Selim042 1.10.2 or 1.11.2?

**Comment by Selim042** [comment]
1.11.2

**Comment by OreCruncher** [comment]
And it doesn't happen for me.  Figures, don't it?  What mod pack are you using?

**Comment by Selim042** [comment]
Just some mods I threw together in Curse. I disabled anything that modifies environmental sounds and it still happened.  It might be there on your side, my hearing range might just be higher.

**Comment by OreCruncher** [comment]
Can you:
* Enable Dynamic Surrounding debug logging and restart client
* Load up your world.  Hit F3 to get the debug display.  Should be some Dynamic Surrounding specific stuff on the left side under the normal Minecraft/Forge stuff.
* Fly to the altitude where you hear the screech.

I am wanting to know if you see something like "EMITTER" in the debug info.  If you do can you tell me what it is (or post a screen shot - would be better).

**Comment by Selim042** [comment]
I can tomorrow.

**Comment by OreCruncher** [comment]
Sounds good. :)

**Comment by OreCruncher** [comment]
The sound that Dynamic Surroundings is emitting is the "dsurround:wind" sound.  No other sounds.  It could be your range of hearing or another mod.  That "SoundSystem: 2/128" tells me there are two sounds playing, one of which is the Emitter.  I am not sure of what the other sound is, but chances are it's not Dynamic Surroundings.

Try adjusting the volume of "dsurround:wind" in the mod's sound volume settings.  Let me know if affects the screech you are hearing.

(I do have tinnitus so if it is in the dsurround:wind sound I am probably not hearing it.)

**Comment by Selim042** [comment]
![2017-01-13_10 59 13](https://cloud.githubusercontent.com/assets/8419844/21938051/4c8bca1c-d97f-11e6-9136-2b46e0888c4a.png)
The only mod I left enabled was Dynamic Surroundings.  I have no clue what could be playing the other sound.

**Comment by OreCruncher** [comment]
You have background music playing?

**Comment by Selim042** [comment]
No it is turned off.

**Comment by OreCruncher** [comment]
Ok.  The other thing you can use to test the sound out is the /playsound command.  Go back to "ground level" and use it to play "dsurround:wind".  If that screech is somehow in that OGG it should show up then as well.

**Comment by Selim042** [comment]
I can hear it when I use playsound.

**Comment by OreCruncher** [comment]
OK.  It's in the dsurround:wind.  Try tweaking the volume to a lesser value and see if it can be diminished.  You can play with the volume and pitch using the /playsound as well.

**Comment by Selim042** [comment]
I can still hear it when the volume is lowered.  If I make the pitch at least 1.25 using playsound it is much less noticeable.

**Comment by OreCruncher** [comment]
You must have some sensitive ears.  Only suggestion I have at this point is to block the "dsurround:wind" sound.  I need to hunt for a replacement sound and that can take a bit of time.

**Comment by Selim042** [comment]
Alright, thanks.  Might it be possible to filter the screech out?  I know very little as to how sound stuff works.

**Comment by OreCruncher** [comment]
That is one of the things I need to look at.  I know little about audio engineering, but it stands to reason that I can take the existing sound and "filter" it.

**Comment by Selim042** [comment]
Okay.

**Comment by Selim042** [comment]
Would it be easier for me to look into it as I can hear it?

**Comment by OreCruncher** [comment]
It would be helpful if you could.  Thanks!

**Comment by Selim042** [comment]
I will see what I can do.

**Comment by TitusArmillius** [comment]
@OreCruncher 
I would like to report that I have the same experience as Selim, regardless of how low the wind sound is their is a high-pitch screeching sound that drives me insane. Also, is there any way to turn down the default sound of the jungle, it is very loud and annoying compared to other biomes. perhaps chnage that sound to something a little less invasive and a bit calmer.

**Comment by OreCruncher** [comment]
@TitusArmillius You can adjust the volume of any sound in the pack using the "Individual Sound Volume Scale Factors" config GUI.  The sound you want to adjust is "dsurround:jungle".  Play with the slider and let me know what you set it to.  I can then use that to gauge what to set the default volume at.

**Comment by Sunconure11** [comment]
I hear the slight screech too on 1.7.10 when you ported it over to 1.7.10. It sounds more like a slight buzzing, or what I imagine tinnitus to sound like. Or alternatively, what everything sounds like when I'm alone.

By any chance, how old are you @TitusArmillius? This is a legitimate question, as us younger individuals can hear things that older individuals cannot.

They even make devices to deter younger individuals by playing sounds that younger individuals can hear, but older individuals cannot.

https://en.wikipedia.org/wiki/The_Mosquito

Check the frequency of the sound, @OreCruncher, and lower it.

**Comment by OreCruncher** [comment]
I ran a lowpass filter on the sound file.  Give it a listen and see if it did the trick: https://github.com/OreCruncher/DynamicSurroundings/blob/1.10.2/src/main/resources/assets/dsurround/sounds/ambient/outside/wind.ogg

**Comment by Sunconure11** [comment]
No weird buzzing or any sounds of the sort, as far as I can tell. Might have to verify with others to make sure though.

**Comment by Selim042** [comment]
@Sunconure11 I am 18
@OreCruncher That sounds much better to me.  Thank you.

**Comment by OreCruncher** [comment]
@Selim042 Thanks for the follow up.  I will update the sound for the next release.

**Comment by AlienXtream** [comment]
i had this too. glad to hear it's been resolved as for me the pitch is quite painful *RIP ears*

**Comment by OreCruncher** [comment]
Pushed released versions to CurseForge.  Let me know if you come across any other annoying sounds.

**Comment by AlienXtream** [comment]
does my sister count?

**Comment by OreCruncher** [comment]
@AlienXtream lol

**Comment by Eonasdan** [comment]
hi @OreCruncher thanks for your hard work on this mod. Unfortunately, it seems like this is present in the latest version. The wind.ogg file has a high pitched whine in the background. It's so bad (to me) that I replaced it with [this sound fx](http://soundbible.com/1810-Wind.html)

MC:   1.12.2
Mod: 3.4.10.5

**Comment by OreCruncher** [comment]
Weird.  I haven’t touched that ohh file since I last updated the OGG file.  What version of DS were you using prior?

**Comment by OreCruncher** [comment]
@Eonasdan The wind recording I am using is a live sound not one generated from software (from Atacama, Chile, of all places).  Did a prior version of DS have a better wind sound, and if so, what version was it?  I haven't updated this OGG in quite a while (about 2 years).

**Comment by OreCruncher** [comment]
@Eonasdan Ping :)

**Comment by Delelo** [comment]
Have experienced the same,  i am playing with 1.7.10 , that is really Rip-ing my ears . i like the mod so much, its so painful to me to disable the wind sound as i hear it most part of the time...

**Comment by Delelo** [comment]
i riped my ears to do this so now i have a low pass filtered at 9500 hz. it seems that the noise was about 10k to 11k hz... where can i post it ?

**Comment by Sagragoth** [comment]
I noticed this in the Savannah (day) sound as well, though to a lesser degree.

**Comment by OreCruncher** [comment]
Thanks to TechnoMysterio the 3.6.0.0 update has fixes for high frequency sounds.
