### ISSUE TITLE
Weird crash

### ISSUE THREAD

**Issue by vpontin** [OreCruncher/DynamicSurroundings#281]
*Mod Version:* DynamicSurroundings-1.12.2-3.4.9.7

*Forge Version:* 1.12.2-forge1.12.2-14.23.2.2624

*Link to crash log (if applicable):* https://gist.github.com/vpontin/09d4d96ef052b7a5897b7e3469640171

*Description:* Got this strange error (the log was generated on my game directory instead of crash-reports) while playing my survival world on minecraft. Since in one part it mentions DS classes i thought it could be more appropriate to find you first.

**Comment by OreCruncher** [comment]
Looks similar to the one in [#259].  The Java version you are running is a bit old - have you tried updating?

**Comment by vpontin** [comment]
Well i didnt even get any update notification on my machine, plus seems like MC is using the crappy JRE the new launcher ships. Will try to switch to the JRE installed on my machine (and which is updated).

**Comment by OreCruncher** [comment]
OK.  Usually these things are JVM/Java library related bugs.  The code that is fingered in the dump is pure Java and is pretty basic stuff.  One thing I learned with the 1.8 versions is to keep up to date.
