### ISSUE TITLE
Walking on Glass, or is it Wood?

### ISSUE THREAD

**Issue by MeinKraft** [OreCruncher/DynamicSurroundings#284]
*Mod Version:*
DynamicSurroundings-1.12.2-3.4.9.8
*Forge Version:*
Forge 1.12.2 - 14.23.2.2625

*Description:*
Maybe nothing to do with your mod but it does seem fitting to your style of mod.

Walking on Glass sounds like youre walking on Wood. Maybe tweak the sound for Glass. Including Tinkers Glass ?  I am running SoundFilters-0.10_for_1.12 mod too.

**Comment by OreCruncher** [comment]
The glass sound has a hollow thunk to it whereas a plank has more of a solid thunk.  This is the original sound from Presence Footsteps. :)  Not sure what a good replacement would be, but I am always looking.

**Comment by MeinKraft** [comment]
maybe part of the 'breaking glass' sound. So it sounds like walking on broken glass but quieter?  Its a weird one. I only noticed because i have a glass floor and thought "thats very woody glass".

**Comment by Tsoccerguy3** [comment]
Careful MeinKraft , your OCD is showing . Minecraft glass will have to substitute for clear acrylic ( type of plastic ) floor as well . A plastic laminate even , Its going to sound close to wood , but that's not glass your walking on . Your going to have to use your imagination . If the OCD persists and you get the chance to walk the transparent deck of say The C.N. Tower or one of the many transparent structural floors around the world , its not going to sound like glass or breaking glass .   

Ore you should close this . This came up when when I was working on P.F. .
