### ISSUE TITLE
Random Java crash: EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by Insane-96** [OreCruncher/DynamicSurroundings#288]
*Mod Version:*
3.4.9.7
*Forge Version:*
14.23.2.2618

*Link to crash log:*
https://pastebin.com/233GdBsY
https://pastebin.com/pCQm4F8i
https://pastebin.com/VuNt5K87
https://pastebin.com/K2F0cTFJ
https://pastebin.com/c98MzVQ4

*Description:*
Sometimes randomly, when using the mod java crashes. Disabling the mod seems like that java no longer crashes.

**Comment by OreCruncher** [comment]
For minecraft these are typically JVM issues. The version of Java you have is an older 1.8 version.  Update your Java and see if the problem goes away.

**Comment by OreCruncher** [comment]
@Insane-96 Have you tried an up to date version of Java 1.8?

**Comment by Insane-96** [comment]
Yep. Seems like is no longer crashing. I didn't test that much, but it
seems like.

**Comment by OreCruncher** [comment]
Cool.  This particular version of Java caused similar issues for other mods as well.  If after a couple more days the problem doesn't show I will close the issue out.  Thanks!

**Comment by Insane-96** [comment]
> This particular version of Java caused similar issues for other mods as well.

The problem is that this version is automatically used by the new launcher and via Twitch App there's no way to change it (unless you use the old launcher, that's what I'm doing, or change java version everytime you open the new launcher)

**Comment by OreCruncher** [comment]
There is a way to change it in Twitch.  In Twtich global settings under the Minecraft options you can change the Minecraft version.  I use Java 1.8 181.  25 is way out of date.

**Comment by Insane-96** [comment]
You can't if you're using the new launcher. The option is grayed out.

Btw, got no more crashes with Java 8u161
