### ISSUE TITLE
Constant water sound and eagle screeching in space stations in Advanced Rocketry.

### ISSUE THREAD

**Issue by Ulisse54** [OreCruncher/DynamicSurroundings#289]
*Mod Version:*
3.4.9.4 for 1.12.2
*Forge Version:*
1.12.2-14.23.1.2604

*Link to crash log (if applicable):*
Not applicable
*Description:*
I discovered this annoying glitch where you can hear a watery sound(somethin along the lines of a stream/river) and occasional eagles or hawks screeching, in space stations. This should not happen in the vacuum of space, and since it's a really minor issue, is there any chance at all for it to be addressed? As a side note, there is no water at all in my station.

**Comment by Curunir** [comment]
Have you checked which biome(s) are registered for that station? My guess is that DS correctly plays the sounds for these biomes, the dimension should just not have them. You can review the current biome in the F3 screen, some other mods can display it as well (JourneyMap, IngameInfoXML and others).

**Comment by Ulisse54** [comment]
It seems like the AR devs have made their own, the biome name is "Space", although space stations spawn at about 130 height in the world, which is where hawks and eagles would normally appear on Earth, I suppose. Although I still can't explain the river sound.

>  P.S.: I just checked dsurround.cfg and found no dimension blacklisting option. Maybe that would be a good addition?

I strongly agree!

**Comment by OreCruncher** [comment]
DS has a fake biome called Space.  It is not something Minecraft is aware of.  Its something that DS uses to attach effects for Y values > world height + 32, or about Y >= 288 for Overworld.  It also has a fake biome called "Clouds" which starts at Y = skyheight / 2, or about Y = 128 for Overworld.

I haven't used the AR mod so I am not entirely sure what it is doing.  In the Revelation instance I am using the AR mod only registers a single biome called "Alien Forest" which has the biome attribute of PLAINS.  Needless to say that biome will have plains sound effects.  The log, though, has some errors related to biome registration and AR so the pack may not be fully sane.

**Comment by Curunir** [comment]
That sounds very sweet. You might even add space-relevant sounds for mods like Advanced Rocketry and Galacticraft one day. Although realistically, those would chiefly be spacesuit breathing and maybe some computer-gizmo sounds suggesting a working space suit.

**Comment by OreCruncher** [comment]
@Ulisse54 Can you do me a favor and post your planetsDef.xml file from the advRocketry config directory?

**Comment by Ulisse54** [comment]
I'm sorry to say that I have no such file in my config directory, not in  `.minecraft/config` or `.minecraft/config/advRocketry` Although, by searching "planetDefs" in the whole .minecraft folder I have found that the file is created in each world, so here is the world I play in usually.
[planetDefs.zip](https://github.com/OreCruncher/DynamicSurroundings/files/1821058/planetDefs.zip)
I'm sorry I had to zip it, GitHub doesn't allow XML files to be uploaded.

**Comment by OreCruncher** [comment]
I'm going to add the dimension blacklist option for now to bridge the gap.  I will replace at some point when I have a better system devised.

**Comment by Ulisse54** [comment]
That sounds great! Thanks for your time :D

**Comment by OreCruncher** [comment]
Pushed v3.4.9.9 with a config option to blacklist dimensions for biome sound play.
