### ISSUE TITLE
Crash Getting Light Value

### ISSUE THREAD

**Issue by InsomniaKitten** [OreCruncher/DynamicSurroundings#290]
The game crashed after I tabbed out to check Discord.. somehow a light value was -1, idek. 

**Mod version:** [1.12.2-3.4.9.8](https://minecraft.curseforge.com/projects/dynamic-surroundings/files/2540758)
**Crash report:** [pastebin:crash-2018-03-17_17.18.18-client.txt](https://pastebin.com/8KvEvusc)

**Comment by OreCruncher** [comment]
This may be fixed with the 3.4.9.9 version I am finalizing.  I saw something similar in dev and it was really strange.

**Comment by Josh74000** [comment]
I found a bug too, auroras appear on the ground instead of in the sky.

**Comment by OreCruncher** [comment]
Are you in Overworld or a modded dimension?

**Comment by OreCruncher** [comment]
Pushed v3.4.9.9 to CurseForge for the crash.
