### ISSUE TITLE
Crashes involving BiomeFogColorCalculator

### ISSUE THREAD

**Issue by xeronut** [OreCruncher/DynamicSurroundings#291]
*Mod Version:*
MC1.7.10-DynSurround v1.0.6.1
*Forge Version:*
MC1.7.10-10.13.4.1614

*Link to crash log (if applicable):*
https://pastebin.com/EbyeWezx
*Description:*
All fog effects were enabled in configs.  Crash occurred while out exploring at night just before the sun rose.  Every attempt to restart the world resulted in an identical crash.  Partially/completely disabling fog effects in the configs did not allow me to access my world (crash on load), but deleting/regenerating configs *then* disabling all fog effect combined with deleting dsurround.dat from the world save folder allowed me to load it.

**Comment by OreCruncher** [comment]
Did you have a blindness potion effect going?

**Comment by xeronut** [comment]
It's possible, as I was fighting mobs and some of them bestow status effects thanks to Infernal Mobs, though I didn't specifically notice it.  I'll turn fog options back on in the config and blind myself to see if that triggers the crash - I'll edit this comment with results.

**Comment by LemADEC** [comment]
I confirm the issue is reproduced on 1.7.10 with blindness potion effect. Any chance we get a fix soon? or should we temporary remove the mod for now?

**Comment by OreCruncher** [comment]
I am currently wrapping up the 1.10.x+ releases.  Once I am done with that I will be working on 1.7.10.  I figure I will have an update to 1.7.10 within the week.

**Comment by LemADEC** [comment]
ok, tk

**Comment by OreCruncher** [comment]
Pushed v1.0.6.2 with the fix.  Let me know how it goes.
