### ISSUE TITLE
Dynamic Surroundings Beta branch crashes when used with Vivecraft

### ISSUE THREAD

**Issue by Cirom** [OreCruncher/DynamicSurroundings#294]
*Mod Version:* 3.4.9.8 (Note: The latest Release version, 3.4.7.2, seems to work fine, so it's definitely an issue with the beta.)

*Forge Version:* forge-14.23.2.2624

*Vivecraft Version:* 1.12.2-jrbudda-6-final-r1-forge

*Link to crash log (if applicable):* Pastebin! https://pastebin.com/NTtMY65g

*Description:*
Basically, when launching Vivecraft with any version of Dynamic Surroundings beyond version 3.4.7.2, the game immediately crashes with the above crash log. I've spoken with the Vivecraft devs about this, and apparently Dynamic Surroundings is changing something with Vec3d which is causing things to break. (I'll admit, I'm not too knowledgeable on this, I'm a player not a coder :V)

I'm curious to know what would have changed between 3.4.7.2 and this version, though. Unfortunately I can't just temporarily use the 3.4.7.2 version on the world I've been playing with, as for some reason as soon as I approach a forest biome the game just freezes up and the console gets spammed with messages saying that it failed to load a resource because it doesn't exist or something like that.

**Comment by OreCruncher** [comment]
No, DS does not change Vec3d.  I will take a look at the log to see what may be going on.

**Comment by Cirom** [comment]
Disabling Optifine is not an option, as Vivecraft comes with Optifine built-in (and basically requires it to run).

**Comment by OreCruncher** [comment]
You can update to the latest 1.12.2 preview build since it has the fix.

**Comment by Cirom** [comment]
To quote one of the Vivecraft devs, _"it's thoroughly integrated into our code, can't just be updated that easily"_

I tried running Dynamic Surroundings with both the version of Optifine Vivecraft currently uses (C9) and the latest Preview build, however. _Both worked just fine._ The game booted up without a crash. I'm not sure if it's an interaction with Optifine after all.

**Comment by OreCruncher** [comment]
Hard to tell.  I know that OptiFine is really intrusive with it's ASM and how it hooks into the ASM process.  I have seen other problems that occur at startup, but never have been seen again.  It is very possible that with Vivecraft in the mix the loading order is changed and it is what triggers the issue.

**Comment by jrbudda** [comment]
Yea we do not modify Vec3d, and neither does Optifine. Forge does, tho. 

I've seen similar errors with ASM before, and I'm thinking the error started when you switched from just  ClassWriter.COMPUTE_MAXS  to  ClassWriter.COMPUTE_MAXS | ClassWriter.COMPUTE_FRAMES in your classwriter code.

Is the recalculation of frames necessary? it wasn't used prior to the beta branch and I'm wondering if switching back to just the MAXS flag, at least for PatchEntityRenderer, might fix it.

**Comment by OreCruncher** [comment]
I was wondering the same thing.  It's on my list of things to check out.

**Comment by jrbudda** [comment]
oooh here's someone with the same problem suggesting the same solution 

https://stackoverflow.com/questions/26573945/classnotfoundexception-at-asm-objectwriter-getcommonsuperclass

**Comment by OreCruncher** [comment]
I made some changes to compute the stack frames if necessary.  Only one of my ASM transforms needs to do that.  OptiFine doesn't mess around with the SoundManager, yet. :)  Changes should show up in a build later today.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.9 with some ASM changes.  Let me know if this does the trick for you.

**Comment by Cirom** [comment]
It does the trick! We're working fine and I can use this mod in VR again! c:

**Comment by OreCruncher** [comment]
Glad to hear!
