### ISSUE TITLE
Major Bug with Foggy BoP biomes

### ISSUE THREAD

**Issue by BrisingrAerowing** [OreCruncher/DynamicSurroundings#298]
*Mod Version:* 3.4.9.9

*Forge Version:* 2631

*Link to crash log (if applicable):*

*Description:* When in a foggy BoP biome, it is impossible to see. Turning off fog processing fixes it.

Screenshot:
![2018-03-27_19 38 20](https://user-images.githubusercontent.com/250409/38000667-ae31c930-31f6-11e8-8719-e71f409485d7.png)

**Comment by OreCruncher** [comment]
Are you running optifine?

**Comment by BrisingrAerowing** [comment]
No optifine.

**Comment by OreCruncher** [comment]
What's your modpack?

**Comment by BrisingrAerowing** [comment]
It's a custom one. [Here's the modlist](http://www.modlister.com/user/BrisingrAerowing)

**Comment by OreCruncher** [comment]
Found it.  Something bonehead I did. :\

**Comment by OreCruncher** [comment]
Pushed v3.4.9.10 to CurseForge that has the fix.  Let me know how it works for you.
