### ISSUE TITLE
Crash with SevTech Ages (forge 2635)

### ISSUE THREAD

**Issue by mistahoward** [OreCruncher/DynamicSurroundings#299]
*Mod Version:* 
3.4.9.10

*Forge Version:*
2635

*Link to crash log (if applicable):*
[crash-2018-03-28_19.36.49-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/1858241/crash-2018-03-28_19.36.49-client.txt)

*Description:*
Crash with Sevtech ages? Figured it was part of the whole sound engine change but even when updating my mod it happens. If I remove dynamic surroundings I no longer have sound, but the game loads. Always at the very end of the loading process, "finalizes" then goes straight to the launcher with a crash.

**Comment by OreCruncher** [comment]
Update AmbientSounds to 2.2.5.

**Comment by mistahoward** [comment]
Yikes! I forgot I had installed that! Thanks my dude.

**Comment by OreCruncher** [comment]
This may also be related to #300.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.11 that has some changes to startup sound processing.  I believe it will also have an impact on this particular issue.  Let me know if the problem persists.
