### ISSUE TITLE
[Enhancement] NetherEx mod compatibility

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/DynamicSurroundings#3]
The Dynamic Surroundings nether effects don't work with the mod.

**Comment by Hypsellis** [comment]
NetherEx is currently in total rewrite state. The version on curse is totally obsolete. The mod changed a lot since this time. It has no use to add a support for it for the time.

**Comment by Sunconure11** [comment]
@Hypsellis What about now?

**Comment by Hypsellis** [comment]
I don't know, I think DynamicSurroundings supports it pretty well, but you should try it by yourself.

**Comment by OreCruncher** [comment]
Closing this issue out.  There is are more current ones. :)
