### ISSUE TITLE
Tardis And DS

### ISSUE THREAD

**Issue by SvEgiiVEteR** [OreCruncher/DynamicSurroundings#30]
*Mod Version:*
1.0.5.7
*Forge Version:*
1614
*Link to crash log (if applicable):*
https://gist.github.com/6479175c2608aa9980cebc48629066cd
*Description:*
created Tardis of mods .
came and the game broke
http://tardismod.com:8080/job/TardisMod/
on 1.0.5.8 work but not sure.

**Comment by OreCruncher** [comment]
Yes, the 1.0.5.8 version has the fix for this.  Thanks for reporting it, though.
