### ISSUE TITLE
Weird Crash

### ISSUE THREAD

**Issue by Sunconure11** [OreCruncher/DynamicSurroundings#300]
*Mod Version:*

1.12.2-3.4.9.9

*Forge Version:*

14.23.2.2634

*Link to crash log (if applicable):*

https://pastebin.com/JLcq5b7p

*Description:*

Happened at random.

**Comment by OreCruncher** [comment]
I guess this is very sporadic.  Do you happen to have the client log?  I need to see if I can figure out the order of events.  What the trace is telling me is that the sound engine is not fully initialized when the ding logic is run.

**Comment by Sunconure11** [comment]
Rather sporadic, yes. Only happened once.

https://gist.github.com/Sunconure11/75237792a443823ec8032870d056087f

**Comment by OreCruncher** [comment]
Pushed v3.4.9.11 that has changes to defer playing the startup sound until the game loop starts running.  Let me know if this does the trick.
