### ISSUE TITLE
[Suggestion] Hurt Treshhold being able to set percentage

### ISSUE THREAD

**Issue by Xaikii** [OreCruncher/DynamicSurroundings#301]
As I see currently it is possible to set the threshhold directly, but I think for Pack with an increased Health Cap (like mine) it'd be better to set it to percentage since for for a pack where the cap is 100 and the threshhold is at 8, it's not the same as 20:8

**Comment by OreCruncher** [comment]
I thought about this when I put the feature in.  The scenario I had in mind was that if I had a health of 100 vs. 20 of a normal "Steve".  Why should a player with 20/100 get the heart beat when a Steve with 20/20 wouldn't?  It just seemed weird to me. :)
