### ISSUE TITLE
One client has crashed when joining the dedicated server

### ISSUE THREAD

**Issue by Matmatix** [OreCruncher/DynamicSurroundings#302]
*Mod Version:*
dsurround{3.4.9.4}

*Forge Version:*
Forge{12.18.3.2511}

*Link to crash log (if applicable):*
https://pastebin.com/NeAh4Cs2

*Description:*
Not everytime, but sometimes one of the clients crashes when joining my server.  This is a NoClassDefFoundError.

**Comment by OreCruncher** [comment]
Update to the latest BETA.  IIRC this has been fixed in a version post v3.4.9.4.

**Comment by OreCruncher** [comment]
@Matmatix Did updating to the latest BETA solve this problem?

**Comment by Matmatix** [comment]
@OreCruncher Yes the issue appears to be fixed! Thank you for your help.
