### ISSUE TITLE
Fog View Distance Issue

### ISSUE THREAD

**Issue by The-Order** [OreCruncher/DynamicSurroundings#304]
*Mod Version:*
DynamicSurroundings-1.12.2-3.4.9.10
*Forge Version:*
14.23.2.2632

*Link to crash log (if applicable):*
NA
*Description:*
Added dynamic surroundings to all the mods 3 mod pack along side optifine, recent issues with the fog have been fixed, however, with dynamic surroundings installed it seems to set the default limit to where fog appears to 16 chunks. Increasing the view distance beyond 16 chunks with cause them to load into the world but the fog doesn't move further out with it resulting in still only being able to see up to 16 chunks when 32 are actually being loaded when set in the options.

Tried without optifine and same issue occurs. However, disabling the fog handling for this mod solves the problem. Not a major bug but limits view distance for those of us with the beefy computers and bases on top of large mountains.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.14 with changes.
