### ISSUE TITLE
CTD Crash during MC Load

### ISSUE THREAD

**Issue by Nargath** [OreCruncher/DynamicSurroundings#306]
*Mod Version: 1.12.2-3.4.9.11

*Forge Version: 14.23.2.2654

*Link to crash log (if applicable): https://gist.github.com/Nargath/0c0fb535ec63ec20a6104d389755a159

*Description: Minecraft loads almost all the way through the pre-launch stuff, but crashes out just before it gets to the first menu.

**Comment by OreCruncher** [comment]
Update your [AmibentSounds to the latest version](https://minecraft.curseforge.com/projects/ambientsounds/files/2545190).

**Comment by Nargath** [comment]
That did it!
Thank you for the advice, and sorry for the run around. I honestly didn't see that Ambient was still in my modlist!
