### ISSUE TITLE
[Request/Suggestion] Search bar in the "individual sounds" window.

### ISSUE THREAD

**Issue by Geethebluesky** [OreCruncher/DynamicSurroundings#307]
Would it be possible to implement a searchbar inside the Individual sounds window? Mods like Mo'Creatures and Lycanites Mobs add a huge number of entities, thus ambient sounds to the game, and when looking to find what particular sound I need to change the volume on I have to guess which mod it comes from and what its name might be (sometimes they're logical, sometimes not as much).

Having that window searchable would resolve the headache. Thank you :)

**Comment by OreCruncher** [comment]
This is something I look at off and on.  Right now the config dialogs use the Forge framework for presentation.  I would have to write my own configuration framework to make the search box possible.  It would be real nice if Forge had search capability integrated into its framework.

**Comment by mindcloud69** [comment]
I came here to suggest this. Maybe @jaredlll08 the author of [Controlling](https://github.com/jaredlll08/Controlling/tree/1.12/src/main) Might let you use his MIT licensed code to help with this. He has a really polished search function for Minecraft control mapping

**Comment by jaredlll08** [comment]
While my code is MIT, I don't suggest straight up copying it, it is geared towards keybinds and has code specific to them. Besides for that, feel free to learn from / ask my stuff about it.

**Comment by OreCruncher** [comment]
It took a while, but I have come up with something.  Essentially adds a search/filter bar on configuration pages in general, so it is applicable outside of Dynamic Surroundings.  It will be in the next update whenever it hits.

**Comment by OreCruncher** [comment]
Pushed v3.6.0.2 with feature.

**Comment by mindcloud69** [comment]
Thank you for your hard work @OreCruncher !
