### ISSUE TITLE
crash sevtech

### ISSUE THREAD

**Issue by dylanortelee** [OreCruncher/DynamicSurroundings#309]
3.0.6 mod version

*minecraft forge_14.23.2.2561*

[crash-2018-04-11_20.06.09-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/1900082/crash-2018-04-11_20.06.09-client.txt)

if i open the mod and wait it crash at the end of the loading

**Comment by dylanortelee** [comment]
But how do i update ds betas

Outlook voor Android<https://aka.ms/ghei36> downloaden

________________________________

**Comment by OreCruncher** [comment]
[CurseForge download page](https://minecraft.curseforge.com/projects/dynamic-surroundings/files)
