### ISSUE TITLE
The Info of The Rain Bug

### ISSUE THREAD

**Issue by Rapolis** [OreCruncher/DynamicSurroundings#31]
*Mod Version: 1.11.2 Latest*

*Forge Version: 2216*

*Link to crash log (if applicable):*

*Description:
Happens in areas where is snow. Splashless rain. IT HAPPENS EVERYWHERE TOO. Including every biome. It goes through blocks all the way to caverns.*

**Comment by OreCruncher** [comment]
Need the mod list.

**Comment by Rapolis** [comment]
Mod List:
Better FPS (doesnt seem to function in 1.11.2 when its for 1.11)
Better PvP
Dynamic Surroundings
liteloader
Auto Fish
Offline Skins (my internet is crep so i use this)
OptiFine (OBVIOUSLY)
Resource Pack Organizer
Sound Filters

**Comment by OreCruncher** [comment]
Better FPS crashes my 1.11.2.  Have all the other mods exception RPO and I am not seeing the issue.  When you started the world was this happening?  Or did it start happening sometime along the way?

**Comment by Rapolis** [comment]
I noticed it the first time. UGH, the snow is replaced with go-through block rain... EVEN ALL OF THE WORLD RAIN GOES THROUGH BLOCKS!

**Comment by OreCruncher** [comment]
And if you make a new world the same thing?

**Comment by Rapolis** [comment]
Yes... The same thing... Try it out yourself with my mods... Except for Better FPS.

**Comment by OreCruncher** [comment]
Did that.  I don't experience the problem.  Must be some other condition.  It rains even under trees?

**Comment by OreCruncher** [comment]
@Rapolis Can you drop this test JAR in  your config?  I need:

- Let me know if it works (obviously)
- Need a ZIP of the client log because it may have debug trace I need.

Jar is here: https://github.com/OreCruncher/DynamicSurroundings/releases/tag/v3.2.1.2TEST

**Comment by Rapolis** [comment]
OK, it's fixed... Good job maybe... The problem is confirmed to be somehow my problem.
Snow is no longer rain and snow.
Rain doesn't go through blocks.
BUG FIXED. I had to remove a buggy mod and update forge....
SUGGESTION: make waterfalls splash when they flow into water not only when hitting blocks, but both hitting blocks or water. That's a realism issue fix.

**Comment by OreCruncher** [comment]
Glad to hear.  As for the waterfall I have been thinking of doing that.  Main challenge I have is making the detection process efficient so it doesn't cause lag.

**Comment by OreCruncher** [comment]
I worked out the waterfall thing. :)

**Comment by OreCruncher** [comment]
Pushed released versions to CurseForge!
