### ISSUE TITLE
Serene Seasons compatibility for weather

### ISSUE THREAD

**Issue by 63502** [OreCruncher/DynamicSurroundings#312]
*Description:*
Winter in serene seasons currently cools down biome temperatures during winter, allowing snow to fall in normally temperate biomes like regular forests and plains, and excludes these temperature changes from already cold or hot biomes like deserts, ice spike plains, etc. What I noticed while I was playing through my first winter in a regular forest biome was that while snow did accumulate on the ground while precipitation was falling, the precipitation itself was still rain. 

Would it be possible to make the type of precipitation that falls respond to biome temperature changes as well as the type of biome?

**Comment by OreCruncher** [comment]
The moved the season support out of Tough as Nails and into a standalone mod.  I need to make changes to DS to account for this split.  DS supports this via TaN prior to the split.

**Comment by 63502** [comment]
Ok, cool. I haven't used TaN in a long time, so I haven't been keeping track of it's progress. 

I hope everything goes smoothly. 😉

**Comment by Sunconure11** [comment]
Speaking of which @OreCruncher, how far along with it are you? I remember you mentioned something about taxes.

**Comment by OreCruncher** [comment]
@Sunconure11 Yeah.  Got taxes done then ran into health issues.  I will be working on it tomorrow.

**Comment by Technowix** [comment]
@OreCruncher take care of yoursel ! :)
Thanks for taking care of this issue !

**Comment by OreCruncher** [comment]
Pushed v3.4.9.12 to CurseForge with compat changes.
