### ISSUE TITLE
current version of Dynamic Surroundings is not compatible with the current version of Tough as Nails.

### ISSUE THREAD

**Issue by LordDecay26** [OreCruncher/DynamicSurroundings#315]
*Mod Version:*
Latest 1.0.6.2
*Forge Version:*
1.12.2-forge1.12.2-14.23.2.2611

*Link to crash log (if applicable):*
 it's applicable but i've gone over the crash logs with the author of TAN as well as the mod author of the Dark Bestiary add-on mod for I/F and yeah, it's a compatibility issue
*Description:*
game crashes every time you attempt to join the game, with the error message "NoClassDefFoundError: toughasnails/api/season/SeasonHelper" this is caused by Dynamic Surroundings and there isn't anything the author of TAN can do about it, according to him.

**Comment by LordDecay26** [comment]
if you still insist on seeing the crash logs they are as follows.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.6.0.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.1.4-universal (1).jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.11.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 4/24/18 3:41 AM
Description: Unexpected error

java.lang.NoClassDefFoundError: toughasnails/api/season/SeasonHelper
	at org.blockartistry.DynSurround.registry.season.SeasonInfoToughAsNails.getSeasonType(SeasonInfoToughAsNails.java:56)
	at org.blockartistry.DynSurround.client.handlers.EnvironStateHandler$EnvironState.tick(EnvironStateHandler.java:146)
	at org.blockartistry.DynSurround.client.handlers.EnvironStateHandler$EnvironState.access$000(EnvironStateHandler.java:68)
	at org.blockartistry.DynSurround.client.handlers.EnvironStateHandler.process(EnvironStateHandler.java:401)
	at org.blockartistry.DynSurround.client.handlers.EffectManager.onTick(EffectManager.java:173)
	at org.blockartistry.DynSurround.client.handlers.EffectManager.clientTick(EffectManager.java:183)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_29_EffectManager_clientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: toughasnails.api.season.SeasonHelper
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.blockartistry.DynSurround.registry.season.SeasonInfoToughAsNails.getSeasonType(SeasonInfoToughAsNails.java:56)
	at org.blockartistry.DynSurround.client.handlers.EnvironStateHandler$EnvironState.tick(EnvironStateHandler.java:146)
	at org.blockartistry.DynSurround.client.handlers.EnvironStateHandler$EnvironState.access$000(EnvironStateHandler.java:68)
	at org.blockartistry.DynSurround.client.handlers.EnvironStateHandler.process(EnvironStateHandler.java:401)
	at org.blockartistry.DynSurround.client.handlers.EffectManager.onTick(EffectManager.java:173)
	at org.blockartistry.DynSurround.client.handlers.EffectManager.clientTick(EffectManager.java:183)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_29_EffectManager_clientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['PATHOLOG1CAL'/429, l='MpServer', x=-229.50, y=65.00, z=86.50]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 04 - customized, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-232,64,84), Chunk: (at 8,4,4 in -15,5; contains blocks -240,0,80 to -225,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 81 game time, 81 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 28 total; [EntityCreeper['Creeper'/458, l='MpServer', x=-281.50, y=12.00, z=128.50], EntitySheep['Sheep'/332, l='MpServer', x=-242.50, y=68.00, z=74.50], EntityBat['Bat'/460, l='MpServer', x=-309.50, y=28.00, z=119.50], EntitySheep['Sheep'/333, l='MpServer', x=-242.50, y=68.00, z=76.50], EntityLatchedRenderer['unknown'/461, l='MpServer', x=-229.50, y=65.00, z=86.50], EntitySheep['Sheep'/334, l='MpServer', x=-244.50, y=68.00, z=76.50], EntitySkeleton['Skeleton'/462, l='MpServer', x=-309.50, y=47.00, z=93.50], EntitySheep['Sheep'/335, l='MpServer', x=-243.50, y=68.00, z=77.50], EntityButterfly['Butterfly'/464, l='MpServer', x=-293.50, y=68.00, z=34.50], EntityMerpig['Merpig'/277, l='MpServer', x=-327.46, y=46.24, z=180.07], EntityMerpig['Merpig'/278, l='MpServer', x=-329.19, y=53.47, z=187.94], EntityMerpig['Merpig'/279, l='MpServer', x=-325.77, y=51.74, z=173.32], EntityMerpig['Merpig'/280, l='MpServer', x=-323.65, y=53.87, z=175.53], EntitySheep['Sheep'/297, l='MpServer', x=-289.50, y=69.00, z=7.50], EntityMerpig['Merpig'/234, l='MpServer', x=-340.52, y=49.15, z=174.91], EntityPig['Pig'/300, l='MpServer', x=-293.50, y=69.00, z=7.50], EntityPig['Pig'/301, l='MpServer', x=-292.50, y=69.00, z=7.50], EntityPig['Pig'/302, l='MpServer', x=-295.50, y=69.00, z=6.50], EntityPig['Pig'/303, l='MpServer', x=-294.50, y=69.00, z=7.50], EntityPlayerSP['PATHOLOG1CAL'/429, l='MpServer', x=-229.50, y=65.00, z=86.50], EntityBat['Bat'/304, l='MpServer', x=-295.90, y=45.12, z=26.75], EntitySkeleton['Skeleton'/433, l='MpServer', x=-291.50, y=45.00, z=52.50], EntityMerpig['Merpig'/306, l='MpServer', x=-288.15, y=58.38, z=175.86], EntityBat['Bat'/434, l='MpServer', x=-292.50, y=46.00, z=46.50], EntityLatchedRenderer['unknown'/435, l='MpServer', x=8.50, y=65.00, z=8.50], EntityMerpig['Merpig'/307, l='MpServer', x=-287.14, y=56.42, z=165.67], EntityMerpig['Merpig'/308, l='MpServer', x=-302.08, y=55.68, z=162.37], EntityMerpig['Merpig'/309, l='MpServer', x=-296.38, y=57.00, z=156.99]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/435, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2737)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1495423816 bytes (1426 MB) / 2550136832 bytes (2432 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.3.2655 Optifine OptiFine_1.12.2_HD_U_C9 65 mods loaded, 65 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version                     | Source                                        | Signature                                |
	|:--------- |:-------------------- |:--------------------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2                      | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp                  | 9.42                        | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99                   | forge-1.12.2-14.23.3.2655.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.3.2655                | forge-1.12.2-14.23.3.2655.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | antiqueatlas         | 4.4.7                       | antiqueatlas-1.12.2-4.4.7.jar                 | None                                     |
	| UCHIJAAAA | antiqueatlasoverlay  | 1.2                         | antiqueatlas-1.12.2-4.4.7.jar                 | None                                     |
	| UCHIJAAAA | examplemod           | 1.0                         | antiqueatlas-1.12.2-4.4.7.jar                 | None                                     |
	| UCHIJAAAA | astikoor             | 1.0.0                       | astikoor-1.0.0.jar                            | None                                     |
	| UCHIJAAAA | autoreglib           | 1.3-16                      | AutoRegLib-1.3-16.jar                         | None                                     |
	| UCHIJAAAA | babyanimals          | 1.11-2                      | BabyAnimals-1.11-2.jar                        | None                                     |
	| UCHIJAAAA | bamboozled           | 1.1.0                       | Bamboozled-1.12-1.1.0.jar                     | None                                     |
	| UCHIJAAAA | baubles              | 1.5.2                       | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UCHIJAAAA | biomesoplenty        | 7.0.1.2381                  | BiomesOPlenty-1.12.2-7.0.1.2381-universal.jar | None                                     |
	| UCHIJAAAA | carbonado            | 1.4.2                       | carbonado-1.4.2-mc1.12.x.jar                  | None                                     |
	| UCHIJAAAA | codechickenlib       | 3.1.6.339                   | CodeChickenLib-1.12.2-3.1.6.339-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | extendedrenderer     | v1.0                        | coroutil-1.12.1-1.1.24.jar                    | None                                     |
	| UCHIJAAAA | coroutil             | 1.12.1-1.1.24               | coroutil-1.12.1-1.1.24.jar                    | None                                     |
	| UCHIJAAAA | configmod            | v1.0                        | coroutil-1.12.1-1.1.24.jar                    | None                                     |
	| UCHIJAAAA | duckcraft            | 3.0.8                       | Duckcraft-1.12.2-3.0.8.jar                    | None                                     |
	| UCHIJAAAA | dsurround            | 3.4.9.11                    | DynamicSurroundings-1.12.2-3.4.9.11.jar       | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJAAAA | presets              | 3.4.9.11                    | DynamicSurroundings-1.12.2-3.4.9.11.jar       | None                                     |
	| UCHIJAAAA | enhancedvisuals      | 1.0                         | EnhancedVisuals+v1.1.4+mc1.12.2.jar           | None                                     |
	| UCHIJAAAA | silentlib            | 2.2.18                      | SilentLib-1.12-2.2.18-100.jar                 | None                                     |
	| UCHIJAAAA | extendeddays         | 0.2.4                       | ExtendedDays-1.12-0.2.4-20.jar                | None                                     |
	| UCHIJAAAA | familiarfauna        | 1.0.6                       | FamiliarFauna-1.12.2-1.0.6.jar                | None                                     |
	| UCHIJAAAA | felling              | 1.4.0                       | felling-1.4.0-1.12.x.jar                      | None                                     |
	| UCHIJAAAA | foragecraft          | 1.14.2                      | foragecraft-1.14.2.jar                        | None                                     |
	| UCHIJAAAA | forgelin             | 1.6.0                       | Forgelin-1.6.0.jar                            | None                                     |
	| UCHIJAAAA | giacomos_fishing_net | 1.6.1                       | GiacomosFishingNet-1.12.2-1.6.1.jar           | None                                     |
	| UCHIJAAAA | guideapi             | 1.12-2.1.4-57               | Guide-API-1.12-2.1.4-57.jar                   | None                                     |
	| UCHIJAAAA | llibrary             | 1.7.9                       | llibrary-1.7.9-1.12.jar                       | None                                     |
	| UCHIJAAAA | iceandfire           | 1.4.0                       | iceandfire-1.4.0-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | ichunutil            | 7.1.4                       | iChunUtil-1.12.2-7.1.4.jar                    | None                                     |
	| UCHIJAAAA | jei                  | 4.9.1.168                   | jei_1.12.2-4.9.1.168.jar                      | None                                     |
	| UCHIJAAAA | jaff                 | 1.7_for_1.12                | JustAFewFish-1.7_for_1.12.jar                 | None                                     |
	| UCHIJAAAA | testdummy            | 1.12                        | MmmMmmMmmMmm-1.12-1.14.jar                    | None                                     |
	| UCHIJAAAA | naturalbabyanimals   | 1.1.3                       | naturalbabyanimals-1.1.3-mc1.12.x.jar         | None                                     |
	| UCHIJAAAA | nethergoldore        | 1.1.2                       | nethergoldore-1.1.2-mc1.12.x.jar              | None                                     |
	| UCHIJAAAA | notenoughscaffold    | 1.7                         | NotEnoughScaffold-1.12.2-1.7.jar              | None                                     |
	| UCHIJAAAA | owls                 | 1.12.2-1.0.1                | Owls-1.12.2-1.0.1.jar                         | None                                     |
	| UCHIJAAAA | bonecraft            | 1.12.2a                     | Pam's+BoneCraft+1.12.2a.jar                   | None                                     |
	| UCHIJAAAA | desertcraft          | 1.12.2a                     | Pam's+DesertCraft+1.12.2a.jar                 | None                                     |
	| UCHIJAAAA | petbat               | 1.4.8                       | PetBat-1.12.2.jar                             | None                                     |
	| UCHIJAAAA | placeableitems       | 3.3                         | placeableitems-3.3.jar                        | None                                     |
	| UCHIJAAAA | pumpkincarving       | 1.3.3                       | PumpkinCarving1.12-1.3.3.jar                  | None                                     |
	| UCHIJAAAA | reforged             | 0.7.5                       | Reforged-0.7.5-1.12+.jar                      | None                                     |
	| UCHIJAAAA | roost                | 1.2.0                       | roost-1.12-1.2.0.jar                          | None                                     |
	| UCHIJAAAA | rustic               | 1.0.3                       | rustic-1.0.3.jar                              | None                                     |
	| UCHIJAAAA | merpig               | 1.12.2-0.0.1.20180406032656 | SBM-Merpig-1.12.2-0.0.1b20180406032702.jar    | None                                     |
	| UCHIJAAAA | sereneseasons        | 1.1.4                       | SereneSeasons-1.12.2-1.1.4-universal (1).jar  | None                                     |
	| UCHIJAAAA | sharpbone            | 1.0                         | SharpBone-1.12.2-1.0.jar                      | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| UCHIJAAAA | simplecorn           | 2.3.7                       | SimpleCorn1.12-2.3.7.jar                      | None                                     |
	| UCHIJAAAA | simplytea            | 1.4                         | simplytea-1.4.jar                             | None                                     |
	| UCHIJAAAA | soundfilters         | 0.10_for_1.12               | SoundFilters-0.10_for_1.12.jar                | None                                     |
	| UCHIJAAAA | sugiforest           | 1.4.0                       | SugiForest_1.12-v1.4.0.jar                    | None                                     |
	| UCHIJAAAA | thut_wearables       | 3.1.6                       | thut-wearables-1.12.2-3.1.6.jar               | None                                     |
	| UCHIJAAAA | totemexpansion       | 1.2.1                       | totemexpansion-1.2.1-1.12.2.jar               | None                                     |
	| UCHIJAAAA | toughasnails         | 3.1.0.114                   | ToughAsNails-1.12.2-3.1.0.114-universal.jar   | None                                     |
	| UCHIJAAAA | transloc             | 1.0.5                       | transloc-1.12.2_1.0.5.jar                     | None                                     |
	| UCHIJAAAA | tumbleweed           | 1.11-0.4.5                  | tumbleweed-1.11-0.4.5.jar                     | None                                     |
	| UCHIJAAAA | veining              | 1.3.0                       | veining-1.3.0-1.12.x.jar                      | None                                     |
	| UCHIJAAAA | venomousfangs        | 1.1                         | VenomousFangs1.12-1.1.jar                     | None                                     |
	| UCHIJAAAA | waddles              | 0.6.0                       | Waddles-1.12.2-0.6.0.jar                      | None                                     |
	| UCHIJAAAA | wearablebackpacks    | 3.1.2                       | WearableBackpacks-1.12.2-3.1.2.jar            | None                                     |
	| UCHIJAAAA | weeeflowers          | 1.12.2b                     | Weee!+Flowers+1.12.2b.jar                     | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.6.0.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.1.4-universal (1).jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.11.jar)
  org.blockartistry.DynSurround.asm.Transformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1008' Renderer: 'AMD Radeon HD 6670'
	Launched Version: 1.12.2-forge1.12.2-14.23.3.2655
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 6670 GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-2130 CPU @ 3.40GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C9
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.201.1151.1008
	OpenGlRenderer: AMD Radeon HD 6670
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by OreCruncher** [comment]
Dupe #308.
