### ISSUE TITLE
My battle music doesn't play!

### ISSUE THREAD

**Issue by DaBomba** [OreCruncher/DynamicSurroundings#316]
*Mod Version:* 3.4.7.2

*Forge Version:* 14.23.3.2655

*Link to crash log (if applicable):*

*Description:* 
My battle music in the individual sound settings doesn't play anymore!
Please help!

**Comment by darthvader45** [comment]
Is it disabled in the settings?  If it is in an earlier version, such as 1.7.10, those don't have battle music.  Try updating to the most recent version.

**Comment by DaBomba** [comment]
No. The sounds are not blocked or Culled. And I have the most recent
version.

**Comment by DaBomba** [comment]
I even reset everything to default, reinstalled the pack. But nothing
happened.

**Comment by OreCruncher** [comment]
Playing SP or MP?

**Comment by DaBomba** [comment]
Single Player.

**Comment by OreCruncher** [comment]
What are the volume settings for Master and Music?  Also, you try boosting the volume of the battle music under "Individual Sound Configuration".  It is possible that it is playing but the volume is too low.

**Comment by DaBomba** [comment]
My mac is playing at about 20/100.
Minecraft Music is at 100%
Everything about Battle Music is true.

**Comment by OreCruncher** [comment]
Have you tried boosting the volume of battle music using the "Individual Sound Configuration" options?

**Comment by DaBomba** [comment]
Can't find them...

**Comment by OreCruncher** [comment]
It's in the mod configuration GUI,  The "Individual Sound Configuration" button is the first button on the first DS config page.

**Comment by DaBomba** [comment]
Can you send me a screen recording of you boosting your battle music sounds?

**Comment by DaBomba** [comment]
Don't Worry! I fixed it!!!
Somehow...
