### ISSUE TITLE
Crash when reloading sound system (through Random Tweaks)

### ISSUE THREAD

**Issue by BrisingrAerowing** [OreCruncher/DynamicSurroundings#319]
*Mod Version:* 3.4.9.11

*Forge Version:*2673

*Link to crash log (if applicable):* [Crash Log](https://gist.github.com/BrisingrAerowing/60aff339e999e8a91c9d2b109485c6f3)

*Description:* Reloaded the sound system using Random Tweaks, the game locked up, then crashed. I was in the Compact Machines dimension, FWIW, though I don't think that had anything to do with it.

**Comment by OreCruncher** [comment]
I will have to take a look.  Reloading the sound system can be touchy when the game is active - its why I made a bunch of changes in this BETA series of releases to change how DS did things.

**Comment by BrisingrAerowing** [comment]
Added to the gist.

**Comment by OreCruncher** [comment]
Posted v3.4.9.12 to CurseForge with defensive code.  Let me know if you have further issues with this.
