### ISSUE TITLE
[Suggestion] Noisy armor

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/DynamicSurroundings#32]
Copied from the BetterRain vault:

@Drakoflame

Hmm... would it be possible to add special biomes "IF chestplate = True: [Iron], Play sound "armor_grind.ogg", On > step" or something (yay for my attempt at something that looks like code XD. Basically, if your wearing a specific type of armor, and walk around, it would either make a ruffling sound if leather, a metal creak/grind/squeak if gold or iron, or a crystalline tinkling sound if diamons? (and maybe OreDic could see if the armor is made out of metal or a gem, if not then time to add every metal added by mods XD)

so, directly copy/pasted from the Curseforge page for two reasons
1: Easier to keep track of
2: I can officially make it a suggestion/request here XD

So, yea, I think it would be kinda cool, but it would be another one of those things that is toggle able, as some people might not enjoy the constant squeaking of their metal armor XD. Either way, it would be a cool feature.
Also, not sure if it would fit into this thread, or if it would belong in another, but would it also be possible to do to armor what Pumpkins do? IE: Make an overlay of the armor in the players face? Now, this wouldn't work with all texturepacks, and would require custom editing for some (especially Metalurgy armors because there are a lot of full piece helms), so maybe a config that lets you offset the overlay, or completely disable it. Again, another feature that would be awesome that helps add to the immersion of the mod :3

**Comment by Drakoflame** [comment]
Sweet, would be really cool to see something like that happen, and the face overlay thing, now that I think bout it, it would get annoying with some armors that don't exactly have "face" friendly helmets. So I'd actually nix that one, but the others would still be awesome to have happen :D

**Comment by OreCruncher** [comment]
Pushed BETA version that has this feature to CurseForge.  Docs are [here](https://github.com/OreCruncher/DynamicSurroundings/wiki/Sound-Overlay).
