### ISSUE TITLE
No sounds appearing

### ISSUE THREAD

**Issue by Andyghandi** [OreCruncher/DynamicSurroundings#320]
Hi, I am having this bug where all the sounds are simply not working, in game and choosing options in title screen. Just silent experience. Sounds work normally without dynamic surroundings installed. The only thing i could get out from the launcher log is:

Error in class 'SoundSystem'
--
00:44:45 | net.minecraft.client.audio.SoundManager | Variable 'soundLibrary' null in method 'CommandNewSource'
00:44:45 | net.minecraft.client.audio.SoundManager | Error in class 'SoundSystem'
00:44:45 | net.minecraft.client.audio.SoundManager | Variable 'soundLibrary' null in method 'CommandSetPitch'
00:44:45 | net.minecraft.client.audio.SoundManager | Error in class 'SoundSystem'
00:44:45 | net.minecraft.client.audio.SoundManager | Variable 'soundLibrary' null in method 'CommandSetVolume'
00:44:45 | net.minecraft.client.audio.SoundManager | Error in class 'SoundSystem'
00:44:45 | net.minecraft.client.audio.SoundManager | Variable 'soundLibrary' null in method 'CommandPlay'
00:44:47 | net.minecraft.client.audio.SoundManager | Error in class 'SoundSystem'
00:44:47 | net.minecraft.client.audio.SoundManager | Variable 'soundLibrary' null in method 'CommandRemoveSource'
00:45:06 | net.minecraft.client.audio.SoundManager | Error in class 'SoundSystem'
00:45:06 | net.minecraft.client.audio.SoundManager | Variable 'soundLibrary' null in method 'CommandNewSource'
00:45:06 | net.minecraft.client.audio.SoundManager | Error in class 'SoundSystem'

I didnt really see a solution for this. Is there any config I need to change?

Thanks for maintaining!

Using

Mod version: 3.4.9.0

Forge version: 14.23.3.2673

Java version: 171-b11

**Comment by Andyghandi** [comment]
Also this section keeps repeating in the launcher log and the game recieve pretty bad lag spikes of 5 seconds every 3 seconds when it happens. Guess it is relaunching the sound engine or something

**Comment by OreCruncher** [comment]
You need to update the latest BETA.  There would be a "conflict" between that version of DS and Forge.

**Comment by Andyghandi** [comment]
Okay, will test it later once I get home from work. Thanks for Quick response!

**Comment by Andyghandi** [comment]
Okay the "ding" sound played when launching was done, good sign! And also it works properly now :)

**Comment by OreCruncher** [comment]
Cool!  I will close the issue.  If you run into further issues let me know.
