### ISSUE TITLE
Crash on server start (SpongeForge)

### ISSUE THREAD

**Issue by Blayyke** [OreCruncher/DynamicSurroundings#321]
*Mod Version:*
DynamicSurroundings-1.12.2-3.4.9.11

*Forge Version:*
forge-1.12.2-14.23.3.2655-universal
If it helps, I'm using SpongeForge 1.12.2-2655-7.1.0-BETA-3064

*Link to crash log (if applicable):*
https://hastebin.com/ofebirerum.md

*Description:*
Server crashed on startup. This was the crash report

**Comment by OreCruncher** [comment]
Smells like Sponge.  I do not recognize the method
```
net.minecraft.world.World.handler$onGetWorldInfo$bbf000(World.java:4680)
```
Dynamic Surroundings is invoking getWorldInfo() on the world object for the world being loaded, and the underlying code has a fit.
