### ISSUE TITLE
Client Crash When Near Specific Chunks - java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Trickysticks** [OreCruncher/DynamicSurroundings#326]
*Mod Version:* DynamicSurroundings-1.12.2-3.4.9.12.jar

*Forge Version:* 14.23.3.2676

*Link to crash log (if applicable):* https://pastebin.com/yC0f0JC0

*Description:* Approaching (a) certain chunk(s) appears to crash the game on my server. Upon relogging the game hangs on the loading screen and then crashes again. This affects all members of my server and the only solution so far has been removing Dynamic Surroundings from the client. DS is client-side only. 

This issue isn't present in Dynamic Surroundings version 3.4.9.7, which is the last one I used before catching up on updates.

**Comment by OreCruncher** [comment]
The code is new to the latest releases so it wouldn't be present in the prior versions.  As for the error it looks like a thread is doing living entity updates when it shouldn't.  This appears to be the same problem as #283.  May have to add back some debug code and make it permanent.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.13 to CurseForge.  The code I added was to check to ensure that the current thread of execution is indeed the client thread, and if not, an exception will be generated, logged, and the client will crash.  The goal is to find what is causing the concurrent access of one of DS internal lists and figure out what to do about it.

**Comment by Trickysticks** [comment]
Hi, I joined the server again using v3.4.9.13 and obtained another crash log. If this isn't what you need (or if I should open another issue) let me know.
[crash-2018-05-14_18.33.18-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/2002810/crash-2018-05-14_18.33.18-client.txt)

**Comment by OreCruncher** [comment]
Can you link the entire client log?

**Comment by Trickysticks** [comment]
[debug.log](https://github.com/OreCruncher/DynamicSurroundings/files/2003433/debug.log)
[latest.log](https://github.com/OreCruncher/DynamicSurroundings/files/2003434/latest.log)
I've attached both latest.log and debug.log.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.14 with changes.  Essentially I modified how DS goes about traversing map objects when deleting rather than relying on the JRE builtin methods for doing such traversal.
