### ISSUE TITLE
(1.12.2) Serene Seasons Compatibility: Tropical Biome Weather Not Changing With Seasons

### ISSUE THREAD

**Issue by TechnoMysterio** [OreCruncher/DynamicSurroundings#327]
The weather in tropical biomes (such as deserts, jungles and savannas) does not change as the seasons in Serene Seasons change. For instance, while it should rain in deserts in late winter/early spring (mid wet season), there are still sandstorms, and while it should be dry in jungles in late summer/early autumn (mid dry season), there is still rain.

Just for further clarity, according to the SS wiki, during the mid wet season it can rain in tropical biomes that normally don't receive rain (savannas, deserts), and during the mid dry season, it doesn't rain in tropical biomes that normally receive rain (jungles, Traverse's mini-jungle). Outside of this, the biomes behave as normal. Traverse has a file called biome_info.json that lists which biomes (including modded biomes) should receive tropical or temperate seasons, so that may be useful.

Also, here's a chart from the dev of SS showing how tropical seasons relate to temperate seasons:

![image](https://user-images.githubusercontent.com/5113920/39429927-55a012ba-4c84-11e8-9423-01ddcd4dafc3.png)

DS: 3.4.9.12
Serene Seasons: 1.1.5
Forge: 14.23.3.2677

**Comment by OreCruncher** [comment]
Pushed v3.4.9.13 to CurseForge.
