### ISSUE TITLE
Weather dose not work with JED dimensions 

### ISSUE THREAD

**Issue by RiptideC27** [OreCruncher/DynamicSurroundings#329]
*Mod Version:*
1.12.2-3.4.9.12.jar
*Forge Version:*
14.23.3.2655

*Link to crash log (if applicable):*
[latest.log](https://github.com/OreCruncher/DynamicSurroundings/files/1971931/latest.log)

*Description:*
When I make a new world with the a JED dimension, I spawn in with thunder and rain turned on which is what I want. But when DynamicSurroundings is added to the pack that does not happen the world spawns, but without the rain and thunder. I have asked the JED mod creator and he has said that it could be an issue with DynamicSurroundings because the vanilla level NBT are right for what I am doing. Dose this mod added its own weather. If so how do I tell JED to use your weather inside of vanilla.

**Comment by OreCruncher** [comment]
#245.  If JED does not use the WorldInfo object for recording rain info things can get weird.  I have not spent time, in detail, to see what is going on.

**Comment by DarkmoreSOS** [comment]
How would I tell DS to allow weather in a dim. Is it in the config or do I have to write a Json?

**Comment by DarkmoreSOS** [comment]
Ok thanks. Do you know of any work arounds?

**Comment by OreCruncher** [comment]
@RiptideC27 I am looking into this issue.  What do I have to do with it to see the problems you are seeing?

**Comment by OreCruncher** [comment]
Pushed a BETA of v3.5 to CurseForge.  Note that the new version has a library dependency on OreLib (another library mod I made).  Make sure you read the release notes prior to upgrade.
