### ISSUE TITLE
Crash (on exploring world) with CubicChunks

### ISSUE THREAD

**Issue by Rongmario** [OreCruncher/DynamicSurroundings#330]
Mod: 3.4.9.12 

Forge: 1.12.2 recommended (2655)

https://gist.githubusercontent.com/Rongmario/da6107df6a68323ac319bb618b7244dc/raw/15ad5a794b0b48721e1d81c12c856f36c5ba3833/gistfile1.txt

When walking around exploring the world, I get hit with a crash with this, tested three separate times in separate worlds, only happens after about a minute or so.

**Comment by BaccarWozat** [comment]
This has also happened to a member on my Cubic Chunks server. (DS is not in my modpack though.)
https://cdn.discordapp.com/attachments/388706158954938369/440872189022175244/crash-2018-05-01_06.47.39-client.txt

**Comment by OreCruncher** [comment]
Dupe #229.  DS is not compatible with it.

**Comment by Rongmario** [comment]
Good to hear you will try support it when it is more stable, but this is a crash unlike #229, just for future reference :)

**Comment by OreCruncher** [comment]
Yep.  Cubic Chunks is a world of hurt.  It changes some fundamentals of Minecraft that touch on a number of different things within DS.  I wouldn't be surprised if there were other crash conditions.

**Comment by Barteks2x** [comment]
Looks like this is actually a very dumb issue with mixin on my side that just happened to go unnoticed so far:
![image](https://user-images.githubusercontent.com/1349112/39652931-62a5f592-4fef-11e8-9b53-fee7b0f3b321.png)
