### ISSUE TITLE
(1.12.2) Serene Seasons Compat (Again) - Savanna Not Receiving Rain In Mid Wet Season

### ISSUE THREAD

**Issue by TechnoMysterio** [OreCruncher/DynamicSurroundings#332]
An extension of the previous Serene Seasons issue: jungles behave as they should, not receiving rain in mid dry season (even variants like Traverse's mini jungle behave correctly), but savannas still don't receive rain in mid wet season. Stranger still is that other hot tropical biomes, like Traverse's badlands biome, DOES receive rain in mid wet season, so I'm not sure what's doing on here.

Also, quick addition, deserts (and variants like the mesa or Traverse's desert shrubland and red desert) get rain as they should, but they don't play the correct sounds, instead just getting wind with no rain sounds.

DS: 3.4.9.13
Serene Seasons: 1.1.5
Forge: 14.23.3.2678

**Comment by OreCruncher** [comment]
Does savanna rain work without DS?

**Comment by TechnoMysterio** [comment]
Yes they do. Also, with DS installed, rain droplets appear under trees in the savanna biome when it should be raining. Is there some override for the savanna's weather in the code or in one of the json files perhaps?

**Comment by OreCruncher** [comment]
No - it's something in my code.  I have to rearrange the check sequence so that tropical seasons get first crack before evaluating for dust.  Question on deserts - should there be dust storms during MID_DRY?

**Comment by TechnoMysterio** [comment]
Could you be more specific?

**Comment by OreCruncher** [comment]
There is a mid dry season for deserts.  Current code says not to do any precipitation effect rendering thus preventing dust storms or rain during that sub season.  My thought was to leave as is.

**Comment by TechnoMysterio** [comment]
So an extra weather variant for the deserts, meaning you get nothing in mid dry season? Sure, keeps it varied.

**Comment by OreCruncher** [comment]
Yep.  So what is going to happen in deserts is:

* MID_WET - it will have rain.  Water rain.
* MID_DRY - there will be no weather rendering.
* Any other season it would have dust storms.

**Comment by TechnoMysterio** [comment]
Yeah, that keeps it interesting, makes it feel like the seasons are progressing. Also, watery rain is my favourite type of rain.

**Comment by OreCruncher** [comment]
For Savanna it will be able to rain during the wet season, and no rendering will take place for the other seasons.

**Comment by TechnoMysterio** [comment]
Mid wet season only, right?

**Comment by OreCruncher** [comment]
Yep.

**Comment by BrisingrAerowing** [comment]
Just came here to report the drips from trees issue. Glad to see it's already fixed.

**Comment by TechnoMysterio** [comment]
That was what I was referring to, yes. By the way, did you look in the rain sound not playing in rainy deserts?

**Comment by OreCruncher** [comment]
Rainy deserts - yes.  I think I have all that resolved as well.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.14 with changes.
