### ISSUE TITLE
[SUGGESTION] Add support for new BoP content

### ISSUE THREAD

**Issue by Sunconure11** [OreCruncher/DynamicSurroundings#334]
I had attempted to try my hand at some of it, but it appears I screwed up, and as a result, the things I tweaked are not playing the sounds I gave them.

Biomes O' Plenty has been adding a bunch of new content lately, it might be worth it to add support for the new content.

Also, Thaumcraft 6 has been out for a bit. Maybe it's time to add support for it's content?

**Comment by Sunconure11** [comment]
As the changelog is a mess, you'd probably have to look at it yourself. They brought back the pasture biome, and removed a lot of fluff.

**Comment by OreCruncher** [comment]
OK - so far it isn't too bad.  Removed some items in the config that are no longer in BoP, changed some of the plant profiles, and fixed footprints on grass covered stone (required some code changes).  No doubt some more stuff will pop out over time.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.14 with additional BoP support changes.
