### ISSUE TITLE
(1.12.2) ProjectRed/ForgeMultipart Microblocks Have Incorrect Footsteps

### ISSUE THREAD

**Issue by TechnoMysterio** [OreCruncher/DynamicSurroundings#336]
ProjectRed was updated to 1.12 the other day, so I had a look through it's features, including the old microblocks feature. The issue with the microblocks is that since they are all based off of the same block id with varying nbt data, they all have the same footsteps in DS. To solve this, I think you'd have to read the nbt tag containing the block id the microblock is mimicking.

On a semi-related note, I also noticed this problem with the blocks from ArchitectureCraft, and while I haven't used BWM in a while (so I can't be sure) I imagine that mod's semi-new dynamic miniblocks update may also create a problem with footsteps.

ProjectRed: 4.8.6.66
DS: 3.4.9.13
Forge: 14.23.3.2680

**Comment by OreCruncher** [comment]
I haven't looked at PR to see if there is an API where the underlying block type can be determined.  I do this with facade/cover support for EnderIO and Thermal Dynamics.  I really don't want to do NBT searching.

**Comment by TechnoMysterio** [comment]
Ah, that seems wiser. Oh, and something else to annoy y- I mean, something else I remembered: Buildcraft also has facades.

**Comment by OreCruncher** [comment]
Just started looking at this for 3.5.  Forge Multipart is written in Scala.  I don't want to learn scala.  Sheesh.

**Comment by OreCruncher** [comment]
Pushed a BETA of v3.5 to CurseForge.  Note that the new version has a library dependency on OreLib (another library mod I made).  Make sure you read the release notes prior to upgrade.
