### ISSUE TITLE
(Suggestion) Move battle music into resource pack, add compat with custom resource packs

### ISSUE THREAD

**Issue by darthvader45** [OreCruncher/DynamicSurroundings#337]
As this has been possibly planned, I'd like to see how this would turn out, as I have been wanting to use my own music for when I am fighting mobs, particularly Led Zeppelin's Immigrant Song (mainly because Thor: Ragnarok's final fight scene, Thor vs Hela's army).

Edit:  Perhaps put this in a milestone, if you have plans for it?

**Comment by OreCruncher** [comment]
Pushed a BETA of v3.5 to CurseForge.  Note that the new version has a library dependency on OreLib (another library mod I made).  Make sure you read the release notes prior to upgrade.  I will be adding a resource pack containing battle music soon.
