### ISSUE TITLE
disabling sound effects

### ISSUE THREAD

**Issue by traso56** [OreCruncher/DynamicSurroundings#338]
*Mod Version:*
1.7.10-1.0.6.0
*Forge Version:*
10.13.4.1614

*Link to crash log (if applicable):*

*Description:*
hello I just wanted to get help disabling the fly or idk what it is because it's very annoying and plays way too often i currently have this in the config

# Sounds to block from playing [default: [dsurround:bison]]
    S:"Blocked Sounds" <
        dsurround:bison
        dsurround:insects/gnatt1
     >

but the sound still plays, i don't think it's a bug but rather I used improper formating please help me ty

**Comment by OreCruncher** [comment]
Close.  You want to block "dsurround:insectbuzz"

**Comment by traso56** [comment]
thank you i supposed i used the improper name or something i will try this out

**Comment by traso56** [comment]
it looks like it worked, thank you, I think it should be easier to know the names of the sounds, I don't need an in-game fancy gui but figuring out the names isn't exactly easy

**Comment by OreCruncher** [comment]
Understand.  Unfortunately sound events are generally an internal thing to Minecraft and do not have "human readable" names/descriptions.  Going to close out the issue as resolved.  If you have any further questions let me know.
