### ISSUE TITLE
Mod assumes water level at Y=64

### ISSUE THREAD

**Issue by SamGunGraven** [OreCruncher/DynamicSurroundings#34]
Fog only starts at Y=64 which is fine for normal worlds, but with f.ex. Biome Bundle, the water level is at 54 which means you get a really weird behavior of fog starting suddenly as you climb hills. Would be good with a configurable Y level.

**Comment by OreCruncher** [comment]
There is a way to configure using [dimension configurations](https://github.com/OreCruncher/DynamicSurroundings/wiki/Tutorial:-Dimension-Configuration).  Alternatively they can change their world provider to report 54 as the average ground height.

**Comment by OreCruncher** [comment]
@SamGunGraven Did you manage to get the configuration set for the dimension?

**Comment by OreCruncher** [comment]
@SamGunGraven Pushed a v3.3.8.0 version that has a simple sea level override setting in the config GUI to make this easier to handle.
