### ISSUE TITLE
[1.12.2] A way to disable Swinging Sounds?

### ISSUE THREAD

**Issue by chland** [OreCruncher/DynamicSurroundings#341]
*Mod Version:*
1.12.2 - 3.4.9.13

*Forge Version:*
14.23.3.2698

*Description:*
I'm wondering if there is a way to disable the swinging sounds for tools (and preferably for weapons, too). I think there was a setting in the past to disable them but it seems like that was removed.

Personally I think the swinging sounds are incredibly annoying (especially while mining or harvesting when you accidently swing your pick/axe through the air a lot) and it would be awesome if it was possible to disable them (or adjust their volume).

**Comment by OreCruncher** [comment]
There is an option.  Under the Sound options there is "Equip Sounds".  Set to false.

**Comment by chland** [comment]
Thanks for the quick reply. I will take a look.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.14 with changes.
