### ISSUE TITLE
[Enhancement] Aurora quality options

### ISSUE THREAD

**Issue by Geethebluesky** [OreCruncher/DynamicSurroundings#343]
*Mod Version:*  DynamicSurroundings-1.12.2-3.4.9.13.jar

*Forge Version:* Build 2705

*Description:*

I'd like to request some settings to adjust aurora quality. The debug profiler shows aurora renders are taking ~200ms.... that's a lot, and seems to be contributing to FPS drops (processing is at 140ms while standing still, at night, in a taiga.)

Could a setting be added for Low/Med/High quality auroras to help combat this please?

**Comment by OreCruncher** [comment]
Only option is to disable the use of shaders.  BTW, what video card do you have?

**Comment by OreCruncher** [comment]
That is weird.  I have a GTX 980 and it runs much much much faster.  Are you running a shader pack?

**Comment by Geethebluesky** [comment]
Yep, I'm running Sildur's Enhanced Default. Should I request an option on the shader author's side then you think? I honestly didn't realize auroras would be impacted by the shader before asking, my apologies.

**Comment by OreCruncher** [comment]
Not sure whether it is the shader pack or not.  Quick way to find out is disabling it and checking the numbers again.  In general, though, my rig performs much much better for some reason than yours.  What version of OptiFine are you running?

**Comment by Geethebluesky** [comment]
D3 for 1.12. I'm also using 32x resource packs and have stuff like BetterFoliage on (along with BetterFPS and Foamfix), all my configs are as tweaked as I could make them. Still runs everything at ~60fps on average, but being in forests with auroras seems to be a bad combination overall.

(Yes I'm aware I'm probably expecting a lot out of that combination, I'm trying it to see if it works. If it doesn't, then it doesn't. :)

**Comment by OreCruncher** [comment]
Can you link a screenshot of the debug screen with the DS timing values?  It may have further clues in the other data points.

**Comment by Geethebluesky** [comment]
Okay, after you said that I learned something: do auroras cast light? What finally made the FPS go back up is setting shadow distance to medium instead of Far, and turning off colored shadows entirely.

If it's still useful though I can upload a few screenshots of the render times on both a 1070 and a gtx 980 with the same modpack and resourcepack (one PC is the server).

**Comment by OreCruncher** [comment]
No - auroras don't cast light.  Or more specifically, the aurora shader does not do any fancy lighting.  Can't speak for what the shader pack is doing.  It doesn't do any shadowing either.  Best way to think of the aurora is as texture that is dynamically generated and rendered onto a triangle strip.

**Comment by Geethebluesky** [comment]
Alright, thanks for your patience with this.

**Comment by Geethebluesky** [comment]
I may have spoken too soon with the shader option change... :/ Either way, I asked about it on the shader dev's forum topic.

[Screenshot from just now](https://i.imgur.com/YSuA4Cm.png)

**Comment by OreCruncher** [comment]
According to that screenshot the render time is 0.241ms of the client tick as compared to the original 200ms.  Maybe you are reading it wrong?

**Comment by Geethebluesky** [comment]
No sorry I mistyped the original comment, should have been ~0.200ms.

**Comment by OreCruncher** [comment]
That number is the aggregate amount of time taken during the client tick to do rendering.  Divide that number by your FPS and that tells you how long it takes to render in a single render pass.  Based on the screenshot it would be 0.241/32 = 0.0075ms for a single frame render.

**Comment by OreCruncher** [comment]
No worries.  I would rather hear about things rather than not. :)

**Comment by OreCruncher** [comment]
Though this is an older issue I am marking it fixed.  In the 3.6.0.0 release I optimized the aurora shader and rendering code.  I can get 120 FPS with a 3 band aurora on my GTX 980.

**Comment by OreCruncher** [comment]
Pushed v3.6.0.0 to CurseForge.  Contains major changes to aurora rendering performance.
