### ISSUE TITLE
Minecraft forge not launching because of DynamicSurroundings (Might be easy fix)

### ISSUE THREAD

**Issue by Spootnark** [OreCruncher/DynamicSurroundings#344]
*Mod Version:*
![dynamic surroundings download](https://user-images.githubusercontent.com/39837102/40854531-cececdb4-659f-11e8-84e0-f4ac7c29beba.PNG)
The version of the mod I downloaded
*Forge Version:*
![forge version](https://user-images.githubusercontent.com/39837102/40854442-7f92e5d2-659f-11e8-9d48-c73358086b03.PNG)
I downloaded this one, but it appears to have installed (1.12.2 - 14.23.0.2529)

*Link to crash log (if applicable):*
![minecraft mod problem](https://user-images.githubusercontent.com/39837102/40854252-d7d3d450-659e-11e8-99cc-51e3bca6863d.PNG)

*Description:*
When I try to launch Minecraft Forge this shows. I made sure to click the download of the latest forge version but it looks like it keeps downloading an older version, i checked this many times and I'm sure it is the problem. Is here a link to the proper forge version I can download to get the mods working?

**Comment by OreCruncher** [comment]
I personally would not trust that site.  Only official direct download site for Forge that I am aware of is [http://files.minecraftforge.net/](http://files.minecraftforge.net/).  Not sure where you got Dynamic Surroundings given that screenshot, but the official download site is [https://minecraft.curseforge.com/projects/dynamic-surroundings](https://minecraft.curseforge.com/projects/dynamic-surroundings).

**Comment by Spootnark** [comment]
![curseforge official](https://user-images.githubusercontent.com/39837102/40862154-981fb458-65b9-11e8-9c6a-33d45ddbe20e.PNG)
Got it from the official mod sire curse forge
And ill try the official minecraft forge now thanks

**Comment by Spootnark** [comment]
![another minecraft forge fail](https://user-images.githubusercontent.com/39837102/40862450-9090050c-65ba-11e8-9c62-5e4efba5faba.PNG)
So I downloaded and installed the correct OFFICIAL Forge and then this happened

**Comment by OreCruncher** [comment]
That is something else which I do not know.  The launchers I use are Twitch and MultiMC - not sure how things work with the most current Minecraft launcher.

**Comment by Spootnark** [comment]
Well then RIP for modded Minecraft.

**Comment by OreCruncher** [comment]
@Spootnark What do you mean?

**Comment by Spootnark** [comment]
@OreCruncher I could get tekkit but Forge is not working so I cannot use mods.

**Comment by MauveCloud** [comment]
@Spootnark the latest screenshot looks like you are still using the profile created by the "minecraft-downloads" install of Forge (since it shows a build ending in 2529), rather than the updated install.  It might be best to delete your local Minecraft folders and reinstall from scratch to make sure you don't have any residual files from the un-trustworthy site.  If that seems too drastic, you could at least check for a different profile with the correct Forge version.

**Comment by Spootnark** [comment]
Ill try that sometime thanks.
