### ISSUE TITLE
Problems with Thaumcraft Particle Engine

### ISSUE THREAD

**Issue by frOOps** [OreCruncher/DynamicSurroundings#347]
Mod Version: 3.4.9.13

Forge Version: 14.23.4.2705 

Link to crash log : https://pastebin.com/xx7e1rHV

Description: Crashes due to some sort of Problem with Thaumcraft Particle Engine
I use Thaumcraft-1.12.2-6.1.BETA15. As I have no programming knowledge I can't say anything else about it but thanks in advance.

**Comment by OreCruncher** [comment]
I would say this is a Thaumcraft issue.  Not sure how DS is involved.  No code from DS is in that callstack.

**Comment by frOOps** [comment]
Thx for the fast reply I'm gonna report it to them instead!

**Comment by OreCruncher** [comment]
Cool.  I will go ahead and close out the issue.  Thanks!
