### ISSUE TITLE
Small issue with JaparyCraft

### ISSUE THREAD

**Issue by Verka-Princess** [OreCruncher/DynamicSurroundings#349]
1.12.2
Sounds from JaparyCraft are not displayed in "Individual sounds configuration" menu.

**Comment by OreCruncher** [comment]
I did a google of JaparyCraft and did not see anything related to such a mod.  Can you provide a link?  As for not showing if a mod handles its own sound handling outside of Minecraft/Forge framework then it would not show.

**Comment by Verka-Princess** [comment]
Here is the link: https://minecraft.curseforge.com/projects/japaricraftmod?gameCategorySlug=mc-mods&projectID=267324

**Comment by OreCruncher** [comment]
Took a quick look at the source tree and do not see any sounds for the mod or any code related to sound registration.  Are you sure the mod has it's own sounds?

**Comment by Verka-Princess** [comment]
Yes, it has!

**Comment by OreCruncher** [comment]
Don't see sound resources in their build tree.  For Minecraft there would be a location in the asset directory with the OGG files.  I will post an issue to find out where there are at.  It could be they are kept separate for whatever reason they do that.

**Comment by Verka-Princess** [comment]
Thank you!
