### ISSUE TITLE
Crash when trying to disable DynSurroundings via fmlModState.properties

### ISSUE THREAD

**Issue by NikkyAI** [OreCruncher/DynamicSurroundings#351]
*Mod Version:*
1.12.2-3.4.9.14

*Forge Version:*
14.23.4.2705

*Link to crash log (if applicable):*
https://gist.github.com/0e3dbbcc34ff1f05c3deb3fd13037f27

*Description:*
using player's choice which configured the `fmlModState.properties` file
on server / world join it crashes,
seems like either fml or this mod is behaving silly

**Comment by OreCruncher** [comment]
My money is on FML.  DS uses ASM to hook that routine when the DS coremod runs.  I have never disabled a mod using that feature (because I think it is incomplete).  Do you also have to disable the coremod as well?

**Comment by Zer0Lyfe** [comment]
this should work :D
  {
    "id": "dsurround",
    "name": "Dynamic Surroundings",
    "desc": "Adds a variety of sound and visual effects to improve your Minecraft experience.",
    "website": "https://minecraft.curseforge.com/projects/dynamic-surroundings",
    "category": "Sounds",
    "extraMods": ["presets", "dynamicsurroundingscore"],
    "base": false
  }

**Comment by OreCruncher** [comment]
@NikkyAI Have you made further progress with the changes @Zer0Lyfe pointed out?

**Comment by NikkyAI** [comment]
we have dropped players choice and have not attepted anything further, the fml feature seems to not be that widely supported
i will leave ths issue open unless someone can validate that the suggested config works

**Comment by Zer0Lyfe** [comment]
@OreCruncher 
For some reason my playerchoices file has seemed to start not working now but seems to be different crash. It looks like it now isn't disabling the core mod for some reason. The mods are the same version and i have tried reversing the versions as well. this is the crash log.
https://paste.dimdev.org/qawegakeqa.mccrash

**Comment by OreCruncher** [comment]
I'm not going to try and do anything with this.  Apparently this feature is going to be removed in Forge 1.13.  Link [here](https://github.com/MinecraftForge/MinecraftForge/issues/2639#issuecomment-354021672).

**Comment by OreCruncher** [comment]
I spent some time looking at it figuring out that it was half way implemented to find out that it's going to be removed.  Not sure if I should be happy or sad. :)

**Comment by NikkyAI** [comment]
should this be closed then ?
