### ISSUE TITLE
custom.json not loading 1.10.2

### ISSUE THREAD

**Issue by resinate** [OreCruncher/DynamicSurroundings#353]
*Mod Version:*
DynamicSurroundings-1.10.2-3.4.9.14.jar
*Forge Version:*
forge-12.18.3.2511

*Link to crash log (if applicable):*

*Description:*
changing custom fog color in json doesnt work anymore and wiki is severely out of date with no working links.

            "biomeName":"Underworld",
			"dust":false,
			"dustColor":"0,0,0",
			"fog":true,
			"fogDensity":0.25,
			"fogColor":"160,150,150"

i use custom biome its worked before

**Comment by OreCruncher** [comment]
Post the complete JSON please.

**Comment by OreCruncher** [comment]
@resinate Following up. :)

**Comment by resinate** [comment]
sry for LATE reply....

{
    "biomes":[
        {
            "biomeName":"Northrend",
			"dust":false,
			"dustColor":"255,255,255",
			"fog":true,
			"fogDensity":0.40,
			"fogColor":"140,140,140"
		},
		{
            "biomeName":"Underworld",
			"dust":false,
			"dustColor":"0,0,0",
			"fog":true,
			"fogDensity":0.40,
			"fogColor":"150,140,140"
		}
    ],
    "blocks":[
    ],
    "dimensions":[
    ],
    "footsteps":{
    },
    "forgeMappings":[
    ]
}

this works perfectly fine on version DynamicSurroundings-1.10.2-3.4.7.2 but not the newest one dunno why lol

**Comment by OreCruncher** [comment]
Check your client log to see if there is an exception.

**Comment by resinate** [comment]
this was changed when u did some changes with fog system way back lol

**Comment by OreCruncher** [comment]
Following up.  It does appear I removed "biomeName" support in favor of the condition approach.  Making the above changes should help. :)

**Comment by resinate** [comment]
thanks man now i can update the mod lol

**Comment by resinate** [comment]
any update lol?

**Comment by OreCruncher** [comment]
It appears you are missing commas at the end of your condition entries.  A nifty website to help check the JSON is www.jsonlint.com

**Comment by resinate** [comment]
ok so overworld looks good but in nether it seems ur fog color u apply is multiplied not replaced lol

		{
			"conditions": "biome.name == 'Underworld'",
			"dust": false,
			"dustColor": "0,0,0",
			"fog": true,
			"fogDensity": 0.40,
			"fogColor": "150,140,140"
		}

in current pack this is supposed to be tint of red/white fog but in nether its showing black with tint of blue LOL

**Comment by OreCruncher** [comment]
Closing out as resolved.  Let me know if you run into any other issues.
