### ISSUE TITLE
Auroras are behaving oddly

### ISSUE THREAD

**Issue by Sunconure11** [OreCruncher/DynamicSurroundings#356]
![screenshot 2018-07-17 09 04 56](https://user-images.githubusercontent.com/5614902/42819102-8ccec19c-89a0-11e8-95e1-9dc14ef331c3.png)

**Comment by OreCruncher** [comment]
Which pack?

**Comment by Sunconure11** [comment]
Currently, my own, but I was working on an update, so that picture may not be accurate. Furthermore, Forge introduced an update which screwed with rendering on blocks, and could be behind this.

Try testing against Forge 1.12.2-14.23.4.2729 or later.

"bs2609: Change some client hooks to use GlStateManager functions (#5010)"

**Comment by OreCruncher** [comment]
Yeah.  Saw some similar things with Revelations 2.1.  Here we go again. :\

**Comment by OreCruncher** [comment]
Not seeing the issue with Forge 2739.  It could be another mod that is mucking with the GL state flags which then in turn triggers this.  Wouldn't be the first time. :\

**Comment by OreCruncher** [comment]
Still chasing this down.  No joy as of yet.

**Comment by OreCruncher** [comment]
Closing for a newer one.  #513
