### ISSUE TITLE
Can't hear rain with Dynamic Surroundings installed

### ISSUE THREAD

**Issue by daPoseidonGuy** [OreCruncher/DynamicSurroundings#358]
*Mod Version:*
1.12.2

*Forge Version:*
1.12.2-Forge1.12.2-14.23.0.2552

*Link to crash log (if applicable):*

*Description:*
With dynamic surroundings installed, one no longer hears Minecraft's sound for rainfall (or any sound for rainfall, for that matter). In cases of rain only, all one hears is splashy footsteps in applicable biome (but the rainfall itself is dead silent, even with every possible slider for sound at the maximum, and rain intensity at the maximum). In cases of rain and thunder, when dynamic surroundings plays the sound for thunder, for the duration of that sound you hear the rain in the background, but then it goes back to silence.

**Comment by OreCruncher** [comment]
What other mods do you have installed?

**Comment by daPoseidonGuy** [comment]
Yea, I was compiling a mod list as you asked that, and trying to test which other mod is causing the issue (the issue does not occur with dynamic surroundings on its own).

The Twilight Forest (by Benimatic)
[ANGRY PIXEL] The Betweenlands (by MrCompost)
Biomes O' Plenty (by Glitchfiend)
Millénaire (by Kinniken)
Baubles (by azanor)
Astral Sorcery (by HellFirePvP)
AbyssalCraft (by Shinoow)
IvToolkit (by Ivorforce)
Recurrent Complex (by Ivorforce)
Guide-API (by TehNut)
Blood Magic (by WayofTime)
Immersive Tech (by ferroo2000)
Immersive Engineering (by BluSunrize)
Immersive Petroleum (by theFlaxbeard)
stimmedcow : NoMoreRecipeConflict (by Oliv1er)
Redstone Flux (by TeamCoFH)
CodeChicken Lib 1.8.+ (by covers1624)
Brandon's Core (by brandon3055)
Draconic Evolution (by brandon3055)
BetterFps (by Guichaguri)
FoamFix for Minecraft (by asiekierka)
MysticalLib (by epicsquid319)
Mystic World (by epicsquid319)
Pam's HarvestCraft (by MatrexsVigil)
Pam's Get All the Seeds! (by MatrexsVigil)
Pam's Clay Spawn (by MatrexsVigil)
Mantle (by mDiyo)
Tinkers Construct (by mDiyo)
Tinkers' Complement (by KnightMiner)
Just Enough Items (JEI) (by mezz)
Tinker's JEI (by Possible_Triangle)
Just Enough Resources (JER) (by Way2muchnoise)
Just Enough HarvestCraft (JEHC) (by mrAppleXZ)
Just a Few Fish (by Tmtravlr)
Morpheus (by Quetzi)
Wawla - What Are We Looking At (by Darkhax)
Hwyla (by TehNut)
ConnectedTexturesMod (by tterrag1098)
Chisels & Bits (by AlgorithmX2)
Chisel (by tterrag1098)
Cooking for Blockheads (by BlayTheNinth)
Immersive Cables (by SanAndreasP)
Immersive Tech OreDictionary (by LiskoSlayer)
Dynamic Surroundings (by OreCruncher)
AbyssalCraft Integration (by Shinoow)
Applied Energistics 2 (by AlgorithmX2)
Inventory Tweaks (by Kobata)
Mouse Tweaks (by YaLTeR97)
Mystcraft (by XCompWiz)
AppleCore (by squeek502)
Hunger Overhaul (by progwml6)
The Erebus (by Vadis365)
Clumps (by jaredlll08)
TexFix (by Speiger)
FPS Reducer (by bre2el)
VanillaFix (by Runemoro)
FastWorkbench (by Shadows_of_Fire)
Dynamic Lights (by AtomicStryker)
ReAuth (by TechnicianLP)
Controlling (by jaredlll08)
KleeSlabs (by BlayTheNinth)
Bad Wither No Cookie - Reloaded (by kreezxil)
SwingThroughGrass (by exidex)
Bed Patch (by Mordenkainen3141)
Crafting Tweaks (by BlayTheNinth)
Client Tweaks (by BlayTheNinth)
No Recipe Book (by Seneschal_Luwin)
Astikoor [Horse Carts] (by MennoMax)
No Night Vision Flashing (by TeamCoFH)
Unloader (by Unnoen)
Born in a Barn (by Speiger)
Questionably Immersive (by theFlaxbeard)
OptiFine_1.12.2_HD_U_D2
MicdoodleCore-1.12.2-4.0.1.181
Galacticraft-Planets-1.12.2-4.0.1.181
Galacticraft-1.12.2-4.0.1.181.jar

**Comment by OreCruncher** [comment]
Have you tried removing mystcraft?

**Comment by daPoseidonGuy** [comment]
So, I went adding 5 mods at a time until I recreated the full mods list, and the issue didn't occur. So then, I replaced my options and optionsof files with the ones from the problematic instance. This created the issue. I isolated it to the options.txt file and compared the one that works with the one that doesnt. I then realised that the issue is because for some reason, the sound for the rain is controlled by the voice/speech slider.

**Comment by OreCruncher** [comment]
Saw EMAIL related to speech sound category being a potential culprit.  For some reason I am not seeing that info on the Github page.  :\  When the splash sound is played DS assigns the Weather category for sound control.  It is possible that some other mod overrides when the sound play request gets processed but I have not seen that in practice.

**Comment by daPoseidonGuy** [comment]
So, its very odd. It seems to me that if I touch anything in the music and sounds category it sometimes stops the rain sound from working. This is the difference between the options.txt that works and the one that doesnt:
https://www.diffchecker.com/HMF5WwEN (working is on the left)

**Comment by OreCruncher** [comment]
Ah!  That is most helpful.  The particle setting is set to none ("particles:2").  This makes sense.  In a nutshell Minecraft generates the rain splash sounds during particle generation of rain splash.  No particle spawned, no sound.  DS mimics this behavior so if particles are turned off you don't get the splash sounds.

**Comment by daPoseidonGuy** [comment]
Ah, yes, that is the case.

I think the reason for my thinking it was the sounds category is because every time I would just change all the settings to match the non-functioning one simultaneously, but it didnt occur to me that any of the others would be the cause, I assumed it would be something related to the sound category.

Sorry for wasting your time, then.

**Comment by OreCruncher** [comment]
No worries.  Would rather hear about potential issues than not. :)
