### ISSUE TITLE
[1.12.2] NetherEx Support Not Working

### ISSUE THREAD

**Issue by TechnoMysterio** [OreCruncher/DynamicSurroundings#359]
The NetherEx support json file doesn't seem to do anything. For instance, the frostburn ice has glass footstep sounds, despite the fact the netherex.json file is supposed to set it to ice footsteps. I gave the file a quick look over, and the syntax seems to be fine, it just doesn't seem like it's being loaded correctly.

DS: 3.4.9.14
Forge: 14.23.4.2739
MC: 1.12.2

**Comment by Sunconure11** [comment]
NetherEX appears to have gotten a massive update, but I currently can't fix support for it. @OreCruncher

**Comment by TechnoMysterio** [comment]
Well, the only reason I tested NetherEx was because of the update. However, I recall that support was still broken even for earlier NetherEx versions, so I'm not sure what's going on here.

**Comment by OreCruncher** [comment]
The internal mod ID changed from "netherex" to "nex".  Geez.

**Comment by TechnoMysterio** [comment]
Perhaps for a bit of extra support, some lines to give tilled soul sand and thornstalks extra sounds:

`"nex:thornstalk": "NOT_EMITTER",`
`"nex:thornstalk+foliage": "straw",`
`"nex:tilled_soul_sand": "quicksand"`

**Comment by LogicTechCorp** [comment]
The internal mod id has never been changed, it has always been "nex". Block names have changed, that is probably why your support no longer works.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.15 to CurseForge with a fix.
