### ISSUE TITLE
[Crash] [Mod Compat] Ender IO Conduit sound crash.

### ISSUE THREAD

**Issue by Notawallplan** [OreCruncher/DynamicSurroundings#36]
*Mod Version:*
3230-1.10
*Forge Version:*
23.18.3.2185

*Link to crash log (if applicable):*
http://pastebin.com/QKpschak
*Description:*
Crash upon walking on Ender IO conduits. Might be a good idea to have some kind of error suppressor for blocks without a sound associated, because this seems to be the issue.

**Comment by OreCruncher** [comment]
Is this a public pack or something you put together?

**Comment by Notawallplan** [comment]
It was a modified version of the Direwolf20 pack. This was specifically caused by me walking ontop the EI/O conduit. Thanks for fixing this btw.

**Comment by OreCruncher** [comment]
Pushed 3.2.4.0 BETA to CurseForge with the fix.
