### ISSUE TITLE
Entity Chat/Chatbubbles not working

### ISSUE THREAD

**Issue by J3LL4** [OreCruncher/DynamicSurroundings#362]
*Mod Version:*
3.4.9.14
*Forge Version:*

*Description:*
Every other feature seems to work but chatbubbles doesn't

**Comment by OreCruncher** [comment]
Single player or server?

**Comment by J3LL4** [comment]
Both. Maybe its caused by one of my other mods. here's the list: Optifine, Shoulder Surfing Reloaded, Fancy Block Particles, More Player Models, Sound Filters.

**Comment by OreCruncher** [comment]
Can you post a link to your dsurround.cfg file?

**Comment by J3LL4** [comment]
https://pastebin.com/k8NFBjtu
Sorry for the late response.
My forge version is 13.23.4.2705

**Comment by OreCruncher** [comment]
@J3LL4 Following up - have you had a chance to fiddle with this?

**Comment by J3LL4** [comment]
@OreCruncher (oof sorry for the late response) Nope, still not working ._.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.17 to CurseForge.
