### ISSUE TITLE
Crash after few seconds launched the game

### ISSUE THREAD

**Issue by tunaeskanaytac** [OreCruncher/DynamicSurroundings#363]
*Mod Version:*
1.12.2
*Forge Version:*
14.23.4.2705

*Link to crash log (if applicable):*
[PasteBin](https://pastebin.com/MqXP25Zb)
*Description:*
I don't if is this the right mod but I really don't know how to read crash reports I do some researchment and I think this mod causes the crash.

> **The crash happens a few seconds later launching the game**

Please help me.

**Comment by OreCruncher** [comment]
This is a weird one.  Shouldn't be happening.  Is it possible to update your Java to the latest 1.8 version?

**Comment by tunaeskanaytac** [comment]
If it is true, yes
![image](https://user-images.githubusercontent.com/13142062/43676280-d20cdb86-97f6-11e8-8f47-836bc75ede22.png)

**Comment by OreCruncher** [comment]
You need to tweak your Minecraft instance config in your launcher to use it.  The pastebin log indicated you are using an older version: Java Version: 1.8.0_51, Oracle Corporation

**Comment by tunaeskanaytac** [comment]
I'm searching to how to do that but can u tell me how to if u are available ?

**Comment by tunaeskanaytac** [comment]
it didn't help :/

**Comment by OreCruncher** [comment]
Can you post the updated log using the update version of Java?

**Comment by tunaeskanaytac** [comment]
Sorry I didn't literally understand you (My bad english :/ But if u were talking about crash log here is the link:
[Minecraft Crash Log PasteBin](https://pastebin.com/Xm7rSyzJ )

**Comment by OreCruncher** [comment]
Thanks!  According to the log it is still using version 51 (Java Version: 1.8.0_51, Oracle Corporation).

**Comment by tunaeskanaytac** [comment]
How can I update that ?

**Comment by tunaeskanaytac** [comment]
[Ok, I'm sure about I did it](https://pastebin.com/4SXn8TVu) but any changes about crashing

**Comment by OreCruncher** [comment]
Cool.  The Java version updated and you still have the crash.  I have some ideas as to what it may be.  I am going to make some tweaks.  I should have a new version posted to CurseForge in a day or 2.

**Comment by tunaeskanaytac** [comment]
So I'll leave up to you thanks for your helps ! ^^

**Comment by tunaeskanaytac** [comment]
Hey! I have something about crash I thought you should know:
I disabled the mod and entered the game. After that Trollager mob from Primitive mobs mod, Attacked me with throwing cobblestone entity. I think this is the reason of crash

**Comment by tunaeskanaytac** [comment]
![image](https://user-images.githubusercontent.com/13142062/43687882-751b642e-98e6-11e8-8f86-97f5cb991424.png)
Just like that

**Comment by OreCruncher** [comment]
I don't think its any other mod causing it.  If anything the mod changes the timing during startup which triggers a bug in DS.  I did find an issue in my code that could lead to this type of exception.  I am making a fix for it.  Unfortunately it may be 2 weeks for me to update the JAR.  A family emergency has come up and I don't want to publish something and walk away for 2 weeks.

**Comment by tunaeskanaytac** [comment]
Oh I'm sorry about that. Hope nothing is bad. Anyway that's your mod after all. You can update it anytime you want. Thanks for all of your helps.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.15 to CurseForge with a fix.

**Comment by tunaeskanaytac** [comment]
Hello again it didn't fixed :/
I use the latest version of forge and the latest version of mod but I get the same issue
[https://pastebin.com/xL2jmJvZ](url)

**Comment by OreCruncher** [comment]
If I pull together a debug JAR would you be willing to test it for me?  This problem defies explanation beyond the fix I made.  (There was a real problem there which would have resulted in a concurrency exception.)

**Comment by tunaeskanaytac** [comment]
I would but you need to lead me because I don't know the things that much :/

**Comment by OreCruncher** [comment]
It wouldn't be something to difficult.  It's a matter of downloading a JAR and putting it in your mods folder.  I will see about making one available tomorrow sometime.

**Comment by tunaeskanaytac** [comment]
ok then no problem with that ^^
