### ISSUE TITLE
Rain Volume 2.0

### ISSUE THREAD

**Issue by Artres** [OreCruncher/DynamicSurroundings#364]
*Mod Version:*
DynamicSurroundings-1.12.2-3.4.9.14.jar 

*Forge Version:*
1.12.2-forge1.12.2-14.23.4.2705

*Description:*
Before this goes anywhere, I want to point out that I have read this whole issue here from a year ago. https://github.com/OreCruncher/DynamicSurroundings/issues/77

So continuing... DynamicSurroundings' rain seems to be relatively really quiet compared to other sounds. Is there any way to fix this? I've tried checking through the config but still no ball there. I read through that past issue but I didn't get much out of it besides needing to install some sound mods (SoundFilters seems to screw up rain volume entirely making it silent) and that a new build was pushed out that was supposed to have fixed it. If you could help me out here, I would be really grateful. Thanks no matter the response.

**Comment by OreCruncher** [comment]
What modpack are you using?  As I type this I am running on a Revelations server and it is raining and I hear it fine.

**Comment by Artres** [comment]
I run a custom modpack. ^^" I'll just post my modlist since I imagine that's what you're looking for.

Modlist: https://pastebin.com/3mW7WUZN

**Comment by OreCruncher** [comment]
What is your weather sound slider set to?

**Comment by Artres** [comment]
100%. I think you're trying to solve this via turning up general audio, which I can do via just increasing my desktop audio but that would also turn up other sounds which is exactly what I don't want to do. I mean, don't get me wrong, I appreciate your help here, I'm just looking for a way to turn up rain rather than weather or audio as a whole. Thanks for the quick responses by the way! Really can appreciate when developers respond quickly. ^^

**Comment by OreCruncher** [comment]
Actually I was making sure that something else in the system wasn't turning down the volume. :)  Several factors do come into play when determining the final volume at which a sound plays.

I took a look at your mod list and nothing stood out as a potential conflict.  The base rain sound is pretty soft on it's own.  The overall sound experience for rain is based more on the quantity of rain splashes around the player (higher the intensity of the storm the more splashes that play).  The sounds are "layered" to give a sense of immersion.

I will have to do a bit more thinking on this.

**Comment by Artres** [comment]
Roger that, understood. Whilst I have you here, though it's off-topic I may as well ask... I plan to add TaN to the modlist, but I've read a number of posts on compatibility being a bit shaky with DynamicSurroundings here. Has that been rectified out of curiosity?

**Comment by OreCruncher** [comment]
What happened is the BoP guys split the season stuff off from TaN into a separate mod called Serene Seasons.  DS was caught in the crossfire.  The version of DS you are using is compatible with the latest TaN/Serene Seasons.  (I would recommend installing Serene Seasons as well to get the weather variations in the biomes.)

**Comment by Artres** [comment]
Oh, okay. I have Serene Seasons installed already, though I imagine you probably weren't looking for it to begin with so it's fair game, it was in the modlist, but thanks appreciate the recommendation anyway, haha. As for TaN, good news there then. I'll be adding that then in the near future then. As for the issue topic, I'll be patiently awaiting your response. Thanks for the help.

**Comment by OreCruncher** [comment]
Note To Self: Add option to use the vanilla rain sounds rather than the ones DS has.

**Comment by OreCruncher** [comment]
I am adding an option to use the vanilla rain sound which is louder and stronger.  Will show up in the v3.5 release.

**Comment by OreCruncher** [comment]
Pushed a BETA of v3.5 to CurseForge.  Note that the new version has a library dependency on OreLib (another library mod I made).  Make sure you read the release notes prior to upgrade.

**Comment by MauveCloud** [comment]
I'm liking the "Use Vanilla Rain Sound" option.  Seems better than my attempt to re-create my old resource pack that overrode the DS rain sounds, which came out a little too loud this time (and I had to turn down the weather volume to 70% 😕  )
