### ISSUE TITLE
SereneSeasons changes desert weather

### ISSUE THREAD

**Issue by RiptideC27** [OreCruncher/DynamicSurroundings#365]
DynamicSurroundings-1.12.2-3.4.9.14.jar
SereneSeasons-1.12.2-1.2.6-universal.jar
Forge 14.23.4.2705

When SereneSeasons is installed it seem to change the the desert weather from a dust storm to rain.

**Comment by OreCruncher** [comment]
From the changelog:
* More Serene Seasons compatibility changes:
 * Rainfall rendering occurs in Savanna during wet seasons.
 * Rainfall rendering occurs in Deserts during wet seasons. Dust storms will not render during the dry season. Dust storms will render in other seasons.

If it is the wet subseason in the Desert then yes you will get rain fall.  Can you confirm it is the wet season in the Desert?
