### ISSUE TITLE
[SUGGESTION] Blacklist JJ Meteors from being affected by particle changes in this mod

### ISSUE THREAD

**Issue by Sunconure11** [OreCruncher/DynamicSurroundings#366]
https://minecraft.curseforge.com/projects/jj-meteor

With these two mods installed, the explosion particles constantly fire from the meteors from JJ's meteor mod, causing quite a bit of lag.

**Comment by OreCruncher** [comment]
@Sunconure11 I am removing the explosion effect from the v3.5 version of DS.  It can easily cause lag overload on really large explosions and there is no real easy way to address.

**Comment by OreCruncher** [comment]
Pushed a BETA of v3.5 to CurseForge that has explosions removed.  Note that the new version has a library dependency on OreLib (another library mod I made).  Make sure you read the release notes prior to upgrade.
