### ISSUE TITLE
Issues with BiomeRegistry and OpenTerrainGenerator Biomes

### ISSUE THREAD

**Issue by atomyc-py** [OreCruncher/DynamicSurroundings#368]
*Mod Versions:*
DynamicSurroundings: 1.12.2-3.4.9.14
OpenTerrainGenerator:  1.12.2 v6
*Forge Version:*
14.23.4.2749

[Log Snippet](https://pastebin.com/d4bkXLhF)

*Description:*
Following the tutorial on biome-configuration results in a biome registry error.  To be more thorough, I tried specifically configuring both custom and built-in Minecraft biomes, as well as adding custom ones to the alias list.

**Comment by OreCruncher** [comment]
What's the error?  OTG is rather strange in how it handles biome registration.

**Comment by OreCruncher** [comment]
@atomyc-py Can you post the tutorial.json file you are using?

**Comment by OreCruncher** [comment]
@atomyc-py Any update?

**Comment by OreCruncher** [comment]
Pushed a BETA of v3.5 to CurseForge.  Note that the new version has a library dependency on OreLib (another library mod I made).  Make sure you read the release notes prior to upgrade.
