### ISSUE TITLE
Repeating Footsteps Sounds When Standing Still

### ISSUE THREAD

**Issue by Fytax** [OreCruncher/DynamicSurroundings#369]
Minecraft: 1.12.2
Dynamic Surroundings: 3.4.9.14
Forge: 14.23.2.2611

For some odd Reason, everytime i play on a Server with a Friend, his Footsteps Sounds Repeat whilst he Stands still and It doesn't stop, even when he Moves again.

I have Some Mods, but only Two of those are Sound Mods: Dynamic Surroundings and Sound Filters.
The Other Mods are just Appearance Mods like Better Foliage or just Inventory or Mini Map Mods.
I also have Mo' Bends but that just changes the Animation a bit.
I would greatly appreciate it, if you can Help me With this Problem.

Sincerely,
Fytax

**Comment by OreCruncher** [comment]
That is weird.  Does it matter what block they are standing on?  I know that players standing on a slime block get repeated sounds because of Minecraft issues.

**Comment by OreCruncher** [comment]
@Fytax I am making a change for [#374].  Not sure what is causing your particular issue but the change may address the problem.  I am going to mark this one fixed for now but if it continues to be a problem let me know.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.17 to CurseForge.  Let me know if it fixes your issue.
