### ISSUE TITLE
[Enhancement] Sound Filters , Reverb , Sound Physics

### ISSUE THREAD

**Issue by Tsoccerguy3** [OreCruncher/DynamicSurroundings#37]
*Mod Version:*
1.11.2
*Forge Version:*
1.11.2 Any version

*Link to crash log (if applicable):*

*Description:*
Sonic Ether's sound physics is already partially supported with footsteps , I can hear the echo and reverb while walking , not sure about the rest of the background sounds . Sonic has said that the sounds should be mono channel to work . Try DS with SoundPhysics , may there is a way to get everything working together

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2771480-sound-physics-realistic-sound-reverberation

**Comment by OreCruncher** [comment]
Almost all the sounds are mono.  There are a few exceptions.  The background sounds are positioned sounds that follow the player.

**Comment by Tsoccerguy3** [comment]
Since Sonic Ether hasn't posted the source for Sound Physics and it only worked in 1.11 , will have to wait for him to update to 1.11.2 to test with DS .  Right now the only other sound add on is Sound Filters 1.11.2 , https://mods.curse.com/mc-mods/minecraft/222789-sound-filters , which will work with DS footsteps in a boxed space that has at least 3 closed sided . It only ads in reverb . DS 1.10.2 with Sound Physics 1.10.2 is really interesting to hear

**Comment by Tsoccerguy3** [comment]
I just tested DS with Sound Physics 1.10.2  directional sound working with footsteps and block placement/breaking . Not with ambient sounds .

**Comment by OreCruncher** [comment]
Those are two different sound categories.  Not sure if these sound enhancement mods filter on that.  Ambient sounds are the AMBIENT sound category, and footsteps are PLAYER.

**Comment by OreCruncher** [comment]
Just looked a decompiled Sound Physics.  It does pattern matching against sound names.  Works for Vanilla sounds, but not necessarily modded sounds.

**Comment by Tsoccerguy3** [comment]
https://github.com/prook/fml-sound-physics
Not sure why can't get any sound after ported to 1.11.2 and compiled . Am i missing a dependency . Or has a name changed going from 1.11 to 1.11.2

Got everything working in DS 1.10.2 and sound physics . Maybe you can catch the mistake i missed in sound physics 1.11.2

**Comment by OreCruncher** [comment]
SonicEther just opened sourced SoundPhysics.  The current BETA will not work well with SoundPhysics.  He does a lot of ASM on the sound manager that will conflict with what Dynamic Surroundings needs right now.  Best option is to use Sound Filters because she avoids ASM.

**Comment by Galindorf** [comment]
I have been using a mod called "Sound Filters" by Tmtravlr, with version 1.11.2. It does a really nice job of echo and reverb especially in caves. Maybe give that a try?

**Comment by OreCruncher** [comment]
Replaced with #246.
