### ISSUE TITLE
Question about external JSON

### ISSUE THREAD

**Issue by RiptideC27** [OreCruncher/DynamicSurroundings#370]
I see that you said Yes, a pack author has the ability to configure DS behavior using external JSON config files, including turning on weather for a dimension. I just want to know is there any documentation to shows me how to use external JSON to enable weather for a dimension?

**Comment by RiptideC27** [comment]
Thanks :)

**Comment by OreCruncher** [comment]
Closing out the issue.  If you have further questions just ask. :)
