### ISSUE TITLE
Weird entity rendering with Albedo

### ISSUE THREAD

**Issue by Boymann** [OreCruncher/DynamicSurroundings#372]
Mod version: 1.12.2-3.4.9.14
Forge: 2756

Entities are visible (very gray) in rain/fog with Albedo installed.

**Comment by OreCruncher** [comment]
I have seen this myself and I believe this to be an Albedo issue.  It is not handling fog too well.  Albedo is not being developed anymore so I am not sure what can be done.  To be clear fog is handled by OpenGL - all that DS does is set the parameters for fog handling.

**Comment by Sunconure11** [comment]
@OreCruncher Someone took up Albedo, along with most of Elucent's mods.

https://discord.gg/75aVV7C

**Comment by OreCruncher** [comment]
I removed albedo support in v3.5.  I will add back in when maintenance starts happening, or change to a new library if I find one.
