### ISSUE TITLE
Server Crash Startup (1.12.2-3.4.9.15)

### ISSUE THREAD

**Issue by AngelusQQ** [OreCruncher/DynamicSurroundings#373]
Mod Version: DynamicSurroundings-1.12.2-3.4.9.15

Forge Version: 1.12.2-14.23.4.2705

Crash Report:
> Exception in server tick loop
> 
> java.lang.RuntimeException: java.lang.ClassNotFoundException: org.blockartistry.DynSurround.client.hud.CompassHUD
>     at net.minecraftforge.registries.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:110)
>     at net.minecraftforge.registries.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:80)
>     at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:624)
>     at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
>     at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
>     at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125)
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
>     at java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.ClassNotFoundException: org.blockartistry.DynSurround.client.hud.CompassHUD
>     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
>     at java.lang.ClassLoader.loadClass(Unknown Source)
>     at java.lang.ClassLoader.loadClass(Unknown Source)
>     at java.lang.Class.forName0(Native Method)
>     at java.lang.Class.forName(Unknown Source)
>     at net.minecraftforge.registries.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:104)
>     ... 7 more
> Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@50f40653 from coremod FMLCorePlugin
>     at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
>     at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
>     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
>     ... 12 more
> Caused by: java.lang.RuntimeException: Attempted to load class org/blockartistry/DynSurround/client/hud/CompassHUD for invalid side SERVER
>     at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
>     at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
>     ... 14 more
> 

Description: Crash upon start up for server (Client loads fine)

**Comment by OreCruncher** [comment]
Yay!  Forge ObjectHolder annotation ignoring the SideOnly annotation on the class. :\

**Comment by Sunconure11** [comment]
Encountering the same issue.

https://pastebin.com/ZJZsTpGu

**Comment by LordPhrozen** [comment]
looks like its trying to load the compas stuff on server. plz no.

**Comment by kreezxil** [comment]
Issue:  1.12.2-3.4.9.15 crashes dedicated server Forge 1.12.2 build 2759

Notes:
     looking for client side classes, you said if this was installed on a server we could see player footprints, that's not gonna happen if you keep forgetting about the @sidedz

crash report:
https://gist.github.com/baf5e2c9c92ec498060b3c65813e0193

fml server latest:
https://gist.github.com/6ab95ee98f6be2d2aaba87ca5d1a4a42


**I see you say it's fixed in dev can you please push it to CurseForge**? Thanks. :)

**Comment by OreCruncher** [comment]
Not forgetting about sides.  The Forge annotation processing for an object holder annotation processing is not honoring the side declaration of the class.  IMO its a Forge bug. :)

**Comment by jprocket45** [comment]
I know you gave a explanation about footprints in general though if this is fixed in dev can you send the update to curse?? thanks for your hard work on this mod btw!!

**Comment by Xenoamor** [comment]
+1 for a push to curse please

**Comment by EngineerXL** [comment]
+1 pls update on curseforge

**Comment by KamiSami** [comment]
Battle music is not working on server as it does not have the mod in it, but works in singleplayer that has the mod, may ned the fix so i can heal normal battle music in server too..

**Comment by kreezxil** [comment]
Issue:  3.4.9.15 crashes dedicated server Forge 1.12.2 build 2760

Notes:
     Class Not Found Exception

crash report:
https://gist.github.com/a9ed8184421218d66d7993f86000a9dd

fml server latest:
https://gist.github.com/1124b0c3c8b54371eeea784857a8e0d5


**not sure why i posted again with a new pack, but well, w/e you said this fixed 10 days ago but you still haven't pushed the fix**?

**Comment by OreCruncher** [comment]
Sorry for not getting to this sooner.  Some important RL stuff came up and this took a back burner.  The build has been posted to CurseForge.  Just waiting for it to get approved.

**Comment by Xenoamor** [comment]
Can confirm this is now working. Thanks for all your efforts OreCruncher!
