### ISSUE TITLE
Slime Block sound repetition

### ISSUE THREAD

**Issue by the-red-soul** [OreCruncher/DynamicSurroundings#374]
*Mod Version:*
3.4.9.15
*Forge Version:*
8.0.99.99

*Link to crash log (if applicable):*

*Description:*

Great mod truley great. 

Anyways I was making a slime block flying machine, and in doing so i walked one of the slime blocks from a piston.. Then for some reason the armorclink and slime sounds kept on playing as if i was still moving, even though I was completely still on said block. If I held shift the sounds would silence, until I let go. 

I am assuming that the mod is assuming im bouncing on the slime blocks for whatever reason. If I jump and land normally, shift or unshifted the sounds do not loop. 

Tbh when they are looping the sounds are rather suggestive......

**Comment by OreCruncher** [comment]
Pushed v3.4.9.17 to CurseForge.
