### ISSUE TITLE
random crashes

### ISSUE THREAD

**Issue by blubbll** [OreCruncher/DynamicSurroundings#376]
*Mod Version:*
latest
*Forge Version:*
idk, check log

*Link to crash log (if applicable):*
https://bpaste.net/show/f280a8d58436
*Description:*
the game randomly crashes from time to time, saying
"The game crashed whilst ticking particle
Error: java.lang.ArrayIndexOutOfBoundsException: -1"

**Comment by OreCruncher** [comment]
I’m out of town currently.  Can you remove less lag and see if it still happens?  The error occurs in regula Minecraft code.  I have seen this with cubic chunks until they made some fixes.

**Comment by blubbll** [comment]
i removed it and will report occuring crashes in the future

**Comment by OreCruncher** [comment]
@blubbll Just checking in to see if there is anything further to report about the crashes.

**Comment by blubbll** [comment]
I haven't had one yet. I suggest to close  this issue and i will reopen it if i occur something related to dsurroundings again.

**Comment by OreCruncher** [comment]
Sound good.  Thanks!
