### ISSUE TITLE
Serene Seasons autumn season non-functional

### ISSUE THREAD

**Issue by phyne** [OreCruncher/DynamicSurroundings#378]
The season clock from Serene Seasons is displaying [this](https://i.imgur.com/lWBo1RE.png) during the autumn season (early, mid, and late). Summer specific crops are still growing and Autumn specific crops will not grow.

For those needing to circumvent the issue, you can build a greenhouse with the Serene Seasons included greenhouse blocks to grow the autumn crops out of season.

**Comment by phyne** [comment]
I'm an idiot. Non-summer crops weren't growing because I was in a [tropical biome type](https://github.com/Glitchfiend/SereneSeasons/wiki/Seasons). The text is still a bug I suppose, so I'll leave the issue open for you to decide.

**Comment by OreCruncher** [comment]
Yep.  Still looks like the rendering of the hud has an issue.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.17 to CurseForge.
