### ISSUE TITLE
Startup crash with latest Forge release for 1.12.2

### ISSUE THREAD

**Issue by ChinChopper** [OreCruncher/DynamicSurroundings#383]
*Mod Version:*
3.4.9.16
*Forge Version:*
14.23.5.2768

*Link to crash log (if applicable):*
https://paste.ee/p/lSYSY
*Description:*
Recently the forge version 14.23.5.2768 has become recommended and this mod is causing crash in the game after initialization.
Says LexMano in this session (3th comment)
http://www.minecraftforge.net/forum/topic/66711-forge-1122-142342768-startup-crash/

**Comment by OreCruncher** [comment]
It's not dynamic surroundings.  Two mods appear to be having a challenge: Better Foliage and SecurityCraft.  I recommend removing those two to ensure things work, then add back Better Foliage.  The SecurityCraft triggers the first error and may be causing the second with Better Foliage.

**Comment by ChinChopper** [comment]
I verified, only better foliage.
The first error of SecurityCraft always occurred but never had problems within the game.
Thanks, and sorry, I dont know to see a log, LexManos gave me a list with the mods that said in the LOG in "warning", so I decided to report.

**Comment by OreCruncher** [comment]
No worries.  That info in the log is standard boiler plate.  Forge dumps all coremods and asks that authors be contacted first.  The reason is that coremods rewrite portions of Forge/Minecraft at load time and can screw things up royally - something Lex and crew cannot do anything about.  I would rather see these things than have it be my issue and know nothing about it. :)

**Comment by Drakoflame** [comment]
okay I know this is old and been fixed... but holy fucking shit this is my isue as well... I just want to confirm D-H-U, it's Better Folliage causing the issue? It recently was updated but I haven't tested to see if it's fixed.

**Comment by OreCruncher** [comment]
In my experience the latest version of Better Foliage with the latest version of Forge causes a crash.

**Comment by Drakoflame** [comment]
I actually just tested, the version of BF updated yesterday (10/26/2018), works with Forger version 2768, does indeed work. My crashes were happening the moment I got to the main menu screen.
