### ISSUE TITLE
Some Chisel Blocks dont have sound when i step on it

### ISSUE THREAD

**Issue by SugarDaddii** [OreCruncher/DynamicSurroundings#384]
*Mod Version: 1.12.2*

*Forge Version: 14.23.5.2768*

*Link to crash log (if applicable):no crash log luckly XD*

*Description: When i step for example on Laboratory Block from chisel (0.2.1.35) in any style i dont get a sound of metal or something else...if i step on Tyrian there is a sound! So there are also no sounds for some other blocks too: factory block or factory1 block in any styles
Do you have any suggestions or help?*

**Comment by OreCruncher** [comment]
This is something I have on my list to look at.  It could be there is no sound assigned to the block material.

**Comment by SugarDaddii** [comment]
But its not possible to make sound by myself
i try it with a json file but it doesnt work XD lol

"footsteps":{
		"minecraft:barrier":"NOT_EMITTER",
		"minecraft:air":"NOT_EMITTER",
		"minecraft:stone":"stone",
		"minecraft:grass":"grass",
		"minecraft:grass_path":"grass"
		"chisel:glass":"glowstone",
		"chisel:factory_6":"metalbar",
		"chisel:factory 4":"metalbar",
		"chisel:tyrian":"stone",
		"chisel:laboratory^6":"metalcompressed,hardmetal"

**Comment by OreCruncher** [comment]
I think there is something else at work here beyond configuration.  I noticed it myself on some of the servers I have played on.

**Comment by OreCruncher** [comment]
Checking in to this.  In my development environment the debug trace shows it is playing the sound and the appropriate step sound for the block is indeed played.  However, in a pack that I am working on I do not get the sound, but the log indicates that the sound is queued for play.  What's funny is if I jump up and down on the block I do get the sound.

**Comment by SugarDaddii** [comment]
yeah same on me when i jumped on these blocks sound will play very funny (also in my version)

**Comment by OreCruncher** [comment]
Found the problem. :)

**Comment by SugarDaddii** [comment]
cant wait to download the fixed version HURREJ 💃

**Comment by OreCruncher** [comment]
Version v3.4.10.1 pushed to CurseForge.
