### ISSUE TITLE
Suggestion: Configure Power Words

### ISSUE THREAD

**Issue by PixelmonPRO** [OreCruncher/DynamicSurroundings#386]
Hello! I would like to be able to localize and configure power words, in game, or `.lang` files. Is it possible to add a similar option? Thanks!

**Comment by OreCruncher** [comment]
I've been meaning to do this for a bit.  I'll add this to the 3.5 release train.

**Comment by OreCruncher** [comment]
Pushed a BETA of v3.5 to CurseForge.  Note that the new version has a library dependency on OreLib (another library mod I made).  Make sure you read the release notes prior to upgrade.
