### ISSUE TITLE
Player chat bubble not showing if entity chat is disabled

### ISSUE THREAD

**Issue by KenyMylankca** [OreCruncher/DynamicSurroundings#388]
Can you please add a feature that will display players' chat message above their head?
You could make it passive and can be activated in config by the user. I think this would improve the mod a bit :D

**Comment by OreCruncher** [comment]
It's already a feature.  Turn chat bubbles on.

**Comment by OreCruncher** [comment]
Which version of DS are you using?

**Comment by KenyMylankca** [comment]
3.4.10.0 on Forge 2772. If you need more info for anything with my modpack, you can see [everything here](https://github.com/KenyMylankca/Harshen-Modpack).

**Comment by OreCruncher** [comment]
Are you hosting the server?

**Comment by KenyMylankca** [comment]
Yeah, as i said, it's my local world (via Open to LAN)
![saa](https://user-images.githubusercontent.com/41585837/48005674-12306080-e125-11e8-870b-17f2d9f37972.PNG)

**Comment by OreCruncher** [comment]
Right - just needed to know if you were hosting or your friend was :)

**Comment by KenyMylankca** [comment]
uhm, (in my local hosted world) i pressed f5 (seeing myself) and wrote something in chat, and no, can't see anything above my head.
same with my friend.
I already load a local world, i create new world every week and we play it.

**Comment by OreCruncher** [comment]
What I mean by local is single player - no LAN.  I looked at the config on github and it looks good for settings.

**Comment by KenyMylankca** [comment]
Oh you want me check it myself alone in my singleplayer world, without hosting. Ok gonna do it.

**Comment by KenyMylankca** [comment]
Well, did it, sadly kinda the same.
![fds](https://user-images.githubusercontent.com/41585837/48013392-3f850a80-e135-11e8-900d-875cea271151.PNG)

**Comment by OreCruncher** [comment]
OK - found it.  It's a bug in DS.  It will be fixed in the next drop.  If you really want it on in the mean time turn on entity chatting.  Downside is that you have to listen to mobs. :)

**Comment by KenyMylankca** [comment]
Oh, i'm glad that ive found a bug! :D Thanks! I'll be waiting :)

**Comment by OreCruncher** [comment]
Version v3.4.10.1 pushed to CurseForge.
