### ISSUE TITLE
[1.12.2 - Suggestion] Possible to change the Hurt Threshold to be scaled by percentage instead of a flat value?

### ISSUE THREAD

**Issue by Z-Tunic** [OreCruncher/DynamicSurroundings#389]
I don't know of any mods out there that increases the max Hunger/Saturation value from the default 20 but for Health... some mods out there allow you to increase it's max value from the default 20.

Would it be possible to have a config option to have these thresholds play out based on a percentage of the remaining Health instead of a flat value? A few examples...

Config option is set at 25% for Hurt Threshold. It's sound effect will only play if the player's health is at 5 or less if their max health is 20. If the player increased their health to... say 40 and their health is 10 or less... the sound effect plays.

10% would be 2/20 | 4/40 | 10/100, etc. for the sound to play.
50% would be 10/20 | 20/40 | 50/100, etc. for the sound to play.

**Comment by OreCruncher** [comment]
I can probably do this for the 3.5.0.0 version (which I am currently working on).

**Comment by OreCruncher** [comment]
Pushed a BETA of v3.5 to CurseForge.  Note that the new version has a library dependency on OreLib (another library mod I made).  Make sure you read the release notes prior to upgrade.
