### ISSUE TITLE
Gradle is broken

### ISSUE THREAD

**Issue by Tsoccerguy3** [OreCruncher/DynamicSurroundings#39]
*Mod Version:*
1.11.2
*Forge Version:*
forge-1.11.2-13.20.0.2232

*Link to crash log (if applicable):*

*Description:*
edit : missing ToughAsNails-1.11-2.0.5.jar .

**Comment by OreCruncher** [comment]
Actually I use the JARs in the "libs" directory.

**Comment by Tsoccerguy3** [comment]
Hi Ore , I found the missing ToughAsNails-1.11-2.0.5.jar and DS compiled , thanks
To help others , maybe add a brief list of dependencies and where they go on OP or in readme.md
