### ISSUE TITLE
 [Crash] After updating to Version 1.12.2-3.4.10.1 from 1.12.2-3.4.10.0

### ISSUE THREAD

**Issue by SugarDaddii** [OreCruncher/DynamicSurroundings#391]
*Mod Version:* 1.12.2

*Forge Version:* 14.23.5.2768

*Link to crash log (if applicable):* https://pastebin.com/S3EQUqPB

*Description:* Crashed after new update

**Comment by SugarDaddii** [comment]
After deleting the mod this will came 

http://prntscr.com/lhzhsm

**Comment by MasterEnderman** [comment]
I'm having the same problem.

**Comment by OreCruncher** [comment]
For some reason there are two coremods in the 1.12.2 mod directory:
```
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.10.1-core.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.10.0-core.jar)
```
Navigate to the 1.12.2 subfolder in your mods directory and delete both instances of the DS core mod.  Then start your client.

**Comment by MasterEnderman** [comment]
That fixed it!. Thanks.

**Comment by SugarDaddii** [comment]
okay that is fixed but maybe you need to fix it by your own because when someone updates this will happen

**Comment by OreCruncher** [comment]
Yeah.  Forge policy wants us to have the coremod seperate and embedded in the JAR.  However, it doesn't cleanup its own cache so this happens.  What a bunch of...well...  *rolls eyes*

**Comment by OreCruncher** [comment]
Pushed v3.4.10.2 to CurseForge.  Lemme know how it goes.  You will need to delete the older coremod from the mods/1.12.2 folder.  Going forward the coremod should find its way into the memory_repo folder and be managed properly.  Yay.

**Comment by OreCruncher** [comment]
It's there....https://github.com/OreCruncher/DynamicSurroundings/blob/1.12.2/CHANGELOG.md

**Comment by TimGoll** [comment]
oh.
I'm just dumb, sorry!

**Comment by OreCruncher** [comment]
lol.  No worries.  I've been having similar moments as of late.  Maybe it's the season. :)

**Comment by TimGoll** [comment]
I'm tired. Too much university, too much work! :D
