### ISSUE TITLE
[FEATURE] Make Animania interaction comfigurable

### ISSUE THREAD

**Issue by V10lator** [OreCruncher/DynamicSurroundings#393]
As the title says it would be great if the animania interaction (showing hunger/thirst) would be configurable.

**Comment by OreCruncher** [comment]
Configurable how?  You can turn them off using the config.  Look under speech bubble options.

**Comment by V10lator** [comment]
Yes, thanks.

**Comment by OreCruncher** [comment]
Cool!  On a related note are running animania and turning the feature off?  If so i am curious as to the reason.  I am just trying to understand my customer base a bit more. :)

**Comment by V10lator** [comment]
There are players not using DS and I don't want to see more information than them. Also WAYLA already covers that info (and is used by all players on the server).
