### ISSUE TITLE
Serene Seasons snow broken

### ISSUE THREAD

**Issue by V10lator** [OreCruncher/DynamicSurroundings#394]
*Mod Version:* 3.4.10.2

*Forge Version:* 1.12.2-14.23.5.2768

*Serene Seasons Version:* 1.2.6

*Description:* According to #312 DS should be compatible with SS but when players without DS see snow in winter all I see is rain. A workaround is to disable better rain and better snow in DS. If it helps this was on a Beach biome near a Flower Field (Biomes o Plenty) biome.

**Comment by OreCruncher** [comment]
Maybe they changed something.  I use v1.2.3 to build against.  I will update to 1.2.6 and take a peek.

**Comment by OreCruncher** [comment]
Just loaded it up.  Went to a beach.  Did a /ss setseason mid_winter.  Then did a /toggledownfall.  I get snow.  What modpack are you using?

**Comment by OreCruncher** [comment]
@V10lator Gentle Ping.  (You been fixing a bunch of Animania stuff so you been busy.)

**Comment by V10lator** [comment]
> What modpack are you using?

It's not a mod pack one could download but "some" selected mods. I guess you need the ones installed client-side? I really need to clean the list as some of the mods aren't installed server-side anymore but here you go:
````
$ ls ~/.minecraft/mods/
 1.12.2
 AdChimneys-1.12.2-3.3.12.0-build.0197.jar
 BetterFoliage-MC1.12-2.1.10.jar
 BetterFps-1.4.8.jar
 BetterRecords-1.12.2-1.6.1.jar
 BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar
 CTM-MC1.12.2-0.3.2.20.jar
 CarryOn+MC1.12.2+v1.12.jar
 ClientTweaks_1.12.2-3.1.9.jar
 CodeChickenLib-1.12.2-3.2.2.353-universal.jar
 CraftStudio-1.0.0.93-mc1.12-alpha.jar
 DynamicSurroundings-1.12.2-3.4.10.4.jar
 DynamicTrees-1.12.2-0.9.1d.jar
 DynamicTreesBOP-1.12.2-1.4.1d.jar
 FamiliarFauna-1.12.2-1.0.10.jar
 FancyBlockParticles-1.12.x-2.4.1.jar
 FastFurnace-1.12.2-1.2.1.jar
 FastWorkbench-1.12.2-1.5.3.jar
 ForgeEndertech-1.12.2-4.4.0.0-build.0180.jar
 ForgeMultipart-1.12.2-2.6.0.79-universal.jar
 Forgelin-1.8.0.jar
 FutureMinecraftV1.1.1.jar
 GraveStone-1.12.2-Graves-1.2.0.jar
 HardcoreDarkness-MC1.12.2-2.0.jar
 Hwyla-1.8.26-B41_1.12.2.jar
 InventoryTweaks-1.63.jar
 JEHC-1.12.2-1.6.2.0.jar
 LagGoggles-FORGE-1.12.2-4.1.jar
 MAGE-0.2.4.jar
 MetalChests-v3.9.0.g9b0c79e.jar
 NotEnoughItems-1.12.2-2.4.2.240-universal.jar
 ObsidianAPI-1.0.0.jar
 ObsidianPlates-1.3.0_1.12.jar
"Pam's+HarvestCraft+1.12.2z.jar"
 Placebo-1.12.2-1.4.1.jar
 Prehistoric+Eclipsev0.6-BETA.jar
 ProportionalDestructionParticles-1.12.2-1.2.3.jar
 Railcraft_1.12.2-10.4.0-beta-1-unofficial.jar
 RebornCore-1.12.2-3.10.1.335-universal.jar
 SereneSeasons-1.12.2-1.2.12-universal.jar
 ServerObserver-1.12.2-1.0.2.36-universal.jar
 ShadersMod-v2.7.1mc1.12.jar.disabled
 SimpleDimensions-MC1.12-1.3.1.jar
 SmoothFont-mc1.12.2-1.16.1.jar
 SophisticatedWolves-1.12.2-3.13.7.jar
 SoundFilters-0.10_for_1.12.jar
 StevesCarts-1.12.2-2.4.24.118.jar
 ThirstyBottles-1.12.2-1.1.4.jar
 Toast+Control-1.12.2-1.7.1.jar
'Vanilla Life-1.6.2.jar'
 VanillaFix-1.0.10-99.jar
 VoxelMods
 WR-CBE-1.12.2-2.3.1.null-universal.jar
 Wawla-1.12.2-2.5.259.jar
 WearableBackpacks-1.12.2-3.1.3.jar
'Weee!+Flowers+1.12.2b.jar'
 WorldEdit+CUI+Forge+Edition+2-2.2.0-mf-1.12.2-14.23.5.2768.jar
 XaerosWorldMap_1.3.2_Forge_1.12.jar
 Xaeros_Minimap_1.15.9_Forge_1.12.jar
 aether_legacy-1.12.2-v3.2.jar
 animania-1.12.2-1.6.2.jar
 animation
 bearwithme-1.12.2-1.3.1.jar
 betteranimals-3.0.jar
 bibliotheca-1.3.3-1.12.2.jar
'bookworm animator'
 clearwater-1.2.jar
 coroutil-1.12.1-1.2.14.jar
 desirepaths-1.12.1-1.2.jar
 enchanting_tweaks-1.1.jar
 foamfix-0.10.2-1.12.2.jar
 furniture-6.0.0-1.12.2.jar
 hempfarmer-0.0.1.jar
 hopperducts-mc1.12-1.5.jar
 install-asm-all-5.2-for-minecraft.jar
 jei_1.12.2-4.13.1.225.jar
 kjlib-1.0.4.jar
 lightningtweaks-1.12.2-1.1.1.0.jar
 memory_repo
 mobends-0.24_for_MC-1.12.jar
'moon-core+7.0+(1.12).jar'
 movinglightsource-1.12.2-1.0.15.jar
 qsilkspawners-1.1.2.jar
 randompatches-1.12.2-1.8.0.0.jar
 redstonepaste-mc1.12-1.7.5.jar
 simpleportals-1.12.2-1.5.1.0.jar
 sparkshammers-1.12.2-1.9.2.jar
 stonechests-1.0.0.jar
````
Shoot into the blue: It might be connected to SimpleDimensions as this is in a world created by it and (I just noted) /ss setseason doesn't work there.

> EDIT: Another thing you can do is enable DS debug logging. When in game hit F3 to get the debug screen. Take a screenshot and post a link here.

One time with DS snow/rain enabled and one time disabled:
![2018-12-03_14 58 45](https://user-images.githubusercontent.com/1312422/49378254-6c184c00-f70c-11e8-8701-58fdb7109395.png)
![2018-12-03_14 58 20](https://user-images.githubusercontent.com/1312422/49378265-70446980-f70c-11e8-840b-86283d4283d9.png)

> EDIT2: The other thing you can do is get a hold of a season clock

Again two screens. But it doesn't matter what sub-season, it's all the time in winter:
![2018-12-03_14 58 51](https://user-images.githubusercontent.com/1312422/49378310-8c480b00-f70c-11e8-80a9-a36f1f11ef96.png)
![2018-12-03_14 58 23](https://user-images.githubusercontent.com/1312422/49378327-979b3680-f70c-11e8-84d1-31da382ceb14.png)

> EDIT3: Are you running with the default Serene Seasons config, or has it been tweaked?

Default config.

> Gentle Ping.

Sorry for the late reply. If you need me to I could zip my mods and config folders for you.

**Comment by OreCruncher** [comment]
@V10lator Upon review I think this problem is related to [#417].  Updating to v3.4.10.5 as well as the latest SS should address the issue.  Let me know what you find out.

**Comment by OreCruncher** [comment]
@V10lator Have you had a chance to update to see if the problem persists?

**Comment by V10lator** [comment]
I just did but now there's only rain even without DS. So I can't test untill SS fixes this.

**Comment by OreCruncher** [comment]
@V10lator It's been a bit and I was wondering if you managed to get any closure?

**Comment by V10lator** [comment]
@OreCruncher The server I experienced this is no longer online and the complete world has been deleted some time ago. Also I'm way to busy in RL to debug this any further.
That said I'm sorry but I'm out of this bug report.

**Comment by OreCruncher** [comment]
No worries.  I haven't seen any additional issues like this with SS.  When I develop I always have SS installed.  I'm going to close.  Thanks for taking the time to respond.

**Comment by ErynRev** [comment]
Hey, sorry to open this again as it’s so much later on. I am using SS without DS on 1.20.1 and i am having this exact same issue where when it should be appearing as snow in winter, it appears as rain. Snow is accumulating like normal just the texture isn’t snow. Is there any way to fix this? It’s on a server, i have reinstalled SS multiple times checked the config. 
It started off working until i restarted the server.
Thanks
