### ISSUE TITLE
Presets' update nag message can't be turned off

### ISSUE THREAD

**Issue by ItsTheKais** [OreCruncher/DynamicSurroundings#396]
Turning off the update message in DS's config only disables DS's message, and Presets doesn't have a setting for its own message.

**Comment by OreCruncher** [comment]
Pushed a BETA of v3.5 to CurseForge that has Presets! removed.  Note that the new version has a library dependency on OreLib (another library mod I made).  Make sure you read the release notes prior to upgrade.
