### ISSUE TITLE
 [1.12] NoClassDefFoundError crash with latest DS update

### ISSUE THREAD

**Issue by xAlicatt** [OreCruncher/DynamicSurroundings#398]
*Mod Version:* 3.4.10.2

*Forge Version:* 2768 (1.12)

*Link to crash log (if applicable):* https://hastebin.com/tematubobo.rb

*Description:* This crash is talked about in #390 but it is closed and I wanted to make sure you saw it, and I wasn't sure if it was exactly the same thing. I was able to startup with no issues with the previous release version (3.4.9.17)

**Comment by OreCruncher** [comment]
Remove any Dynamic Surroundings coremods from your instance/mods/1.12.2 folder and try again.  From the report it appears you have two coremods trying to load.  Also, did you have a BETA v3.4.10.0 or v3.4.10.1 installed prior?

**Comment by OreCruncher** [comment]
@xAlicatt Are you back up and running?

**Comment by xAlicatt** [comment]
Yes...sorry, I meant to come back and say that the duplicate mods seemed to be the issue. Thank you for the help!
