### ISSUE TITLE
[Enhancement] Support tools/weapons from the Tetra mod

### ISSUE THREAD

**Issue by fisher521** [OreCruncher/DynamicSurroundings#400]
*Mod Version:* 3.4.10.2

*Forge Version:* 2768

*Description:* 
When using a Tetra improved sword or tool, the swing sound and equip sound don't play at all. 
Tetra Mod: https://minecraft.curseforge.com/projects/tetra?gameCategorySlug=mc-mods&projectID=289712

Edit: added link

**Comment by OreCruncher** [comment]
What's a Tetra sword?  What mod does it come from?  Chances are it either doesn't derive from one of the Minecraft types or I don't have a config for it.

**Comment by fisher521** [comment]
A Tetra sword is a sword that has been improved using the [Tetra mod](https://minecraft.curseforge.com/projects/tetra?gameCategorySlug=mc-mods&projectID=289712).

**Comment by OreCruncher** [comment]
Pushed a BETA of v3.5 to CurseForge.  Note that the new version has a library dependency on OreLib (another library mod I made).  Make sure you read the release notes prior to upgrade.
