### ISSUE TITLE
explosion crash

### ISSUE THREAD

**Issue by TheNimbleNinja** [OreCruncher/DynamicSurroundings#401]
DynamicSurroundings-1.12.2-3.4.10.2
fore-14.24.5.2772

https://gist.github.com/TheNimbleNinja/e5454b30eb27401707b51a875b35f736

lycanite mob went and exploded and game crashed

**Comment by OreCruncher** [comment]
You can turn off explosions if its a real problem.  Not going to fix because the feature is being removed in the v3.5 update.

**Comment by OreCruncher** [comment]
Pushed a BETA of v3.5 to CurseForge that removes the explosion feature.  Note that the new version has a library dependency on OreLib (another library mod I made).  Make sure you read the release notes prior to upgrade.
