### ISSUE TITLE
Cubic Chunks rendering bug

### ISSUE THREAD

**Issue by Adam-R-Kaminski** [OreCruncher/DynamicSurroundings#403]
*Mod Version: 1.12.2*

*Forge Version: 2768*

*Link to crash log (if applicable): didnt crash*

*Description: well, after getting below y=0 strange graphical seemingly bug occurs (yes i double checked if thats Dynamic surroundings to make sure)*
![2018-11-23_17 05 26](https://user-images.githubusercontent.com/34427698/48952358-37550980-ef42-11e8-8f7c-656a908862ea.png)

**Comment by OreCruncher** [comment]
Yep :)
