### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by agentwolf88** [OreCruncher/DynamicSurroundings#405]
*Mod Version:* latest

*Forge Version:* latest

*Link to crash log (if applicable):* https://paste.ee/p/M1shJ

*Description:* Server crash at startup

**Comment by OreCruncher** [comment]
Did you install the mod dependency OreLib?

**Comment by agentwolf88** [comment]
oh, no, is this new?

**Comment by OreCruncher** [comment]
Yep - it's new with 3.5.  If you use the Twitch launcher it should automagically pull down the dependency.

**Comment by OreCruncher** [comment]
@agentwolf88 Did you confirm it was the missing OreLib?

**Comment by agentwolf88** [comment]
Yes, this was the problem. Thx for support.

**Comment by OreCruncher** [comment]
Cool!  Let me know if you have any other issues.
