### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by ScienceDrummer** [OreCruncher/DynamicSurroundings#406]
*Mod Version:*
1.12.2-3.5.0.0BETA
*Forge Version:*
14.23.5.2780 
*Link to crash log (if applicable):*
https://paste.dimdev.org/zuvavezipu.mccrash
*Description:*
I had set fire to a forest and when I crossed a river, I got this crash. No idea if that has anything to do with it.

**Comment by OreCruncher** [comment]
Were you able to successfully log back in and continue?  And yes it looks like mine.

**Comment by ScienceDrummer** [comment]
I loaded up the world and then immediately crashed again.

**Comment by OreCruncher** [comment]
Can you post a link to your client log?

**Comment by OreCruncher** [comment]
Thanks!  Best I can tell the blockstate in question has no bounding or collision box.  Need to dig further.

**Comment by Tsoccerguy3** [comment]
Getting a similar crash with WorldDownloader conflict , the logs on my OneDrive  http://sdrv.ms/TPcx5v in ore directory

**Comment by OreCruncher** [comment]
@TheRealDadbeard That crash is a different one.  I'll create another issue to track it.  I'm going to need the client log.

**Comment by OreCruncher** [comment]
Version v3.5.0.1 BETA pushed to CurseForge.  I don't need the client log anymore.  If the crash continues to happen I will need it.
