### ISSUE TITLE
Crash with Serene Seasons

### ISSUE THREAD

**Issue by lebanni** [OreCruncher/DynamicSurroundings#408]
Version :
DynamicSurroundings-1.12.2-3.5.0.0BETA.jar
SereneSeasons-1.12.2-1.2.9-universal.jar

[crash-2018-11-28_07.54.10-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/2623241/crash-2018-11-28_07.54.10-client.txt)

https://github.com/Glitchfiend/SereneSeasons/issues/101

**Comment by OreCruncher** [comment]
Waiting on updated Serene Seasons JAR.

**Comment by OreCruncher** [comment]
Both v3.4.10.3 and v3.5.0.1 are both on CurseForge.  Yay.
