### ISSUE TITLE
Error in log executing scripts 

### ISSUE THREAD

**Issue by NerdCraft** [OreCruncher/DynamicSurroundings#41]
Mod Version: 3.2.8.1

Forge Version: 12.18.3.2234

http://pastebin.com/y9HGMjxR

**Comment by OreCruncher** [comment]
Modpack/mods?

**Comment by NerdCraft** [comment]
modlist: https://i.cubeupload.com/oX8B9j.png
 
Yes, I did.

**Comment by OreCruncher** [comment]
OK.  Think I know the problem.  Fix will be in the next beta.  Until then you need to un-disable the the block effect if the issue is causing you a problem.
