### ISSUE TITLE
Heartbeat sound, then a screen rendering crash

### ISSUE THREAD

**Issue by crysthala** [OreCruncher/DynamicSurroundings#410]
*Mod Version:* OreLib-1.12.2-3.5.0.0BETA, DynamicSurroundings-1.12.2-3.5.0.1BETA

*Forge Version:* 14.23.5.2772

*Link to crash log:* [crash-2018-11-28_20.48.01-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/2627415/crash-2018-11-28_20.48.01-client.txt)

*Description:*
Created a new world. It was a bit stuttery when it loaded in, and I started to hear the low-health "heartbeat" sound. I tried to open the mod's settings page. The screen turned gray for a moment, then the game crashed.

I love the bug reporting template on this page, by the way. Makes it a lot easier to remember what needs to be included. :)

**Comment by OreCruncher** [comment]
This is interesting.  Did you start with an old config file or from scratch?

**Comment by crysthala** [comment]
Wow, quick response! Old config file. I updated from 3.4.9.17. Good thing these logs get backed up... [debug-1.log](https://github.com/OreCruncher/DynamicSurroundings/files/2627659/debug-1.log)

**Comment by OreCruncher** [comment]
Maybe this is a faster response? :)
```
[20:47:57] [main/ERROR] [FML]: There was a critical issue trying to build the config GUI for dsurround
java.lang.NumberFormatException: For input string: "0.0"
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_181]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_181]
	at java.lang.Integer.valueOf(Unknown Source) ~[?:1.8.0_181]
```
It's not liking the config.  Can you post a link to it so I can take a peek?

**Comment by crysthala** [comment]
I didn't know Usain Bolt made mods!

I rolled back to the previous version I was using so I could keep testing my modlist. I did notice that some of the settings had been reverted to default when I started back up: damage popoffs, critical messages, and footprints had all been re-enabled. So I switched them back, rolled forward, and tested it again. Same exact story as before. Here, have some fresh logs. I have no idea if they'll help, but just in case.

[crash-2018-11-28_23.35.35-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/2627708/crash-2018-11-28_23.35.35-client.txt)
[debug.log](https://github.com/OreCruncher/DynamicSurroundings/files/2627709/debug.log)
Backup I made of the config file with the working version: [dsurround - backup.txt](https://github.com/OreCruncher/DynamicSurroundings/files/2627713/dsurround.-.backup.txt)
And this is the one left after running the game: [dsurround.txt](https://github.com/OreCruncher/DynamicSurroundings/files/2627714/dsurround.txt)

**Comment by OreCruncher** [comment]
OK.  For the v3.5.0.1 version of the config you need to manually edit and change the "Hurt Threshold" from 8 to 0.25.  With v3.5.0.1 it is now a percentage rather than a specific number.  This should get you going.  I will need to add some validation code to clamp values when the config file is read to prevent stuff like this.

**Comment by crysthala** [comment]
Hooray, no more heartbeats. It still crashes when I attempt to open the config screen, so I just backed up the old config and let the mod generate a new default one. Now works perfectly.

Thanks so much for your help! This mod is great, really makes MC feel more alive.

**Comment by OreCruncher** [comment]
Pushed OreLib v3.5.0.1 to CurseForge.  This should fix the crash and handle the config property conversion.  Another change for Dynamic Surroundings will be posted in a couple days (depending) that caps the hurt threshold percentage at 0.5 (50%).

**Comment by crysthala** [comment]
Cool! Thanks again for your help.

**Comment by OreCruncher** [comment]
Pushed v3.5.0.2 to CurseForge.
