### ISSUE TITLE
DSurroundings crashing the client:

### ISSUE THREAD

**Issue by Adam-R-Kaminski** [OreCruncher/DynamicSurroundings#411]
*Mod Version: 3.4.10.2 *

*Forge Version: 2772*

[dsurround-ss can water freeze.log](https://github.com/OreCruncher/DynamicSurroundings/files/2635235/dsurround-ss.can.water.freeze.log)
[showfrostbreath crash.log](https://github.com/OreCruncher/DynamicSurroundings/files/2635238/showfrostbreath.crash.log)

**Comment by OreCruncher** [comment]
Update to v3.4.10.3 - it has the fixes.

**Comment by OreCruncher** [comment]
@Adam-R-Kaminski Have you had a chance to update?

**Comment by Adam-R-Kaminski** [comment]
Yes, i did, update fixed the issues. I'll report new ones if i find them.

**Comment by OreCruncher** [comment]
Cool!  I will close the issue then.  Thanks!
