### ISSUE TITLE
Crash Report 

### ISSUE THREAD

**Issue by DrakeBD** [OreCruncher/DynamicSurroundings#412]
*Mod Version:*
DynamicSurroundings-1.12.2-3.5.0.2BETA.jar
*Forge Version:*
1.12.2 - 14.23.5.2768

*Link to crash log (if applicable):*
[crash-2018-12-01_12.10.31-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/2635853/crash-2018-12-01_12.10.31-client.txt)

*Description:*
World loads up fine but when i started to move and open up new chunks game crashed to desktop

**Comment by OreCruncher** [comment]
@PG85 When does the biome information get loaded on the client?  With v3.5 I have a world load event handler at the lowest priority that will initialize my biome registry.  My goal is to avoid lag doing this reset during world load rather than when the player is wandering around.

**Comment by OreCruncher** [comment]
Pushed v3.5.0.3 to CurseForge with a fix.
