### ISSUE TITLE
crash on launch

### ISSUE THREAD

**Issue by HentaiHamster** [OreCruncher/DynamicSurroundings#414]
*Mod Version:*
3.4.10.3

*Forge Version:*
14.23.5.2768

*Link to crash log (if applicable):*
https://pastebin.com/eY1m9cEw

*Description:*
crash on launch.
idk whats causing it. just saw something about dynamic surroundings so I figured id paste it here
didn't have this issue until I updated to latest version.

**Comment by OreCruncher** [comment]
You have two DS core JARs.  Go into your mods/1.12.2 folder and delete the DS JAR there.  Then try starting again.

**Comment by HentaiHamster** [comment]
That didn't work. I sitll get a crash. Here's the report.
