### ISSUE TITLE
Serene seasoins bug 

### ISSUE THREAD

**Issue by DrakeBD** [OreCruncher/DynamicSurroundings#417]
*Mod Version:*
DynamicSurroundings-1.12.2-3.4.10.4
*Forge Version:*
1.12.2 - 14.23.5.2768

*Link to crash log (if applicable):*
No crash
*Description:*
![2018-12-03_15 20 20](https://user-images.githubusercontent.com/1292832/49383919-c071fa80-f711-11e8-9227-0c729a6160f9.png)
There is no crash here just odd mechanics.
It seem dynamic surroundings is messing with seasons winters and making it so that all Plains type biomes have constant snow laying on the ground even when it is not winter for example in spring it started raining but snow was settling on the ground even though it was not snowing changing the season to winter did change the rain to snow and when changing back to spring snow turned to rain but snow on the ground continued to grow and settle.

**Comment by OreCruncher** [comment]
What version of SS are you using?  I know what you have is relatively current - just getting a fix on it because SS has been changing quite a bit.

If snow is accumulating on the ground it means that SS is making that happen.  The recent builds of SS it is possible for it to snow even though it is not specifically winter.  Snow/ice is tied to temperature now a days and not some sort of biome attribute.  Pinging @Forstride for more insight.

(And to make it more complicated temperature is tied to a specific block position.  In classic vanilla you can see this by going up elevation in extreme hills while raining and it turns to snow.)

**Comment by OreCruncher** [comment]
Hmmm.....[this is where ](https://github.com/OreCruncher/DynamicSurroundings/blob/1.12.2/src/main/java/org/blockartistry/DynSurround/registry/season/SeasonInfo.java#L101)I calculate the temp for the location.  getFloatTemperature() will call BiomeHooks.getFloatTemperature() in a [derived class](https://github.com/OreCruncher/DynamicSurroundings/blob/1.12.2/src/main/java/org/blockartistry/DynSurround/registry/season/SeasonInfoSereneSeasons.java#L97).  Where SS is concerned do I need to do all that heightmap stuff, or does the BiomeHooks take care of it?  (I'm stretching here a bit to figure out what is going on).

**Comment by DrakeBD** [comment]
We are putting together a modpack for our community it's in beta so everytime you guys update we push the mod updates so to answer your question I'm using the current released version of SS the biomes subjected to this bug are any biome with plains in it so sunflower plains are also affected by the summer snow settling when it rains

**Comment by OreCruncher** [comment]
@Forstride I have seen it snow in plains during early spring. :)

**Comment by OreCruncher** [comment]
Other possibility that occurred to me is that it could be a disconnect between the server and client.  DS relies on client side SS information so it *could* be operating off incorrect information.  Not saying this is the issue - just spitballing.

**Comment by DrakeBD** [comment]
I would say it could have been but tested on a server and single player same occurrence but yes not a problem will test again when you push a new update and will let you know if this persists

**Comment by xkforce** [comment]
https://paste.ee/p/XbafL

The latest versions of both Serene Seasons and Dynamic Surroundings crash if they're together.

**Comment by OreCruncher** [comment]
@xkforce You have v3.5.0.2BETA installed.  v3.5.0.3BETA is the latest and should work.

**Comment by DrakeBD** [comment]
> Pushed v.3.5.0.4 to CurseForge. Give it a try and let me know if the problem resolves. If not, enable Dynamic Surroundings debug tracing and take a screenshot. It will have some information in yellow on the left side of the debug HUD that may have some clues.

Well thanks for pushing the new version but now the game wont even load crashes on start here is the logs

[crash-2018-12-04_15.04.01-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/2644565/crash-2018-12-04_15.04.01-client.txt)
[latest.log](https://github.com/OreCruncher/DynamicSurroundings/files/2644567/latest.log)

no other mod has changed appart from Orelib and DynamicSurroundings.

**Comment by OreCruncher** [comment]
Do you have crystal chests by chance?

**Comment by DrakeBD** [comment]
> Do you have crystal chests by chance?
> 
> It's what I thought. I will have a fix posted shortly. Gotta love mod interactions.

Yeah have iron chests mod i figured the log reference that mod but also mentioned dynamic surrounding too and as i changed no other mod other than this one figured it was related so posted here 💃

**Comment by OreCruncher** [comment]
OK. v3.5.0.5 is up.  And I double checked it with iron chests. :)

**Comment by DrakeBD** [comment]
> OK. v3.5.0.5 is up. And I double checked it with iron chests. :)

Ok ill test it now and get back to you

**Comment by DrakeBD** [comment]
@OreCruncher Good news all bugs fixed snow now melts in summer and no crashes on RTP commands

**Comment by OreCruncher** [comment]
Yay!  Thanks for dogging this for me.  Let me know if you see any other weirdness.

**Comment by DrakeBD** [comment]
> Yay! Thanks for dogging this for me. Let me know if you see any other weirdness.

Your most welcome and will do 💃
