### ISSUE TITLE
[1.11] Metallic-ish sound when walking on edge of block

### ISSUE THREAD

**Issue by Kiyaku** [OreCruncher/DynamicSurroundings#42]
*Mod Version:* 3.2.8.1

*Forge Version:* 13.20.0.2252

*Description:*
It seems like when you walk on an edge of a block, the footsteps sound sometimes is the metallic one (could be a different one, is that the default one when no other sound could be found?) 

Here is an example: http://i.imgur.com/JLx1LxV.png

I'm walking along the edge of this grass and once in a while i hear that metallic sound.

Let me know if there is anything more useful i could provide!

Cheers,
SC

**Comment by OreCruncher** [comment]
Need a list of mods as well as the client mod up to the point the world is loaded.

**Comment by Kiyaku** [comment]
Heya,

modlist here: http://pastebin.com/ncrH8kvE
As well as the client log: https://dl.dropboxusercontent.com/u/1658875/Minecraft/fml-client-latest.log 

So i noticed it's not always the metallic sound. The other time it was the sand one (even though i was walking on dirt). 
I can reproduce it 100% of the time by just walking to the edge of a block and jump or walk. 

Cheers,
SC

**Comment by OreCruncher** [comment]
Found it.  The bug has been around since the 1.10.x branch.  Go figure. :)  Fix will be in the next BETA.

**Comment by Kiyaku** [comment]
Awesome, thank you! Looking forward to it :D

**Comment by OreCruncher** [comment]
Pushed v3.3.0.0 BETA to CurseForge.
