### ISSUE TITLE
3.4.10.5 Rendering Errors while using Shaders Mod.

### ISSUE THREAD

**Issue by SirChamomile** [OreCruncher/DynamicSurroundings#420]
*Mod Version:*
DynamicSurroundings-1.12.2-3.4.10.5.jar

*Forge Version:*
Forge-14.23.5.2768

*Link to crash log (if applicable):*

*Description:*
When used with shaders, there is very strange opaque black shadows on most surfaces.

**Comment by OreCruncher** [comment]
Screenshot?  I don't experience those issues.  I also need a list of mods in your pack.  There are mods out there that mess with the lighting routines and can futz things up.

**Comment by SirChamomile** [comment]
This was due to a mod version mismatch on a server.
