### ISSUE TITLE
cannot find class crash

### ISSUE THREAD

**Issue by mightydanp** [OreCruncher/DynamicSurroundings#421]
*Mod Version:*
3.4.10.5
*Forge Version:*
1.12.2-14.23.5.2772

*Link to crash log (if applicable):*
https://pastebin.com/qEWv0piJ
*Description:*
it gives me that crash log after it crashes and also in the launcher before it crashes it tells me it cannot find minecraft.jar

**Comment by OreCruncher** [comment]
Looks like you have 2 DS core mods.  Look in your mods/1.12.2 folder.  Delete any DS core mods and then try again.

**Comment by mightydanp** [comment]
ohhh i feel so stupid right now
