### ISSUE TITLE
Crashes with Vivecraft again

### ISSUE THREAD

**Issue by Novotisy** [OreCruncher/DynamicSurroundings#425]
*Mod Version:*
[latest.log](https://github.com/OreCruncher/DynamicSurroundings/files/2681574/latest.log)

DynamicSurroundings-1.12.2-3.5.2.0BETA.jar
--
*Forge Version:*
Recommended and newest

*Link to crash log (if applicable):*

*Description:*
Crashes with Vivecraft, no other mods except with OreLib

**Comment by OreCruncher** [comment]
Not sure how I am going to fix this as of yet.  Reason is I added additional ASM which requires a recompute of the frames.

**Comment by OreCruncher** [comment]
Can you test out this one-off JAR?
https://github.com/OreCruncher/DynamicSurroundings/releases/tag/v3.5.2.1TEST

**Comment by OreCruncher** [comment]
Pushed v3.5.3.0 with code changes that should address the issue.  Let me know.  Thanks!
