### ISSUE TITLE
[Enhancement] Air Bubbles

### ISSUE THREAD

**Issue by InsomniaKitten** [OreCruncher/DynamicSurroundings#427]
Inspired by the concept that the player does, in fact, breathe (as seen by the visible breath mist in cold areas), it would be cool to see this come into play underwater too, with bubbles rising from the players mouth intermittently as they slowly lose air - with an increased frequency of bubbles when drowning, possibly an extra amount too on the initial drowning tick.

**Latest used version:** [1.12.2-3.5.3.1BETA](https://minecraft.curseforge.com/projects/dynamic-surroundings/files/2649763)

**Comment by OreCruncher** [comment]
Hmmm.....could be modeled just like the frost breath in cold biomes, but have bubbles underwater.

**Comment by OreCruncher** [comment]
Actually it looks like Minecraft has a bubble effect when drowning.  I will take a look at that.  Maybe it needs some help. :)

**Comment by OreCruncher** [comment]
Pushed v3.5.4.0 to CurseForge with the feature.  Give it a looksee and let me know.

The bubbles from the mouth are smaller and dribble up in a thin stream.  When the player runs out of air a burp of bubbles is generated, and the stream of bubbles will stop.  Every second the player will burp large bubbles until they die, or surface to get more air.
