### ISSUE TITLE
Sound scaling not working

### ISSUE THREAD

**Issue by EvertX** [OreCruncher/DynamicSurroundings#430]
*Mod Version:*
3.5.4.0BETA

*Forge Version:*
2784

*Description:*
Raptor sound button in config is mapped to other birds (crows? in the distance). And it seems the raptor sound is not mapped to a volume control at all?

**Comment by OreCruncher** [comment]
Shot in the dark - make a backup copy of your dsurround.cfg, and then delete the one in your instance folder.  The 3.5.x versions of DS may not have converted the cfg file correctly from the prior version.  As for the config entry not mapping to the right sound that is really weird.  This is a first.

(Oh, and post a link to your client log  - there may be something else going on.)

FYI - I am going to be away for the holidays and will not be able to actually look at this until I get back.

**Comment by EvertX** [comment]
I think resetting the config did the trick. I should've tried that before posting I guess. Sorry to have bothered you.
Happy holidays and safe travels.

**Comment by EvertX** [comment]
Reopening since I think the high-pitched raptor sound does not adhere to the set volume. It does in the config screen when pressing 'play', but in-game it is still max volume.

**Comment by EvertX** [comment]
It is all the sounds! I just didn't notice because I only lowered the raptor sounds. But trying to lower the elephant sounds also doesn't work. It seems the individual volumes are not respected. You can test this by enabling the crafting sound and then setting the crafting sound volume to 1 (ore even 0). It is still played at max volume.
Sorry for the confusion, it wasn't apparent to me it was all the sounds since I only noticed it with raptors.

**Comment by OreCruncher** [comment]
@EvertX Did you have DS prior to version 3.5 installed?  If so, did you delete the config file?

**Comment by OreCruncher** [comment]
Pushed v3.5.4.1 with a fix.
