### ISSUE TITLE
[Conflict] Startup sound conflict with RandomTweaks

### ISSUE THREAD

**Issue by DemonfangArun** [OreCruncher/DynamicSurroundings#431]
Dynamic Surroundings: 3.4.10.5
Forge: 2768

The startup sound from this mod cannot be properly disabled (that I know of) and conflicts with other mods trying to play a startup sound. Simply removing the startup sound results in it being reset to default. I had it set to minecraft:potato (which doesn't exist) for the longest time to hackily fix the issue. That has unfortunately stopped working.

I would like to request that a disable option of some kind be added to the configuration.

Edit: TRL in the below referenced thread helped me get it disabled. Perhaps some instructions for how to properly disable it could be added, or the configuration format could be changed to make it a bit more straightforward.

**Comment by OreCruncher** [comment]
@DemonfangArun Took a look at the code and removing the entries from the list should disable the startup sound playing.  If you delete the entire config option from the file it will reset back to default, which is what I think you did.  Don't leave any blank lines in the list.

**Comment by DemonfangArun** [comment]
I didn't delete the whole config option, but I did accidentally leave a blank line in, which triggered the reset. Deleting the whole line that the sound was on, but not the whole config option, solved the issue.

**Comment by OreCruncher** [comment]
Glad to hear.  If you have any other issues let me know.
