### ISSUE TITLE
Log spamming Post Render

### ISSUE THREAD

**Issue by plenet10** [OreCruncher/DynamicSurroundings#433]
*Mod Version:*
3.5.4.0BETA
*Forge Version:*
14.23.5.2796
*Description:*
This is the error that happens if you hover over any configuration items. 
########## GL ERROR ##########
@ Post render
1281: Invalid value

**Comment by OreCruncher** [comment]
What other mods do you have installed?  Reason I ask is because the config system uses built in stuff from forge and Minecraft to do the GUI rendering.

**Comment by OreCruncher** [comment]
@plenet10 I am not able to repro the problem in my dev environment.  I will need a mod list.

**Comment by plenet10** [comment]
Hope this helps dont know what fixed it?
The thing right now is i added a bit more mods and it doesn't happen the mods i use:
  # LibLoader
  [1.12.2]+BetterFarmland-v0.0.8-BETA
  [1.12.2]+RecipeBookNullifier_v0.0.2
  [1.12.2]+VersionChecker-1.4.0
  [1.12]+Fullbright+-+v1.2
  [MC1.12.2]DeconTable-3.0.4
  ActuallyAdditions-1.12.2-r144
  AdditionalEnchantedMiner-1.12.2-0.10.6-universal
  additionalpipes-6.0.0.7
  Advanced+Solar+Panels-4.2.0
  AdvancedRocketry-1.12.2-1.4.1-117-universal
  ae2stuff-0.7.0.4-mc1.12.2
  AE2WTLib-1.12.2-1.0.5
  AppleCore-mc1.12.2-3.1.4
  AppleSkin-mc1.12-1.0.9
  appliedenergistics2-rv6-stable-5
  Aroma1997Core-1.12.2-2.0.0.0.b162
  Aroma1997s-Dimensional-World-1.12-2.0.0.0.b48
  AromaBackup-1.12.2-3.0.0.0.b114
  astralsorcery-1.12.2-1.10.7
  AutoRegLib-1.3-21
  auxiliumequivalence-1.12.2-1.1.1
  Avaritia-1.12.2-3.3.0.28-universal
  backpacks+1.12.2+-+3.5.2
  base-1.12.2-3.11.0
  BasicNetherOres-1.12.2-1.0.3.0
  Baubles-1.12-1.5.2
  baubley-heart-canisters-1.12.2-1.2.1
  bc-extra-pipes-7.99.14-1
  bc-ore-processing-7.99.15-1
  bdlib-1.14.3.12-mc1.12.2
  beebetteratbees-1.12.2-2.0.3
  BetterAdvancements-1.12.2-0.0.14.68
  BetterFps-1.4.8
  binnie-mods-1.12.2-2.5.1.183
  BiomesOPlenty-1.12.2-7.0.1.2422-universal
  BloodArsenal-1.12.2-2.1.0-26
  BloodMagic-1.12.2-2.3.3-101
  bonsaitrees-1.1.1-b138
  Bookshelf-1.12.2-2.3.570
  Botania+r1.10-358
  botaniatweaks-1.7
  BrandonsCore-1.12-2.4.2.157-universal
  buildcraft-all-7.99.20
  burnbabyburn-1.4
  careerbees-0.4.0
  CEU-1.12.2-1.0.1.1
  Chameleon-1.12-4.1.3
  Chargers-1.12.2-1.0.0.1
  Charset-Lib-0.5.5.6
  CharsetPatches-0.1.6
  Charset-StorageTanks-0.5.4.8
  Charset-TransportCartsRails-0.5.5.6
  Charset-Tweaks-0.5.5.6
  ChickenASM-1.12-1.0.2.9
  ChickenChunks-1.12.2-2.4.1.73-universal
  Chunk+Pregenerator+V1.12-1.9
  clearlag-1.0
  ClientTweaks_1.12.2-3.1.11
  CodeChickenLib-1.12.2-3.2.2.353-universal
  CoFHCore-1.12.2-4.6.1.22-universal
  CoFHWorld-1.12.2-1.3.0.6-universal
  CompactSolars-1.12.2-5.0.18.341-universal
  compfac-1.3.1
  conarm-1.12.2-1.2.1
  Config+Checker-1.12.2-1.3
  CraftingTweaks_1.12.2-8.1.9
  culinaryconstruct-1.2.0.1
  Cyclic-1.12.2-1.17.12
  DankNull-1.12-1.4.43
  DeepSeaExpansion-1.12.2-Preview-A2
  deuf-1.1-1.12.2
  dirt2path-1.8.0
  diy-1.12.2-1.1.1
  dooglamoocitiesmod-1.12-1.6.3
  Draconic-Evolution-1.12-2.3.11.290-universal
  DummyCoreUnofficial-2.4.112.4
  Dungeons2-mc1.12.2-f14.23.5.2768-v1.5.0
  Durability Show-1.12-5.0.0
  DynamicLights-1.12.2
  DynamicSurroundings-1.12.2-3.5.4.0BETA
  DynamicSurroundingsHuds-1.12.2-3.5.4.0BETA
  EnderCore-1.12.2-0.5.43
  EnderIO-1.12.2-5.0.39
  EnderStorage-1.12-2.4.0.119-universal
  endertanks-1.12.0-1.6.6
  EndReborn+II+[0.2.5]
  Exchangers-1.12.2-2.8
  extrautils2-1.12-1.9.8
  extreme_cobble_generator-1.12.2-0.2.2.6-SNAPSHOT
  exu2cer-1.12-1.0
  Fancy+Fluid+Storage-1.12-2.1.3
  FastFurnace-1.12.2-1.2.1
  FastLeafDecay-v14
  FastWorkbench-1.12.2-1.6.0
  fencejumper-1.12-1.0.5
  fluxnetworks-1.12.2-3.0.19-21
  foamfix-0.10.3-1.12.2
  forestry_1.12.2-5.8.2.378
  Forgelin-1.8.2
  ForgeMultipart-1.12.2-2.6.0.79-universal
  gendustry-1.6.5.8-mc1.12.2
  gendustryjei-1.0.2
  GottschCore-mc1.12.2-f14.23.5.2768-v1.6.0
  gravestone-1.10.2
  GregicAdditions-1.12.2-1.3.0
  gregtech-1.12.2-1.0.124
  GTCEBees-1.12.2-1.0.2
  Guide-API-1.12-2.1.7-62
  HammerCore-1.12.2-2.0.3.5
  Harvest-1.12-1.2.7-20
  HungerOverhaul-1.12.2-1.3.3.jenkins148
  Hwyla-1.8.26-B41_1.12.2
  IC2CropBreeding+Plugin+V1.12-1.1
  ImmersiveCables-1.12.2-1.3.2
  ImmersiveEngineering-0.12-88
  immersivepetroleum-1.12.2-1.1.9
  industrialcraft-2-2.8.105-ex112
  industrialforegoing-1.12.2-1.12.2-226
  IndustrialWires-1.7-33
  instantunify-1.12.2-1.1.2
  InventoryTweaks-1.64+dev.144
  irontanks-2.1.0-beta-5
  jei_1.12.2-4.14.3.240
  jeibees-0.9.0.5-mc1.12.2
  jeiintegration_1.12.2-1.5.1.36
  jeivillagers-1.12-1.0.2
  JEROreIntegration-1.12.2-1.1.0
  journeymap-1.12.2-5.6.0b2
  JourneyMapFixer-1.12.2-1-SERVER
  justenoughdimensions-1.12.2-1.6.0-dev.20181019.003124
  JustEnoughIDs-1.0.2-26
  JustEnoughResources-1.12.2-0.8.10.50
  LagGoggles-FORGE-1.12.2-4.1
  LargeFluidTank-3.7
  LibVulpes-1.12.2-0.3.0-45-universal
  Login_Shield-1.12.2-3-g7c6e7ac
  longfallboots-1.2.1a
  Lord+Craft+2.9.5
  MagicBees-1.12-3.1.7
  Mantle-1.12-1.3.3.39
  mcjtylib-1.12-3.0.7
  MCMultiPart-2.5.3
  MetalChests-v3.9.0.g9b0c79e
  minecolonies-1.12.2-0.10.87-BETA-universal
  MiscTweaks-1.12-1.3.0
  ModularPowersuits-1.12.2-0.7.0.25
  modular-routers-1.12.2-3.2.1
  moreavaritia-mc1.12.2-2.4
  morebees-1.12.2-2.0.1
  moreoverlays-1.14-mc1.12.2
  morepaintings-paintings-1.12.2-4.0.0.1
  MouseTweaks-2.9-mc1.12.2
  mtqfix-1.12.2-1.1.0
  NetherPortalFix_1.12.1-5.3.13
  NHCore-1.12-4.0.3
  nmclc-1.12-MC1.12.2-1.2.0-b67-universal
  NoFog-1.12.2b3
  NoMoreRecipeConflict-0.12(1.12.2)
  notenoughwands-1.12-1.7.1
  Novam+Terram+1.12.2+-+6.1
  OreLib-1.12.2-3.5.1.3BETA
  p455w0rdslib-1.12.2-2.0.36
  Pam's+HarvestCraft+1.12.2zb
  Pam's+Simply+Strawberries+1.12.2+-+1.0.0
  pamsimpleharvest-2.0.0
  Pewter-1.4.1
  Placebo-1.12.2-1.5.0
  plustic-6.5.4.2
  PowerAdapters-1.12.2-1.0.11
  ProjectE-1.12-PE1.3.2h
  projecteplus-1.0.0a
  quantumflux-1.12.2-2.0.16
  QuantumStorage-1.12-4.6.4
  railcraft-12.0.0-beta-2
  randomconfigs-1.12.2-1.2.0.2
  randompatches-1.12.2-1.11.0.1
  randomtweaks-1.12.2-2.4.0.2
  RebornCore-1.12.2-3.12.1.385-universal
  RedstoneFlux-1.12-2.1.0.6-universal
  redstonic-2.0
  refinedexchange-2.0.0
  refinedstorage-1.6.12
  refinedstorageaddons-0.4.3
  RetroBees-1.12.2-1.0.4
  sampler-1.80
  SeasonalBees-[1.12]--1.0
  serversync-2.6.17
  ServerTabInfo-1.12.2-1.2.3
  shetiphiancore-1.12.0-3.5.8
  SimplyJetpacks2-1.12.2-2.2.10.63
  Singularities-1.12.2-2.3.1
  smarthoppers-mc1.12.2-4.1.5
  Snad-1.12.1-1.7.09.16a
  sonarcore-1.12.2-5.0.19-20
  StevesCarts-1.12.2-2.4.27.127
  StorageDrawers-1.12.2-5.3.8
  taiga-1.12.2-1.3.4
  tcexpansion-0.0.2
  TConstruct-1.12.2-2.11.0.106
  tesla-core-lib-1.12.2-1.0.15
  Thaumcraft-1.12.2-6.1.BETA26hotfix1
  thaumcraftresearchloader-1.0
  Thaumic+Arcana-0.6.0
  ThaumicAdditions-1.12.2-10r
  thaumicbases-3.2.270.4r
  ThaumicInventoryScanning_1.12.2-2.0.10
  ThaumicJEI-1.12.2-1.5.4-22
  thaumictinkerer-1.12.2-5.0-353c71c
  TheOneWrench-1.12.2-2.1.2
  ThermalDynamics-1.12.2-2.5.3.16-universal
  ThermalExpansion-1.12.2-5.5.2.39-universal
  ThermalFoundation-1.12.2-2.6.1.22-universal
  TickDynamic-1.12.2-1.0.1
  TickProfiler-1.12-0.0.7
  TidyChunk-1.12.2-1.0.0.0
  tinker_io-1.12.2-rw2.7.1
  TinkersComplement-1.12.2-0.2.3b
  TinkersExtras-1.12.2-1.0.5
  tinyprogressions-1.12.2-3.3.29-Release
  Toast+Control-1.12.2-1.7.1
  torcherino-7.5
  torchmaster_1.12.2-1.6.4.62
  Translocators-1.12.2-2.5.1.77-universal
  u_team_core-1.12.2-2.0.2.87
  UniDict-1.12.2-2.9.1
  WailaHarvestability-mc1.12-1.1.11
  WaitingTime-1.0.0
  WanionLib-1.12.2-2.2
  Wawla-1.12.2-2.5.265
  WirelessCraftingTerminal-1.12.2-3.11.86
  WR-CBE-1.12.2-2.3.1.30-universal

**Comment by OreCruncher** [comment]
This type of error is hard to find.  When drawing graphics there are a bunch of OpenGL settings that can be made.  These settings do things like lighting, blending, etc.  If a mod leaves does not properly clean up it's state it could cause problems for another mod.

In this particular case the rendering is done by Minecraft/Forge code, not by DS.  It could be that one of the new mods resets the state properly so when the tooltip is rendered there is no error.  Were any mods updated?

**Comment by plenet10** [comment]
Yes but i haven't noticed that it was to do with graphical stufs but it could very much be. Thanks for explaining that i hope i will narrow it down some day.
