### ISSUE TITLE
Latest Roguelike Adventures Dungeons Mod Pack error issue

### ISSUE THREAD

**Issue by DreadPirateKate** [OreCruncher/DynamicSurroundings#440]
*Mod Version:* R.A.D. 1.21

*Forge Version:* 14.23.5.2768

*Link to crash log (if applicable):* https://paste.dimdev.org/ipowerazir.mccrash

*Description:* Just tried to log in to my personal MC server, and got a crash that I can't seem to work around. It provided mod name in the error and the link I pasted above.

**Comment by Autistic-Guitar** [comment]
Mod Version: DynamicSurroundings-1.12.2-3.4.10.5

Forge Version: forge-1.12.2-14.23.5.2768

Crash Link: https://pastebin.com/FTvAfAxL

Hey @DreadPirateKate  . Getting the same issue over here playing Roguelike Adventures and Dungeons pack. Thought it was a clash with Optifine and shaders, but removed optifine and still getting the same issue.

Game is crashing whenever loading into a world and the screen is unpaused or out of menu. If game is opened while tabbed etc., the game doesn't crash until I close the menu

**Comment by OreCruncher** [comment]
Try out the 3.5.4.3 release version I just posted to CurseForge.
