### ISSUE TITLE
NoClassDefFoundError - org.blockartistry.DynSurround.client.ClientRegistry

### ISSUE THREAD

**Issue by SSKirillSS** [OreCruncher/DynamicSurroundings#441]
*Mod Version:* DynamicSurroundings-1.12.2-3.4.10.5

*Forge Version:* forge-1.12.2-14.23.4.2750

*Link to crash log (if applicable):* https://pastebin.com/sVAzVysB

*Description:* Unfortunately, I can not say anything about this. I do not have such an error, but other players have it.

**Comment by Autistic-Guitar** [comment]
_Mod Version:_ DynamicSurroundings-1.12.2-3.4.10.5

_Forge Version:_ forge-1.12.2-14.23.5.2768

_Crash Link:_ https://pastebin.com/FTvAfAxL

Hey @SSKirillSS . Getting the same issue over here playing Roguelike Adventures and Dungeons pack. Thought it was a clash with Optifine and shaders, but removed optifine and still getting the same issue. 

Game is crashing whenever loading into a world and the screen is unpaused or out of menu. If game is opened while tabbed etc., the game doesn't crash until I close the menu

**Comment by OreCruncher** [comment]
This is related to Open Terrain Generator.  There is a fix in the 3.5.4.3 version I just posted to CurseForge.
