### ISSUE TITLE
Can't disable footstep sounds in 3.5.x.x?

### ISSUE THREAD

**Issue by ItsTheKais** [OreCruncher/DynamicSurroundings#445]
I am unable to find a setting to turn off footstep sounds after updating from 3.4.10.6 to 3.5.4.3. Blocking DS's footsteps under individual sound config results in no footstep sounds at all, so apparently it's impossible to use default footsteps with newer DS releases?

* Dynamic Surroundings 3.5.4.3
* OreLib 3.5.2.2
* Forge 14.23.5.2796
* Minecraft 1.12.2

**Comment by DemonfangArun** [comment]
This moved to the volume options menu, along with biome sounds.

**Comment by ItsTheKais** [comment]
I can only find two settings related to footsteps on that screen; whether footsteps match the first-person or third-person animation, and whether to use quadrupedal footsteps, neither of which disable the footsteps entirely.

A ctrl+F in the config file only turns up these two settings, which suggests to me that this setting slipped through the cracks during the 3.5 rewrite.

**Comment by OreCruncher** [comment]
Under Effect Options.  There is a "Footprint Style" and "Entity Footprints".

**Comment by ItsTheKais** [comment]
Those settings seem to only control the footprint particles. No amount of fiddling with them is bringing back the vanilla footstep sounds. (which came as a relief to me, because tying the sounds to the presence of a particle would be very very silly!)

**Comment by OreCruncher** [comment]
If you want to disable the DS footstep sounds set the Footstep Sound Slider in Minecraft's Volume control to 0.

**Comment by ItsTheKais** [comment]
That worked. Didn't realize DS changes the vanilla volume screen now. Thank you for the help.
