### ISSUE TITLE
Missing stuff?!

### ISSUE THREAD

**Issue by DemonfangArun** [OreCruncher/DynamicSurroundings#446]
*Mod Version:*
3.5.4.3
*Forge Version:*
2800

*Link to crash log (if applicable):*
n/a
*Description:*
The options for light level overlay and chunk borders seem to have disappeared, along with the volume controls. There may be other stuff missing, but that's what I've run into sofar.

**Comment by DemonfangArun** [comment]
Nevermind, found the thing that says it's a new mod now. You should consider putting that into the changelogs so people aren't wondering what's going on, along with all the other stuff that's changed.

**Comment by OreCruncher** [comment]
Need to read the changelog - it really isn't that long.  A more complete list is in process.

**Comment by DemonfangArun** [comment]
"
Requirements

    Forge 2768+
    OreLib-1.12.2-3.5.2.1+
    If upgrading from version 3.4.x or earlier:
        Delete your dsurround.cfg and let it regenerate
        Check your mods/1.12.2 folder and ensure there are no Dynamic Surroundings files within
Fixes
    Fix block state matching RE: BoP overgrown blocks
"

I read the changelog, this change wasn't in there anywhere.

**Comment by DemonfangArun** [comment]
I did not see that anywhere. If that is contained within something that is supposed to show up ingame it didn't. Apart from ingame notices, I only read curseforge changelogs, as most modpack creators do not go through GitHub changelogs as it takes too long when you have 250+ mods.

**Comment by OreCruncher** [comment]
Believe me I understand.  While having 2 different versions for 1.12.2 a lot of limitations of CurseForge popped out.  Big one was indicating the dependency on OreLib. :\  It would be nice if it had a better changelog mechanism - like providing hyperlink rather than copy/paste.

**Comment by OreCruncher** [comment]
I updated the online docs with the update info and provided a link in the change log on CurseForge.
