### ISSUE TITLE
Disabling sounds entirely doesn't work

### ISSUE THREAD

**Issue by SextupleTap** [OreCruncher/DynamicSurroundings#447]
*Mod Version:*
DynamicSurroundings-1.12.2-3.4.10.6
*Forge Version:*
1.12.2-forge1.12.2-14.23.5.2768

*Description:*
Disabling noises by ticking the "block" box to where it shows a red x does not work, and setting sounds to 0 also doesn't work. For example I find the cave insect crawl sound (dsurround:insectcrawl) to be very annoying, this also goes the same for other sounds like MC sounds or sounds from a mod like Ambient Sounds.

I would rather not have to go into the jar file(s) itself and change out the .ogg files to empty .ogg files just so the sounds I don't like don't play. Yet as of now I am probably going to resort to that.

**Comment by cosmicdan** [comment]
Restart the client when you change the settings? Works fine for me.

**Comment by SextupleTap** [comment]
I'll try going from 3.4 to the 3.5 editions (3.5.4.2) and I'll get back to you with the results :)

**Comment by SextupleTap** [comment]
~Update I still hear some sounds that are set to 0 or 2 and are also blocked at the same time~

Here is my config (I have 11 sounds blocked and several more set to 0/2 and or less than 100):
https://paste.dimdev.org/ayimuheqam.coffeescript

Client Log Paste:
https://paste.dimdev.org/utimuyiyex.makefile

Also side question... What does "culling" a sound do, the "Cull" setting?

**Comment by cosmicdan** [comment]
Cull will stop them from spamming so much (e.g. good for a cow farm).

Are you running the latest version? I reduced volume and blocked villager sound in individual sound setting, and restated my whole client, and I can't hear them anymore. But you need to save and quit first. If you force close with X or Crash then it won't save the config.

On 30 Jan 2019, SextupleTap <notifications@github.com> wrote:
>~Update I still hear some sounds that are set to 0 or 2 and are also
>blocked at the same time~
>
>Here is my config (I have 11 sounds blocked and several more set to 0/2
>and or less than 100):
>https://paste.dimdev.org/ayimuheqam.coffeescript
>
>Client Log Paste:
>https://paste.dimdev.org/utimuyiyex.makefile
>
>Also side question... What does "culling" a sound do, the "Cull"
>setting?

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by SextupleTap** [comment]
The game was restarted multiple times, the configs were successfully saved since in the paste of the config I provided you can see which sounds had "block" on them and which sounds were reduced to volumes lower than 100. I was running DynamicSurroundings-1.12.2-3.5.4.3.jar which is the latest so thus I did wipe my config, the config I sent was the one I re created for the new config system.

So yes, it is still messed up for me, I would imagine at this point it's mod incompatibility.

**Comment by cosmicdan** [comment]
Are any sounds blocking at all? For example vanilla ones? If not then yeah, but be something else that's taken over the audio engine or something. Try removing all the other sound related mods you have and see what happens. If nothing, process of elimination time - remove every other mod and add them back (a few at a time) to narrow down the suspect into smaller and smaller groups.

On 31 Jan 2019, SextupleTap <notifications@github.com> wrote:

The game was restarted multiple times, the configs were successfully saved since in the paste of the config I provided you can see which sounds had "block" on them and which sounds were reduced to volumes lower than 100. I was running DynamicSurroundings-1.12.2-3.5.4.3.jar which is the latest so thus I did wipe my config, the config I sent was the one I re created for the new config system.

So yes, it is still messed up for me, I would imagine at this point it's mod incompatibility.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread. 


-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by OreCruncher** [comment]
Nothing stands out in the client log provided.  Is this pack available on CurseForge?

**Comment by SextupleTap** [comment]
It is a custom pack that I am making for personal use on a server called Wynncraft.

The mod list goes as followed:

1. BetterFoliage-MC1.12-2.2.0
2. Controlling-3.0.6
3. CustomBackgrounds-MC1.12-1.1.1
4. customnausea-1.12.2-1.0
5. FancyBlockParticles-1.12.x-2.4.1
6. Forgelin-1.8.2 (Better Foliage Library)
7. FpsReducer-mc1.12.2-1.10.3
8. infotooltip-1.12.2-1.0
9. ItemLocks-1.0
10. journeymap-1.12.2-5.5.3
11. Mantle-1.12-1.3.3.39 (Library for mods like TConstruct but I also use it for the overlapping hearts feature)
12. nomoreglowingpots-1.1
13. nopotionshift_1.12.2-1.2.0
14. noRecipeBook_v1.2.2formc1.12.2
15. OptiFine_1.12.2_HD_U_E2
16. OreLib-1.12.2-3.5.2.2 (Your library for 3.5 editions of Dynamic Surroundings - Obviously)
17. ProportionalDestructionParticles-1.12.2-1.2.4 (Used along side of Fancy Block Particles)
18. rebindnarrator-1.0
19. ResourceLoader-MC1.12.1-1.5.3
20. SmoothFont-mc1.12.2-1.16.1
21. The 5zig Mod v3.12.5 for Minecraft 1.12.2
22. Wynntils-0.1.9_21 (This is an experimental mod)
23. AmbientSounds_v2.3_mc1.12.2
24. customfov-1.12.2-1.0
25. NoNVFlash-1.12.2-1.2.0.3-universal
26. Placebo-1.12.2-1.5.0 (Library mod for Toast Control)
27. Tips-1.12.2-1.0.2 (Misc mod)
28. Toast+Control-1.12.2-1.7.1
29. Better-hud-1.3.9-1.12
30. SmoothWater-0.1.4
31. AutoRegLib-1.3-24 (Library mod for Quark)
32. Quark-r1.5-137 (Used only for its client side, aesthetic features such as greener grass)
33. cic-1.12.2-1.0 (Custom Cursor Icon in game)
34. foamfix-0.10.3-1.12.2 (Unstable FPS Booster)
35. VanillaFix-1.0.10-99 (Unstable FPS Booster and _"Crash Prevention"_)
36. Blur-1.0.4-14 (Blurs the background when a GUI is open)

If any of these mods do also effect ASM / the sound engine in some way then I am completely unaware of the effect/feature.

**Comment by njtxus** [comment]
i have the same problem. i went in and deleted the actual sound files. only thing i could get to work.

**Comment by ChloeDawn** [comment]
I am able to reproduce this with `Forge 1.16.4-35.1.36` and `Dynamic Surroundings 1.16.4-4.0.3.3` - marking sounds as `block` does not silence them. The easiest way to test is to block village sounds and then use `/locate village` to find an area to teleport to.

**Possibly related to https://github.com/OreCruncher/DynamicSurroundings/issues/643?**

Configuration file used in testing:
```toml
#General options for defining sound effects
["Sound Options"]
	#Enable sound reverb and filtering
	"Enable Enhanced Sounds" = true
	#Enable sound occlusion calculations (sound muffling when positioned behind blocks)
	"Enable Sound Occlusion Calculations" = true
	#Enable conversion of stereo sounds to mono format for spacial play
	"Enable Stereo to Mono Conversion" = true
	#Enable enhanced sounds for weather effects
	"Enable Enhanced Weather Sounds" = true
	#Options to configure sounds on an individual basis
	"Individual Sound Config" = [
		"dsurround:bird block",
		"dsurround:bison block",
		"dsurround:bullfrog block",
		"dsurround:coyote block",
		"dsurround:crocodile block",
		"dsurround:crow block",
		"dsurround:elephant block",
		"dsurround:frog block",
		"dsurround:heartbeat block",
		"dsurround:loon block",
		"dsurround:monstergrowl block",
		"dsurround:nightingale block",
		"dsurround:owl block",
		"dsurround:primates block",
		"dsurround:raptor block",
		"dsurround:rattlesnake block",
		"dsurround:seagulls block",
		"dsurround:tummy block",
		"dsurround:village.anvil block",
		"dsurround:village.dogbark block",
		"dsurround:village.rooster block",
		"dsurround:woodpecker block",
		"minecraft:entity.chicken.ambient cull",
		"minecraft:entity.cow.ambient cull",
		"minecraft:entity.dragon.death cull 10",
		"minecraft:entity.dragon.spawn cull 10",
		"minecraft:entity.llama.ambient cull",
		"minecraft:entity.pig.ambient cull",
		"minecraft:entity.sheep.ambient cull",
		"minecraft:entity.wither.death cull 10",
		"minecraft:entity.wither.spawn cull 10"
	]
	#Possible sounds to play when client reaches main game menu
	"Startup Sound List" = []
	#Ticks between culled sound events (0 to disable culling)
	#Range: > 0
	"Sound Culling Interval" = 20
	#Number of background threads to handle sound effect calculations (0 is default)
	#Range: 0 ~ 8
	"Background Workers" = 1

#Defines parameters for special effects
["Effect Options"]
	#Replace client side Randomizers with faster versions
	"Replace Randoms" = true
	#Block range of entity special effect handling
	#Range: 16 ~ 64
	"Block Range" = 24

#Defines how Sound Control logging will behave
["Logging Options"]
	#Enables/disables debug logging of the mod
	"Debug Logging" = false
	#Bitmask for toggling various debug traces
	#Range: > 0
	"Debug Flag Mask" = 0
```

**Comment by OreCruncher** [comment]
@ChloeDawn Did you manually copy/paste from a 1.12.2 DS config?  Reason I ask is that instead of "dsurround" as a sound prefix you need to be using "environs".

**Comment by ChloeDawn** [comment]
Oh, is there new documentation for this? I got my info from https://github.com/OreCruncher/DynamicSurroundings/wiki/Sounds-in-the-Mod and the new/unlisted sound ids from https://github.com/OreCruncher/DynamicSurroundings/blob/01707e27dd800509409c9830e7709aaac6cdc0de/src/main/resources/assets/dsurround/sounds.json

**Comment by OreCruncher** [comment]
Different repo: https://github.com/OreCruncher/DynamicSurroundings2/blob/master/src/main/resources/assets/environs/sounds.json

EDIT:  You can also access an in game menu for manipulating these settings by hitting CTRL+s.

**Comment by ChloeDawn** [comment]
Oh! Thank you
