### ISSUE TITLE
DS and Abyssalcraft sound issue

### ISSUE THREAD

**Issue by MineyShadow** [OreCruncher/DynamicSurroundings#448]
*Mod Version:* 1.12.2/3.5.4.3

*Forge Version:* 1.12.2 - 14.23.5.2808

*Link to crash log (if applicable):* N/A

*Description:* No other mods installed, With both abyssalcraft and dynamic surroundings present, There is a sound issue where the nether ambient sound plays constantly in every biome/dimension.

**Comment by sadface-0** [comment]
I'm also having the same issue.

**Comment by daPoseidonGuy** [comment]
Another person with the same issue. Anyone found a solution?

**Comment by GrumpyPirate** [comment]
Same here - the Nether biome sound plays everywhere. The workaround I'm using in the meantime is to simply disable `dsurround:dimension.nether` in the individual sound config menu.

**Comment by mvlabat** [comment]
@GrumpyPirate But that's disables the only sound we can hear, right? :)

**Comment by GrumpyPirate** [comment]
Yeah, it just disables the 'bugged' sound effect. It's a shame, because by doing so it removes some of the atmosphere of going to the Nether, but I'd take that over constantly hearing it everywhere!

**Comment by GrumpyPirate** [comment]
@jtgibson01 Fantastic. Thanks for digging into this one!

**Comment by OreCruncher** [comment]
BTW, I am fixing for the next maintenance update.  Bet you guys thought I died or something.

**Comment by mvlabat** [comment]
@OreCruncher, we're glad you're back! :) I hope everything is alright

**Comment by OreCruncher** [comment]
I'm doing pretty good.  Just was a rough start to the year, though the year is almost over. :)

**Comment by OreCruncher** [comment]
Pushed DynamicSurroundings-1.12.2-3.5.5.0 to CurseForge.
