### ISSUE TITLE
Water issues

### ISSUE THREAD

**Issue by DemonfangArun** [OreCruncher/DynamicSurroundings#452]
Forge 2800
Dsurround: 3.5.4.3

There seem to be some issues with how water is being handled in certain circumstances. Here's a link to information provided by someone that knows more than I do: https://github.com/Angry-Pixel/The-Betweenlands/issues/785

**Comment by DemonfangArun** [comment]
Bump

**Comment by OreCruncher** [comment]
Yeah.  I think this is a bug I am fixing for the next update.  I will mark fixed.

**Comment by OreCruncher** [comment]
Pushed DynamicSurroundings-1.12.2-3.5.5.0 to CurseForge.
