### ISSUE TITLE
Crash with upcoming mod Arcane Archives

### ISSUE THREAD

**Issue by Dragnier** [OreCruncher/DynamicSurroundings#453]
*Mod Version:* 3.5.4.3

*Forge Version:* 14.23.5.2811

*Link to crash log (if applicable):* https://paste.dimdev.org/kezofafilu.mccrash

*Description:* Error when loading. Never gets to the main screen.

**Comment by OreCruncher** [comment]
Have you reported to the mod author as well?

**Comment by Dragnier** [comment]
Looked like it was on your end based on the crash log, but I'm far from an expert. Added to their issue tracker as well.

**Comment by duely** [comment]
@OreCruncher This is definitely an issue on our end that may have been fixed in the alpha-preview6 release made a day or two ago. Please feel free to close the issue.
