### ISSUE TITLE
Cubic Chunks Support

### ISSUE THREAD

**Issue by Xorbah** [OreCruncher/DynamicSurroundings#455]
When going above or below a certain range, Dynamic Surroundings and Ore library both cause the client to crash. Any way to possibly fix this? If I have to choose between the two i'll pick this but it'd be pretty awesome to have infinite depth in my world alongside this.

**Comment by BrisingrAerowing** [comment]
A crash log would be helpful.

**Comment by OreCruncher** [comment]
Yes, please attach a crash log.
