### ISSUE TITLE
[Sugestion] mod sound support/user add-on

### ISSUE THREAD

**Issue by OutcastZeroOne** [OreCruncher/DynamicSurroundings#457]
no real issue with the mod.

Possibility of adding sounds for immersive engineering, or an addon library for mods. Possibly an ability for users to add a sub-folder in the config files or mod folder to add sounds for a mod?

**Comment by OreCruncher** [comment]
https://dynamicsurroundings.readthedocs.io/en/master/tutorials/resource_packs.html
