### ISSUE TITLE
[1.12.2] No Nether Ambient Audio

### ISSUE THREAD

**Issue by TechnoMysterio** [OreCruncher/DynamicSurroundings#458]
When going to the Nether, the background ambient loop I heard in earlier versions does not play. I've seen this on servers and in singleplayer, and I only noticed it in more recent versions.

Perhaps it doesn't play it because the Nether is not open to the sky, and therefore you are considered to be indoors?

DS: 3.5.4.3
Forge: 14.23.5.2815
MC: 1.12.2

**Comment by OreCruncher** [comment]
I've noticed this off and on as well.  The strange thing is that it only happens with the Nether ambient.  Haven't noticed it with anything else.  The only condition for the sound to play is if the player's dimension is the Nether - nothing complicated like indoors or biome.

**Comment by OreCruncher** [comment]
I haven't been able to repro with a release I am working on in my sandbox.  I did some changes fixing other things and it may have addressed this as well.  Going to mark fixed.

**Comment by OreCruncher** [comment]
Pushed v3.6.0.0 to CurseForge.
