### ISSUE TITLE
Crash related to "ticking Particle" (ENTITY_PARTICLE_TEXTURE)

### ISSUE THREAD

**Issue by Null-151** [OreCruncher/DynamicSurroundings#459]
*Mod Version:*3.5.4.3

*Forge Version:*14.23.5.2815

*Link to crash log (if applicable):*https://paste.dimdev.org/fegaralocu.mccrash

*Description:* I cannot say much appart from that the only thing I was doing was walking in a ravine placing torches in a creative world. Have a good day

**Comment by Null-151** [comment]
The same crash happened again in a new world, this time only a few seconds after starting it. I begin to suspect that this has something to do with CubicChunks, since I didn't had any problems like this before installing it
https://paste.dimdev.org/vizojoxecu.mccrash

**Comment by TimTinkers** [comment]
I'm also encountering this same crash. @Null-151 were you able to work around it at all?

**Comment by Null-151** [comment]
@TimTinkers No luck, its a compatibility problem with Cubic Chunks.

**Comment by TimTinkers** [comment]
@Null-151 I was able to avoid this crash by modifying the Dynamic Surroundings configuration file such that "Enable Client Chunk Caching" was set to false, like so.
```
    B:"Enable Client Chunk Caching"=false
```

**Comment by Xorbah** [comment]
Can confirm this works and was actually looking for this as I have just gotten a fresh install of Minecraft + Forge and was trying to find the workaround for D-surround and CC again. Cheers. Might as well close this issue.
