### ISSUE TITLE
Lingering icons after feeding animals

### ISSUE THREAD

**Issue by darthvader45** [OreCruncher/DynamicSurroundings#460]
*Mod Version:* 3.5.4.3

*Forge Version:* 14.23.5.2815

*Description:*  Water bucket and other animal food/water icons don't go away after the animal has fed/been given water.

**Comment by OreCruncher** [comment]
I am going to be posting an update that makes use of the latest version of Animania.  It has a cleaner API and has a good chance at resolving.  (I was not able to repro myself.)

**Comment by OreCruncher** [comment]
Pushed DynamicSurroundings-1.12.2-3.5.5.0 to CurseForge.
