### ISSUE TITLE
Aurora texture

### ISSUE THREAD

**Issue by Akiraca** [OreCruncher/DynamicSurroundings#462]
*Mod Version:*3.5.4.3

*Forge Version:*1.12.2-14.23.5.2768

*Optifine Version:*1.12.2_HD_U_E2

*Shader Pack:*Continuum-1.3-Low-Ultra

*Description:*Aurora texture failed when using shaders.

![2019-03-27_20 13 56](https://user-images.githubusercontent.com/23720781/55064304-d8f58e80-50cd-11e9-89b1-5f2ea4d969d7.png)
![2019-03-27_20 14 05](https://user-images.githubusercontent.com/23720781/55064307-d8f58e80-50cd-11e9-8681-2ef0b1c6d8d1.png)

**Comment by OreCruncher** [comment]
Yep. https://dynamicsurroundings.readthedocs.io/en/master/features/aurora.html at the bottom.
