### ISSUE TITLE
[Feature] Update to Forge 1.13.2 or 1.14.0 when it releases

### ISSUE THREAD

**Issue by Tsoccerguy3** [OreCruncher/DynamicSurroundings#464]
*Mod Version:*
Preview

*Forge Version:*
Forge for 1.13.2 

*Description:*
This mod is a essential extension of Minecraft , much appreciated if you were going to maintain into 1.13.2 or 1.14.0 and beyond . I only mention the 1.14 because the Minecraft 1.14 pre2 is out and expecting final very soon . thank you

**Comment by miiichael** [comment]
...or 1.15, I guess. :sweat_smile:

Though given the sudden drop off in github activity since February, I fear DynamicSurroundings is not long for this world...

**Comment by OreCruncher** [comment]
Actually its called Real Life. :)  There are versions for 1.14.2 already.  Split into 3 mods: Sound Control, Mob Effects, and Environs.
