### ISSUE TITLE
Dynamic Surroundings crashes with OpenJ9

### ISSUE THREAD

**Issue by Dimentive** [OreCruncher/DynamicSurroundings#466]
I switched from Hotspot (the default JVM) to the OpenJ9 JVM as [this guide on r/FeedTheBeast](https://www.reddit.com/r/feedthebeast/comments/as6p87/java_vms_and_you_how_to_reduce_your_ram_and_cpu/) suggested for better performance, and Dynamic Surroundings crashed my game when I loaded my world.

Crash report: https://pastebin.com/raw/pTc0TrcC

#### Versions

* **Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version [1.65a](https://minecraft.curseforge.com/projects/enigmatica2/files/2700051)), with some mods added
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2781
* **OreLib:** [3.5.2.2](https://minecraft.curseforge.com/projects/orelib/files/2664386) (latest)
* **Dynamic Surroundings:** [3.5.4.3](https://minecraft.curseforge.com/projects/dynamic-surroundings/files/2664392) (latest)

**Comment by OreCruncher** [comment]
Not compatible with Java versions > 1.8
