### ISSUE TITLE
[1.7.10]No rain sound when using weather2 (v2.3.9+)

### ISSUE THREAD

**Issue by Josh74000** [OreCruncher/DynamicSurroundings#468]
Dynamic Surroundings 1.0.6.4

Forge 1614

When using weather2, features like weather fog, morning fog and others work, but the only way to see rain is using weather2's custom rain particles as the rain doesn't show unless if overcast mode is on, that is when rain can be seen, and the rain sound also plays, but when its off, it doesn't have the rain sound playing and rain particles disappear, but the rain splash is seen, I'm using weather2 v2.3.9 too.

Screenshot to show that I had to use the custom rain particles from weather2 as the rain from dsurround isn't working, also the rain sound, but rain splash isn't affected:
![2019-04-29_21 19 15](https://user-images.githubusercontent.com/32041132/56926097-ca353980-6ac8-11e9-979a-6b2ddfbd5c98.png)

**Comment by Josh74000** [comment]
I installed dsurround to make it look more foggy when a storm from weather2 happens, I had to turn off the rain effect in the config as rain isn't working, so it'll be using vanilla's rain instead.

**Comment by OreCruncher** [comment]
Dupe #371
