### ISSUE TITLE
Client crash in BubbleJetEffect

### ISSUE THREAD

**Issue by MatthiasMann** [OreCruncher/DynamicSurroundings#469]
Mod Version: DynamicSurroundings-1.12.2-3.5.4.3
Forge Version: forge-1.12.2-14.23.5.2824

Link to crash log (if applicable): 
[crash-2019-05-01_13.24.11-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/3134389/crash-2019-05-01_13.24.11-client.txt)

Description:
I have a world made with Streams-1.12-0.4.4 which I updated to Streams-1.12-0.4.5 which resulted in reports of missing blocks from the streams mod (not sure if that is related).
Then I went exploring and found a flower fields biomes (BOP?) which had what looked like an river bed without water in it - and once my mouse cursor come over the river bed the client crashed.
So I assume that the river bed was not in fact empty bad had remains? of the stream and dsurroundings was trying to render the water particle effects?

**Comment by MatthiasMann** [comment]
After looking at the code I assume that https://github.com/OreCruncher/DynamicSurroundings/blob/602d27cde783233fd23f27355086c74d335d734a/src/main/java/org/orecruncher/dsurround/client/fx/BubbleJetEffect.java#L63 returned 0.

**Comment by SirAron111** [comment]
https://pastebin.com/ having the same problem here i think

**Comment by OreCruncher** [comment]
Pushed DynamicSurroundings-1.12.2-3.5.5.0 to CurseForge.
