### ISSUE TITLE
Certain Hostile mobs no longer trigger the battle music

### ISSUE THREAD

**Issue by Ghostrider231** [OreCruncher/DynamicSurroundings#471]
Mod Version: 1.12.2-3.5.4.3 (latest)
Orelib version: 1.12.2-3.5.2.2 (latest)

Forge Version: 14.23.5.2835

Description:

Hello, I don't know if 1.12.2 is being looked at anymore, but i'm going to post this anyways.

I can't help but notice, combat music doesn't play at the appropriate time regardless of the conditions matching. (Fighting Hostile mob. check, Not Invisible. check, Battle music works correctly itself. check, Let the hostile mob hit me once, check.)

Here's a list of Hostile mobs that do NOT trigger the battle music (even though they should):
---
Electroblob's Evil Wizards **(Their summons can trigger the battle music [which is intentional, but most of them], but NOT themselves)**
Most of Erebus' Mobs **(Most notable but not limited to: Centipedes, Antlions, bombardier beetle larvaes, and etc.)**
Slimes **(Vanilla mob, this also affects any modded mobs that extend to this entity)**
Skeleton Druids from Twilight Forest
Mother Spider Family from Primitive mobs
Skeleton Warriors from Primitive mobs
Wither Skeletons **(Vanilla mob, this also affects EB Wizardry's Summon too)**
Blazes **(Vanilla mob, this also affects EB Wizardry's Summon too)**
**(There could be more that I didn't test yet)**

All of the mobs that I've listed here used to be able to trigger the battle music like in 3.4.9.14. And yes, all of them extend to EntityMob or something similar [AKA IMob or EntityMonster]. **(Checked Wizardry's evil wizard source code and checked Erebus' Mobs source code for proof)**

**Comment by OreCruncher** [comment]
This would be weird. One of the checks is if the object implements IMob.

**Comment by OreCruncher** [comment]
I reworked how attacks/flees are detected in the AI code in order to support Open J9.  As a side effect this may be addressed.

**Comment by OreCruncher** [comment]
Pushed v3.6.0.0 to CurseForge.
