### ISSUE TITLE
[Suggestion] magma/netherrack rain options

### ISSUE THREAD

**Issue by rayblon** [OreCruncher/DynamicSurroundings#472]
Hopefully I'm not just blind, but I couldn't find any options to change the behavior of magma or netherrack when rain hits it. This wouldn't be a big deal usually, but in netherrack and magma filled builds, you hear constant lava pops and have fire flying everywhere, which is a bit obnoxious. 

I know that there's some way to use external config files, but after digging through the files it looks to be a bit above my pay grade.

**Comment by OreCruncher** [comment]
I am assuming you are referring to the Overworld particle effects on these blocks.  Right now there isn't a way to turn this off in configuration.  I would need some code to do this.

**Comment by OreCruncher** [comment]
Pushed v3.6.0.0 to CurseForge.
