### ISSUE TITLE
[Suggestion] 1.12.2 Config option for list of sounds volume and disabling

### ISSUE THREAD

**Issue by DWX12** [OreCruncher/DynamicSurroundings#473]
One of the other sound mods I use, Ambient Sounds 3, has a config file that allows the volume of each individual sound to be changed or muted. Would like to see the same or similar options for Dynamic Surroundings.

I may want to use this mod for certain sounds like crafting, armor, etc., but have other mods for other environmental sounds. Or people may just want to disable bird screeching or specific animal sounds in certain biomes.

This would be a nice feature to see in a future version.

Thanks so much and keep up the great work.

**Comment by Zygus42** [comment]
In line with this suggestion, I have had people on my server complaining about the snake noises in deserts and the elephant sounds in savannas when there are no such animals around ( and we do have those animals added by other mods, so they could be), but it seems the only option is to turn odd the entire biome-specific sound system, which is sad.

**Comment by Zygus42** [comment]
Strange thing is, that even with this turned off:
    # Enable biome background and spot sounds [default: true]
    B:"Enable Biomes Sounds"=false

You still get the desert and savanna animal sounds.

**Comment by OreCruncher** [comment]
I'm a bit confused.  Dynamic Surrounds has a rather large configuration section for tuning individual sounds.  Using the mod options GUI navigate to Dynamic Surroundings.  The first button at the top should be "Individual Sound Configurations".  Let me know if you are not seeing it.

As for the animal sounds those are ambient sounds, not biome.  Biome sounds are the sounds that play like a sound track (wind in mounts, general bird chirps and leaf rustle in forest, crickets at night in plains, etc.)

As for snakes and elephants, yes, those sounds are in the mod.  If they don't want those sounds they can turn off in "Individual Sound Configurations".

**Comment by Zygus42** [comment]
Only ever tried to adjust settings in the config.  Didn't try the ingame config, as I figured it would have the same options.  We ended up taking this off, because our players hated the snake sounds.  Will do a test on it at some point and look at the ingame config.

**Comment by OreCruncher** [comment]
FYI - the next update (3.6.0.0) will have some of the sounds players find annoying disabled as a default.  Snake is one.  I will mark this issue as fix because of that.

**Comment by OreCruncher** [comment]
Pushed v3.6.0.0 to CurseForge.
