### ISSUE TITLE
Feedback on a particular jungle bird sound

### ISSUE THREAD

**Issue by katubug** [OreCruncher/DynamicSurroundings#475]
*Mod Version:*
DynamicSurroundings-1.12.2-3.5.4.3

*Forge Version:*
forge-1.12.2-14.23.5.2838-universal

*Link to crash log (if applicable):*
n/a

*Description:*
There's a particular bird in the jungles (bird-ambience-jungle-night2) that kind of sounds like a truck backing up. It's very repetitive and gets maddening after a while. I have personally muted it, which is fine, but I thought you might want to know in case it's something you wanted to tone down. Thank you for the amazing mod though!

**Comment by OreCruncher** [comment]
Its been a bit since you opened this.  I don't have a sound with that name.  Are you sure the sound is from Dynamic Surroundings?  I do have bird sounds, and most do not play at night.  The only one that does is the loon, and that doesn't trigger in jungle.

**Comment by katubug** [comment]
Ah, sorry about that. I'm relatively certain that that'll be from Ambient Sounds 3. At the time I made this report, I didn't realize that Dynamic Surroundings allowed you to alter sounds from other mods, so I mistakenly assumed that it was from your mod instead. I'll go ahead and close this issue. Thank you for responding!
