### ISSUE TITLE
[Bug/Issue] Ringing in Wind At High Altitudes

### ISSUE THREAD

**Issue by RageYT** [OreCruncher/DynamicSurroundings#477]
### **Mod Version:**
3.5.4.3
### **Forge Version:**
14.23.5.2838

---
### **Description**
The high pitch wind sound, in issue #28 still occurs as I get high in altitude. It is very disturbing and hurts my ears plenty.

**Comment by OreCruncher** [comment]
The next update will have an updated Wind sound courtesy of TechnoMysterio.

**Comment by OreCruncher** [comment]
Pushed v3.6.0.0 to CurseForge.
