### ISSUE TITLE
[Bug/Issue] Nether ambient sounds playing in all non-vanilla biomes/dimensions.

### ISSUE THREAD

**Issue by Raithion** [OreCruncher/DynamicSurroundings#478]
**Mod Version:**

3.5.4.3

**Forge Version:**

14.23.5.2836

**Description:**
With AbyssalCraft (version 1.9.8) installed, the sound "dsurround:dimension.nether" plays in every non-vanilla biome. This includes *all* biomes from Biomes O'Plenty, as well as biomes from other dimensions. Aether II, Twilight Forest, Tropicraft, The Beneath, and The Betweenlands are all affected.

Vanilla biomes are unaffected by this issue, and play their intended ambient sounds. Upon *uninstalling* AbyssalCraft, the issue is fixed and all mod-added biomes and dimensions play their intended ambient sounds again.

I also found that disabling "dsurround:dimension.nether" in the mod options DOES in fact fix the nether's sound from playing... but it also results in all those biomes being dead silent with no ambience at all.

My guess would be this is some kind of integration issue. Regardless, it's incredibly annoying hearing this howling sound everywhere I go, and I hope a fix is able to be found. Others are having the same issue on the CurseForge mod page.

**Comment by mvlabat** [comment]
One more report:
https://github.com/OreCruncher/DynamicSurroundings/issues/448

**Comment by OreCruncher** [comment]
It is a bug in the config file I think.  It's a regression from when I refactored the internal expression engine.

**Comment by OreCruncher** [comment]
Pushed 1.12.2-v3.5.5.0 to CurseForge.
