### ISSUE TITLE
[Bug/Issue] I hear foot steps from mobs right in my head.

### ISSUE THREAD

**Issue by SadGuyWithEmptyList** [OreCruncher/DynamicSurroundings#479]
*Mod Version:*
3.5.4.3
*Forge Version:*
14.23.5.2838 
*Link to crash log (if applicable):*

*Description:*
So i know why it's happening, but i don't know how to fix it my self.
The thing is that i had 2 mods for good sound phyx: sound physics, sound filters. and both of those cause this bug when i hear every mob/player like it's me making those sounds.
So is there a switch to toggle off mobs/other_players foot steps? like leave them default.

**Comment by OreCruncher** [comment]
As a rule I don't support Sound Physics.  Does too many strange things with sound volume.  As for Sound Filters I have not experienced what you describe.  What version are you using?

**Comment by OreCruncher** [comment]
@SadGuyWithEmptyList I received a pull request for changes in support of sound physics.  When that build is published I will mark this as closed and you can try it out.

**Comment by OreCruncher** [comment]
Pushed v3.6.0.0 to CurseForge.  Let me know if it addresses.
