### ISSUE TITLE
[1.12.2] crash when sun is in view

### ISSUE THREAD

**Issue by HEAAAG** [OreCruncher/DynamicSurroundings#480]
*Mod Version:* 3.5.4.3

*Forge Version:* 14.23.5.2768

*Link to crash log (if applicable):* 
[crash-2019-06-14_20.43.47-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/3291837/crash-2019-06-14_20.43.47-client.txt)

*Description:* When playing in a homemade kitchen-sink pack, game would crash at what seemed to be random intervals.
Later found out it was crashing because the sun was in view.
This quickly degraded to the point of crashing whenever the in-game sun was anywhere on screen (even when walls, roof, or ground was obscuring it).  
Hope this helps.

**Comment by OreCruncher** [comment]
This isn't a Dynamic Surroundings issue.  It is an issue with the Regeneration mod.  Looking at the callstack there is something on a Bibliocraft armor stand that Regeneration does not like.
