### ISSUE TITLE
Game Crashes when creating Dimension with SimpleDimensions while DynamicSurroundings installed

### ISSUE THREAD

**Issue by JohnJack3001** [OreCruncher/DynamicSurroundings#481]
*Mod Version:* 3.5.4.3

*Forge Version:* 14.23.5.2838

*Link to crash log (if applicable):* https://paste.dimdev.org/tehagavahe.mccrash

*Description:*
Whenever I use the command to create a new dimension using the SimpleDimensions mod, the game crashes and mentions dynamic surroundings in the crash report. If I remove the dynamic surroundings jar from my mods folder the game doesn't crash.

**Comment by OreCruncher** [comment]
After looking at this there is a bug in SimpleDimensions.  There WorldCustom implementation overrides the init() method, and does not fire the event necessary to attach world capabilities.  Dynamic Surroundings makes use of world capabilities.

**Comment by OreCruncher** [comment]
Update issue in the SimpleDimension repo and closing this one.
