### ISSUE TITLE
Effects like breathing in the cold and burning in lava still happen in Spectator mode

### ISSUE THREAD

**Issue by aaronhowser1** [OreCruncher/DynamicSurroundings#482]
*Mod Version:*
DynamicSurroundings-1.12.2-3.5.4.3
*Forge Version:*
14.23.5.2836

*Description:*
When I fly around in spectator mode, I still get particle effects like frosty breath and fire particles, which messes up the screenshots I'm trying to take. I feel like this shouldn't happen in Spectator mode, because you aren't really supposed to exist then.

**Comment by OreCruncher** [comment]
Which fire particles?

**Comment by aaronhowser1** [comment]
I made this issue a long time ago, and honestly I can't remember what the fire particles were.

If you're fixing the breathing though, can you also stop bubbles from coming from your mouth in spectator mode?

**Comment by OreCruncher** [comment]
Yep, the same fix will get both.  Also not doing footprint sounds because spectator is flight and flying through things like sugar cane would make noise.

**Comment by OreCruncher** [comment]
Pushed DynamicSurroundings-1.12.2-3.5.5.0 to CurseForge.
