### ISSUE TITLE
[1.12.2] Crash when fire jet effect is applied to non-liquid block

### ISSUE THREAD

**Issue by ItsTheKais** [OreCruncher/DynamicSurroundings#486]
*Mod Version:* 3.5.4.3

*Forge Version:* 14.23.5.2838

*Link to crash log (if applicable):* https://pastebin.com/uLgqqu0e

*Description:* The effect seems to expect that any given block has a "level" blockstate and crashes if it doesn't.

**Comment by OreCruncher** [comment]
Yeah.  The jet effect applies to liquid blocks not solid.  I am going to put a block in to prevent the effect on solids for now.  I am considering allowing it for solids because that would be pretty cool.  Would need some rework.

**Comment by OreCruncher** [comment]
Pushed DynamicSurroundings-1.12.2-3.5.5.0 to CurseForge.
