### ISSUE TITLE
[Suggestion] Global volume option

### ISSUE THREAD

**Issue by Crowfooted** [OreCruncher/DynamicSurroundings#487]
Right now the volume for all Dynamic Surroundings sounds is a lot higher than all other Minecraft sounds on my game and without going in and reducing the volume of every individual DSurround sound, it's deafening. Please could we have a global volume control for all sounds from the mod?

**Comment by OreCruncher** [comment]
Which version of DS?  There should be a global volume control option under Minecraft's sound option page.
