### ISSUE TITLE
[Suggestion] Aurora Biome Config

### ISSUE THREAD

**Issue by Nohicom** [OreCruncher/DynamicSurroundings#488]
*Mod Version:*
1.12.2-3.5.4.3

*Forge Version:*
14.23.5.2838

*Link to crash log (if applicable):*
N/A

*Description:*
Is there a way you could add a config option for which biomes produce an aurora? They look beautiful, but they're only in a couple biomes. I know there's an option to enable auroras in all biomes, but that doesn't quite make sense. Essentially what I'm thinking of is a list where you can manually add/remove biomes for Auroras, without enabling the all-biome option.

**Comment by OreCruncher** [comment]
There is a mechanism already.  It requires the creation of a configuration file.  Here is a simple one that turns on the effects for all biomes: https://dynamicsurroundings.readthedocs.io/en/master/howdoi.html#aurorasallbiomes
