### ISSUE TITLE
Client crash when walking on a server (server does not crash)

### ISSUE THREAD

**Issue by stormbringerGT** [OreCruncher/DynamicSurroundings#490]
*Mod Version:*
DynamicSurroundings-1.12.2-3.5.4.3.jar

*Forge Version:*
forge-1.12.2-14.23.5.2838-universal

*Link to crash log (if applicable):*
https://pastebin.com/7WrkQG2p

*Description:*
Client crash when walking on a server. Crash report attached.

**Comment by OreCruncher** [comment]
I cannot duplicate.  I will make a speculative fix meaning that I will make a change based on what I suspect the issue might be.

**Comment by OreCruncher** [comment]
Pushed DynamicSurroundings-1.12.2-3.5.5.0 to CurseForge.
