### ISSUE TITLE
Crash: Game crashes when I try to click the in game config button for volume!

### ISSUE THREAD

**Issue by SirAron111** [OreCruncher/DynamicSurroundings#491]
*Mod Version:*
DynamicSurroundings-1.12.2-3.5.4.3.jar

*Forge Version:*
14.23.5.2838 

*Link to crash log (if applicable):*
https://pastebin.com/e4ABiSRJ
https://pastebin.com/hA7YsL0b

*Description:*
Game crashes when I try to click the in game config button for volume!

**Comment by OreCruncher** [comment]
Can you try with pre 2837?  Reason is in 2837 Forge changed one of the routine my ASM stuff uses and it may have broke me.

**Comment by SirAron111** [comment]
Was already fixed by a new forge and the other incompat mod.

**Comment by OreCruncher** [comment]
Cool!  Thanks for letting me know.  It wasn't making too much sense otherwise.
