### ISSUE TITLE
Crash when starting new world with Serene Seasons

### ISSUE THREAD

**Issue by stormbringerGT** [OreCruncher/DynamicSurroundings#494]
*Mod Version:*
1.12.2-3.5.4.3
*Forge Version:*
14.23.5.2846

*Link to crash log (if applicable):*
https://paste.dimdev.org/jigazuquke.mccrash
*Description:*
Game crashes when starting new world

https://github.com/Glitchfiend/SereneSeasons/issues/171

**Comment by Boymann** [comment]
I have this same issue.

**Comment by jtx46** [comment]
Same issue, but i found a work around. SereneSeasons seems to be the issue and/or DS hasnt been updated to account for any changes in SereneSeasons.

Solution : Use SereneSeasons Version 1.2.16, it worked for me at least.
https://www.curseforge.com/minecraft/mc-mods/serene-seasons/files/2710586

**Comment by Crabby-Gamer** [comment]
Same issue here
https://paste.dimdev.org/rusiqulomi.mccrash

**Comment by OreCruncher** [comment]
Hey all!  Apparently this was an issue with Serene Seasons.  Make sure you update to the last.  If you have further problem feel free to open an new incident.  Thanks!
