### ISSUE TITLE
Disable water fall sound

### ISSUE THREAD

**Issue by ExDomino** [OreCruncher/DynamicSurroundings#496]
Hello, I'm just wondering how to disable water fall sound please.
It's a bit annoying when mining clay underwater, for example.
I searched into config but I didn't found anything.

**Comment by OreCruncher** [comment]
Can you tell me what it is doing?  There is a bug with waterfalls that I am fixing where they don't go away when they should.  It could be this.

**Comment by ExDomino** [comment]
Just a way to disable this sound could be fine until you find out how to fix that bug please.

**Comment by OreCruncher** [comment]
I hope to have the fix posted in a day or so.  Otherwise the easiest way is to block the waterfall sounds.  Go to the mod configuration page under "Individual Sound Configurations" and select BLOCK for the sounds you want to block.

**Comment by OreCruncher** [comment]
Pushed DynamicSurroundings-1.12.2-3.5.5.0 to CurseForge.  Can you check this out and see if it addresses your annoyance?

**Comment by ExDomino** [comment]
What is the setting name for the water fall sound?

**Comment by OreCruncher** [comment]
As indicated I pushed a maintenance release to CurseForge this AM.  I am wondering if the fix addresses the concern you had with the waterfall sound.

The sounds you are looking for are "dsurround:waterfall.0" through "dsurround.waterfall.5".  Use the "Individual Sound Configurations" option and select BLOCK for each of these sounds.  It will turn off the waterfall sounds.

**Comment by ExDomino** [comment]
The only "waterfall" in the config is at line 131 and is already at 0:
`# Waterfall strength below which sounds will not play [range: 0 ~ 10, default: 0]
I:"Waterfall Cutoff"=0`

**Comment by OreCruncher** [comment]
@ExDomino You can set that config value to 10.

**Comment by OreCruncher** [comment]
Pushed v3.6.0.2 with fix.

**Comment by ExDomino** [comment]
There is still no way to disable this sound ?
I don't want to be obligated to fix all water bug in the game to prevent this loud sound to be played near of my base.
Please, give us a way to disable it !

**Comment by OreCruncher** [comment]
Read above.  Edit your config and set "Waterfall Cutoff" to 10.
