### ISSUE TITLE
Aurora won't disable 

### ISSUE THREAD

**Issue by KrawlingKaos** [OreCruncher/DynamicSurroundings#497]
*Mod Version:*
DynamicSurroundings-1.12.2-3.5.4.3.jar
*Forge Version:*
forge-14.23.5.2838.jar

*Link to crash log (if applicable):*

*Description:*
I've started a brand new server and edited the dsurround config file to turn off the aurora. I've set it to false.

aurora {
    # Enable/disable Aurora processing on server/client [default: true]
    B:Enabled=false

    # Use shader when rendering aurora [default: true]
    B:"Use Shaders"=true
}

No matter what I do, it won't turn it off. What am I doing wrong?

**Comment by OreCruncher** [comment]
Are you trying to edit on the server?  If so, this is a client side option.  If a player wants to disable they will need to modify the config on their end.

**Comment by KrawlingKaos** [comment]
> Are you trying to edit on the server? If so, this is a client side option. If a player wants to disable they will need to modify the config on their end.

I edited it on the server config in hopes it would effect the setting for everyone who joins. 
The aurora looks terrible with our shaders and not all of the people who join our server are savvy with editing configs on their computers. 

Thanks for the heads up.

**Comment by OreCruncher** [comment]
The config option is available through the in-game config editor.  If I recall all options are available through that menu.  Mod Options -> Dynamic Surroundings -> Config.
