### ISSUE TITLE
Game Crash With Another Mod

### ISSUE THREAD

**Issue by kenijey** [OreCruncher/DynamicSurroundings#50]
i am also using Tree Chopper mod, and it crashed when i cut down a tree.
[crash-2017-03-12_17.06.09-server.txt](https://github.com/OreCruncher/DynamicSurroundings/files/836559/crash-2017-03-12_17.06.09-server.txt)

**Comment by OreCruncher** [comment]
@kenijey On the surface this does not appear to be a Dynamic Surroundings issue.  I do not see any of my mods code in that call stack.  Have you reported to @DuchLord?

**Comment by kenijey** [comment]
no i didn't, i will do it right now.
by the way, it didn't happen again. i don't know should i report this thing to the developers...

**Comment by OreCruncher** [comment]
@kenijey Going to close this as a not a problem with Dynamic Surroundings.  Not sure when TreeChopper will be updated - does not look to have a lot of activity.  I will be more than willing to help figure the issue out if indeed it is a conflict.
