### ISSUE TITLE
Speech Bubbles were black with orange text before. Now they're white/gray?

### ISSUE THREAD

**Issue by Noxalas** [OreCruncher/DynamicSurroundings#502]
*Mod Version:*
3.5.5.0

*Forge Version:*
14.23.5.2847

*Description:*
Using the latest versions of Forge and DS with a lot of other mods. Has to be some kind of incompatibility with another mods rendering(?), but I'm not sure what's causing the issue. Works fine when DS is launched by itself.

**Comment by OreCruncher** [comment]
The 3.5.4.3 version didn't do this?  I don't recall changing anything rendering related.  You update any other mods at the same time?  Also, you using a shader pack?  Those are notorious for these types of things.

**Comment by Noxalas** [comment]
Well, there's probably no need to worry. I didn't use Optifine or anything, but apparently just restarting my computer fixed the issue!
