### ISSUE TITLE
server crashes when a player leaves the game

### ISSUE THREAD

**Issue by EgorLead** [OreCruncher/DynamicSurroundings#505]
*Mod Version:*
DynamicSurroundings-core-1.12.2-3.5.4.3
*Forge Version:*
14.23.5.2838

*Link to crash log (if applicable):*
https://drive.google.com/file/d/1t4jwBp4aT9Cg4RbRyrT4dAHCZd0Vz-EF/view?usp=sharing
*Description:*
I would be grateful if you help to deal with the problem :)

**Comment by OreCruncher** [comment]
Does it always happen, or sporadically?

**Comment by EgorLead** [comment]
> Does it always happen, or sporadically?

It always happens.



> EDIT: Also can you post a link to your server log? May need to zip it.

[2019-10-13_22.48.46-log.zip](https://github.com/OreCruncher/DynamicSurroundings/files/3723652/2019-10-13_22.48.46-log.zip)

> EDIT2: And was this a logoff or disconnect? Routine in question is due to disconnect and I need to confirm.

disconnect

**Comment by OreCruncher** [comment]
Has this server ever worked, or is it something you are working on?  There are other errors in the log from plugins reporting errors accessing fields and that looks suspicious.  One thing I saw was information related to OptiFine.  Traditionally that would not be installed on a server.  Not sure if that changed recently, but if you have that on the server I would remove that first and see what happens.

**Comment by EgorLead** [comment]
> 
> 
> Has this server ever worked, or is it something you are working on? There are other errors in the log from plugins reporting errors accessing fields and that looks suspicious. One thing I saw was information related to OptiFine. Traditionally that would not be installed on a server. Not sure if that changed recently, but if you have that on the server I would remove that first and see what happens.

I deleted all the plugins and mods which  don`t create a config file. But now I have a lot more errors and crash when disconnecting remained :(
[2019-10-14-1.log.zip](https://github.com/OreCruncher/DynamicSurroundings/files/3724903/2019-10-14-1.log.zip)

**Comment by EgorLead** [comment]
> Has this server ever worked, or is it something you are working on?

The server worked before installing the mod. After the first use, I realized that this mod is the best of its kind and should work on my server

**Comment by OreCruncher** [comment]
This is an interesting issue.  I am going to make some changes - not entirely sure its going to fix this issue.  Also, not sure if you are aware - you can disable the mod on the server, and the client will still be able to make use of it.  There are something you will not get (like speech bubbles) but all the sounds and effects will happen.

I am not sure when a build will be available for you to try.  I have some testing I need to complete before I publish.

**Comment by EgorLead** [comment]
@OreCruncher , In any case, thank you so much for your help in this problem. I hope in future versions you fix it. Good luck with your work :)

**Comment by OreCruncher** [comment]
Pushed v3.6.0.0 to CurseForge.  Let me know if it fixes the issue.  If it doesn't please reopen the issue.

**Comment by VyaCHACHsel** [comment]
i think it did...
