### ISSUE TITLE
Dynamic Surroundings Update 3.5.5.0 Doesn't Work

### ISSUE THREAD

**Issue by TexanWarrior33** [OreCruncher/DynamicSurroundings#506]
*Mod Version:*
v2.71   14.23.5.2838

*Forge Version:*
1.12.2

*Link to crash log (if applicable):*
It doesn't crash it just says I don't have the correct version.

*Description:*
Couldn't use dynamic surroundings 3.5.5.0 without it saying you must include the right dependencies for Dynamic Surroundings and it also says its only compatible with Serene Seasons 1.2.18 or above. I only have 1.2.16 it says.

**Comment by OreCruncher** [comment]
Right.  Update to 1.2.18 of serene seasons.

**Comment by TexanWarrior33** [comment]
how

**Comment by OreCruncher** [comment]
https://www.curseforge.com/minecraft/mc-mods/serene-seasons

**Comment by TexanWarrior33** [comment]
It worked thank you so much!

**Comment by OreCruncher** [comment]
Cool. :)
