### ISSUE TITLE
no way to disable the update notification?

### ISSUE THREAD

**Issue by Shivaxi** [OreCruncher/DynamicSurroundings#508]
I might be a dumb dumb here but i scoured the config file and I cannot find any way to disable the in game update notification when there's a new update available.  Same with OreLib.

**Comment by OreCruncher** [comment]
Dynamic Surroundings and DS: Huds have this in the config:

    # Enables/disables display of version check information [default: true]
    B:"Enable Online Version Check"=true

OreLib currently does not.  This will be going in for the next update.

**Comment by Shivaxi** [comment]
I am pepega haha, i went through searching "update" and "notification" haha, my bad.  Thanks!
