### ISSUE TITLE
Weather intensity and auroras not rendering when Stellar Sky is installed

### ISSUE THREAD

**Issue by OtterofDeath** [OreCruncher/DynamicSurroundings#51]
*Mod Version: 1.10.2 - 3.3.2.0*

*Forge Version: 12.18.3.2239*

Short version: Weather intensity, sandstorms, and auroras don't work with Stellar Sky installed. They work fine when only Stellar API is installed.

Long version: I noticed this while testing a modpack and thought at first that auroras and sandstorms were uncommon and the variation in weather intensity weren't noticeable. Looked at the wiki and found out that I could use /ds status aurora to see if I should be seeing one. Made a new profile with just Dynamic Surroundings tested everything, added Stellar Sky and they stopped working. Tested again with just Stellar API and everything worked fine.

**Comment by OreCruncher** [comment]
@OtterofDeath Can you post a link to your client log after you have loaded your world?

**Comment by OreCruncher** [comment]
@OtterofDeath @Abastro It looks like Dynamic Surroundings hooks the weather renderer correctly during world load.  It appears that when Stellar Sky replaces the world provider my hook gets stomped.  Continuing to dig.

**Comment by OreCruncher** [comment]
@OtterofDeath Check out the latest version of StellarSky (v0.5.5.1.9).  Abastro made a fix.  Please close this issue out once you had a chance to verify.  Thanks!

**Comment by OtterofDeath** [comment]
Looks like it is working perfectly. Thanks @OreCruncher and @Abastro

![2017-03-25_13 34 46](https://cloud.githubusercontent.com/assets/26151796/24324655/d83c1a6c-1160-11e7-9b92-7ac63bee2a2a.png)
