### ISSUE TITLE
weather effects bug

### ISSUE THREAD

**Issue by FStrean** [OreCruncher/DynamicSurroundings#511]
**Mod Version:**
3.5.5.0
**Forge Version:**
14.23.5.2847

**Link to latest log:**
https://drive.google.com/open?id=1wkuR2P3qnKmc37EE3Z4s42rq6RWD6POY

**Link to dsurround.cfg:**
https://drive.google.com/open?id=1c6jWzBB8vMOMsBKioQgFjtVpXi2Jyolw

Link to Youtube video that shows the problem:
https://www.youtube.com/watch?v=CpZ2tiQT1CE

**Comment by OreCruncher** [comment]
OK - I think I know the what, but not the why.  It looks like something is interfering with my rain splash routine.  This routine gets patched in with ASM, so another mod could be stomping on it.  The 3.6.0.0 release (posting tomorrow sometime) changes how all this works.  I would like you to try the update when it is available to see if it still occurs.

**Comment by FStrean** [comment]
Ok, i have tried a new version of the mod, and problem is gone. Thank you for helping me!

**Comment by OreCruncher** [comment]
Nice!  Thanks for letting me know.
