### ISSUE TITLE
Can’t load the game with new version of Dyn surround! (yes I use the right orelib version.)

### ISSUE THREAD

**Issue by SirAron111** [OreCruncher/DynamicSurroundings#512]
**Mod Version:**
DynamicSurroundings-1.12.2-3.6.0.0.jar
OreLib-1.12.2-3.6.0.0.jar

**Forge Version:**
Forge 1.12.2  - 14.23.5.2847 

The actual Forge version - "latest" does not count.

**Link to client log:**

https://paste.dimdev.org/uhegosomav.rb

**Link to crash log:**

https://paste.dimdev.org/ibopivusuk.mccrash

**Description:**

Well nothing much to say it simply crashes on game startup.

Description of the problem.  In the case of crashes, it is good to know things like the following:

* Did you just add the mod to a pack? -- No. It’s been in my modpack for some time now but I did as stated in the change log delete the old config for the mod and the lib.

* Did it just start crashing, or has it always crashed? -- Just this update It started (updated mod via twitch launcher but no duplicate or older versions remain in the mods folder)

* Did you update any other mods in your pack and it started crashing?  This includes Forge. (NO)

* If updating multiple mods did you update one by one or all at once?  To help narrow the problem down adding one by one is helpful. (Only orelib and dyn surround)

* Is the modpack you are using available online somewhere?  If the crash is due to mod interaction having the pack available makes things much easier.  It is much harder to work these types of issues with a private kitchen sink pack containing 250 mods.
"Modpack: Dimension Zero"

**Comment by OreCruncher** [comment]
Yep.  Mod is creating a fake world during post init, and it fired before my event handler.  Need to think on the best way to fix.

**Comment by OreCruncher** [comment]
Try this one and let me know if it works.  https://github.com/OreCruncher/DynamicSurroundings/releases/tag/3.6.0.1

**Comment by OreCruncher** [comment]
Fixed with v3.6.0.1

**Comment by SirAron111** [comment]
Seems to work now.
