### ISSUE TITLE
Auroras can be seen through blocks and entities

### ISSUE THREAD

**Issue by tappaja666** [OreCruncher/DynamicSurroundings#513]
Mod Version: 3.6.0.1
Forge Version: 14.23.5.2847

Video: https://streamable.com/wz9at

Description: Auroras can be seen through blocks and entities when holding a gun from flansmod while having betweenlands installed. This doesn't happen if betweenlands isn't installed.

Mods needed to reproduce:
- Dynamic surroundings and orelib
- Flansmod
- Betweenlands

**Comment by OreCruncher** [comment]
Did this happen with v3.5.5.0?

**Comment by tappaja666** [comment]
yes it did

**Comment by OreCruncher** [comment]
I can't duplicate the problem with the latest from CurseForge/Flans.  The aurora renders correctly.  Can you list the versions of the mods you are running?

**Comment by tappaja666** [comment]
Forge 1.12.2-14.23.5.2847

DynamicSurroundings-1.12.2-3.6.0.1
Flan's Mod-1.12.2-5.5.2
OreLib-1.12.2-3.6.0.1
TheBetweenlands-3.4.13-universal

Only happens when holding a weapon in first person

**Comment by OreCruncher** [comment]
OK - let me try that.  I didn't have anything in my hand.  Does it happen when holding a mincraft item, or only a flans one?

**Comment by OreCruncher** [comment]
Still trying to understand this one.  My render world last handler renders the aurora before the hand held item.  I need to check into Flans code to see what they are doing.

**Comment by tappaja666** [comment]
This probably an issue with the betweenlands as changing B:dimension_shader_only=false to true or disabling shaders completely from the betweenlands config fixes this issue it just disables the portal animation in the overworld

**Comment by OreCruncher** [comment]
I changed the priority of the render handler to happen *before* BLs shader handling and I side stepped the issue.

**Comment by OreCruncher** [comment]
Pushed v3.6.0.2 with fix.
