### ISSUE TITLE
[BUG] Game does no launch after pressing "Play" from the launcher every time with no exception since the installation of the mod

### ISSUE THREAD

**Issue by TheMasterMM** [OreCruncher/DynamicSurroundings#519]
**Mod Version:** Tried some, but currently is 3.6.0.1

The version that is installed in your pack.

**Forge Version:** Not sure

The actual Forge version - "latest" does not count.

**Link to client log:**
https://pastebin.com/aEjthVtB

Even of there is a crash log, the client log can provide the necessary context for why the exception occured.  You can use a service like [pastebin](https://pastebin.com) or [hastebin](https://hastebin.com) to upload the log, and paste the link here.  The log file is called latest.txt and can be found in your logs folder.

**Link to crash log:**
https://pastebin.com/bNhrkfwZ
I believe this is it

The callstacks in the log will help pinpoint the actors involved in the crash and give a developer a pointer in the code where to start looking at the problem.  You can use a service like [pastebin](https://pastebin.com) or [hastebin](https://hastebin.com) to upload the log, and paste the link here.

**Description:**
To be honest I got a lot of mods and everything was working fine, though with dynamic trees installed the game would not launch. I also installed OreLib and the DynamicTrees HUD

Description of the problem.  In the case of crashes, it is good to know things like the following:

* Did you just add the mod to a pack? I am using over 20 mods
* Did it just start crashing, or has it always crashed? Since the installation, every time
* Did you update any other mods in your pack and it started crashing?  This includes Forge. No
* Is the modpack you are using available online somewhere?  If the crash is due to mod interaction having the pack available makes things much easier.  It is much harder to work these types of issues with a private kitchen sink pack containing 250 mods. It is not available online, I'll send a picture:

![Captura de pantalla (1)](https://user-images.githubusercontent.com/57868910/69010142-25325f00-093b-11ea-953f-793ae25de25c.png)

**Comment by TheMasterMM** [comment]
Btw, i also got the shaders chocapic, seuss and KUDA installed

**Comment by OreCruncher** [comment]
Two things:
1. Update your Forge version to at least 2779.
2. Should update DS to 3.6.0.2 - has some additional tweaks related to startup in case of dependency failure.

**Comment by TheMasterMM** [comment]
thanks for answering so fast! though I did what you said and it still crashed at launch, same as before

Here is the crash log
https://pastebin.com/KiDghmyH

**Comment by OreCruncher** [comment]
Update Forge.  The log says 1.12.2-forge1.12.2-14.23.5.2768.  You need at least 2779.

**Comment by TheMasterMM** [comment]
I missed to update my client to the last version after installing forge (?
That was the problem, Thank you!
