### ISSUE TITLE
Not resetting rain will also not reset the time.

### ISSUE THREAD

**Issue by Ash70** [OreCruncher/DynamicSurroundings#52]
*Mod Version: 3.3.2.0 (but it also happened in older versions)

*Forge Version: 12.18.3.2254 (here also, it happened in older versions)

*Description: I have set the "reset rain on sleep" to false (I love the sound of rain). Now whenever it rains at night and I sleep, the time will not reset (it remains night). It also happens in creative using the /time set day command.

**Comment by OreCruncher** [comment]
@Ash70 Do you have a mod list?

**Comment by Ash70** [comment]
Yep:

animania-1.10-1.0.2.jar
AppleCore-mc1.10.2-2.1.2.jar
AppleSkin-mc1.10.2-1.0.5.jar
ArchitectureCraft-1.7.1-mc1.10.2.jar
Aroma1997Core-1.9.4-1.1.1.1.jar
AromaBackup-1.9.4-1.0.1.1.jar
AutoRegLib-1.0-2.jar
Baubles-1.10.2-1.3.9.jar
BetterFoliage-MC1.10.2-2.1.3.jar.disabled
BetterFps-1.3.2.jar
BiomesOPlenty-1.10.2-5.0.0.2162-universal.jar
Chameleon-1.10-2.2.2.jar
Chisel-MC1.10.2-0.0.8.12.jar
chiselsandbits-12.12.jar
compatlayer-1.10-0.2.2.jar
CookingForBlockheads_1.10.2-4.2.39.jar
Craftable_Waypoints_1.3.1_Forge_1.10.2.jar
CraftTweaker-1.10.2-3.0.24.jar
Cyclic-1.10.2-1.10.15.jar
davincisvessels-1.10.2-0006-full.jar
dendrology-1.10.2-L1.0.2.jar
DynamicSurroundings-1.10.2-3.3.2.0.jar
Farseek-1.9.4-2.1.jar
foamfix-0.6.1-anarchy.jar
GraveStone Mod 1.5.12.jar
ImmersiveEngineering-0.10-57.jar
IronBackpacks-1.10.2-2.2.23.jar
IvToolkit-1.3.2.1-1.10.jar
jei_1.10.2-3.14.7.416.jar
koresample-1.10.2-L1.1.jar
magneticraft-1.0.2-release.jar
malisiscore-1.10.2-4.4.0.jar
malisisdoors-1.10.2-5.2.0.jar
MouseTweaks-2.8-mc1.10.2.jar
movingworld-1.10.2-0007-full.jar
notenoughwands-1.1x-1.5.4.jar
OptiFine_1.10.2_HD_U_D7.jar
Pam's HarvestCraft 1.9.4-1.10.2h.jar
platforms-1.10.0-1.2.9.jar
Quark-r1.1-70.jar
Railcraft_1.10.2-10.0.1.jar
RecurrentComplex-1.2.9.1-1.10.jar
SaltyMod-1.10.2-1.8.d.jar
shetiphiancore-1.10.0-3.3.8.jar
SoundFilters-0.9_for_1.9.4.jar.disabled
SpiceOfLife-mc1.9.4-1.3.8.jar
StevesCarts-1.10.2-2.1.4.83.jar
StorageDrawers-1.10.2-3.6.1.jar
Streams-1.9.4-0.3.jar.disabled
theoneprobe-1.1x-1.4.4.jar
Tool-Upgrades 1.10.2 (v.1.2.1).jar
ToolBelt-1.10.2-1.3.0.jar
topaddons-1.10.2-0.9.1c.jar
TreeChopper-1.10.2-1.1.2.jar
XaerosWorldMap_b1.8.1_Forge_1.10.2.jar
Xtones-1.10.2-1.0.1-3.jar

**Comment by OreCruncher** [comment]
Is this a modpack I can download?

**Comment by Ash70** [comment]
No, it's my own concoction. I did forget to mention it doesn't happen 100% of the time, sometimes it does reset to morning. Looks like an odd bug. np if you cannot reproduce or find the cause I'll be able to live with it.

**Comment by OreCruncher** [comment]
That is strange it doesn't happen 100% of the time.  Have to love mod conflicts.  One last thing - can you post a link to a client log that shows the problem?  There may be an error in the log that may shed some light.

**Comment by Ash70** [comment]
[This one?](https://paste.ee/p/8SAMI)

**Comment by OreCruncher** [comment]
Yep, that one.  Didn't see anything that stands out as a problem.  I'll keep looking.  I assume that if the option is left "true" the rain/time works correctly?

**Comment by Ash70** [comment]
Yes

**Comment by Ash70** [comment]
Since I am still fine-tuning my modpack I do tend to ad and remove mods as I play the game. Today I updated dynamic surroundings and removed Railcraft and Steve's Carts. I also enabled the debug option of your mod to see if I could catch what happens. As is usually the case I slept 3x during rain and all 3 times the time reset worked. So not sure if this is because of your new version, the removal of the other mods or just coincidence. I'll keep the debug option on just in case.

**Comment by OreCruncher** [comment]
Hmmm.  The area of code in question did not change between 3.3.2.0 and 3.3.2.1.  My inkling is that it is either Railcraft or Steve's Carts with the edge going to Railcraft.  I will add it to my list of stuff to look at.

**Comment by Ash70** [comment]
Quick update.
I am currently working on making 3 modpacks of which one is 1.11.2 and 2 are 1.10.2. I found that it occurs in all three packs. So if this is a mod compatibility problem then I can now narrow it down to one of the following mods, as they are used in all three packs:

```
AppleSkin
AromaBackup
Baubles
BetterFps
BiomesOPlenty
Chisel
chiselsandbits
CraftTweaker
foamfix
GraveStone Mod 
jei
malisisdoors-1.10.2-5.2.0.jar
MouseTweaks
notenoughwands
OptiFine
StorageDrawers
theoneprobe
ToolBelt
topaddons
XaerosWorldMap
Xtones
```

As soon as I have some time (2nd week of april I think), I'll make a pack with just these mods and do some testing by disabling/enabling each of them.

**Comment by OreCruncher** [comment]
Cool.  Thanks!

**Comment by OreCruncher** [comment]
@Ash70 I have a pack I am working on and I have some overlap with the above list.  Going to cross out the ones that I have in my pack because the rain reset toggle works for me.

**Comment by OreCruncher** [comment]
@Ash70 OK - added the mods to my pack and I am unable to duplicate the problem. :\  It could be that some of the mods I use that aren't listed above "fix" the issue because of any ASM they do.  This is going to be fun.

**Comment by Ash70** [comment]
Well, like I said. It's not a big problem and seeing as I am the only one reporting it, it may not be systemic.  So don't waste too much time on it, I'll see if I can narrow it down, this also gives me a chance to refresh my java-knowledge if nothing else ;)

**Comment by OreCruncher** [comment]
:)  OK - I will wait to hear back.

**Comment by Ash70** [comment]
I had some time to test last night, using MC1.10.2, Forge Build 2254 and Dynamic Surroundings 3.3.4.0 (latest?) No other mods loaded.

I found that it doesn't happen during rain but during a thunderstorm.
Steps I took to reproduce each time (in creative mode for convenience):

1) Set 'reset rain on sleep' to false
2) put down a bed
3) /weather thunder
4) /time set night
5) go sleep -> time does not reset

Changing the option to true does reset the time properly.
So it does not seem to be a mod compatibility issue.

**Comment by OreCruncher** [comment]
Hmmmm..... OK - may be related somehow to the /weather command.  I will take a look.

**Comment by OreCruncher** [comment]
I cannot duplicate. :\  The time reset normally for me.  Of course this is in a debugger.  I will take a look at my MultiMC setup to see I can get it to happen.

I am going to ask a seemingly stupid question, but how do you verify the time hasn't changed?  Do you do a /time?

**Comment by Ash70** [comment]
Yes using time command. If you cannot reproduce it must be my hardware or drivers. I can live with it. Apologies for the trouble.

**Comment by OreCruncher** [comment]
No worries.  Can't rule a problem out - we just don't know the cause as of yet.  Did you tweak anything else in the DS configuration?

**Comment by Ash70** [comment]
Im currently not at home. Will paste my cfg tonight i did change a few things yes.

**Comment by Ash70** [comment]
Here's [my config file](https://pastebin.com/Lf5NPuD5). I mostly disabled some sounds and animations that cause lag for me.

**Comment by OreCruncher** [comment]
Looked at the log and nothing stands out.  If you are having performance issues with particles you may also want to disable the particle suspend effects for water source blocks.  The option to do that is new.

**Comment by OreCruncher** [comment]
Digging into the minecraft code the adjust for world time on sleep occurs before the players are awaken.  (The weather reset occurs during the player awaken logic.)  There is a condition on the world time adjustment - if "doDaylightCycle" is turned off the time will not advance.  By chance is it turned off?  You can do a "/gamerule doDaylightCycle" to see if it is set true/false.

**Comment by Ash70** [comment]
It is set to true. Did you change something in the last update? Because now the time does reset during a  thunderstorm. At least in  my test-instance. Will see if it also works in other instances tomorrow.

**Comment by OreCruncher** [comment]
No - didn't make any changes in that area.  It's pretty simple logic and is not prone to breakage.  This is a baffler.

**Comment by Ash70** [comment]
The mystery continues but the major "problem" seems to be solved. I remembered I also updated forge this morning so I reverted back to an older version and yes, the failure to reset time occurred; updating forge solved it.... but (there always is) now it seems that after sleeping I can keep going to sleep no matter what time of day it is as long as there is a thunderstorm.
I didn't check to see if this keeps resetting the time to 1000 since I didn't think to do that at the time, but will look at that tomorrow. Anyway, at least sleeping works now so that is something.

**Comment by Ash70** [comment]
I give up; disregard my previous reply. Using the `/time set day` command now works. But whenever I use a bed during a thunderstorm, no matter what the time is, I can go to sleep and the time will reset to 0 (midnight) of the following day. Since the behaviour changed after updating forge I guess we found the culprit. I propose we leave this open until either someone else also reports this or the problem changes again after a forge update?

**Comment by OreCruncher** [comment]
No problems leaving it open for now.  Thanks for the effort in narrowing it down..

**Comment by OreCruncher** [comment]
@Ash70 Following up to see if things are still OK. :)

**Comment by Ash70** [comment]
Haven't been able to play much and currently making a resourcepack to go with my modpack, so not been looking into this much. Last time I played (1.11.2) didn't notice any problems. If you want to close this; np.

**Comment by OreCruncher** [comment]
Sounds good.  If it turns out to be a problem again we can reopen.  Thanks!
