### ISSUE TITLE
Aegis Invisible

### ISSUE THREAD

**Issue by TexanWarrior33** [OreCruncher/DynamicSurroundings#520]
**Mod Version:** 

v2.7.1, 14.23.5.2838

**Forge Version:**

1.14.4

**Link to client log:**

None

**Link to crash log:**

None

**Description:**

The aegis mob is invisible and i don't know why. They dont have an invisible affect or anything like that but there just not appearing. It still shows their shadow and health bar though.

**Comment by OreCruncher** [comment]
Did you file the issue in the right place?  DS doesn't work with 1.14 as of yet.

**Comment by TexanWarrior33** [comment]
I tried forge 1.12.2 and that doesn’t work either. It could be because I updated the lycanites mobs.


On Nov 18, 2019, at 3:40 AM, OreCruncher <notifications@github.com> wrote:

﻿

Did you file the issue in the right place? DS doesn't work with 1.14 as of yet.

**Comment by TexanWarrior33** [comment]
![2019-11-18_16 34 37](https://user-images.githubusercontent.com/56708578/69105861-7c126400-0a21-11ea-94b6-4e609e25374c.png)

Here's a picture of it.

**Comment by OreCruncher** [comment]
Well, yeah.  Just trying to figure out what it has to do with Dynamic Surroundings.  Aegis is not related to my mod.

**Comment by OreCruncher** [comment]
Just dawned on me - I think this is an invisible entity.  That display looks like Neat rendering information about the entity above it.  Nothing to do with DS.
