### ISSUE TITLE
Dynamic Surroundings Crash

### ISSUE THREAD

**Issue by RetroGamerAndre** [OreCruncher/DynamicSurroundings#522]
**Mod Version:**

3.6.0.2

**Forge Version:**

1.12.2-14.23.5.2768

**Link to client log:**

https://pastebin.com/zM6zeiMa

**Link to crash log:**

https://pastebin.com/ij8eC1F5

**Description:**

I just recently went back to 1.12.2 and decided to try and find a mod similar to MAtmos. that was my favorite mod back when Huricaannee was making it. I tried to use the newest one sollace made but it crashed my game. I found dynamic surroundings could do the same thing and downloaded that along with dynamic surroundings HUDs and OreLib. I've tried running minecraft but every time it ends in failure. the logs say something about a transformloader. A little help would be appreciated.

**Comment by OreCruncher** [comment]
Update to Forge 2779.

**Comment by OreCruncher** [comment]
@RetroGamerAndre Have you had a chance to upgrade and verify the error went away?  The reason I ask to upgrade is that DS does have a minimum dependency on 2779, and it is the dependency failure that is triggering the error you are seeing.
