### ISSUE TITLE
Dynamic Surroundings 1.12.2 crashes upon start

### ISSUE THREAD

**Issue by blueye704** [OreCruncher/DynamicSurroundings#526]
**Mod Version:**

3.6.0.1

**Forge Version:**

1.12.2 - 14.23.5.2800

Client Log:
https://pastebin.com/raw/LDdwi0id
Crash Log:
https://pastebin.com/ki2ziD06

**Description:**

I am using the Dynamic Surroundings mod with More Player Models Mod 1.12.2,  Optifine 1.12.2  HD U F5, OreLib 1.12.2 3.6.0.1, and SOM1.12.2 - 1.14.4

**Comment by Tyderf** [comment]
I get the same issue regardless of mods.

**Comment by blueye704** [comment]
Same here. Try using the version of Orelib just after the beta versions.
That did the trick for me.

**Comment by OreCruncher** [comment]
Please make sure you use the latest DS and OreLib.

**Comment by f8upd8** [comment]
Resolved this issue by using the latest version of Forge
