### ISSUE TITLE
crash with stacking dimensions mod

### ISSUE THREAD

**Issue by Zeinoth** [OreCruncher/DynamicSurroundings#530]
mod version 3.6.0.1

Forge 14.23.5.2831

Latest log https://pastebin.com/FwESGKPu

crash report https://pastebin.com/quU5f0Cc

This crash occurs in my private modpack. It appears to be an incompatability between stacking dimensions and dynamic surroundings/orelib. The crash appears when the game starts.

**Comment by OreCruncher** [comment]
Have you tried 3.6.0.2?  Also there are other errors related to ASM in that trace that do not involve DS.

**Comment by Zeinoth** [comment]
wow sorry i didn't even see that version. it works, thanks
