### ISSUE TITLE
Strange Fog bug! Especially with morning fog it seems.

### ISSUE THREAD

**Issue by SirAron111** [OreCruncher/DynamicSurroundings#536]
**Mod Version:**
DynamicSurroundings-1.12.2-3.6.0.2.jar
The version that is installed in your pack.

**Forge Version:**
14.23.5.2847
The actual Forge version - "latest" does not count.

**Description:**

Players of my Modpack Dimension zero have found a rare bug with dyn surroundings fog handling. Under certain not yet clear circumstances during morning fog times, the fog can suddenly pop into the renderer above all other things making it look like this https://youtu.be/gcDfnuzWCjk?t=3235 . I sadly don’t have a log of this since it didn’t happen on my end, Optifine seems to fix it and so does the better fps turning fog off option but then you have no fog at all. Sometimes it fixes itself on client restart. But it seems to be narrowed down to the custom fog handling of dynsuround. Not the highest priority only had this reported 2 times in like half a year but still not a pleasant experience and should be looked into when you have some spare time.

**Comment by OreCruncher** [comment]
Took a look at the video.  Are you referring to when all the terrain disappears, mobs get whited out, but some blocks still render (like at the tail end of the video)?

**Comment by SirAron111** [comment]
Yep that’s why I posed it at this timestamp. For some reason if the custom font render handling in your mod is activated this has been reported to happen.

**Comment by OreCruncher** [comment]
I don't think this is fog.  Reason is that the blocks are visible as per normal.  If it were fog related they would have been masked out as well.  Is this is a private or public modpack?

**Comment by SirAron111** [comment]
public available on twitch free to download for anyone. well it happened realy rareely and seems to be affected by the fog options to turn off fog compleatly.

**Comment by OreCruncher** [comment]
Trying to tell from the video but it looks like your elevation was around y = 114?  I think I may know what happened but not sure of the cause yet.

**Comment by OreCruncher** [comment]
Pushed 3.6.1.0 to CurseForge.
