### ISSUE TITLE
Heal/damage pop-offs on servers

### ISSUE THREAD

**Issue by Helmasaur** [OreCruncher/DynamicSurroundings#54]
*Mod Version:* 3.2.8.1

*Forge Version:* 13.2.0.2228

*Link to crash log (if applicable):* -

*Description:*
Hello,

First of all, I have to say that this mod changed a lot the gameplay of Minecraft. Although, I am wondering if it's normal to not see heal/damage pop-offs on servers? They are displayed on my solo games.

Thansk for all,
Helmasaur

**Comment by OreCruncher** [comment]
If Dynamic Surroundings is not installed on the server you will not see the pop-offs.  This is expected.  Reason is that the events that Dynamic Surroundings listens to in order to get this information occur in the server side thread.

**Comment by Helmasaur** [comment]
Oh, on this server, I wanted to have mods only on my client. I guess I'll keep it this way.

Thanks for your quick answer :) !
