### ISSUE TITLE
[Dynamic Surroundings Issue With EnderIO DS Padding] helmet drop fps to 0 [clientside only]

### ISSUE THREAD

**Issue by CitiesXL2815** [OreCruncher/DynamicSurroundings#541]
**Issues:**

So my friend was have some issue with EnderIO helmet after Installing Padding then just drops the fps down to 5 to 0, so i tested around with it and when it's equipped the fps drops but unequipped the helmet fps goes back to normal and i tested and Dynamic Surroundings likes to break the client and removing DS fixes it so i reported it to EIO Discord 

**===============================================**

**LogFiles or Crashes:**

there no log bc it doesn't show issue nor debug but i can still get the log if you need a log just ask me

**===============================================**

**Versions Affected:**

- Mincraft Version: 1.12.2
- Forge Version: 2847

**===============================================**

**Mods Affected:**

- DS Version: 3.6.0.2
- EnderIO Version: 5.1.55
- EnderIO Nightly Build: 5.1.1153
- Optifine: nope
- SpongeForge: nope
- Server or SP: both

**Comment by CitiesXL2815** [comment]
actually a problem so one of my friend in our base placed null Chunkloader that lag us out completely well i tested the helmet of padding think it was cause of DS nope until she told me that chunkloader causing FPS issues lol and i'm going to kill her in minecraft issue solved

**Comment by OreCruncher** [comment]
lol
