### ISSUE TITLE
After updating LittleTiles and CreativeCore game crashes right after loading the world

### ISSUE THREAD

**Issue by alynw** [OreCruncher/DynamicSurroundings#544]
**Mod Version:**

DynamicSurroundings-1.12.2-3.6.0.2

**Forge Version:**

forge-14.23.5.2847

**Link to client log:**

The code was to big to be updated on pastebin or hastebin so uploaded it on google drive [clientlog](https://drive.google.com/open?id=1GzIduhnV9Nwr__eSh67EqPFmfJHAOXhG)

**Link to crash log:**

[crash log on pastebin](https://pastebin.com/UWK7hvGv)

**Description:**

I updated to last version CreativeCore_v1.9.91_mc1.12.2 and LittleTiles_v1.5.0-pre199_12_mc1.12.2 and the game started to crash right after i load the world.

**Comment by OreCruncher** [comment]
Yes.  You are using the latest little tiles?  If so it will not work with the version I have posted.  I am working on a build that addresses.

**Comment by blakedj012** [comment]
How long do you need for the new version?

**Comment by blakedj012** [comment]
How long do you need for the new version?

**Comment by OreCruncher** [comment]
Hopefully will be out soon.  RL stuff is happening.

**Comment by OreCruncher** [comment]
Pushed 3.6.1.0 to CurseForge.
