### ISSUE TITLE
Crash While Loading Game With External Config

### ISSUE THREAD

**Issue by Exsolutus** [OreCruncher/DynamicSurroundings#549]
**Mod Version:**

DynamicSurroundings-1.12.2-3.6.0.2

**Forge Version:**

1.12.2 forge-14.23.5.2847

**Link to client log:**

File was too long for Hastebin 🤷‍♂ 

**Link to crash log:**

https://hastebin.com/akayagifek.rb

**Description:**

I attempted to create an external config file to modify aurora behavior, as follows:

```
{
        "biomes":[
			{
				"conditions": "TRUE",
				"_comment": "Disable default aurora settings",
				"aurora": "FALSE"
			},
			{
				"conditions": "abs(ceiling(player.Z)) > 14000",
				"_comment": "Auroras occur beyond 14km north and south of the equator",
				"aurora": "TRUE"
			}
        ]
}
```

As far as I can tell, I've written this correctly. But there appears to be some issue with the "player.Z" condition string (see crash log).

**Comment by OreCruncher** [comment]
Going through the old issues.  You may have moved on from this, but the issue is the condition string is not evaluated at run time.  it is only evaluated at startup and is used to select biomes in order to apply those settings.
