### ISSUE TITLE
Is there any up to date information on getting Weather 2 compatible with this mod?

### ISSUE THREAD

**Issue by Sunconure11** [OreCruncher/DynamicSurroundings#55]
Either I'm unlucky, or changing the setting mentioned in the wikia did not do anything about the aurora and rain settings.

**Comment by OreCruncher** [comment]
The 1.10.2/1.11.x versions auto-disable aurora and rain.  IIR Weather2 and Dynamic Surroundings both want to register a weather render and that would cause issues.  It's on my list of things to figure out a way they can both co-exist.

**Comment by OreCruncher** [comment]
Question: in terms of compatibility what would you be looking for?  Since Weather2 wants to do the rain/thunder/whatever rendering it makes sense to let it do that.  Only thing that could be missing is the Dynamic Surroundings Auroras.

**Comment by Sunconure11** [comment]
Yeah, the auroras and what not, basically.

**Comment by OreCruncher** [comment]
OK.  As mentioned Weather2 wants to override weather rendering to do what it does, and when it does that Dynamic Surroundings can't do aurora or weather rendering.  I am looking at doing auroras separate from rainfall so that at least that effect can work.

(I also sent a message to Corosus about this.  There may be other issues at it relates to how it overrides the EntityRenderer.)

**Comment by OreCruncher** [comment]
@Sunconure11 I moved the aurora rendering out of the normal weather render hook into a RenderWorldLastEvent handler.  Net result is that Auroras will render when Weather 2 is installed.  Still not sure about the normal storm render paths since Weather2 wants to own those.

**Comment by OreCruncher** [comment]
Posted v3.3.3.1 that addresses the Aurora rendering portion.

**Comment by OreCruncher** [comment]
No response for Corosus.  At the moment I believe this to be more an issue for Weather2 in how it handles any hooked weather renders in the base EntityRenderer instance it replaces.  I am going to close for now since the aurora rendering was moved out and should render when Weather2 is installed.
