### ISSUE TITLE
Crash with Performant

### ISSUE THREAD

**Issue by V-Boy** [OreCruncher/DynamicSurroundings#552]
**Mod Version:**
Performant 1.8
DynamicSurroundings-1.12.2-3.6.0.2.jar
OreLib-1.12.2-3.6.0.1.jar

**Forge Version:**
Forge 1.12.2-14.23.5.2847

**Link to client log:**

debug: https://hastebin.com/azedotomow.md
latest: https://hastebin.com/usejakuxoh.md

**Description:**

1. Download latest version of performant and dynamic surroundings with its dependencies
2. load up minecraft
3. within the first few seconds it wont work

i tested this with just dynamic surroundings and performant btw, still bugs out

**Comment by OreCruncher** [comment]
```
[16:11:06] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: java.util.ServiceConfigurationError: org.spongepowered.asm.service.IMixinServiceBootstrap: Provider org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap could not be instantiated
```

**Comment by BobDaGecko** [comment]
Same issue.

**Comment by OreCruncher** [comment]
@V-Boy Can you try out https://github.com/OreCruncher/DynamicSurroundings/releases/tag/3.6.1.0  I updated mixin.

**Comment by V-Boy** [comment]
I launched my game, works for me so far

Sent from my iPhone

On Apr 4, 2020, at 10:47 AM, OreCruncher <notifications@github.com<mailto:notifications@github.com>> wrote:


@V-Boy<https://github.com/V-Boy> Can you try out https://github.com/OreCruncher/DynamicSurroundings/releases/tag/3.6.1.0 I updated mixin.

**Comment by OreCruncher** [comment]
Pushed 3.6.1.0 to CurseForge.
