### ISSUE TITLE
Crash with VanillaFix due to Mixins conflict

### ISSUE THREAD

**Issue by RexOrbis** [OreCruncher/DynamicSurroundings#556]
**Mod Version:**

DynamicSurroundings-1.12.2-3.6.0.2.jar

**Forge Version:**

14.23.5.2847

**Link to client log:**

N/A

**Link to crash log:**

N/A

**Description:**

VanillaFix-1.0.10-150 crashes on startup with DynamicSurroundings-1.12.2-3.6.0.2, leaving no crash log. Boots back to the launcher.

According to the author of VanillaFix:

"These issues are all related to mod loading issues and outdated Mixins versions. The way Mixins 0.8 was made, 0.7.X can work on 0.8, but it is not the same the other way around, so mods need to update to newer versions... DynamicSurroundings will more than likely do an update if told about this. Either way, this crash is not a fault on us, and mod developers should update as more mods are being updated to 0.8."

Are there any plans to update this mod to Mixins 0.8 (Assuming what was said is true)?

**Comment by Darkmega18** [comment]
Hi. this. I just saw this line when loading up my pack with the latest version then backdating to see what it crashed on. I can wait, glad someone's already let yous know.
https://github.com/DimensionalDevelopment/VanillaFix/issues/244

**Comment by RobinTR** [comment]
Rename vanillafix to @VanillaFix-1.0.10-150.jar it should work. (Temporarily solution before this mod updated)

**Comment by Darkmega18** [comment]
seems a little hacky. I'll just wait on it. No big deal, right...?

**Comment by DemonfangArun** [comment]
> 
> 
> Rename vanillafix to @VanillaFix-1.0.10-150.jar it should work. (Temporarily solution before this mod updated)

This is unfortunately unacceptable for modpacks published on curseforge.

**Comment by Darkmega18** [comment]
indeed. like myself. :V

**Comment by Wohlf-craft** [comment]
Here is the client log, I mainly find issues with just this mod using old mixin.
https://gist.github.com/Wohlf-craft/812862d3c9f0b35f7db3dc19482bdae9

**Comment by OreCruncher** [comment]
Hello all!  Can you try out https://github.com/OreCruncher/DynamicSurroundings/releases/tag/3.6.1.0  I updated mixin.

**Comment by ScienceDrummer** [comment]
Does this need an updated version of OreLib as well?

**Comment by OreCruncher** [comment]
Nope

**Comment by ScienceDrummer** [comment]
I realized that was a dumb question to ask when I can just boot the game up itself and find out, but thanks for answering anyways.

**Comment by OreCruncher** [comment]
It was a fair question.  I had to look at OreLib just to make sure I didn't do Mixin there as well. :)

**Comment by vico93** [comment]
@OreCruncher worked here alongisde VanillaFix and DiscordIntegration, both with mixin 0.8. Many thanks!

**Comment by Falcion** [comment]
@OreCruncher When will this update be released on CurseForge? After all, Twitch can't see such modifications... (unfortunately)

**Comment by OreCruncher** [comment]
@Falcion Very soon.

**Comment by OreCruncher** [comment]
Pushed 3.6.1.0 to CurseForge.
