### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by agentwolf88** [OreCruncher/DynamicSurroundings#558]
**Mod Version:**

DynamicSurroundings-1.12.2-3.6.1.0.jar

**Forge Version:**

14.23.5.2847

**Link to client log:**

https://paste.ee/p/MRnA5

**Link to crash log:**

https://paste.dimdev.org/atufilucob.mccrash

**Description:**

Description of the problem.  In the case of crashes, it is good to know things like the following:

crash at startup

**Comment by OreCruncher** [comment]
JustEnoughIds - have you tried the lastest published version of that mod?

**Comment by agentwolf88** [comment]
Yes, now. But still crashing.

https://paste.dimdev.org/kanirocule.mccrash

**Comment by OreCruncher** [comment]
Update VanillaFix - I know that one is behind.  The key here is finding all the mods that have Mixin embedded and get them updated.

**Comment by ChromaPIE** [comment]
I encountered exactly the same problem just as what has been described above. After VanillaFix and JEIDs has been updated to the latest release the game could be successfully launched.

Successfully launched with **VanillaFix-1.0.10-150** and **JustEnoughIDs-1.0.3-55**.

**Comment by OreCruncher** [comment]
I am removing the embedded Mixin library and taking a dependency on MixinBootstrap.

**Comment by OreCruncher** [comment]
Posted 3.6.2.0 to CurseForge as BETA.  MixinBoostrap will also need to be installed.
