### ISSUE TITLE
water particles reduces fps

### ISSUE THREAD

**Issue by Hypsellis** [OreCruncher/DynamicSurroundings#56]
I had already talked a lot of this problem, anyway this issue still exists. The water particles when they a lot reduces drastically the fps.
![2017-04-03_06 41 14](https://cloud.githubusercontent.com/assets/17103411/24595634/abf9346a-1838-11e7-885e-03397f4cc211.png)
![2017-04-03_06 41 25](https://cloud.githubusercontent.com/assets/17103411/24595636/abfe8e7e-1838-11e7-86e6-24780e1a094e.png)
![2017-04-03_06 41 35](https://cloud.githubusercontent.com/assets/17103411/24595635/abfb7cca-1838-11e7-8569-d194a725e74b.png)

**Comment by OreCruncher** [comment]
In my rig running in debug mode I get 120FPS with larger falls without using optifine or other speed enhancing mods.  And the reason I get 120FPS is because I cap it at that number.  Of course I am not running with 278 mods.  Is Foamfix still installed?

**Comment by Hypsellis** [comment]
I thought FoamFix would solve it, but it doesn't. And I get normally 30fps with the shader I have, and 100 without shader. The presence of shader doesn't change anything.

**Comment by OreCruncher** [comment]
FoamFix does a lot in terms of memory pressure.  The pack you are running requires a lot of memory so FoamFix does help in that regard.

As it relates to FPS I noticed that the first two screen shots are 22FPS while the 3rd is 4FPS.  The middle screenshot has particles being rendered so it should be factored into the 22FPS.  However, depending on how fast you moved and when you took the shots it could be misleading.

Do you have Tough as Nails installed?

**Comment by Hypsellis** [comment]
Yes

**Comment by OreCruncher** [comment]
I've noticed that TAN can take up some CPU with regards to particles.  I have noticed that travelling through my world that sometimes FPS will drop through the floor, and it is related to some of TANs particle handling.  I can't say that this your problem, but if you can remove the mod for testing purposes it would help eliminate that as an issue.

(In your screenshots there are 1000-1300 particles in the Minecraft ParticleManager - that is what that "P" is on the 5th line.  In my test world I have a much larger waterfall and the particle count is around 500.  This is telling me that in your pack there are bunch of other particles being generated.  I assume that you have Better Foliage installed and dropping leaves may account for some of that.)

**Comment by Hypsellis** [comment]
Yeah better foliage is present too.

**Comment by Hypsellis** [comment]
Oh I don't get more fps problems without TAN.

**Comment by OreCruncher** [comment]
Sorry, not clear to me. :)  Without TAN is the FPS problem better?

**Comment by Hypsellis** [comment]
Yes

**Comment by OreCruncher** [comment]
How much?  Does it go back to the normal 30FPS?

**Comment by Hypsellis** [comment]
Yeah it seems.

**Comment by OreCruncher** [comment]
OK.  I am reworking the water splash particle rendering for the next BETA (v3.3.4.0).  Should help improve FPS around large waterfalls, but it is dependent on the circumstances.

If you want to try something experimental, the v3.3.3.0 has an ASM Transformer Option to enable replacement of the Java Random with my custom random number generator.  By default it is OFF, but you can turn it on and restart the client.  If you try this do not use an existing world otherwise it will scramble the map - the interpretation of the map seed will be different and result in strange world generation for new chunks.  Start with a fresh map.  If you do this I am interested in what you experience.  When you want to go back to your old maps just turn it of and restart the client.

**Comment by Hypsellis** [comment]
I will try it ;)

**Comment by Hypsellis** [comment]
It doesn't change a lot. :(

**Comment by OreCruncher** [comment]
OK - the bulk of the FPS time is related to rendering that doesn't really involve randoms.

**Comment by OreCruncher** [comment]
Pretty much gutted the splash particle and wrote my own lightweight version.  It improves FPS around large falls a fair bit, but as mentioned prior it really is dependent on the modpack in question.

**Comment by OreCruncher** [comment]
Posted a BETA to CurseForge that has the performance tweaks for waterfall effects.  I don't think it will overcome TAN issues but it should help Minecraft under general situations.  I also provided an option to disable Minecraft's water suspend particle effect (those little motes that show up in water blocks).  If you spend a lot of time around water this may help reduce particle load.
