### ISSUE TITLE
Crash Between Level Up 2, Dynamic Surroundings, and Various Other 'Trigger' Mods.

### ISSUE THREAD

**Issue by VT-14** [OreCruncher/DynamicSurroundings#560]
**Mod Version:**

DynamicSurroundings-1.12.2-3.6.1.0
levelup2-1.3.0-shaded
OreLib-1.12.2-3.6.0.1

**Forge Version:**

forge-1.12.2-14.23.5.2854

**Link to client log:**

Botania Trigger: https://gist.github.com/VT-14/3bfcc8e38f3d18bd8ae715704e5dfbdf
The Betweenlands Trigger: https://gist.github.com/VT-14/4d3a70dbdb8002879ca5e65e0c983e9b

**Link to crash log:**

Botania Trigger: https://gist.github.com/VT-14/fcd4292a00e9b5ec0395c2f05cdffe74
The Betweenlands Trigger: https://gist.github.com/VT-14/efbda0f287aa909a4e4ff989b817c588

**Description:**

Using both Level Up 2 and Dynamic Surroundings, along with any number of 'trigger' mods, will cause the game to crash.  The first line in the stacktrace is always:

    java.lang.NoSuchMethodError: net.minecraftforge.common.capabilities.Capability$IStorage.writeNBT(Lnet/minecraftforge/common/capabilities/Capability;Ljava/lang/Object;Lnet/minecraft/util/EnumFacing;)Lnet/minecraft/nbt/NBTBase;

From there, the stacktrace points out code in the 'trigger' mod.  Attempting to remove that 'trigger' mod usually results in a new mod triggering the crash and getting blamed instead.

The two known 'trigger' mods I've used are Botania and The Betweenlands.  Since this appears to be NBT related, I expect there are *far* more out there.  [This post on /r/FeedTheBeastCrashes](https://www.reddit.com/r/FeedTheBeastCrashes/comments/g0rlh4/updated_mods_in_custom_modpack_now_doesnt_work/) (where I first saw this issue) suggests that Everlasting Abilities and Locks are also affected, and a conversation in the Ender IO Discord's bug report channel brought up [this crash report](https://paste.dimdev.org/iboresuniz.mccrash) implying an issue between Craft Tweaker, Nuclearcraft, and Ender IO.

The author of that Reddit post managed to solve their crash by removing Level Up 2.  I passed that on to the Discord User and they managed to solve the issue the same way.  I investigated further on my own and managed to narrow the mod list down to these 2 mods, a trigger mod, and dependencies.  To recap:

* Level Up 2 + Dynamic Surroundings + Trigger Mod = Crash.
* Level Up 2 + Trigger Mod (no Dynamic Surroundings) = No Crash.
* Dynamic Surroundings + Trigger Mod (no Level Up 2) = No Crash.
* Level Up 2 + Dynamic Surroundings (No Trigger Mods) = No Crash.

The tested "Trigger" mods were Botania and The Betweenlands.  Others are believed to exist.

****

Furthermore, I found that when Level Up 2 is combined with either Phosphor or VanillaFix, the modpack won't even launch.  Adding Dynamic Surroundings does allow the pack to launch without any immediately apparent issues (other than the rest of this bug report).

**Link to Issue on Level Up 2's GitHub**

BeetoGuy/LevelUp2/issues/74

**Comment by OreCruncher** [comment]
Does this happen with the 3.6.0.2 version of DS?

**Comment by VT-14** [comment]
The crash does not occur if you revert to Dynamic Surroundings 3.6.0.2.

Also, adding Phosphor (forge-mc1.12.2-0.2.7-universal) along with Level Up 2 does prevent Minecraft from starting again (no crash report or logs), regardless of having Dynamic Surroundings 3.6.0.2 or not.  I didn't check VanillaFix or with other mods.

**Comment by OreCruncher** [comment]
Yep - sounds like it is mixin related.  The latest version of VanillaFix and Phosphor are updated to 0.8 Mixin as well.

**Comment by OreCruncher** [comment]
Changing DS to use MixinBootstrap instead of embedding the Mixin library.

**Comment by OreCruncher** [comment]
Posted 3.6.2.0 to CurseForge as BETA.  MixinBoostrap will also need to be installed.
