### ISSUE TITLE
An IllegalAccessError after updated to the new version 3.6.10

### ISSUE THREAD

**Issue by KevynTang** [OreCruncher/DynamicSurroundings#562]
Hi, I love this mod very much. but today when I use the v3.6.10 to replace the v3.6.02 in my mods pack, there occurred an error when the game was initializing. 
**Mod Version:**
3.6.10

**Forge Version:**
14.23.5.2847

**crash log:**
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2020-04-18 20:03:05 CST
Description: Initializing game

java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinTransformer from class net.minecraftforge.fml.common.Loader
    at net.minecraftforge.fml.common.Loader.handler$zza000$mzzBeforeConstructingMods(Loader.java:1174)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_241, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 110165160 bytes (105 MB) / 486539264 bytes (464 MB) up to 3221225472 bytes (3072 MB)
  JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx3072m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 62 mods loaded, 62 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                  | Version            | Source                                             | Signature |
       |:----- |:------------------- |:------------------ |:-------------------------------------------------- |:--------- |
       | L     | minecraft           | 1.12.2             | minecraft.jar                                      | None      |
       | L     | mcp                 | 9.42               | minecraft.jar                                      | None      |
       | L     | FML                 | 8.0.99.99          | forge-1.12.2-14.23.5.2847.jar                      | None      |
       | L     | forge               | 14.23.5.2847       | forge-1.12.2-14.23.5.2847.jar                      | None      |
       | L     | creativecoredummy   | 1.0.0              | minecraft.jar                                      | None      |
       | L     | itemphysic          | 1.4.0              | minecraft.jar                                      | None      |
       | L     | jecharacters        | 1.12.0-3.4.3       | JustEnoughCharacters-1.12.0-3.4.3.jar              | None      |
       | L     | littletilescore     | 1.0.0              | minecraft.jar                                      | None      |
       | L     | foamfixcore         | 7.7.4              | minecraft.jar                                      | None      |
       | L     | randompatches       | 1.12.2-1.19.1.1    | Randompatches-1.12.2-1.19.1.1.jar                  | None      |
       | L     | aiimprovements      | 0.0.1.3            | AIImprovements-1.12-0.0.1b3.jar                    | None      |
       | L     | craftstudioapi      | 1.0.0              | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None      |
       | L     | harvestcraft        | 1.12.2zb           | Pam's+HarvestCraft+1.12.2zg.jar                    | None      |
       | L     | animania            | 1.7.3              | Animania-1.12.2-1.7.3.jar                          | None      |
       | L     | antiqueatlas        | 4.6.3              | Antiqueatlas-1.12.2-4.6.3.jar                      | None      |
       | L     | antiqueatlasoverlay | 1.2                | Antiqueatlas-1.12.2-4.6.3.jar                      | None      |
       | L     | applecore           | 3.2.0              | AppleCore-mc1.12.2-3.2.0.jar                       | None      |
       | L     | betteroffhand       | 0.2                | BetterOffhand1.12.2.jar                            | None      |
       | L     | bspkrscore          | 7.6.0.1            | BspkrsCore-universal-7.6.0.1.jar                   | None      |
       | L     | chunkanimator       | 1.2                | Chunk-Animator-Mod-1.12.jar                        | None      |
       | L     | crafttweaker        | 4.1.20             | CraftTweaker2-1.12-4.1.20.jar                      | None      |
       | L     | ctgui               | 1.0.0              | CraftTweaker2-1.12-4.1.20.jar                      | None      |
       | L     | jei                 | 4.15.0.281         | JustEnoughItem_1.12.2-4.15.0.281.jar               | None      |
       | L     | crafttweakerjei     | 2.0.3              | CraftTweaker2-1.12-4.1.20.jar                      | None      |
       | L     | creativecore        | 1.10.0             | CreativeCore_v1.10.10_mc1.12.2.jar                 | None      |
       | L     | culinaryconstruct   | 1.3.3.2            | Culinaryconstruct-1.3.3.2.jar                      | None      |
       | L     | orelib              | 3.6.0.1            | OreLib-1.12.2-3.6.0.1.jar                          | None      |
       | L     | dsurround           | 3.6.1.0            | DynamicSurroundings-1.12.2-3.6.1.0.jar             | None      |
       | L     | fbp                 | 2.4.1              | FancyBlockParticles-1.12.x-2.4.1.jar               | None      |
       | L     | fastfurnace         | 1.3.1              | FastFurnace-1.12.2-1.3.1.jar                       | None      |
       | L     | fastleafdecay       | v14                | FastLeafDecay-v14.jar                              | None      |
       | L     | fastbench           | 1.7.3              | FastWorkbench-1.12.2-1.7.3.jar                     | None      |
       | L     | fenceoverhaul       | 1.3.4              | FenceOverhaul-1.3.4.jar                            | None      |
       | L     | foamfix             | 0.10.8-1.12.2      | Foamfix-0.10.8-1.12.2.jar                          | None      |
       | L     | fpsreducer          | mc1.12.2-1.14.1    | FpsReducer-mc1.12.2-1.14.1.jar                     | None      |
       | L     | gravestone          | 1.10.3             | Gravestone-1.10.3.jar                              | None      |
       | L     | waila               | 1.8.26             | Hwyla-1.8.26-B41_1.12.2.jar                        | None      |
       | L     | jehc                | 1.7.0              | JustEnougHarvestcraft-1.12.2-1.7.0.jar             | None      |
       | L     | kleeslabs           | 5.4.12             | KleeSlabs_1.12.2-5.4.12.jar                        | None      |
       | L     | dogslie             | 1.0.2              | LetSleepingDogsLie-1.12.2-1.0.2.jar                | None      |
       | L     | littletiles         | 1.5.0              | LittleTiles_v1.5.0-pre199_19_mc1.12.2.jar          | None      |
       | L     | makezoomzoom        | 0.0.4              | MakeZoomZoom-0.0.4.jar                             | None      |
       | L     | mobends             | 0.24               | Mobends-0.24_for_MC-1.12.jar                       | None      |
       | L     | orecore             | 1.4.1              | OreCore-1.12.2+-(v.1.4.1).jar                      | None      |
       | L     | getalltheseeds      | 1.12a              | Pam's+Get+all+the+Seeds!+1.12a.jar                 | None      |
       | L     | pizzacraft          | 2.0.18.18          | PizzaCraft-1.12.2-2.0.18.18.jar                    | None      |
       | L     | potioncore          | 1.8_for_1.12.2     | PotionCore-1.8_for_1.12.2.jar                      | None      |
       | L     | traverse            | 1.6.0              | Traverse-1.12.2-1.6.0-69.jar                       | None      |
       | L     | pvj                 | 1.6.4              | ProjectVibrantJourneys-1.12.2-1.6.4.jar            | None      |
       | L     | reforged            | 0.7.5              | Reforged-Mod-1.12.jar                              | None      |
       | L     | seedprotect         | 1.2.0              | Seedprotect-1.12.2-1.2.0.jar                       | None      |
       | L     | sit                 | v1.3               | Sit-1.12.2-v1.3.jar                                | None      |
       | L     | soundphysics        | 1.0.4              | Sound-Physics-1.12.2.jar                           | None      |
       | L     | surge               | 2.0.77             | Surge-1.12.2-2.0.77.jar                            | None      |
       | L     | treecapitator       | 1.43.0             | TreeCapitator-client-1.43.0.jar                    | None      |
       | L     | vanillafix          | 1.0.10-SNAPSHOT    | VanillaFix-1.0.10-99.jar                           | None      |
       | L     | kiwi                | 0.5.3.32           | Kiwi-1.12.2-0.5.3.32.jar                           | None      |
       | L     | cuisine             | 0.5.22-build929    | Cuisine-0.5.22-build929.jar                        | None      |
       | L     | vanillafoodpantry   | 4.3.1              | Vanillafoodpantry-mc1.12.2-4.3.1.jar               | None      |
       | L     | rtg                 | 6.1.0.0-snapshot.1 | RTG-1.12.2-6.1.0.0-snapshot.1.jar                  | None      |
       | L     | snowrealmagic       | 0.3.3              | SnowRealMagic-0.3.3.jar                            | None      |
       | L     | solcarrot           | 1.8.3              | Solcarrot-1.12.2-1.8.3.jar                         | None      |
  Loaded coremods (and transformers): TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
                                        
                                      MZZLoadingPlugin (MakeZoomZoom-0.0.4.jar)
                                        xyz.ajp.makezoomzoom.asm.MZZClassTransformer
                                      ItemPatchingLoader (ItemPhysic_Full_1.4.32_mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (Foamfix-0.10.8-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      JechCore (JustEnoughCharacters-1.12.0-3.4.3.jar)
                                        me.towdium.jecharacters.core.JechClassTransformer
                                      RandomPatches (Randompatches-1.12.2-1.19.1.1.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      LittlePatchingLoader (LittleTiles_v1.5.0-pre199_19_mc1.12.2.jar)
                                        com.creativemd.littletiles.LittleTilesTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      CreativePatchingLoader (CreativeCore_v1.10.10_mc1.12.2.jar)
                                        
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      LoadingPlugin (Chunk-Animator-Mod-1.12.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
                                      CoreModLoader (Sound-Physics-1.12.2.jar)
                                        com.sonicether.soundphysics.CoreModInjector
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.91' Renderer: 'GeForce MX250/PCIe/SSE2'
  Suspected Mods: Unknown
  Launched Version: HMCL 3.2.149
  LWJGL: 2.9.4
  OpenGL: GeForce MX250/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.91, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: Custom Sky (No stars at daytime).zip
  Current Language: 简体中文 (中国)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz

**Comment by OreCruncher** [comment]
Update VanillaFix.

**Comment by tDemur** [comment]
I have now updated the VanillaFix to the newest version on curseforge (1.0.10-150).
There is still an IllegalAccessError there, I think these two crash-reports are the same.

**crash log**
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2020-04-19 00:46:46 CST
Description: Initializing game

java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinTransformer from class net.minecraftforge.fml.common.Loader
    at net.minecraftforge.fml.common.Loader.handler$zza000$mzzBeforeConstructingMods(Loader.java:1174)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)d
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_241, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 183232904 bytes (174 MB) / 503316480 bytes (480 MB) up to 3221225472 bytes (3072 MB)
  JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx3072m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 64 mods loaded, 64 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                  | Version            | Source                                             | Signature |
       |:----- |:------------------- |:------------------ |:-------------------------------------------------- |:--------- |
       | L     | minecraft           | 1.12.2             | minecraft.jar                                      | None      |
       | L     | mcp                 | 9.42               | minecraft.jar                                      | None      |
       | L     | FML                 | 8.0.99.99          | forge-1.12.2-14.23.5.2847.jar                      | None      |
       | L     | forge               | 14.23.5.2847       | forge-1.12.2-14.23.5.2847.jar                      | None      |
       | L     | creativecoredummy   | 1.0.0              | minecraft.jar                                      | None      |
       | L     | itemphysic          | 1.4.0              | minecraft.jar                                      | None      |
       | L     | jecharacters        | 1.12.0-3.4.3       | JustEnoughCharacters-1.12.0-3.4.3.jar              | None      |
       | L     | littletilescore     | 1.0.0              | minecraft.jar                                      | None      |
       | L     | foamfixcore         | 7.7.4              | minecraft.jar                                      | None      |
       | L     | randompatches       | 1.12.2-1.19.1.1    | Randompatches-1.12.2-1.19.1.1.jar                  | None      |
       | L     | aiimprovements      | 0.0.1.3            | AIImprovements-1.12-0.0.1b3.jar                    | None      |
       | L     | craftstudioapi      | 1.0.0              | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None      |
       | L     | harvestcraft        | 1.12.2zb           | Pam's+HarvestCraft+1.12.2zg.jar                    | None      |
       | L     | animania            | 1.7.3              | Animania-1.12.2-1.7.3.jar                          | None      |
       | L     | antiqueatlas        | 4.6.3              | Antiqueatlas-1.12.2-4.6.3.jar                      | None      |
       | L     | antiqueatlasoverlay | 1.2                | Antiqueatlas-1.12.2-4.6.3.jar                      | None      |
       | L     | applecore           | 3.2.0              | AppleCore-mc1.12.2-3.2.0.jar                       | None      |
       | L     | betteroffhand       | 0.2                | BetterOffhand1.12.2.jar                            | None      |
       | L     | betterplacement     | 1.0.0-1            | BetterPlacement-1.0.0-1.jar                        | None      |
       | L     | bspkrscore          | 7.6.0.1            | BspkrsCore-universal-7.6.0.1.jar                   | None      |
       | L     | chunkanimator       | 1.2                | Chunk-Animator-Mod-1.12.jar                        | None      |
       | L     | crafttweaker        | 4.1.20             | CraftTweaker2-1.12-4.1.20.jar                      | None      |
       | L     | ctgui               | 1.0.0              | CraftTweaker2-1.12-4.1.20.jar                      | None      |
       | L     | jei                 | 4.15.0.281         | JustEnoughItem_1.12.2-4.15.0.281.jar               | None      |
       | L     | crafttweakerjei     | 2.0.3              | CraftTweaker2-1.12-4.1.20.jar                      | None      |
       | L     | creativecore        | 1.10.0             | CreativeCore_v1.10.10_mc1.12.2.jar                 | None      |
       | L     | culinaryconstruct   | 1.3.3.2            | Culinaryconstruct-1.3.3.2.jar                      | None      |
       | L     | orelib              | 3.6.0.1            | OreLib-1.12.2-3.6.0.1.jar                          | None      |
       | L     | dsurround           | 3.6.1.0            | DynamicSurroundings-1.12.2-3.6.1.0.jar             | None      |
       | L     | fbp                 | 2.4.1              | FancyBlockParticles-1.12.x-2.4.1.jar               | None      |
       | L     | farseek             | 2.5                | Farseek-1.12-2.5.jar                               | None      |
       | L     | fastfurnace         | 1.3.1              | FastFurnace-1.12.2-1.3.1.jar                       | None      |
       | L     | fastleafdecay       | v14                | FastLeafDecay-v14.jar                              | None      |
       | L     | fastbench           | 1.7.3              | FastWorkbench-1.12.2-1.7.3.jar                     | None      |
       | L     | foamfix             | 0.10.8-1.12.2      | Foamfix-0.10.8-1.12.2.jar                          | None      |
       | L     | fpsreducer          | mc1.12.2-1.14.1    | FpsReducer-mc1.12.2-1.14.1.jar                     | None      |
       | L     | gravestone          | 1.10.3             | Gravestone-1.10.3.jar                              | None      |
       | L     | waila               | 1.8.26             | Hwyla-1.8.26-B41_1.12.2.jar                        | None      |
       | L     | jehc                | 1.7.0              | JustEnougHarvestcraft-1.12.2-1.7.0.jar             | None      |
       | L     | kleeslabs           | 5.4.12             | KleeSlabs_1.12.2-5.4.12.jar                        | None      |
       | L     | dogslie             | 1.0.2              | LetSleepingDogsLie-1.12.2-1.0.2.jar                | None      |
       | L     | littletiles         | 1.5.0              | LittleTiles_v1.5.0-pre199_19_mc1.12.2.jar          | None      |
       | L     | makezoomzoom        | 0.0.4              | MakeZoomZoom-0.0.4.jar                             | None      |
       | L     | mobends             | 0.24               | Mobends-0.24_for_MC-1.12.jar                       | None      |
       | L     | orecore             | 1.4.1              | OreCore-1.12.2+-(v.1.4.1).jar                      | None      |
       | L     | getalltheseeds      | 1.12a              | Pam's+Get+all+the+Seeds!+1.12a.jar                 | None      |
       | L     | pizzacraft          | 2.0.18.18          | PizzaCraft-1.12.2-2.0.18.18.jar                    | None      |
       | L     | potioncore          | 1.8_for_1.12.2     | PotionCore-1.8_for_1.12.2.jar                      | None      |
       | L     | traverse            | 1.6.0              | Traverse-1.12.2-1.6.0-69.jar                       | None      |
       | L     | pvj                 | 1.6.4              | ProjectVibrantJourneys-1.12.2-1.6.4.jar            | None      |
       | L     | reforged            | 0.7.5              | Reforged-Mod-1.12.jar                              | None      |
       | L     | seedprotect         | 1.2.0              | Seedprotect-1.12.2-1.2.0.jar                       | None      |
       | L     | sit                 | v1.3               | Sit-1.12.2-v1.3.jar                                | None      |
       | L     | soundphysics        | 1.0.4              | Sound-Physics-1.12.2.jar                           | None      |
       | L     | streams             | 0.4.8              | Streams-1.12-0.4.8.jar                             | None      |
       | L     | surge               | 2.0.77             | Surge-1.12.2-2.0.77.jar                            | None      |
       | L     | treecapitator       | 1.43.0             | TreeCapitator-client-1.43.0.jar                    | None      |
       | L     | vanillafix          | 1.0.10-150         | VanillaFix-1.0.10-150.jar                          | None      |
       | L     | kiwi                | 0.5.3.32           | Kiwi-1.12.2-0.5.3.32.jar                           | None      |
       | L     | cuisine             | 0.5.21-build920    | Cuisine-0.5.21-build920.jar                        | None      |
       | L     | vanillafoodpantry   | 4.3.1              | Vanillafoodpantry-mc1.12.2-4.3.1.jar               | None      |
       | L     | rtg                 | 6.1.0.0-snapshot.1 | RTG-1.12.2-6.1.0.0-snapshot.1.jar                  | None      |
       | L     | snowrealmagic       | 0.3.3              | SnowRealMagic-0.3.3.jar                            | None      |
       | L     | solcarrot           | 1.8.3              | Solcarrot-1.12.2-1.8.3.jar                         | None      |
  Loaded coremods (and transformers): FarseekCoreMod (Farseek-1.12-2.5.jar)
                                        farseek.core.FarseekClassTransformer
                                      TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
                                        
                                      MZZLoadingPlugin (MakeZoomZoom-0.0.4.jar)
                                        xyz.ajp.makezoomzoom.asm.MZZClassTransformer
                                      ItemPatchingLoader (ItemPhysic_Full_1.4.32_mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (Foamfix-0.10.8-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      JechCore (JustEnoughCharacters-1.12.0-3.4.3.jar)
                                        me.towdium.jecharacters.core.JechClassTransformer
                                      RandomPatches (Randompatches-1.12.2-1.19.1.1.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      LittlePatchingLoader (LittleTiles_v1.5.0-pre199_19_mc1.12.2.jar)
                                        com.creativemd.littletiles.LittleTilesTransformer
                                      CreativePatchingLoader (CreativeCore_v1.10.10_mc1.12.2.jar)
                                        
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      LoadingPlugin (Chunk-Animator-Mod-1.12.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
                                      CoreModLoader (Sound-Physics-1.12.2.jar)
                                        com.sonicether.soundphysics.CoreModInjector
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.91' Renderer: 'GeForce MX250/PCIe/SSE2'
  Suspected Mods: Unknown
  Launched Version: HMCL 3.2.149
  LWJGL: 2.9.4
  OpenGL: GeForce MX250/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.91, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: Custom Sky (No stars at daytime).zip
  Current Language: 简体中文 (中国)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz

**Comment by OreCruncher** [comment]
There is another mod that may be using an older version of Mixin.  Make sure all your mods are up to date.

**Comment by OreCruncher** [comment]
I am changing DS to use MixinBootstrap for Mixin.

**Comment by OreCruncher** [comment]
Posted 3.6.2.0 to CurseForge as BETA.  MixinBoostrap will also need to be installed.
