### ISSUE TITLE
Crash With Recurrent Complex and Ruins

### ISSUE THREAD

**Issue by TheVisionaryOne** [OreCruncher/DynamicSurroundings#563]
**Mod Version:**

DynamicSurroundings-1.12.2-3.6.0.2 (core mods in my pack use an older version of mixin than the latest 1.12.2 DynamicSurroundings build).

**Forge Version:**

14.23.5.2487

**Link to client log:**

https://pastebin.com/eZTe7rgL (shortened to just what happened after I joined the world, since the full log was too long for pastebin's size limit)

**Link to crash log:**

https://pastebin.com/BFQUyD62

**Description:**

I just added Dynamic Surroundings to my pack, and the game loaded fine, but crashed on the creation of a new world. My pack never crashes on world creation/join, so this is definitely tied to the addition of Dynamic Surroundings. I've also never seen Recurrent Complex or Ruins be listed as the culprit of a crash until this one, which is interesting.

I did notice that Recurrent Complex and Ruins both loaded multiple chunks to generate structures right before it crashed, so it could be tied to that.

I hate to be that guy, but this crash is indeed currently part of a private kitchen sink pack of 250 mods (on the nose). It's an RPG-themed pack, and I am intently developing it, tweaking configs, creating new structures, etc., and I am planning on releasing it to the public once it's been fully developed. But there's no available CurseForge page for the pack at the moment. I could drop a link to the modpack's .zip on DropBox, if that'd be helpful.

**Comment by OreCruncher** [comment]
Unfortunately this has nothing to do with DS specifically.  This crash happens during world gen on the server thread.  Though DS does have a server side piece with the 1.12.2 the logic has absolutely nothing to do with world gen.  It could be that the addition of DS altered startup timing a bit which exposed this particular issue.
