### ISSUE TITLE
Not Loading Game Issue With LiteLoader?

### ISSUE THREAD

**Issue by Zoombb** [OreCruncher/DynamicSurroundings#564]
**Mod Version:**

DynamicSurroundings-1.12.2-3.6.1.0

**Forge Version:**

tried first with 
14.23.5.2847
and then with latest as well
14.23.5.2854

**Link to client log:**

https://pastebin.com/4C3rPSx7

**Link to crash log:**

no crash, game couldn't load

**Description:**

I installed OreLib-1.12.2-3.6.0.1 and the mod but game won't start. If I remove the mod it starts. As far as I can read the log I see LiteLoader mentioned. I have LiteLoader installed no issues with it. I tried updating the installation but no luck.

**Comment by OreCruncher** [comment]
This mixin crap is becoming a pain.  Does this happen with the 3.6.0.2 version of Dynamic Surroundings?  If not, then you have another mod that is using Mixin that is pre 0.8.  Make sure all your mods are updated to the latest versions.

**Comment by OreCruncher** [comment]
Changing DS to use MixinBootstrap for Mixin.

**Comment by OreCruncher** [comment]
Posted 3.6.2.0 to CurseForge as BETA.  MixinBoostrap will also need to be installed.
