### ISSUE TITLE
Doesn't work in server but works in single player

### ISSUE THREAD

**Issue by 2zl** [OreCruncher/DynamicSurroundings#565]
**Mod Version:**

1.12.2-0.9.6

**Forge Version:**

forge-1.12.2-14.23.5.2854

**Link to client log:**

attached
[latest.log](https://github.com/OreCruncher/DynamicSurroundings/files/4557768/latest.log)

**Description:**

The mod just doesn't work on my server but when I use it in single player it works fine i have no clue why this is the case. Sorry for not having enough info

**Comment by 2zl** [comment]
just realised i uploaded this to dynamic surroundings not trees sorry

**Comment by OreCruncher** [comment]
No worries.  I will go ahead and close out.
