### ISSUE TITLE
Crash on Startup with TickCentral Installed

### ISSUE THREAD

**Issue by CactusDuud** [OreCruncher/DynamicSurroundings#569]
**Mod Version:** 3.6.1.0
**Forge Version:** 14.23.5.2854

**Link to client log:** https://pastebin.com/xF1ZK2VN
**Link to crash log:** none

**Description:**
Startup crash. Originally from a personal modpack, narrowed it down to DS and [TickCentral ](https://www.curseforge.com/minecraft/mc-mods/tickcentral/)(a coremod for [LagGoggles](https://www.curseforge.com/minecraft/mc-mods/laggoggles)) not playing nice.

**Comment by OreCruncher** [comment]
Have you tried version 3.6.0.2 of Dynamic Surroundings?  Reason I ask is that the 3.6.1.0 version uses mixin version 0.8 whereas 3.6.0.2 uses 0.7.11.

**Comment by CactusDuud** [comment]
Unfortunately I'm using another mod that requires Mixin 0.8, when I get the chance I'll try that.

If it ends up being Mixin version incompatibility, I'll probably move this issue to LagGoggles instead.

**Comment by OreCruncher** [comment]
I am changing DS to depend on MixinBootstrap for Mixin support.

**Comment by OreCruncher** [comment]
Posted 3.6.2.0 to CurseForge as BETA.  MixinBoostrap will also need to be installed.
