### ISSUE TITLE
missing grass support for fireflies

### ISSUE THREAD

**Issue by Hypsellis** [OreCruncher/DynamicSurroundings#57]
The AbyssalCraft, Botania, RandomThings, Tinker's Construct, Natura and Betweenlands grasses still don't support fireflies. :(

**Comment by OreCruncher** [comment]
The firefly effect is tied to specific grasses/plants and is not generalized.  Also, fireflies are limited to biomes that have some level of humidity and isn't too hot.  For example, desert/arid biomes/hot will not have the firefly effect.

AbyssalCraft - I elected not to add firefly effects to that grass.  The AbyssalCraft biomes in Overworld have an end particle effect and it would seem to be a bit much.

Botania - flowers already have a shimmering/spark particle effect.  Not aware of any other grass.

Tinkers slime grass - to me it didn't right to have firefly particles.

Natura - don't see grass as part of the mod.  It does have shrooms and crops - I avoid tying fireflies to those.

Betweenlands - not there yet.  I been looking at that mod and it's on my list to provide support.

This being said I am looking at increasing the frequency of fireflies from Vanilla items.  Just need to figure out a good way to balance it against having BoP installed.

**Comment by Hypsellis** [comment]
So why not give the choice in the config for adding manually the grass for supporting fireflies ?

**Comment by OreCruncher** [comment]
[You can do that already using external configuration files.](https://github.com/OreCruncher/DynamicSurroundings/wiki/Tutorial:-Configuration-Files)

**Comment by Hypsellis** [comment]
Okay thanks, I will look at it. ;)

**Comment by OreCruncher** [comment]
I'm increasing the spawn rate of fireflies for the Vanilla red, yellow, and double tall plants.  Should be about 40% more frequent.

**Comment by Hypsellis** [comment]
Oh I don't think it's the good place for asking about that, but I tried to add my own config for supporting other grass for fireflies you won't support. But the condition doesn't work, I get fireflies all the time :(
https://pastebin.com/jnakNHj4

**Comment by OreCruncher** [comment]
Try this condition string: "weather.isNotRaining && isNight && !biome.isDry && ONEOF(biome.temperature,'mild','warm')"

And the chance is low.  Essentially it says 1 in 10.  Try something like 30-40.

**Comment by Hypsellis** [comment]
Oh wait it works now, I made made an error in the condition, I had written "isNotRaining" instead of "weather.isNotRainning".

**Comment by Hypsellis** [comment]
Oh wait the chance is reversed, more the value is high, less there are fireflies.

**Comment by OreCruncher** [comment]
Yep

**Comment by Hypsellis** [comment]
It's not really normal. ^^'

**Comment by Hypsellis** [comment]
Anyway I still think you give a support for all the grasses I put in my own external config. ;)

**Comment by OreCruncher** [comment]
Posted a BETA to CurseForge that increases the number of fireflies around Minecraft flowers.  Regular Minecraft "tallgrass" does not have this block effect.  Other modded plants will be handled via mod support.
