### ISSUE TITLE
Excessive frost breath

### ISSUE THREAD

**Issue by DemonfangArun** [OreCruncher/DynamicSurroundings#572]
Forge: x.2854 (1.12)
Dsurround: 3.6.1.0

Frost breath used to have a nice pulsing, now it's just a constant stream of particles.

**Comment by OreCruncher** [comment]
@DemonfangArun Sorry it took so long to get to this.  I am not able to duplicate this issue.  What modpack are (were) you using?

**Comment by DemonfangArun** [comment]
Unfortunately I no longer play minecraft, and the pack in use is no longer available.
