### ISSUE TITLE
Animania 2.0.0

### ISSUE THREAD

**Issue by Tschipp** [OreCruncher/DynamicSurroundings#573]
It pains me to say that we have done a major refactor of the animania codebase on our end, moving to a new addon-based system.
I promise that this will be the final major refactor that we will do (I sure as hell don't want to do another one).

You will probably need to update the imports, but other than that mostly everything should be the same. 

In other news, thanks to Jared we now have Animania on a maven.
Using
```
repositories {
	maven {
		url "https://maven.blamejared.com/"
	}
}

dependencies {
        deobfCompile "com.animania:animania-1.12.2-base:2.0.0.15"
        deobfCompile "com.animania:animania-1.12.2-farm:1.0.0.15"
        deobfCompile "com.animania:animania-1.12.2-extra:1.0.0.15"
}
```
you can get the most recent versions for the addons. Note though, that these versions are not publically released yet, so you might not want to update yet. I will report back when these versions are publicly available on CF.
Please let me know if I can be of assistance.

**Comment by spruill7716** [comment]
Was there ever a fix to this? Both of these mods are great. It's a shame you can't play them both simultaneously.

**Comment by Tschipp** [comment]
No, this is exactly what I'm talking about in this issue.

**Comment by spruill7716** [comment]
> No, this is exactly what I'm talking about in this issue.

I see the author is still active and has been replying recently to some other threads. All we can do is wait for a response.

**Comment by Tschipp** [comment]
I know. I'd also gladly help (with a PR) if they want that.

**Comment by OreCruncher** [comment]
@Tschipp Hey!  If you want to make a PR please do so.  I am planning on carving out some time this weekend to do some maintenance on my 1.12.x release and could include.

**Comment by Tschipp** [comment]
Ok I‘ll try to get it done asap. I‘m also very short on time but it would be good if we could get this fixed.

**Comment by Tschipp** [comment]
@OreCruncher I'm having trouble setting up the workspace. Are you using some other version of OreLib? There's a few missing imports for me. Could you add me on discord? Tschipp#3159

**Comment by OreCruncher** [comment]
Posted 3.6.2.0 to CurseForge as BETA.  MixinBoostrap will also need to be installed.
