### ISSUE TITLE
Crash on Startup "Error: java.lang.NoSuchMethodError: "

### ISSUE THREAD

**Issue by ShootingStar0312** [OreCruncher/DynamicSurroundings#577]
Mod Version: 3.6.1.0.

Forge Version: 14.23.5.2854

https://hastebin.com/riqofocame.md Client Log

https://hastebin.com/wonuvekiqa.bash Crash Log

Description:
I tried Installing dynamic surroundings the other day, with no success, I am not using a modpack but rather made one myself, or better said just downloaded a bunch of mods, and in the loading phase of minecraft after the crash the following message appears

"The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: net.minecraftforge.common.capabilities.Capability$IStorage.writeNBT(Lnet/minecraftforge/
common/capabilities/Capability;Ljava/lang/Object;Lnet/minecraft/util/EnumFacing;)Lnet/minecraft/
nbt/NBTBase;"

Description of the problem.

I recently added the mod to my collection
I experienced no prior crashes 
No mods have been updated
yes sadly this is a home kitchen sink with lots of mods, and no official modpack

**Comment by OreCruncher** [comment]
Try DS 3.6.0.2 and let me know if it works.

**Comment by ShootingStar0312** [comment]
> Try DS 3.6.0.2 and let me know if it works.

yes it did work, thank you :D

**Comment by OreCruncher** [comment]
OK.  I suspect there is a mod in your pack that is using Mixin 0.7.11.  The 3.6.1.0 version of DS uses version 0.8 - the stable build for 1.12.2.
