### ISSUE TITLE
crash at forge loading screen

### ISSUE THREAD

**Issue by Milky435** [OreCruncher/DynamicSurroundings#578]
**Mod Version:**

3.5.4.3

**Forge Version:**

14.23.5.2854

**Link to client log:**

https://hastebin.com/lubugupoci.md

**Link to crash log:**

https://hastebin.com/uyajodegun.sql

**Description:**

it crashes when i have the mod in my mods folder

**Comment by OreCruncher** [comment]
You need to update Dynamic Surroundings to either 3.6.0.2 or 3.6.1.0.

**Comment by Milky435** [comment]
> You need to update Dynamic Surroundings to either 3.6.0.2 or 3.6.1.0.

its fixed now thanks
