### ISSUE TITLE
Not Finding Config File

### ISSUE THREAD

**Issue by benjamindobbs** [OreCruncher/DynamicSurroundings#582]
**Mod Version:**

The version that is installed in your pack.
3.6.1.0
**Forge Version:**

The actual Forge version - "latest" does not count.
14.23.5.2854
**Link to client log:**

Even of there is a crash log, the client log can provide the necessary context for why the exception occured.  You can use a service like [pastebin](https://pastebin.com) or [hastebin](https://hastebin.com) to upload the log, and paste the link here.  The log file is called latest.txt and can be found in your logs folder.
https://hastebin.com/vemokalugo.md
**Link to crash log:**

The callstacks in the log will help pinpoint the actors involved in the crash and give a developer a pointer in the code where to start looking at the problem.  You can use a service like [pastebin](https://pastebin.com) or [hastebin](https://hastebin.com) to upload the log, and paste the link here.

**Description:**

Description of the problem.  In the case of crashes, it is good to know things like the following:
I added a json file in the same directory as the dssurround.cfg. I don't see any verification that this file is being found. Anything I put in the file does not get updated in game.
* Did you just add the mod to a pack?
No
* Did it just start crashing, or has it always crashed?
No crashes
* Did you update any other mods in your pack and it started crashing?  This includes Forge.
No
* If updating multiple mods did you update one by one or all at once?  To help narrow the problem down adding one by one is helpful.
No
* Is the modpack you are using available online somewhere?  If the crash is due to mod interaction having the pack available makes things much easier.  It is much harder to work these types of issues with a private kitchen sink pack containing 250 mods.
It's on Twitch, here is the [zip](https://drive.google.com/file/d/1nuJfdmC1Kf0zWL8W1vKniTLLb4nlCtng/view?usp=sharing)

**Comment by xemnes** [comment]
im having the exact same issue, i have created a "modified.json" in the dsurround config folder then added it to the config file
```
    # Configuration files for customization [default: ]
    S:"External Configuration Files" <
        modified.json
     >
```

console shows no indication of it being loaded, and none of my settings actually do anything.

**Comment by OreCruncher** [comment]
I am not able to repro the problem.  I will be adding additional diagnostics to the routine to see if it can be figured out.

**Comment by xemnes** [comment]
i was doing a lot of playing around, its inconsistent. im trying to change the fog for the "underground" biome but it just doesnt work, but if i set specific nether biome fogs (from biomesoplenty) it seems to work.

**Comment by xemnes** [comment]
update: now my nether biome fog settings arent working correctly or is inconsitent, its just black fog wherever i am in the nether. i cant figure out whether something in the mod is overriding it as theres no way of indicating whether a config might be.

**Comment by OreCruncher** [comment]
Posted 3.6.2.0 to CurseForge as BETA.  MixinBoostrap will also need to be installed.
