### ISSUE TITLE
Log flood: "Fog calculator 'MorningFogRangeCalculator' has invalid results"

### ISSUE THREAD

**Issue by Krutoy242** [OreCruncher/DynamicSurroundings#583]
**Mod Version:** 1.12.2-3.6.1.0
**Forge Version:** 14.23.5.2847
**Link to client log:** https://gist.github.com/Krutoy242/89f2104bedf541ae8046f9b4f55d354a

**Description:**
Playing with DynamicSurroundings a while, but recently found, that my `latest.log` and `debug.log` overfilled with 6500 lines of same warning:
```java
[Client thread/WARN] [dsurround]: Fog calculator 'MorningFogRangeCalculator' has invalid results (start 11.000000, end 8.815777); ignoring
```
Whats wrong and how to remove this flood from logs?

**Comment by OreCruncher** [comment]
Posted 3.6.2.0 to CurseForge as BETA.  MixinBoostrap will also need to be installed.
