### ISSUE TITLE
Crash on startup, log says something about mixin

### ISSUE THREAD

**Issue by dzahlus** [OreCruncher/DynamicSurroundings#584]
**Mod Version:**
3.6.1.0
The version that is installed in your pack.

**Forge Version:**
14.23.5.285
The actual Forge version - "latest" does not count.

**Link to client log:**
https://pastebin.com/KF8cCzM4
Even of there is a crash log, the client log can provide the necessary context for why the exception occured.  You can use a service like [pastebin](https://pastebin.com) or [hastebin](https://hastebin.com) to upload the log, and paste the link here.  The log file is called latest.txt and can be found in your logs folder.

**Link to crash log:**
https://pastebin.com/g2PmBWTS
The callstacks in the log will help pinpoint the actors involved in the crash and give a developer a pointer in the code where to start looking at the problem.  You can use a service like [pastebin](https://pastebin.com) or [hastebin](https://hastebin.com) to upload the log, and paste the link here.

**Description:**
Crash on startup with dynamic surroundings installed. Doesn't crash at all without it
Description of the problem.  In the case of crashes, it is good to know things like the following:

* Did you just add the mod to a pack? 
yes

* Did it just start crashing, or has it always crashed? 
always crashed

* Did you update any other mods in your pack and it started crashing?  This includes Forge. 
modpack was built on the latest versions of all listed mods

* If updating multiple mods did you update one by one or all at once?  To help narrow the problem down adding one by one is helpful. 
see above

* Is the modpack you are using available online somewhere?  If the crash is due to mod interaction having the pack available makes things much easier.  It is much harder to work these types of issues with a private kitchen sink pack containing 250 mods.
sorry not yet atleast

**Comment by OreCruncher** [comment]
Make sure *all* your mods are up to date in your pack.  One of them is using a Mixin version different from DS 3.6.1.0.  For example, the version of Vanilla Fix you have is using an older version and it needs to be updated.

**Comment by dzahlus** [comment]
Damn fast reply.

I updated vanilla fix to ver 100 and that fixed it!

Thanks alot love your mod.
