### ISSUE TITLE
Crash on accessing navigation block in advanced rocketry, while rocket is built.

### ISSUE THREAD

**Issue by FluffyCloud** [OreCruncher/DynamicSurroundings#585]
**Mod Version:**

DynamicSurroundings-1.12.2-3.6.0.2.jar

**Forge Version:**

forge-14.23.5.2847

**Link to client log:**

ahh, don't have it.

**Link to crash log:**

I get this:
https://hastebin.com/odusefazox.rb
followed by half a dozen of this:
https://hastebin.com/ubogudolom.rb

before the client actually quits.  i think the multiple crashes is 'VanillaFix' trying to let us continue after the first exception.

**Description:**

Advanced Rocketry has a block called the Navigation Computer that you add to a rocket.  when the rocket is built, you can enter the rocket, hit 'c' to open the rockets gui, which brings up a panel with 2 squares with blocks in them, one is the station bay, and the other is the navigation computer.  if you click the nav computer, the client crashes.

In the case of crashes, it is good to know things like the following:

* Did you just add the mod to a pack? no
* Did it just start crashing, or has it always crashed? always crash, every time.
* Did you update any other mods in your pack and it started crashing?  has been happening since adv rocketry was added to the pack, as before, we couldn't build a rocket and try to access the nav computer.
* If updating multiple mods did you update one by one or all at once?  To help narrow the problem down adding one by one is helpful.
* Is the modpack you are using available online somewhere?  MC Eternal version 1.3.7.1 (also happened in 1.3.7 and 1.3.6 i think, since they added adv. rocketry to the pack)

**Comment by OreCruncher** [comment]
Yeah - something is in a bad state where the player information in the Minecraft world is missing.  Not sure what the cause is.  I am adding defensive code to protect DS.

**Comment by OreCruncher** [comment]
Posted 3.6.2.0 to CurseForge as BETA.  MixinBoostrap will also need to be installed.
