### ISSUE TITLE
[Enhancement] Support for The Betweenlands mod

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/DynamicSurroundings#59]
Provide built in support for items and biomes in The Betweenlands mod.

**Comment by Hypsellis** [comment]
I add to the list all these dimensions:
- The Abyssal Wasteland (AbyssalCraft)
- The Dreadlands (AbyssalCraft)
- The Omothol (AbyssalCraft)
- The Dark Real (AbyssalCraft)
- The Deep Dark (ExtraUtilities)
- The Underworld (LightningCraft)
- Tyros (FuturePack)
- Menelaus (FuturePack)
- The Abyss (Ad Inferos)
- The Wyvern Lair (MoCreatures)

I could add to the list the Aether and the Outer Lands from Thaumcraft, but they still didn't update for 1.10.2.

**Comment by Hypsellis** [comment]
I add the Aether to the list now it updated for 1.10.2

**Comment by OreCruncher** [comment]
Now that Betweenlands is released....

**Comment by OreCruncher** [comment]
Pushed v3.4.9.4 to CurseForge.
