### ISSUE TITLE
Massive log spam "Attaching capabilities to world [the_nether]", debug.log growing at 1KB/second from it

### ISSUE THREAD

**Issue by aaronhowser1** [OreCruncher/DynamicSurroundings#590]
**Mod Version:**

DynamicSurroundings-1.12.2-3.6.1.0

**Forge Version:**

14.23.5.2847

**Link to client log:**
The part that is repeating:
```
[11:47:22] [Client thread/INFO] [dsurround]: Attaching capabilities to world [the_nether] (CLIENT)
[11:47:22] [Client thread/INFO] [dsurround]: DimensionInfo{id=0, name=the_nether, seaLevel=63, cloudHeight=128, skyHeight=256, haze=true, aurora=true, weather=true, fog=true}
```
The debug.log is 16 MB, and grows a KB every second while the game is running. Both are too large for pastebin.
[debug.log](https://github.com/OreCruncher/DynamicSurroundings/files/5184081/debug.log)
[latest.log](https://github.com/OreCruncher/DynamicSurroundings/files/5184082/latest.log)

**Description:**
![image](https://user-images.githubusercontent.com/15698722/92407483-4ea5bc80-f100-11ea-8206-f14562979aae.png)
![image](https://user-images.githubusercontent.com/15698722/92407514-64b37d00-f100-11ea-8fb6-a97bea5f29be.png)

**Comment by OreCruncher** [comment]
It's because a mod is more than likely creating temporary worlds (client side) repeatedly just to discard.  That message gets logged when the attach capability event fires for a world.  I have seen some mods do this because they create entities that exist only client side and then discard.  I could remove that log statement, but then I would not have *any* message emitted when  capabilities are attached.  Trick here is finding that mod that is doing this and finding out why.

**Comment by aaronhowser1** [comment]
A stopgap could be a config to disable this log, maybe

**Comment by aaronhowser1** [comment]
Here's a mod list, if you think it would be useful

- AdvancedRocketry-1.12.2-1.7.0-232-universal.jar                       
- AE2WTLib-1.12.2-1.0.34.jar                                            
- aerialaffinity-1.2.jar                                                
- AgriCraft-2.12.0-1.12.0-a6.jar                                        
- AkashicTome-1.2-12.jar                                                
- AppleSkin-mc1.12-1.0.14.jar                                           
- appliedenergistics2-rv6-stable-7.jar                                  
- AttributeFix-1.12.2-1.0.4.jar                                         
- AutoRegLib-1.3-32.jar                                                 
- Avaritia-1.12.2-3.3.0.33-universal.jar                                
- BackpackBaubles-0.2.0.jar                                             
- base-1.12.2-3.13.0.jar                                                
- Baubles-1.12-1.5.2.jar                                                
- bdlib-1.14.3.12-mc1.12.2.jar                                          
- beebetteratbees-1.12.2-2.0.3.jar                                      
- BetterAdvancements-1.12.2-0.1.0.77.jar                                
- BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar                       
- BetterFps-1.4.8.jar                                                   
- BetterMineshaftsForge-1.12.2-2.0.1.jar                                
- BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar                         
- Biome_Bundle-1.12.2-v6.1.jar                                          
- Biome_Bundle_O_Plenty-1.12.2_v1.0.jar                                 
- BloodMagic-1.12.2-2.4.3-105.jar                                       
- Bookshelf-1.12.2-2.3.590.jar                                          
- Botania r1.10-363.jar                                                 
- BuildingGadgets-2.8.4.jar                                             
- capabilityadapter-1.1.0.jar                                           
- Chameleon-1.12-4.1.3.jar                                              
- Charm-1.12.2-1.3.7.jar                                                
- Chisel-MC1.12.2-1.0.2.45.jar                                          
- chiselsandbits-14.33.jar                                              
- CodeChickenLib-1.12.2-3.2.3.358-universal.jar                         
- CoFHCore-1.12.2-4.6.6.1-universal.jar                                 
- CoFHWorld-1.12.2-1.4.0.1-universal.jar                                
- colorfulhealthbar-0.0.4a.jar                                          
- CommonCapabilities-1.12.2-2.4.7.jar                                   
- CompactDrawers-1.12.2-1.0.5.125.jar                                   
- compactmachines3-1.12.2-3.0.18-b278.jar                               
- ContentTweaker-1.12.2-4.9.1.jar                                       
- Controlling-3.0.10.jar                                                
- craftdumper-1.12.2-1.3.0.jar                                          
- craftingstation-0.1.7c.jar                                            
- CraftPresence-1.12.2-1.6.1.jar                                        
- CraftTweaker2-1.12-4.1.20.586.jar                                     
- CTM-MC1.12.2-1.0.2.31.jar                                             
- Cucumber-1.12.2-1.1.3.jar                                             
- CustomMainMenu-MC1.12.2-2.0.9.1.jar                                   
- CyclopsCore-1.12.2-1.6.6.jar                                          
- DarkoHatesBounces-1.12.2-1.0.0.jar                                    
- DarkUtils-1.12.2-1.8.230.jar                                          
- deepmoblearning-1.12.2-2.5.4-universal.jar                            
- denseneutroncollectors-1.1.jar                                        
- diethopper-1.1.jar                                                    
- DynamicSurroundings-1.12.2-3.6.1.0.jar                                
- EnchantmentDescriptions-1.12.2-1.1.15.jar                             
- EnderCore-1.12.2-0.5.76.jar                                           
- EnderIO-1.12.2-5.2.59.jar                                             
- EnderIO-endergy-1.12.2-5.2.59.jar                                     
- EnderStorage-1.12.2-2.4.6.137-universal.jar                           
- energyconverters_1.12.2-1.3.7.30.jar                                  
- engineers_doors-1.12.2-0.9.1.jar                                      
- environmentaltech-1.12.2-2.0.20.1.jar                                 
- ExtendedCrafting-1.12.2-1.5.6.jar                                     
- extrautils2-1.12-1.9.9.jar                                            
- FancyBlockParticles-1.12.x-2.4.1.jar                                  
- FastFurnace-1.12.2-1.3.1.jar                                          
- FastWorkbench-1.12.2-1.7.3.jar                                        
- foamfix-0.10.10-1.12.2.jar                                            
- forestry_1.12.2-5.8.2.387.jar                                         
- Forgelin-1.8.4.jar                                                    
- ForgeMultipart-1.12.2-2.6.2.83-universal.jar                          
- FpsReducer-mc1.12.2-1.18.jar                                          
- framedcompactdrawers-1.2.7.jar                                        
- FTBBackups-1.1.0.1.jar                                                
- FTBLib-5.4.7.2.jar                                                    
- FTBQuests-1.9.0.12.jar                                                
- ftbtracker-1.0.jar                                                    
- FTBUltimine-1.12-1.3.4.jar                                            
- FTBUtilities-5.4.1.130.jar                                            
- GameStages-1.12.2-2.0.123.jar                                         
- gendustry-1.6.5.8-mc1.12.2.jar                                        
- gendustryjei-1.0.2.jar                                                
- geneticsreborn-1.12-1.29.jar                                          
- Guide-API-1.12-2.1.8-63.jar                                           
- hooked-1.0.3.jar                                                      
- ikwid-1.0.2.jar                                                       
- ImmersiveEngineering-0.12-98.jar                                      
- immersivepetroleum-1.12.2-1.1.9.jar                                   
- industrialcraft-2-2.8.220-ex112.jar                                   
- infinitylib-1.12.0.jar                                                
- IntegratedCrafting-1.12.2-1.0.10.jar                                  
- IntegratedDynamics-1.12.2-1.1.9.jar                                   
- integratednbt-1.12.2-1.2.1.jar                                        
- IntegratedTerminals-1.12.2-1.0.14.jar                                 
- IntegratedTunnels-1.12.2-1.6.12.jar                                   
- InventoryTweaks-1.63.jar                                              
- ItemFilters-1.0.4.2.jar                                               
- jeibees-0.9.0.5-mc1.12.2.jar                                          
- jeivillagers-1.12-1.0.2.jar                                           
- jei_1.12.2-4.16.1.301.jar                                             
- jetif-1.12.2-1.5.1.jar                                                
- journeymap-1.12.2-5.7.1.jar                                           
- JustEnoughCalculation-1.12.2-3.2.3.jar                                
- JustEnoughEnergistics-1.12.2-1.0.8.jar                                
- JustEnoughPetroleum-0.1.jar                                           
- JustEnoughResources-1.12.2-0.9.2.60.jar                               
- justthetips-1.12-1.0.1.1.jar                                          
- KleeSlabs_1.12.2-5.4.12.jar                                           
- KubeJS-forge-1.12.2-1.1.0.63.jar                                      
- LagGoggles-1.12.2-5.8-132.jar                                         
- lazy-ae2-1.12.2-1.1.21.jar                                            
- legiblenei-1.12.2-1.6.12.10.jar                                       
- letsencryptcraft-1.10.2-1.2.0.jar                                     
- libnine-1.12.2-1.1.9.jar                                              
- librarianlib-1.12.2-4.22.jar                                          
- LibVulpes-1.12.2-0.4.2-75-universal.jar                               
- llibrary-1.7.19-1.12.2.jar                                            
- logisticspipes-0.10.3.62.jar                                          
- lostcities-1.12-2.0.22.jar                                            
- MAGE-0.2.4.jar                                                        
- MagicBees-1.12.2-3.1.10.jar                                           
- mahoutsukai-1.12.2-v1.19.20.jar                                       
- mcjtylib-1.12-3.5.4.jar                                               
- MCMultiPart-2.5.3.jar                                                 
- Mekanism-1.12.2-9.8.3.390.jar                                         
- MekanismGenerators-1.12.2-9.8.3.390.jar                               
- MekanismTools-1.12.2-9.8.3.390.jar                                    
- MetalChests-v6.1.0+mc1.12.2.jar                                       
- MineTogether-1.12.2-1.12.2-2.3.2.jar                                  
- minicoal-1.12.2-1.0.jar                                               
- MmmMmmMmmMmm-1.12-1.14.jar                                            
- modnametooltip_1.12.2-1.10.1.jar                                      
- mods.txt                                                              
- modtweaker-4.0.18.jar                                                 
- moreoverlays-1.15.1-mc1.12.2.jar                                      
- MouseTweaks-2.10-mc1.12.2.jar                                         
- mowziesmobs-1.5.8.jar                                                 
- MrTJPCore-1.12.2-2.1.4.43-universal.jar                               
- MTLib-3.0.6.jar                                                       
- mysticallib-1.12.2-1.9.0.jar                                          
- mysticalworld-1.12.2-1.9.1.jar                                        
- NaturesCompass-1.12.2-1.8.5.jar                                       
- NetherPortalFix_1.12.1-5.3.17.jar                                     
- NuclearCraft-2o.4.0-1.12.2.jar                                        
- OpenComputers-MC1.12.2-1.7.5.192.jar                                  
- OpenTerrainGenerator-1.12.2_-_v9.0_r10.jar                            
- OreLib-1.12.2-3.6.0.1.jar                                             
- overloadedarmorbar-1.0.4g.jar                                         
- p455w0rdslib-1.12.2-2.3.161.jar                                       
- Patchouli-1.0-21.jar                                                  
- phosphor-1.12.2-0.2.6+build50-universal.jar                           
- Placebo-1.12.2-1.6.0.jar                                              
- pneumaticcraft-repressurized-1.12.2-0.11.15-398.jar                   
- prefab-1.3.0.26.jar                                                   
- PrettyBeaches_1.12.2-1.0.4.jar                                        
- ProjectRed-1.12.2-4.9.4.120-Base.jar                                  
- ProjectRed-1.12.2-4.9.4.120-integration.jar                           
- ProjectRed-1.12.2-4.9.4.120-lighting.jar                              
- QMD-0.9.3-1.12.2.jar                                                  
- Quark-r1.6-179.jar                                                    
- QuarkOddities-1.12.2.jar                                              
- rats-3.2.14-1.12.2.jar                                                
- RebornCore-1.12.2-3.19.4.529-universal.jar                            
- RecipeStages-1.1.3.jar                                                
- RedstoneFlux-1.12-2.1.1.1-universal.jar                               
- ResourceLoader-MC1.12.1-1.5.3.jar                                     
- ResourceReloader-1.0.2.5.jar                                          
- rftools-1.12-7.73.jar                                                 
- rftoolsdim-1.12-5.71.jar                                              
- Simple-Void-World-1.12-1.2.0.9-universal.jar                          
- simpletrophies-1.2.2.1.jar                                            
- smooth-scrolling-everywhere-1.1.jar                                   
- SmoothFont-mc1.12.2-2.1.2.jar                                         
- somnia-1.9.7.jar                                                      
- Sound-Physics-1.12.2-1.0.9.jar                                        
- StorageDrawers-1.12.2-5.4.2.jar                                       
- supersoundmuffler-revived_1.12.2_1.0.2.10.jar                         
- Surge-1.12.2-2.0.77.jar                                               
- TBone-v1.6.8+mc1.12.2.jar                                             
- Thaumcraft-1.12.2-6.1.BETA26.jar                                      
- ThaumicAugmentation-1.12.2-1.1.19.jar                                 
- thaumicbrewing-1.0.2.jar                                              
- ThaumicComputers-MC1.12.2-0.5.1.jar                                   
- thaumicenergistics-2.2.4.jar                                          
- ThaumicInventoryScanning_1.12.2-2.0.10.jar                            
- ThaumicJEI-1.12.2-1.6.0-27.jar                                        
- thaumicperiphery-0.3.1.jar                                            
- theoneprobe-1.12-1.4.28.jar                                           
- ThermalFoundation-1.12.2-2.6.7.1-universal.jar                        
- TickCentral-2.6.jar                                                   
- TipTheScales-1.12.2-1.0.4.jar                                         
- TombManyGraves-1.12-4.2.0.jar                                         
- topaddons-1.12.2-1.13.0.jar                                           
- UniDict-1.12.2-2.9.6.jar                                              
- unloader-1.2.0.jar                                                    
- valkyrielib-1.12.2-2.0.20.1.jar                                       
- VanillaFix-1.0.10-150.jar                                             
- Vanilla_Vistas 1.1.jar                                                
- WanionLib-1.12.2-2.4.jar                                              
- WirelessCraftingTerminal-1.12.2-3.12.97.jar                           
- xnet-1.12-1.8.2.jar                                                   
- YABBA-1.1.2.54.jar                                                    
- zenny3d.saturationoverflow-1.1.1.jar                                  
- zerocore-1.12.2-0.1.2.8.jar

**Comment by OreCruncher** [comment]
Posted 3.6.2.0 to CurseForge as BETA.  MixinBoostrap will also need to be installed.
