### ISSUE TITLE
Can't disable footsteps

### ISSUE THREAD

**Issue by bladebaka** [OreCruncher/DynamicSurroundings#591]
**Mod Version:**
3.4.9.17

**Forge Version:**
12.18.3.2511

**Description:**

Installed to deal with the sounds from Immersive Engineerings' Diesel Generators, but I can't figure out how to change footsteps to the regular sounds - any changes I made didn't seem to take hold.

**Comment by OreCruncher** [comment]
The latest version of DS is 3.6.1.0.  To disable DS footstep sounds go to the Volume Control page and set the Footstep slider to 0.

**Comment by bladebaka** [comment]
> The latest version of DS is 3.6.1.0. To disable DS footstep sounds go to the Volume Control page and set the Footstep slider to 0.

I can't seem to find a Volume Control page, with or without a Footstep slider. The closest thing I am able to find with the version available to me through the Twitch Age of Engineering profile is a Sound Options page  with a set of integer fields and true/false buttons. 
![image](https://user-images.githubusercontent.com/9071117/92746856-dd088100-f340-11ea-8d12-d76bbf615376.png)

**Comment by OreCruncher** [comment]
The Volume Controls in the regular Minecraft menus.

**Comment by demiena** [comment]
fix your mod.

**Comment by OreCruncher** [comment]
If you are going to comment please be constructive.  Not sure how your comment relates to this topic.
