### ISSUE TITLE
1.12.2 Crash

### ISSUE THREAD

**Issue by Basedgod199** [OreCruncher/DynamicSurroundings#593]
**Mod Version:**

The version that is installed in your pack: DynamicSurroundings-1.12.2-3.6.1.0

**Forge Version:**

The actual Forge version - "latest" does not count: Forge-1.12.2-14.23.5.2847

**Link to client log:**

Even of there is a crash log, the client log can provide the necessary context for why the exception occured.  You can use a service like [pastebin](https://pastebin.com) or [hastebin](https://hastebin.com) to upload the log, and paste the link here.  The log file is called latest.txt and can be found in your logs folder: https://pastebin.com/8trEnun7

**Link to crash log:**

The callstacks in the log will help pinpoint the actors involved in the crash and give a developer a pointer in the code where to start looking at the problem.  You can use a service like [pastebin](https://pastebin.com) or [hastebin](https://hastebin.com) to upload the log, and paste the link here: https://pastebin.com/4ue7GExb

**Description:**

Description of the problem.  In the case of crashes, it is good to know things like the following:

* Did you just add the mod to a pack? No.
* Did it just start crashing, or has it always crashed? just started, it only happened once.
* Did you update any other mods in your pack and it started crashing?  This includes Forge. No.
* If updating multiple mods did you update one by one or all at once?  To help narrow the problem down adding one by one is helpful. N/A
* Is the modpack you are using available online somewhere?  If the crash is due to mod interaction having the pack available makes things much easier.  It is much harder to work these types of issues with a private kitchen sink pack containing 250 mods.
It's not publicly available just yet.

**Comment by OreCruncher** [comment]
How often does this crash happen?  Does it happen without Lag Goggles installed?

**Comment by Basedgod199** [comment]
I'll do some testing to see if it happens without laggoggles, but it only happened once

**Comment by OreCruncher** [comment]
OK. Based on the call stack it appears that a capability DS attaches to a world instance client side is not present.  Not sure how that could have happened.  Capabilities are normally attached during world instance creation.

**Comment by Basedgod199** [comment]
Okay so i've been trying to get it to happen again for the past day and it just won't happen again, so possibly just a one-off. You can go ahead and close this and if it happens again i'll make another report

**Comment by OreCruncher** [comment]
Going to put in some defensive code.

**Comment by OreCruncher** [comment]
Posted 3.6.2.0 to CurseForge as BETA.  MixinBoostrap will also need to be installed.
