### ISSUE TITLE
Game crashes when I remove the mod

### ISSUE THREAD

**Issue by demiena** [OreCruncher/DynamicSurroundings#597]
**Mod Version: **

3.6.10

**Forge Version:**
14.23.5.2854

**Link to client log:**

Even of there is a crash log, the client log can provide the necessary context for why the exception occured.  You can use a service like [pastebin](https://pastebin.com) or [hastebin](https://hastebin.com) to upload the log, and paste the link here.  The log file is called latest.txt and can be found in your logs folder.

**Link to crash log:**

There are no crash logs because Mojang was stupid enough to not make crash reports for unexpected issues.
**Description:**

Description of the problem.  In the case of crashes, it is good to know things like the following:

* Did you just add the mod to a pack? No...
* Did it just start crashing, or has it always crashed? It started crashing
* Did you update any other mods in your pack and it started crashing?  No...
* If updating multiple mods did you update one by one or all at once?  To help narrow the problem down adding one by one is helpful. No...
* Is the modpack you are using available online somewhere?  No...

**Comment by demiena** [comment]
PLSS!!! FIX THIS!!!!!! I CANNOT REMOVE THE MOD!!!!!

**Comment by demiena** [comment]
FIX YOUR MOD!!! **PLSSSS!!!**

**Comment by demiena** [comment]
wait nvm it fixed itself

**Comment by demiena** [comment]
NVM ITS BACK NANI?!?!?!!

**Comment by OreCruncher** [comment]
If you removed the mod how can it be my mod?  And you are sure there are no log files, like the forge log?

**Comment by TheFurryDevil** [comment]
Not an expert at all, but maybe DSurround causes Mixin 0.8 to load and when removed the next mod in load order has older Mixin and then again the next mods needs 0.8?

**Comment by david73754** [comment]
same issue for me. idk if i have any logs.

**Comment by OreCruncher** [comment]
That is why I need the logs to understand what is going on.  If they removed my mod it would not be a factor.  However, there could be another mod needing Mixin.  That information will be in the Forge log.

**Comment by demiena** [comment]
[latest.log](https://github.com/OreCruncher/DynamicSurroundings/files/5372967/latest.log)
do you need this?

**Comment by OreCruncher** [comment]
Yep that's it.  And it is Mixin like I was suspecting.  It is being triggered by SteveKunG's-Lib-1.12.2-1.1.9.jar.  You can try adding [MixinBootstrap ](https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap) to your pack to see if it helps.  If that continues to cause an issue, add [Mixin Compatibility](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility).

**Comment by OreCruncher** [comment]
Posted 3.6.2.0 to CurseForge as BETA.  MixinBoostrap will also need to be installed.
