### ISSUE TITLE
Sounds like iron when walking with 1 leg on block other on air

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/DynamicSurroundings#6]
@BeefyTim Moved from the BetterRain repository.

**Comment by OreCruncher** [comment]
@BeefyTime I am unable to duplicate this issue with my 1.10.2 build.  I know what you are talking about - I experience the problem in my 1.7.10 build using Crackpack.  What version of the mod are you using?

**Comment by BeefyTim** [comment]
I was using version 1.0.5.6

**Comment by Fortist** [comment]
As a side note, it also happens to me. I did edit the data files to remove sounds/stop certain sounds from playing.

**Comment by OreCruncher** [comment]
@Fortist You experienced this with the 1.10.2 build?  I know its in the 1.7.10 version.

**Comment by OreCruncher** [comment]
@BeefyTim @Fortist OK - been thinking on this a bit.  I am wondering if a block sound is getting stomped.  If you are running the latest version for 1.10.2/1.11.2 what you can do for me is:

- Enable the "Debug Dialog" option under "Logging Options" in the config GUI for the mod.
- Restart the client.
- Find a block that exhibits the bad behavior.
- Focus your crosshairs on the block.
- Look at the "Block Data" tab in the Debug Dialog.
- Let me know what "Block Name", "Block Material" and "Acoustics" contains.  (Or you can screen shot the dialog and post a link.)

**Comment by OreCruncher** [comment]
I found the problem in 1.7.10.  I am putting in extra code for 1.10.2/1.11.2 to detect similar conditions to prevent this from happening.

**Comment by OreCruncher** [comment]
Pushed release (3.2.1.2) with fix to CurseForge
