### ISSUE TITLE
[Enhancement] The addition of presets because there is so many sounds

### ISSUE THREAD

**Issue by Tsoccerguy3** [OreCruncher/DynamicSurroundings#60]
*Mod Version:*
all versions
*Forge Version:*
all versions

*Link to crash log (if applicable):*

*Description:*
Because there is so many sounds to keep track of , a good idea to implement a preset system to create different atmospheres . Low , medium , high , intense  , spooky , happy , sad , etc ... . This way people can upload and share some sort of sound config file  , an atmospheric sound file to drop in to a default directory.
Where D.S is to sound and effects ! , as Optifine is to Graphics and shaders . D.S becomes the definitive Audio and Effects mod .

**Comment by OreCruncher** [comment]
Not sure exactly what you are looking for, but it is possible to create a resource pack with sounds and Dynamic Surroundings config information.  Find that link [here](https://github.com/OreCruncher/DynamicSurroundings/wiki/Tutorial:-Resource-Packs).

**Comment by Tsoccerguy3** [comment]
That great Ore for people making these sound packs , I was hoping for something internal ( maybe a sub GUI under the sound/music tab , like sp614x has for loading shaders , except for the special sound/effect packs , It's a suggestion , I have set up sound settings a couple of times and forgot what settings i had set , its really time consuming and a lot of trial and error setting it up . Look here https://en.wikipedia.org/wiki/Foley_(filmmaking) . These guys set up and set the mood of a Film or a game.
I was hoping for something super simple , drop your " Foley_Packs " in a directory . Then from the new GUI menu under Sound and music , select a Foley_Pack. Instant sound and visual effects . I suggested this because not everyone is going to have a talent for creating a Gaming atmosphere .

**Comment by OreCruncher** [comment]
I been thinking about this preset idea a bit.  A preset load/save option would be added to a configuration dialog somewhere.  The content of the preset file would be:

+ Minecraft options that folks typically tweak such as chunk render distance, cloud settings, etc.
+ Blocked/culled sounds for Dynamic Surroundings
+ Options for configuring the light level hud, compass, etc.

This may be an idea of an entirely separate mod, something similar to WAILA.  The mod would provide the preset framework, and generate events via API to capture the important state from other mods to the preset file.  And of course, when the file is loaded mods are notified and provided their data to handle.

**Comment by OreCruncher** [comment]
Been mulling this one over - I think I will add the feature to DS.  It may take a bit.

**Comment by OreCruncher** [comment]
@Tsoccerguy3 Added presets to v3,.8.0.0 BETA.  Idea is to configure everything you want, and create a preset.  The preset is stored on disk as  a file.  Later on you can apply that preset back setting the various config values based on the preset.  The preset will also contain Minecraft setting information so applying the preset would also put back the Minecraft option states (volumes, render distance, cloud settings, etc.)
