### ISSUE TITLE
Crash on Forge startup or dosent open (help pls this mod is so cool :( )

### ISSUE THREAD

**Issue by CubeeGuy** [OreCruncher/DynamicSurroundings#601]
**Mod Version:**
1.12.2
The version that is installed in your pack.
1.12.2
**Forge Version:**
1.12.2 - 14.23.5.2854
The actual Forge version - "latest" does not count.
1.12.2 - 14.23.5.2854
**Link to client log:**

Even of there is a crash log, the client log can provide the necessary context for why the exception occured.  You can use a service like [pastebin](https://pastebin.com) or [hastebin](https://hastebin.com) to upload the log, and paste the link here.  The log file is called latest.txt and can be found in your logs folder.

**Link to crash log:**

The callstacks in the log will help pinpoint the actors involved in the crash and give a developer a pointer in the code where to start looking at the problem.  You can use a service like [pastebin](https://pastebin.com) or [hastebin](https://hastebin.com) to upload the log, and paste the link here.

**Description:**

Description of the problem.  In the case of crashes, it is good to know things like the following:

* Did you just add the mod to a pack? no
* Did it just start crashing, or has it always crashed? yes it always
* Did you update any other mods in your pack and it started crashing? no  This includes Forge.
* If updating multiple mods did you update one by one or all at once?  To help narrow the problem down adding one by one is helpful.
* Is the modpack you are using available online somewhere?   no I don't have a modpack. If the crash is due to mod interaction having the pack available makes things much easier.  It is much harder to work these types of issues with a private kitchen sink pack containing 250 mods.

**Comment by S2008Gaming** [comment]
help pls :( this mod is so cool :(

**Comment by OreCruncher** [comment]
I need the mod version number as well as crashlog.
