### ISSUE TITLE
Massive console spam: "Attempt to attach world capability before mod is inititalized - silly fake worlds" repeated 1500+ times

### ISSUE THREAD

**Issue by aaronhowser1** [OreCruncher/DynamicSurroundings#602]
**Mod Version:**
DynamicSurroundings-1.12.2-3.6.1.0

**Forge Version:**

14.23.5.2847

**Link to client log:**

[latest-3.log](https://github.com/OreCruncher/DynamicSurroundings/files/5454991/latest-3.log)

**Description:**

Description of the problem.  In the case of crashes, it is good to know things like the following:

The lines
```
[Client thread/INFO] [dsurround]: Attempt to attach world capability before mod is inititalized - silly fake worlds.
[Client thread/INFO] [dsurround]: Creating default SeasonInfo for dimension overworld
```
are spammed a lot in the console and log

**Comment by OreCruncher** [comment]
Yep.  Exactly what the message says.  Some mods create a temporary world object do some sort of initialization and then throw it way - repeatedly.  Newer version of DS hides it behind a flag setting, so update the the latest.

**Comment by aaronhowser1** [comment]
Ah, Twitch never showed there was an update. Sorry about that.

**Comment by OreCruncher** [comment]
No worries.  The latest is a BETA and Twitch may be configured to only show released.
