### ISSUE TITLE
Crash on loading all worlds (at org.orecruncher.dsurround.client.handlers.FogHandler.fogColorEvent)

### ISSUE THREAD

**Issue by aaronhowser1** [OreCruncher/DynamicSurroundings#603]
**Mod Version:**

DynamicSurroundings-1.12.2-3.6.2.0

**Forge Version:**

14.23.5.2847

**Link to client log:**

[latest.log](https://github.com/OreCruncher/DynamicSurroundings/files/5468631/latest.log)

**Link to crash log:**

https://pastebin.com/TVHcyhKQ

**Description:**

Updated University to use 3.6.2.0 rather than 3.6.1.0, and now it crashes when I load any world. Downgrading to 3.6.1.0 removes the crash.

**Comment by OreCruncher** [comment]
Can you try out this JAR: https://github.com/OreCruncher/DynamicSurroundings/releases/tag/3.6.2.1BETA

**Comment by OreCruncher** [comment]
Pushed 3.6.2.1 to CurseForge.
