### ISSUE TITLE
Crush with Animania base 2.0.0.23 + addons

### ISSUE THREAD

**Issue by GreenTample** [OreCruncher/DynamicSurroundings#605]
**Mod Version:**

DynamicSurroundings-1.12.2-3.6.2.0

**Forge Version:**

1.12.2-forge1.12.2-14.23.5.2847

**Link to crash log:**

https://pastebin.com/t6ZkwNmg

**Description:**

Installed new Animalia mods. When entering Twilight Forest, or teleporting in distant locations, game crashes

**Comment by OreCruncher** [comment]
Do you have both Animania Base and Farm installed?  Reason is that there is a soft dependency between the two where if you don't have both mods installed you can get this.  (I don't think @Tschipp got around to fixing this yet?)

**Comment by GreenTample** [comment]
Yes
![image](https://user-images.githubusercontent.com/74113874/98450557-996aa180-214e-11eb-9195-80397cfb5bdf.png)

**Comment by Tschipp** [comment]
yes that's on my end sorry, I hope to release this fix tomorrow.

**Comment by OreCruncher** [comment]
@Tschipp Have you been able to release a version with the necessary changes?

**Comment by Tschipp** [comment]
yes, just yesterday. You can close this now.

**Comment by OreCruncher** [comment]
Thanks!  @GreenTample Let us know if the problem still happens after updating.
