### ISSUE TITLE
Black Screen and White Screen bug

### ISSUE THREAD

**Issue by BunE-exe** [OreCruncher/DynamicSurroundings#609]
![Screenshot (348)](https://user-images.githubusercontent.com/70093903/99257550-2b129700-2852-11eb-96fd-640ab70d0134.png)
**Mod Version:1.12.2-3.6.2.1**

The version that is installed in your pack.

**Forge Version:14.23.5.2854**

The actual Forge version - "latest" does not count.

**Link to client log:**

Even of there is a crash log, the client log can provide the necessary context for why the exception occured.  You can use a service like [pastebin](https://pastebin.com) or [hastebin](https://hastebin.com) to upload the log, and paste the link here.  The log file is called latest.txt and can be found in your logs folder.

**Link to crash log:**

The callstacks in the log will help pinpoint the actors involved in the crash and give a developer a pointer in the code where to start looking at the problem.  You can use a service like [pastebin](https://pastebin.com) or [hastebin](https://hastebin.com) to upload the log, and paste the link here.

**Description: The bug does not cause Minecraft to crash. Having fast render causes the screen turns black, but just without visual. Despite turning off fast render the screen is now obscured by 'white panel (turns white)' but you are still able to see the GUI (Hotbar, Inventory, Menu & Etc.)**

Description of the problem.  In the case of crashes, it is good to know things like the following: I did update it from 3.6.2.0 to 3.6.2.1, along with disenchanter mod from 1.6 to 1.7 at the same time. 

* Did you just add the mod to a pack?
* Did it just start crashing, or has it always crashed?
* Did you update any other mods in your pack and it started crashing?  This includes Forge.
* If updating multiple mods did you update one by one or all at once?  To help narrow the problem down adding one by one is helpful.
* Is the modpack you are using available online somewhere?  If the crash is due to mod interaction having the pack available makes things much easier.  It is much harder to work these types of issues with a private kitchen sink pack containing 250 mods.

**Comment by BunE-exe** [comment]
There were additional mods, but it was working perfectly fine before updating it

**Comment by OreCruncher** [comment]
Have you tried 3.6.2.0 with the updated disenchanter mod, and if so does it still whitescreen?

**Comment by BunE-exe** [comment]
Im very sorry, I miss Identify the problem. Yes it was because of the
disenchanter 1.7 mod

**Comment by BunE-exe** [comment]
Is was with DIsenchanter 1.7
