### ISSUE TITLE
Simply Jetpacks sound loop

### ISSUE THREAD

**Issue by Hirsu** [OreCruncher/DynamicSurroundings#61]
*Mod Version:*
1.10.2-3.3.4.0

*Forge Version:*
1.10.2-12.18.3.2254

*Link to crash log (if applicable):*
NA

*Description:*

I'm currently playing the FTB Beyond modpack (latest version as of writing, which is 1.4.2) on a local server.
To improve on the immersion factor, I've added your mod and Sound Filters to the modpack. I've also added Sound Cap (although I'm not sure if this is still required or may even be interfering with Dynamic Surroundings at this point).

Whenever I use a jetpack from Simply Jetpacks, the sound of the jets 'sticks around' even after I'm not using the jetpack any longer. As long as I don't use the jetpack the sound doesn't get stuck in a loop, but as soon as I've used the jetpack even once, the sound will keep on playing until I relog.

The latest update to FTB Beyond didn't update Simply Jetpacks, but I did switch over to the latest version of Dynamic Surroundigs and that's when the issue started, so I'm inclined to believe that's where I should be looking for a solution. If I'm looking at the wrong mod, please let me know so I can report this question to the correct mod author. Also, if you need more information, feel free to let me know.

On a sidenote: thanks for your work on this mod, it's a great addition to a more immersive Minecraft experience!

**Comment by OreCruncher** [comment]
Thanks!

Yes, get rid of Sound Cap.  Dynamic Surroundings does reconfigure the sound channels and would conflict.  I can't say which mod would "win" in terms of making adjustments to the channels.

As for Simply Jetpacks I will take a look at the code and see if it could be a problem.

**Comment by OreCruncher** [comment]
The issue was introduced with my latest changes for sound looping.  I will make an update to narrow the sounds that get the improved looping to only my mod in order to preserve the old behavior for other mods.

**Comment by OreCruncher** [comment]
Pushed the BETA to CurseForge.  Yay. :)

**Comment by Hirsu** [comment]
Wow, you sure don't mess around!
I've just tested the last beta and the problem seems to be gone.
Thanks!

**Comment by OreCruncher** [comment]
Simple philosophy - if it's broke, fix it. :)
