### ISSUE TITLE
Crash problem 

### ISSUE THREAD

**Issue by RJHG56** [OreCruncher/DynamicSurroundings#612]
[crash-2020-11-20_15.21.50-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/5611750/crash-2020-11-20_15.21.50-client.txt)
**Mod Version:**

The version that is installed in your pack.
DynamicSurroundings-1.12.2-3.6.2.0
**Forge Version:**

The actual Forge version - "latest" does not count.

**Link to client log:**

Even of there is a crash log, the client log can provide the necessary context for why the exception occured.  You can use a service like [pastebin](https://pastebin.com) or [hastebin](https://hastebin.com) to upload the log, and paste the link here.  The log file is called latest.txt and can be found in your logs folder.

**Link to crash log:**

The callstacks in the log will help pinpoint the actors involved in the crash and give a developer a pointer in the code where to start looking at the problem.  You can use a service like [pastebin](https://pastebin.com) or [hastebin](https://hastebin.com) to upload the log, and paste the link here.

**Description:**

Description of the problem.  In the case of crashes, it is good to know things like the following:

* Did you just add the mod to a pack? yes i did
* Did it just start crashing, or has it always crashed? started to crash
* Did you update any other mods in your pack and it started crashing?  This includes Forge. no, i updated this mod and started to crash
* If updating multiple mods did you update one by one or all at once?  To help narrow the problem down adding one by one is helpful. onli this
* Is the modpack you are using available online somewhere? no i crated  If the crash is due to mod interaction having the pack available makes things much easier.  It is much harder to work these types of issues with a private kitchen sink pack containing 250 mods.

**Comment by OreCruncher** [comment]
Not sure why this issue is posted here.  Dynamic Surroundings does not appear to be installed.
