### ISSUE TITLE
[Biomes o' plenty] Inverted fog on Wasteland

### ISSUE THREAD

**Issue by Aphyxia** [OreCruncher/DynamicSurroundings#62]
The wasteland biome from BoP has very thick fog. This seems to conflict with Dynamic Surroundings.
Removing dsurroundings removes this problem. Biome fog, elevation haze or desert fog true/false and values don't have any effect on this. It seems to be similar to inverted fog where the fog is near the player but not far from the player.
Without DS: https://gyazo.com/4d9ac1ab58241250841dd2a8872b1adc
With DS: https://gyazo.com/0807b4d0bcd491a5f5d1f0fd38427663

https://github.com/Glitchfiend/BiomesOPlenty/issues/949

Edit: Upon further testing. Any of the following combination seems to work:
* Dynamic surroundings + BoP
* BoP + optifine
But BoP + optifine + dsurroundings, all three together do not work. And optifine's fog settings or any setting doesn't do anything to remedy this.

*Mod Version:*
1.11.2-3.3.4.1
*Forge Version:*
forge-1.11.2-13.20.0.2277-universal

**Comment by OreCruncher** [comment]
I posted a comment on the issue in the BoP tracker related to fog event handling.  For DS I will see about adding an option to disable fog handling all together so at least you can take DS out the equation.

**Comment by OreCruncher** [comment]
Changed logic so that if desert fog and biome fog are both turned off all fog processing from Dynamic Surroundings is disabled.  Will be in the next BETA.

**Comment by OreCruncher** [comment]
Pushed v3.3.5.0 BETA version that can disable all fog processing from Dynamic Surroundings.
