### ISSUE TITLE
Game doesn't start up at all with Dynamic Surroundings

### ISSUE THREAD

**Issue by OfficialCRUGG** [OreCruncher/DynamicSurroundings#621]
**Mod Version:**

1.12.2-3.6.1.0

**Forge Version:**

forge-14.23.5.2847

**Link to client log:**

https://pastebin.com/prPbPYbv

**Link to crash log:**

N/A

**Description:**

Hello! I am using the Modpack for a German Minecraft Server on Technic Launcher (can be found [here](https://www.technicpack.net/modpack/statemc-roleplay-server.1713851)) and decided to add some client side mods. This means: Better Foliage + Forgelin, Shoulder Surfing and DynamicSurroundings + OreLib. This exact combination works perfectly fine for a friend of mine. I even tried using exactly the same files he uses. However, with Dynamic Surroundings in the Pack, the game doesn't even start. The window doesn't open at all. And there is no crash report created. Once I remove the mod, it works fine again. If you need any more information, just tell me what is needed!

**Comment by OreCruncher** [comment]
Did you install MixinBoostrapper?

**Comment by OfficialCRUGG** [comment]
I have no clue what MixinBootstrapper is, nor is it in my Mod Folder or anything, if it's a mod.

**Comment by OreCruncher** [comment]
Yes, its a mod: https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap

**Comment by OfficialCRUGG** [comment]
Hm. That's not in my mods Folder. As stated earlier, I'm using the same modpack with the same client side mods as a friend of mine. And this only starts to happen, when I drag Dynamic Surroundings in my Mods Folder...

**Comment by OreCruncher** [comment]
And did you try putting MixinBootsrap into your folder as well?  Latest versions of DS do not include Mixin and relies on other mods to provide (or installing MixinBootstrap).

**Comment by OfficialCRUGG** [comment]
Okay, guess I will try that tomorrow. But then, why does it work for m friend who doesn't have the mod? And also, I couldn't see this mod as a dependency on the CurseForge Page...

**Comment by OreCruncher** [comment]
Mixin can be  touchy.  It has a been a real pain.  You can also try the latest BETA versions.  I made some tweaks to mixin loading and those definately need MixinBootstrap.

**Comment by EzerArch** [comment]
Hello,

I would just add that Mixin for 1.16.3 is working in Minecraft 1.12.2. I think it's ok, isn't it?

**Comment by OreCruncher** [comment]
Yes - all it does it make sure that Mixin gets added early to the boot sequence.

**Comment by OfficialCRUGG** [comment]
I didn't try it out yet, but I think I found the Issue. At least this was thew Issue with ReplayMod. I prefix all the file names of mods I add to the pack manually with "z-" which causes the mod to load last. MalasisCore uses an older Version of Mixin, so that one is loaded.

**Comment by OreCruncher** [comment]
Yeah - Mixin Bootstrap could help.  Lucky us they started bundling Mixin with 1.16.4 Forge so this nightmare should not happen.
