### ISSUE TITLE
Game doesn't start up when DS is added

### ISSUE THREAD

**Issue by sunayyagiz** [OreCruncher/DynamicSurroundings#623]
**Mod Version:**
1.12.2-3.6.1.0

**Forge Version:**
14.23.5.2854
**Link to client log:**
[https://hastebin.com/evayawuzem.sql](url)

**Link to crash log:**

N/A

**Description:**

I added this mod now, there was no problem with my modpack at all. Without the mod, mc works just fine but when i add the mod with OreLib-1.12.2-3.6.0.1.jar it isn't even start up, just gives me a crash log. The link of my modpack is here; [https://www.dosya.tc/server23/lfflyu/Mucosoft_Mod_Pack_Extreme_1.12.2.rar.html](url)

**Comment by OreCruncher** [comment]
Mixin.  Yay.  Try updating the latest BETA version of DS.

**Comment by sunayyagiz** [comment]
Wasn't it the latest version?

**Comment by sunayyagiz** [comment]
OMG it worked out, thanks for oyur help bro! I appreciated it 👍

**Comment by OreCruncher** [comment]
Cool!
