### ISSUE TITLE
[1.16.4] ctd on joining the server

### ISSUE THREAD

**Issue by Nazguliki** [OreCruncher/DynamicSurroundings#624]
**Mod Version: DynamicSurroundings-1.16.4-4.0.1.0**

**Forge Version: 35.1.13**

**Link to client log:
[latest.log](https://github.com/OreCruncher/DynamicSurroundings/files/5739307/latest.log)
[debug.log](https://github.com/OreCruncher/DynamicSurroundings/files/5739308/debug.log)**

**Link to crash log:
[crash-2020-12-24_12.50.11-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/5739309/crash-2020-12-24_12.50.11-client.txt)**

**I have moded server for me and my friend. The game crush, when i try to join the server with the mod. If i delete the mod - it works fine.**

The mods pack isnt available anywhere officially. But, for testing purpose, i uploaded the mods i use on the server. Here is the link:
https://drive.google.com/file/d/1ghKGj-ROn08pmJ7NP1lHWasC513hR1WB/view?usp=sharing

**Comment by OreCruncher** [comment]
Posted a 1.16.4-4.0.1.1 update to CurseForge.
