### ISSUE TITLE
Humanoid Mob Step Sounds Lack Directional Audio

### ISSUE THREAD

**Issue by CynicalShrew** [OreCruncher/DynamicSurroundings#629]
1.16.4 - 0.1.3

Forge version: 35.1.15

Humanoid mobs such as zombies, or any that have the same footstep sound as the player, don't have directional audio. So if I'm standing still, and a zombie 20 blocks away is walking, it sounds exactly like if I were walking. Distance doesn't affect the volume, and it lacks direction. This doesn't seem to be the case for any other mobs or sounds. Just these footsteps.

Initially had the issue on a modded server, but it persisted when starting the game with no other mods, so it doesn't seem to be a mod conflict.

**Comment by OreCruncher** [comment]
Sounds like the Mixin didn't fire.  There is special logic to convert an OGG to mono format on the fly.  Can you post a link to your debug.log just after Minecraft loads but before you join a world?

**Comment by CynicalShrew** [comment]
This one, yeah?

https://pastebin.com/nW1NYw6z

**Comment by OreCruncher** [comment]
```
[27Dec2020 16:14:31.597] [Render thread/WARN] [SoundControl/SoundUtils]: Enhanced sounds are not enabled.  No fancy sounds for you!
```

Link your sndctrl-client.toml file.

**Comment by CynicalShrew** [comment]
Yup, checked the file, and they weren't enabled. I remember seeing it disabled, and I thought I enabled it, but I guess not. Enabled it, then launched the game, and the issue is gone. Looks like this was just user error.

**Comment by OreCruncher** [comment]
Glad it was simple :)

**Comment by Forturian** [comment]
> Yup, checked the file, and they weren't enabled. I remember seeing it disabled, and I thought I enabled it, but I guess not. Enabled it, then launched the game, and the issue is gone. Looks like this was just user error.

Can you find more details about this setting?
