### ISSUE TITLE
how to turn off elephant sound in savana

### ISSUE THREAD

**Issue by hunnybunny21** [OreCruncher/DynamicSurroundings#63]
DynamicSurroundings-1.11.2-3.3.3.1

how to turn off elephant sound in savana
i  live in the  savana and i hate always hearing the elephant 

i lboer the water fall sound

**Comment by OreCruncher** [comment]
Block the "dsurround:elephant" sound under the "Blocked Sounds" config menu option.

**Comment by OreCruncher** [comment]
@hunnybunny21 Did you manage to block the elephant sound?

**Comment by OreCruncher** [comment]
@hunnybunny21 Closing the issue due to inactivity.  If you have further problems let me know.
