### ISSUE TITLE
Battle Music config inaccesible in 1.16.4

### ISSUE THREAD

**Issue by Monozari** [OreCruncher/DynamicSurroundings#631]
Using Dynamic surroundings version1.16.4-4.0.1.4

Forge 35.1.10

The actual Forge version - "latest" does not count.

Battle music cannot be configured to play as there is no configuration option for such a thing within the mod or the config file.
Please fix this, battle music was the sole reason I installed this pack.

**Comment by OreCruncher** [comment]
Yep - was removed.  Reason is that the mod is 100% client side.  For battle music to work it would  need to be installed server side.  I may create in a separate mod.
