### ISSUE TITLE
Issues with Terraqueous Small Stone Clusters

### ISSUE THREAD

**Issue by KrysEmlyn** [OreCruncher/DynamicSurroundings#632]
**Mod Version:**

DynamicSurroundings-1.16.4-4.0.1.4

**Forge Version:**

forge-1.16.4-35.1.15

**Description:**

Description of the problem. 

I recently added your mod to my personal collection of mods that I play with, having enjoyed your mod previously on the 1.12.2 version of Minecraft. This time around, I'm playing with a mod called "Terraqueous", which adds small clusters of stones and sandstone to the world. When these are added underwater and are waterlogged, your mod makes them emit smoke particles and a hissing noise. I play with captions on, and the captions read "fire extinguished" every time this occurs. This issue only occurs with your mod active. When Dynamic Surroundings is not active, the smoke and sound effects do not occur. I'm not sure what needs to be changed to make them silent and not emit particles. Help?

**Comment by OreCruncher** [comment]
~~Hmmm.... I will have to take a look at this.  Are you hearing splash sounds as well?~~

It's not dynamic surroundings.  I have a session running without my mod and I still see the same effect.  With Dynamic Surroundings installed and debug tracing enabled I can see it is a mod intentionally playing the sound.

I took a look inside the Terraqueous JAR.  It seems they have a bug in their doodads (all their miscellaneous things).  Burnium has this special logic so if it is in water it will play effects.  However, this check is on the general doodad block and will apply to all doodads.  There is a config settings in terraqueous.toml where you can turn this off (burnium_reacts_to_water).

I recommend reporting it to the Terraqueous author.
