### ISSUE TITLE
Error loading because of sound control encountered an Error.

### ISSUE THREAD

**Issue by ghost** [OreCruncher/DynamicSurroundings#637]
**Mod Version:**

1.16.4

**Forge Version:**

1.16.4

Link to client log: https://pastebin.com/QDZp9d2j

Link to crash log: https://pastebin.com/Lxa2cqPG

Description:
After putting the latest version of this mod in my mod folder and tries to start the game, it gives an error. Says Dynamic Surrounding: sound control encountered an error during the process_imc event phase.

**Comment by OreCruncher** [comment]
Strange.  Something sending my mod an IMC message that isn't me.

**Comment by OreCruncher** [comment]
Pushed 4.0.3.1 to CurseForge.
