### ISSUE TITLE
Rain crashes client on server with mod installed, without mod = no crash

### ISSUE THREAD

**Issue by zachsai** [OreCruncher/DynamicSurroundings#638]
**Mod Version:**
4.0.3.1
The version that is installed in your pack.

**Forge Version:**
35.1.28
The actual Forge version - "latest" does not count.

**Link to client log:**

https://gist.github.com/celsiusqc/86c2115596fa5215c192bf4b7a1f5a6e (lastest log)

Even of there is a crash log, the client log can provide the necessary context for why the exception occured.  You can use a service like [pastebin](https://pastebin.com) or [hastebin](https://hastebin.com) to upload the log, and paste the link here.  The log file is called latest.txt and can be found in your logs folder.

**Link to crash log:**
https://pastebin.com/mFzV4rej (crash report)
The callstacks in the log will help pinpoint the actors involved in the crash and give a developer a pointer in the code where to start looking at the problem.  You can use a service like [pastebin](https://pastebin.com) or [hastebin](https://hastebin.com) to upload the log, and paste the link here.

**Description:**
Rain is causing the client to crash when in a server. When rain is turned off through command, the client does not crash. When joining without the mod installed and rain present, the client does not crash
Description of the problem.  In the case of crashes, it is good to know things like the following:

* Did you just add the mod to a pack? yes
* Did it just start crashing, or has it always crashed? no
* Did you update any other mods in your pack and it started crashing?  This includes Forge. no
* If updating multiple mods did you update one by one or all at once?  To help narrow the problem down adding one by one is helpful.
* Is the modpack you are using available online somewhere?  If the crash is due to mod interaction having the pack available makes things much easier.  It is much harder to work these types of issues with a private kitchen sink pack containing 250 mods.
* no

Am am using 5 resourcepacks with some of them having the optifine folder.

**Comment by OreCruncher** [comment]
Does the crash happen without optifine?

**Comment by BitterSteve** [comment]
Im having a very similar problem (if not the same problem) and i did a few test.

- With optifine + resource pack + shaders = crash
- With resource pack alone = no crash
- With optifine alone = no crash
- With optifine + shaders = no crash
- With optifine + resource pack = crash

again, im not sure if this is the same problem. but the crash only happens when it rains from what i can tell.

**Comment by ils13** [comment]
Just to add to this I'm having the same crash and downgraded to version `DynamicSurroundings-1.16.4-4.0.2.0.jar` which works fine with `OptiFine_1.16.4_HD_U_G5.jar` + `BSL_v7.2.01pre2.zip` shaders.

The crash occurs when rain hits water, I tried the following in a flat world.
- /weather rain 999
- dig a hole, and fill it with a water bucket -> crash.

**Comment by OreCruncher** [comment]
Yes - need to know if the crash happens without optifine.

**Comment by OreCruncher** [comment]
I pushed 4.0.3.2 to CurseForge with a speculative fix for this.  Let me know if you see improvement.

**Comment by Tsoccerguy3** [comment]
tested OptiFine HD U G6 pre10 , DynamicSurroundings-1.16.4-4.0.3.2 and no crash . Server Paper 1.16.4 build 393 , all good

**Comment by OreCruncher** [comment]
Cool!  I will go ahead and close out.  Let me know if anything else pops up.
