### ISSUE TITLE
Rain Drops on Screen

### ISSUE THREAD

**Issue by kenijey** [OreCruncher/DynamicSurroundings#64]
*Mod Version:* latest

*Forge Version:* 2279

*Link to crash log (if applicable):* no crash

*Description:*
i'm in my house but i still see them :D

**Comment by OreCruncher** [comment]
Which rain drops are you referring to?  The falling rain, or the splash particles that hit the gound?  Or both?

**Comment by kenijey** [comment]
on the screen, that bloomy rain drops

**Comment by OreCruncher** [comment]
Not clear to me - can you post a screenshot?  (Could be I need coffee - just woke up. :))

**Comment by kenijey** [comment]
:D ok wait

**Comment by kenijey** [comment]
![2017-04-08_14 47 44](https://cloud.githubusercontent.com/assets/24831406/24828655/5cc9f7fe-1c6a-11e7-93db-513cc8cb06ee.png)
can you see this? left bottom on the screen, that bloomy rain effect. such as a drop on the camera lens.

**Comment by OreCruncher** [comment]
That distortion in the lower left that makes the chest swirly?  That's not Dynamic Surroundings.  I believe it is some sort of shader effect.  Have you updated any other mods recently?

**Comment by kenijey** [comment]
oh, really? then i think it is coming from shaders... hmm... or i don't know... i should try.. ok thank you!

**Comment by OreCruncher** [comment]
Let me know how it goes.

**Comment by kenijey** [comment]
yes it is coming from sildur's shaders :D
