### ISSUE TITLE
[1.16.4] Culling sounds in sndctrl-client.toml disables them entirely, rather than reducing the repetition.

### ISSUE THREAD

**Issue by Vaelzan** [OreCruncher/DynamicSurroundings#643]
**Mod Version:**

1.16.4-4.0.3.3

**Forge Version:**

35.1.36

**Link to client log:**

https://gist.github.com/Vaelzan/5f288c7c0fe7556ad8ef0d14ed4b4ff3

**Link to crash log:**

N/A, not a crash.

**Description:**

Enabling culling for any sound disables it entirely (the subtitle still shows, however), while the description of sound culling in the 1.14/1.15 version indicates that it should cut down on how often the sounds play rather than disable them entirely (and there is no description of sound culling at all in the 1.16.4 version). From my understanding it should be the "blocking" setting that does this, not "culling".

This is in Valhelsia 3 (my development version, but the problem occurs in 3.1.5), and you can see the configs that I'm testing with in our GitHub repository here: https://github.com/ValhelsiaTeam/Valhelsia/tree/1.16/config/dsurround - the configs have several audio effects disabled from mobeffects-client and the fog from environs-client,

You can see that I recently disabled culling there since people complained about animals no longer making noises at all, and I was able to verify that. During testing I was turning culling on and off using the Ctrl-S config menu to verify that the sounds weren't playing at all.

If required I'm happy to turn on debug logging and do further testing, but hopefully you're able to reproduce the issue and diagnose the problem yourself.

As an aside, and unrelated entirely to this issue, the reason we disabled some of the audio is due to the audio being quite literally painful to a person with an auditory processing disorder due to some of the high-pitched frequencies used. We would gladly enable these settings again if that was resolved somehow (notably the footsteps with armour rustling). It is also a touch unintuitive that the footsteps don't play at the same volume as vanilla Minecraft footsteps and instead have their own volume slider (instead of using the existing ones), since they were initially "headphone warning required" loud in my experience with default configs.

**Comment by OreCruncher** [comment]
I was suspecting something like this.  I was playing DW20 this AM and it sounded off.

**Comment by OreCruncher** [comment]
Pushed 4.0.3.4 to CurseForge with a fix for volume calcs.
