### ISSUE TITLE
Game Crashes Right After Minecraft Application Starts

### ISSUE THREAD

**Issue by entschri** [OreCruncher/DynamicSurroundings#646]
**Mod Version:**

DynamicSurroundings-1.16.4-4.0.3.4.jar

**Forge Version:**

1.16.4-forge-35.0.7

**Link to client log:**

https://pastebin.com/xwza55se

**Link to crash log:**

https://pastebin.com/JwMcY6mG

**Description:**

It is not a modpack, just the mod by itself.
It just started crashing.

**Comment by OreCruncher** [comment]
From the log:
```
--fml.forgeVersion, 35.0.7
```
It appears you are using an older version of Forge.  Needs to be 35.1.10 or newer.

**Comment by entschri** [comment]
ok thanks it works now
