### ISSUE TITLE
[1.16.4] Aurora borealis effect instantly shifts to a new position in the sky when moving between y=62/63

### ISSUE THREAD

**Issue by AeiouEnigma** [OreCruncher/DynamicSurroundings#648]
**Mod Version:**

1.16.4-4.0.3.4

**Forge Version:**

1.16.4-35.1.36

**Description:**

Aurora borealis effect has a very jarring shift in positions when crossing between y=62 and y=63

**Comment by OreCruncher** [comment]
Pushed update to CurseForge.
