### ISSUE TITLE
Lightning sound seems to disapear depending on direction facing

### ISSUE THREAD

**Issue by Tsoccerguy3** [OreCruncher/DynamicSurroundings#65]
*Mod Version:*
1.11.2
*Forge Version:*
1.11.2
any version
*Link to crash log (if applicable):*
no crash
*Description:*
I noticed that turning in different directions some sounds (lightning) will almost disappear , regardless of proximity . There should be no perceptual reduction to loudness of a  sound , based on the direction a player looks . Just distance

**Comment by OreCruncher** [comment]
Which lightning are you referring to?  The entity lightning bolt, or the background sound?  Both actually do have a position in the world and so sound would be relative.  The entity version has the sound location to be where the strike occurs, and the background one produced by Dynamic Surroundings is positioned about 128 blocks above the players head.

**Comment by Tsoccerguy3** [comment]
I reset everything . It's now working . Although defaults are really low . Tested on Windows 10 x64 Redstone 2 build 1703.14  . Realtek 5.1 chipset. Starting again to find the listening comfort zone . Starting out on default , can't really hear anything . On a flat-map grass is only 5 above bedrock and don't really hear any of the sound effects . Lightning surround sound is back . Between configuring Windows sound , card sound and in game sound , there's got to be an easier way . Just a note , windows 10 is going to update to Redstone 2 over the next couple of months and from my experience its going to change the OS sound listening defaults. Hope this helps if anyone has same problem

**Comment by OreCruncher** [comment]
I use the Minecraft sound engine, and it uses the "default" sound config of the system whatever that may be.  IIRC I had to do some system tweaking myself to get my headset working properly.

(I do recall some long standing requests that Minecraft support some sort of customization so the appropriate sound config can be used on a system other than default, but that obviously hasn't gone too far.)

**Comment by Tsoccerguy3** [comment]
Ore is there a fix for custom and flat maps not playing ambient sounds below the 60 block height ? I have some maps that are flat height from bedrock to grass is 5 blocks as example . I hear no biome animal or wind sounds , just the sounds related to being so deep in the ground . I could not find anything in the WIKI that would help . Does D.S. have the sounds hard set for worlds 65 blocks sea level .

**Comment by OreCruncher** [comment]
There isn't a code "fix".  The world provider is reporting sea level at 63 blocks.  There is a dimension override you can set to tell DS exactly what it should be.  That information can be found [here](https://github.com/OreCruncher/DynamicSurroundings/wiki/Tutorial:-Dimension-Configuration).

**Comment by OreCruncher** [comment]
@Tsoccerguy3 Did you manage to adjust the sea level for your dimension?

**Comment by OreCruncher** [comment]
@Tsoccerguy3 I was reviewing this issue and noted a situation where you have ground level at Y=5.  I fixed a bug recently where the Superflat world was not getting the correct Y value thus DS thought you were underground.

**Comment by OreCruncher** [comment]
@Tsoccerguy3 Going to close this issue for now.  If you have any other thoughts let me know.
