### ISSUE TITLE
[1.16.5] Ripple effects occuring when certain blocks produce drip particles underwater

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [OreCruncher/DynamicSurroundings#652]
**Mod Version:**

4.0.3.5

**Forge Version:**

36.0.1

**Link to client log:**

https://pastebin.com/Wxnca8sE

**Link to crash log:**

N/A - Game doesn't crash

**Description:**

I have noticed when exploring some underwater structures that some blocks that produce drip particles such as wet sponges and crying obsidian will still produce them when underwater, which leads to ripple effects being created inside of water blocks.

Here are some screenshots to show what I mean:
![2021-01-22_12 11 14](https://user-images.githubusercontent.com/64381954/105489834-cb01fc00-5cab-11eb-9e4b-297067bedbcd.png)
![2021-01-22_12 21 06](https://user-images.githubusercontent.com/64381954/105490258-698e5d00-5cac-11eb-9e10-15c56b726178.png)
![2021-01-22_12 10 05](https://user-images.githubusercontent.com/64381954/105490325-81fe7780-5cac-11eb-94e6-14929e803401.png)
In case you are wondering, I have no other mods installed.

**Comment by OreCruncher** [comment]
Interesting.  Do you know if the blocks where these drips are forming are air blocks?  I wouldn't expect drips to be created in a non-air block.  ~~(I haven't looked at the Minecraft code to see what it is thinking - just wondering if you knew.)~~ EDIT:  Yep - Minecraft doesn't care.  Strange.  Have to think on the best way to handle.  Maybe patch Minecraft to not do this if it is a water block.

**Comment by The-Bernician-Lamb** [comment]
All the screenshots I have shown you were taken when I was underwater. I've checked to make sure but these blocks are surrounded by water blocks, maybe not on all sides, but at the very least they are exposed to water blocks on the face that the particles are forming.

**Comment by OreCruncher** [comment]
Pushed 4.0.3.6 to CurseForge.
