### ISSUE TITLE
OptiFine and dynamic surroundings crash 1.16.4 and .5

### ISSUE THREAD

**Issue by FullMetalMaster** [OreCruncher/DynamicSurroundings#653]
**Mod Version:**

The version that is installed in your pack.

**Forge Version:**
1.16.4 and .5 lastests on both and .36
The actual Forge version - "latest" does not count.  
1.16.4 forges

35.1.37 
35.1.36

1.16.5 forge

1.16.5 - 36.0.1

**Link to client log:**
https://pastebin.com/WgR5Ky6s
**Link to crash log:**
https://pastebin.com/ZRqVYq6d

crashes apon loading into a new world in single player hard crash exit code 0
[crash-2021-01-23_16.51.41-server.txt](https://github.com/OreCruncher/DynamicSurroundings/files/5861163/crash-2021-01-23_16.51.41-server.txt)

[crash-2021-01-23_16.51.41-server.txt](https://github.com/OreCruncher/DynamicSurroundings/files/5861172/crash-2021-01-23_16.51.41-server.txt)
[latest.log](https://github.com/OreCruncher/DynamicSurroundings/files/5861174/latest.log)

**Comment by OreCruncher** [comment]
Is this the entirety of the log?

```
java.lang.NoSuchMethodError: net.minecraft.world.server.ChunkManager$ProxyTicketManager.shouldForceTicks(J)Z
```

Dynamic Surroundings is 100% client side, meaning it does not operate on the server side.

**Comment by FullMetalMaster** [comment]
it seems to be pretty sure this is no longer an issue OptiFine 1. 16.5 fixes the problem
