### ISSUE TITLE
Crash while playing

### ISSUE THREAD

**Issue by Worest0** [OreCruncher/DynamicSurroundings#655]
**Mod Version:**

1.2.2-3.6.1.0

**Forge Version:**

14.23.5.2855

**Link to client log:**

https://pastebin.com/5p34dLtm

**Link to crash log:**

https://pastebin.com/SgGvNpcZ

**Description:**

Played with my friends on LAN and after 1-2 hours play, light blue screen came to the Minecraft screen(only for me, maybe because I was the host) then crashed and because of VanillaFix mod it showed the problem was Dynamic Surroundings mod.
Then I tried go back to the world, but I can't, the light blue screen came again and crashed.
Tried to delete the mod and config too, but when I did that the game wasn't started.

* Did you just add the mod to a pack?
No.

* Did it just start crashing, or has it always crashed?

I using this mod 1 years ago and never happened same.

* Did you update any other mods in your pack and it started crashing?
No, just added some new one.
 
* Is the modpack you are using available online somewhere?  If the crash is due to mod interaction having the pack available makes things much easier.  It is much harder to work these types of issues with a private kitchen sink pack containing 250 mods.
No, it isn't.

**Comment by OreCruncher** [comment]
Did you update Animania recently?

**Comment by Worest0** [comment]
> Did you update Animania recently?

No, we started to play with Animania maybe 2-3 days ago, but we didn't interact with animals when the crash happened(if it matters).
If Animania is a possible problem, we can delete it, isn't an important mod for us.

**Comment by OreCruncher** [comment]
When Animania updated to 2.x it broke DS.  The latest BETA versions of DS have the changes to be compatible again.

**Comment by Worest0** [comment]
> When Animania updated to 2.x it broke DS. The latest BETA versions of DS have the changes to be compatible again.

Okey, I'll try for sure, but if I delete or try to change the file to another version, the game(loading screen too) don't show up, dont happen anything.

**Comment by OreCruncher** [comment]
You will also need to install Mixin Bootstrap.  The BETA versions do not include Mixin within the package.

**Comment by Worest0** [comment]
> You will also need to install Mixin Bootstrap. The BETA versions do not include Mixin within the package.

Okey, I'll try it.
Thank you for the fast reply.

**Comment by OreCruncher** [comment]
@Worest0 I was wondering you were able to get this working?

**Comment by Worest0** [comment]
> @Worest0 I was wondering you were able to get this working?

Oh, sorry, I forgot to inform you about the solvation.
Yes, its worked, thanks a lot for fast help, and the question too! :)

**Comment by OreCruncher** [comment]
Cool.  I will close out.  Let me know if you need anything else.
