### ISSUE TITLE
Severe fps hit/lag near massive flowing water

### ISSUE THREAD

**Issue by slainless** [OreCruncher/DynamicSurroundings#656]
**Mod Version:**
1.16.4 - 4.0.3.5

**Forge Version:**
36.0.1

**Description:**
I installed [Fluid Physics](https://www.curseforge.com/minecraft/mc-mods/fluid-physics-forge). Sometimes worldgen generate a cave at sea floor, so the water will be flowing inside the cave. Since the mod (Fluid Physics) remove infinite water system, the sea water is actually drained inside the cave, leaving an wide area of flowing water block outside the cave.

The problem is: When near a massive flowing water, my fps drop drastically to almost 0 and the flowing water sound effect from DS is stuttering and loud. My fps back to normal when i set master volume to 0, or set Dynamic Surrounding waterfall sound to 0.

**Comment by OreCruncher** [comment]
Only option is to disable the waterfall effect.  That is the "Waterfall Splash" setting in the Environs config.

**Comment by OreCruncher** [comment]
Following up.  Disabling the waterfall effect help?

**Comment by slainless** [comment]
Sorry, been busy so i forgot to reply.
Disabling waterfall sound is enough so i just left the effect on.

**Comment by OreCruncher** [comment]
Interesting.  Are you by chance using Sound Filters?

**Comment by slainless** [comment]
Yes, how did you know?
lol, it just occurred to me that maybe sound filter also takes part in this.

**Comment by OreCruncher** [comment]
:)  By default DS has a feature that does reverb and sound occlusion.  If you want to use Sound Filters turn off enhanced sound processing in DS.  Both running together can do things like this.

EDIT:  I was just doing some testing with Sound Filters and I see that for some reason the client side TPS goes up, especially walking around the surface.  You can see the client side TPS when DS is installed and hitting F3.  Info will be displayed on the right.

**Comment by slainless** [comment]
So, the only solution is to pick either DS or SF then?
If DS feature overlap with SF and does completely what SF does, then i will just disable SF :/

**Comment by OreCruncher** [comment]
You can choose to disable the enhanced sound processing of DS.  By doing that DS will not do reverb and occlusion processing.  I was working today on putting in logic that will auto-disable this processing if Sound Filters is present to prevent this type of thing.  I did notice that Sound Filters has more echo, whereas DS focuses more on reverb.  Reverb and echo are similar in some respects, but are actually different things.  Main difference is the time delta between the original sound and the subsequent repeat.  Echoes have longer periods between, whereas reverb it's much shorter.  Try out both to see which one you prefer.

**Comment by slainless** [comment]
Yes, both mods are really essential (thank you for your great work) but to pick between either is a bit hard, honestly. But i think i will follow your advice.
So i will close this issue since this is not really a bug, but actually incompatibility with Sound Filters. Thank you for your help!
