### ISSUE TITLE
Crash at Startup

### ISSUE THREAD

**Issue by NerdCraft** [OreCruncher/DynamicSurroundings#66]
Mod Version: 1.10.2-3.3.4.1
Forge Version: 12.18.3.2272
Crash: https://pastebin.com/qUnta4F2

This just happened one time.

**Comment by OreCruncher** [comment]
If I am interpreting the trace correctly the sound manager was loaded before the proxy for my mod was created.  Which is outright strange.

**Comment by OreCruncher** [comment]
Pushed v3.3.5.0 BETA version that has a fix for this.
