### ISSUE TITLE
[1.16.5] No sound and occasional crash

### ISSUE THREAD

**Issue by ocram9** [OreCruncher/DynamicSurroundings#660]
**Mod Version:**
DynamicSurroundings-1.16.4-4.0.3.6

**Forge Version:**
36.0.10

**Link to client log:**
https://gist.github.com/ocram9/84061eac149df445ebf558c580aa4df1

**Link to crash log:**
https://gist.github.com/ocram9/813218b36dabcb7527243898b3473177

**Description:**

After the update to java 15 and forge 36.0.10 there are no dynamic surroundings sounds and the game crashes on occasion. Nohting else changed besides the fact this mod updated to a new java version. It was working fine before.

**Comment by OreCruncher** [comment]
What type of server config do you have?  The log shows it connecting to an integrated server, you losing connection, and then connecting to a vanilla server.

**Comment by ocram9** [comment]
I don't have any experience nor knowledge of Minecraft modding but if I remember and read the log right, it was just me joining and leaving a singleplayer test world to check something and then reconnecting to the server. I will add that after that crash I played for another hour or so without it crashing so I'm not sure if it was a one-off. I still don't have any sound though.

Oh and to answer your question, I'm using a server host called mc-node. It's a vanilla paper 1.16.5 server.

**Comment by OreCruncher** [comment]
So the connect to the local single player world worked, and then you tried connecting to a vanilla server running Paper and the crash happened.  What else is running on the server?

What I think may be happening is that during a normal Forge handshake with a server it generates some events, and those events trigger my mod to initialize.  What I think may be happening is those events are not being sent thus my mod does not initialize and it gets into a not-so-good state.

**Comment by OreCruncher** [comment]
I pushed 4.0.3.7 to CurseForge with a change that should fix this immediate issue of the crash.  I think the "no sound" part is because I do not get the event triggers that I am expecting.  I need to do some digging on this one.

**Comment by ocram9** [comment]
> So the connect to the local single player world worked, and then you tried connecting to a vanilla server running Paper and the crash happened. What else is running on the server?
> 
> What I think may be happening is that during a normal Forge handshake with a server it generates some events, and those events trigger my mod to initialize. What I think may be happening is those events are not being sent thus my mod does not initialize and it gets into a not-so-good state.

Correct, though I could connect to the server, after a few seconds it crashed. It only happened twice so it's going to be difficult to test if the fix worked. No problems so far though. I have also found out that in singleplayer the sounds are working, just not on my server. Might be a paper compat issue?

**Comment by ocram9** [comment]
Actually, I think I know what the problem is. The server doesn't run java 15 I think, that would explain the difference between singleplayer and the server. The downside is is that I can't fix that because I'm not running the java, the host is.

**Comment by OreCruncher** [comment]
OK.  Its related to Paper, not Java.  I made a tweak to optimize processing during server connect, and apparently when connecting to a Paper server it doesn't work.  It does work with a Forge server.  I am going to be making another change to deoptimize until I can figure out a better way to handle.

**Comment by OreCruncher** [comment]
Pushed 4.0.3.8 to CurseForge.
