### ISSUE TITLE
[1.12.2] Game crush while modlaoding

### ISSUE THREAD

**Issue by NePlo** [OreCruncher/DynamicSurroundings#661]
**Mod Version: 3.6.2.1**

**Forge Version: 14.23.5.2854**

**Link to client log:**
Debug log
https://pastebin.com/9Z2CwnrE
Launcher log
https://pastebin.com/uQg7S2J4

**Link to crash log:**
https://pastebin.com/pnWdss8T

**Description:**
I cant lauch any version of it, with any version of oreLib, mixin, forge and optifine. I've never used this mod before. 
I saw recommandations like "Set "Enable Client Chunk Caching" to false in the dsurround.cfg." and adding z- but nothing helped.
(Sorry for my bad English by the way, still learning it)

**Comment by OreCruncher** [comment]
Try updating Vanilla Fix to the latest.  This has the feel of a Mixin issue.

**Comment by NePlo** [comment]
Oh, thank you so much, it actually helped! You're the best!
