### ISSUE TITLE
[1.16.5] World Startup Crash

### ISSUE THREAD

**Issue by XoeSara** [OreCruncher/DynamicSurroundings#663]
**Mod Version:**
1.16.5

**Forge Version:**
36.0.10

**Link to client log:**
https://pastebin.com/WsJD5EtQ

**Link to crash log:**
https://pastebin.com/Njh1Lrcw

**Description:**

First time I've used the mod. Crashes on world startup with or without other mods. Launching from CurseForge Client.

**Client Error Text:**

The game crashed whilst unexpected error
Error: java.lang.UnsupportedClassVersionError: org/openjdk/nashorn/api/scripting/NashornScriptEngineFactory has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
Exit Code: -1

**Comment by OreCruncher** [comment]
Update to 4.0.3.7.  Had to put in a workaround for a Forge issue.
