### ISSUE TITLE
[1.16.4] Time of day shows in F3 debug screen even when gamerule reducedDebugInfo is enabled

### ISSUE THREAD

**Issue by AeiouEnigma** [OreCruncher/DynamicSurroundings#666]
**Mod Version:**

DynamicSurroundings-1.16.4-4.0.3.8

**Forge Version:**

1.16.5-36.0.7

**Description:**

Showing the time of day in the F3 debug screen is a helpful feature, but it completely removes all utility from the clock item. In particular, when gamerule reducedDebugInfo is enabled, this information should not be made available to the player in this way. Please consider either somehow making this feature dependent on the reducedDebugInfo gamerule being disabled or otherwise adding a config flag to disable this information in F3.

**Comment by OreCruncher** [comment]
Thanks for reminding me.  Since I condensed 3 mods into one I had planned on changing this.

**Comment by OreCruncher** [comment]
Pushed 4.0.3.9 to CurseForge.
