### ISSUE TITLE
[1.16.4]Can't change WaterRipples style?

### ISSUE THREAD

**Issue by EarlyProject** [OreCruncher/DynamicSurroundings#668]
**Mod Version:**

DynamicSurroundings-1.16.4-4.0.3.8

**Forge Version:**

1.16.4-35.1.37

**Description:**

I can't change WaterRipples style or How can I change its style?
default：pixel_ripples
It cannot be configured.
Please consider adding WateRrippleStyle config option or change its default in the next release.

**Comment by OreCruncher** [comment]
Actually this is a bug.  You should be able to configure it.  Somehow it was not on my punch list.

**Comment by OreCruncher** [comment]
Pushed 4.0.3.9 to CurseForge.
