### ISSUE TITLE
Game crashes on the last 3 versions for 1.12.2

### ISSUE THREAD

**Issue by AzCreep** [OreCruncher/DynamicSurroundings#669]
**Mod Version:**

3.6.2.1 / 3.6.2.0 / 3.6.1.0 

ONLY works on 3.6.0.2

The version that is installed in your pack.

3.6.0.2

**Forge Version:**

14.23.5.2854

The actual Forge version - "latest" does not count.

**Link to client log:**

Even of there is a crash log, the client log can provide the necessary context for why the exception occured.  You can use a service like [pastebin](https://pastebin.com) or [hastebin](https://hastebin.com) to upload the log, and paste the link here.  The log file is called latest.txt and can be found in your logs folder.

**Link to crash log:**

https://pastebin.com/XqzNbr2i

**Description:**

Description of the problem.  In the case of crashes, it is good to know things like the following:

* Did you just add the mod to a pack? No i had it long time before but it started crashing when i started updating
* Did it just start crashing, or has it always crashed? Never crashed before
* Did you update any other mods in your pack and it started crashing?  This includes Forge. No right now i updated all the mods on my mod pack and if i use the version 3.6.0.2 the mod pack loads fine
* If updating multiple mods did you update one by one or all at once?  To help narrow the problem down adding one by one is helpful. Answer: Well at first i did all at once but now i gained some patient and i updated 1 by 1 and i came to a conclusion that dynamic surroundings was the main source for all the crashes.
* Is the modpack you are using available online somewhere?  If the crash is due to mod interaction having the pack available makes things much easier.  It is much harder to work these types of issues with a private kitchen sink pack containing 250 mods.
* Ahm...no my mod pack was made by me threw several youtube vids

**Comment by OreCruncher** [comment]
Make sure all your mods are updated.  For example, VanillaFix is behind.  I point that one out specifically because this looks like a Mixin conflict.

**Comment by AzCreep** [comment]
well that's another issue sir when i use vanilla fix latest version my game doesn't launch at all like i press launch and nothing happens the client closes but ye...nothing shows up

**Comment by AzCreep** [comment]
This is what happens without the vanilla fix mod

https://pastebin.com/UFAkAjbx

**Comment by OreCruncher** [comment]
Did you install MixinBoostrap?

**Comment by AzCreep** [comment]
i didn't cause i didn't seem to find a 1.12.2 version of it

**Comment by OreCruncher** [comment]
Install the latest.  It works with 1.12.2

**Comment by AzCreep** [comment]
insta crash on start up error code: 0

**Comment by AzCreep** [comment]
Oh found a solution for the problem i used this mod 
https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility/files

works now with the latest version of dynamic sourrundings and vanilla fix 150 thanks for the help anyway ^^

**Comment by OreCruncher** [comment]
That would have been the next step if MixinBootstrap didn't work.
