### ISSUE TITLE
Suggestion: Footfalls volume

### ISSUE THREAD

**Issue by Galindorf** [OreCruncher/DynamicSurroundings#67]
*Mod Version:* 
1.11.2-3.3.3.0

*Forge Version:*
13.20.0.2255

*Link to crash log (if applicable):*

*Description:*
It would be really great if there was a way to adjust the volume of the footfalls in general, instead of tracking down every single sound file of a footstep on various materials. If there is a way to do that, I would love to know! I enjoy wandering around in the wilderness and listening to the amazing soundscape you've created, but the footsteps get to be a bit much after a while. (especially in the forest). 

I think this has been my absolute favorite enhancement on Minecraft, hands down.

**Comment by OreCruncher** [comment]
Footstep Sound Scale Factor.  Default is 0.35 - make it a smaller number to reduce footstep volume.

**Comment by Galindorf** [comment]
Ah THANK you. I was looking in the "Mod Config" menu, not the actual Config file.

**Comment by OreCruncher** [comment]
Actually it is in the menu under "Sound Options" from the main DS config page.  The entry is called "Footsteps Sound Factor".

**Comment by OreCruncher** [comment]
Pushed v3.3.5.0 that has the V keyboard shortcut for adjusting master volume scale
