### ISSUE TITLE
Biome Fog can not be disabled

### ISSUE THREAD

**Issue by Vazkii** [OreCruncher/DynamicSurroundings#672]
**Mod Version:** 1.16.4-4.0.3.8

**Forge Version:** 35.1.37

**Description:**

Disabling Biome Fog has no effect. The nether wastes biome still has a yellow brimstone fog. Removing dsurround returns the red fog. 

Logs and config: https://gist.github.com/Vazkii/eaabed0dff1c3da5f4c506cdedd87f0c

**Comment by OreCruncher** [comment]
This is interesting.  DS does not, by default, have any fog coloration for nether biomes.  I loaded up a simple 1.16.5 world without DS and see the red fog for nether wastes.  I add DS, and the red fog is still there.  Not sure why the sky is being tinted atm.  Do you have a mod list so I can load up and see if there is an interaction?

(There is a bug with coloration where if biome fog is disabled it still reports the fog color to MC if DS has a definition.  Need to fix that.)

**Comment by Vazkii** [comment]
Unfortunately, the modpack I'm using currently has some unreleased mods. If you want access to it, feel free to give me a poke on discord at https://discord.gg/vazkii

I'm doing some more tests to see if I can find the culprit myself. Here's what I'm seeing, with a default ds config:
![2021-02-09_07 36 00](https://user-images.githubusercontent.com/1794735/107330526-9498ef00-6aa9-11eb-9dbf-a97da2cc7500.png)

**Comment by Vazkii** [comment]
Further testing - the minimal configuration that causes this to happen requires Environmental, an unreleased mod to be in the pack. I'll poke this over at their side.

**Comment by OreCruncher** [comment]
Ah, OK.  Based on that PR I know what happened.  Because it was tagged wasteland it got the yellow fog tint from DS.  Though DS fog effects are disabled for the Nether, the bug I mentioned in the above would still cause the color to be reported to MC whenever the biome fog was queried.  With the fix I am making this should not happen.

**Comment by Vazkii** [comment]
That's what I figured, yeah - this was the only relevant reference to
NETHER_WASTES in environmental I could find.
