### ISSUE TITLE
Is this mod compatible with OptiFine?

### ISSUE THREAD

**Issue by SlamminSalmon** [OreCruncher/DynamicSurroundings#674]
I cannot get this mod to work with any of my OptiFine launchers. Do I make the mod run by dragging it into the behavior slots in the world creator, or do I have to create a separate launcher?

**Comment by OreCruncher** [comment]
What specific version of the mod are you using?  Also, what Java version?  As for working with OptiFine I am using it with the DW20 1.6.0 pack without errors.

**Comment by SlamminSalmon** [comment]
> What specific version of the mod are you using? Also, what Java version? As for working with OptiFine I am using it with the DW20 1.6.0 pack without errors.

I have tried running these combinations, only being able to get OptiFine working:

1.) OptiFine HD U G6 1.16.5 ---- DynamicSurroundings 1.16.4-4.0.3.9 ---- Java1.8.0
2.) OptiFine HD U G6 1.16.4 ---- DynamicSurroundings 1.16.4-4.0.3.4 ---- Java 1.8.0

I have tried to make this work by installing OptiFine into my minecraft launcher as an installation, and then dragging the DynamicSurroundings mod into my behavior file while creating a world. I am doing it this way because I cannot seem to make DynamicSurroundings into a Minecraft installation on my launcher. OptiFine is working for me no problem, but I can't get this mod into my game. This question is probably kinda dumb but I'm pretty inept when it comes to technology, so my apologies in advance

**Comment by SlamminSalmon** [comment]
> What specific version of the mod are you using? Also, what Java version? As for working with OptiFine I am using it with the DW20 1.6.0 pack without errors.

Also, if it is helpful information, I have managed to get OptiFine and DynamicSurroundings to work simultaneously on "RLCraft" with CurseForge. I did this by dragging the OptiFine for 1.12.2 into my RLCraft mods folder, but I can't seem to find a "mods" folder for any other minecraft version and I also cannot find this mod on the CurseForge applicaton

**Comment by OreCruncher** [comment]
Did you install Forge?

**Comment by SlamminSalmon** [comment]
I did. It says it's version 0.167.2.4

I used it to successfully create an installation of "RLCraft 1.12.2" on my minecraft launcher. When I search for "DynamicSurroundings" or "OptiFine" it does not show up on there, so I had to find java files for OptiFine on the OptiFine.net website, and I am getting my DynamicSurroundings mods from this website

Actually, hold on. What I have installed is called "CurseForge" by overwolf. I also see a way to install "Minecraft Forge" from this link: https://files.minecraftforge.net/ 

Is this the forge you're referring to?

**Comment by SlamminSalmon** [comment]
> Did you install Forge?

Hey, I figured it out. I had "CurseForge" installed and not "Forge". Feel stupid lol. Thanks for the help, and also, just wanted to say that this mod you've made is by far my favorite minecraft mod. Awesome work!

**Comment by OreCruncher** [comment]
Glad you figured it out.  OptiFine is unique in that it can work as a Forge mod, as well as with Vanilla.
