### ISSUE TITLE
Crashing in 1.12.2 with Version 3.6.2.1 of DS

### ISSUE THREAD

**Issue by helixxger** [OreCruncher/DynamicSurroundings#675]
DynamicSurroundings-1.12.2-3.6.2.1

FORGE: forge-1.12.2-14.23.5.2816 **AND** forge-1.12.2-14.23.5.2854 - I tried both

Link to crash log:

https://pastebin.com/yxVkQM11

AND

https://pastebin.com/czRyk5sw

I played Minecraft 1.12.2 with Dynamic Surroundings Version 3.6.1.0 and Forge 14.23.5.2854

Everything worked fine.

Then I updated to DS 3.6.2.1 and the game started crashing - I also tried to use Forge 2816, but it didn't helped.

I also use LiteLoader.

Is this problem known?

**Comment by OreCruncher** [comment]
Did you install MixinBootstrap?  If so, add this mod as well: https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility

**Comment by helixxger** [comment]
> Did you install MixinBootstrap? If so, add this mod as well: https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility

So, I installed the mod but I still get a Crash - look here: https://pastebin.com/bK1XNs4C

I'm using DS 3.6.2.1 and Forge 2854

**Comment by OreCruncher** [comment]
Did you install both MixinBootstrap AND mixin compat?

**Comment by mporter012** [comment]
I've been getting this same problem lately with all versions of Dynamic Surroundings. Very sad because it is one of my must have mods...

**Comment by helixxger** [comment]
> Did you install both MixinBootstrap AND mixin compat?

But MixinBootstrap is only available for 1.15.2 and 1.16.+, but not for 1.12.2

**Comment by helixxger** [comment]
> Did you install both MixinBootstrap AND mixin compat?

So now I installed both, but I still get a crash.

https://pastebin.com/bzq3WVSw

**Comment by OreCruncher** [comment]
Post a link to your debug.log.  It's possible that something happened earlier which prevented the mixin being applied.

**Comment by helixxger** [comment]
> Post a link to your debug.log. It's possible that something happened earlier which prevented the mixin being applied.

where do I find it?

**Comment by Timofey511** [comment]
The mod is incompatible with the forge LiteLoader version, can you update the mod from the game version 1.12.2? Version 3.6.2.1 does not work in forge LiteLoader, Version 3.6.2.0 works
