### ISSUE TITLE
Light Level HUD Display Crashes Game

### ISSUE THREAD

**Issue by coryjreid** [OreCruncher/DynamicSurroundings#679]
**Mod Version:**

DynamicSurroundings-1.16.4-4.0.3.9

**Forge Version:**

forge-35.1.36

**Link to client log:**

https://pastebin.com/GBpDB5pX

**Link to crash log:**

https://pastebin.com/upwYESX8

**Description:**

Attempting to enable the light level display will occasionally result in it not displaying at all. In a particular spot in our base, having it on and walking by a specific location will cause the game to crash.

We've been using this mod since we spun up this server. It's always crashed, occasionally in various areas (but now we have a reproducible location).

The pack being used is maintained by me, and is located at https://www.curseforge.com/minecraft/modpacks/logicraft_. However CurseForge is slow to publish updates, so we stopped updating the pack on CurseForge and I distribute the pack from my server directly to my friends.

**Comment by coryjreid** [comment]
Wanted to report we upgraded to 1.16.4-4.0.3.10 and now the light level HUD is no longer togglable at all. The option to configure the keybind is totally removed from settings as well. Not sure if this was intentional so wanted to report as such. Thanks!

**Comment by OreCruncher** [comment]
Yes, intentional.  These HUDs were added for debugging purposes.  I may activate in the future - needs polishing.  If you want to enable set "Debug Flag Mask" to 3 under the Dynamic Surroundings config section, or dsurround.toml file.

**Comment by coryjreid** [comment]
Alrighty, thanks! A semi-related question: are there any plans to bring Dynamic Surroundings: HUDs to 1.16+? I presume that's where that feature would end up in the end.

**Comment by OreCruncher** [comment]
I haven't decided.  The Light Level HUD that is buried in the 1.16.4 version is the one from HUDs.  Chunk fencing is a short cut to the built in chunk fence debug feature of Minecraft.  I am not sure about implementing the compass or the Seasonal Clock from Serene Seasons.  If anything I would put in item frame support for it.
