### ISSUE TITLE
Aurora is opaque/grey when using SEUS and other shaders

### ISSUE THREAD

**Issue by Konlii** [OreCruncher/DynamicSurroundings#68]
Mod Version: 1.11.2-3.3.4.1

Forge Version: 1.11.2-forge1.11.2-13.20.0.2228

Description:
Running SEUS-v11.0 shaderpack using OptiFine_1.11.2_HD_U_B7, aurora bands are grey and opaque.  Aurora has color and transparency when shaders are disabled.

**Comment by OreCruncher** [comment]
Yep.  Its the shader pack - it wants to own the rendering.  Not all shader/packs do that.  Not a bug.

**Comment by Konlii** [comment]
Do you know a shaderpack that plays well with others?

**Comment by OreCruncher** [comment]
I do not know of any "heavy" shader packs that play well.  The built-in Minecraft shaders work well, but that may not be what you are looking for.

**Comment by Konlii** [comment]
I will look around.  Would you like me to post a follow-up comment here if I find one that is compatible?

**Comment by OreCruncher** [comment]
Yes, please do.

**Comment by Konlii** [comment]
Unfortunately, what SEUS provides is actually the best compatibility with your aurora out of the dozen shaderpacks I tested.

**Comment by birdspider** [comment]
I tried a few and liked [kuda-shaders](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293662-kuda-shaders-v6-5-24-last-update-february-4th-2017) - all the others gave me broken skies. But I'm not sure if I've seen an Aurora - gray or otherwise.

**Comment by Konlii** [comment]
In my testing, anything based on Chocapic13's Shaders seemed to break completely on trying to render auroras.

**Comment by Hypsellis** [comment]
Same with BSL shader too.

**Comment by OreCruncher** [comment]
Yep.  Most if not all advanced shader packs will have this problem.  It's a common issue and a lot of mods have similar problems.

**Comment by vpontin** [comment]
Sildurs Shaders render aurora nice too

**Comment by OreCruncher** [comment]
Pushed v3.4.9.3 with changes.
