### ISSUE TITLE
Issue with the newest version

### ISSUE THREAD

**Issue by Matt577** [OreCruncher/DynamicSurroundings#680]
**Mod Version:**

4.0.3.10

**Forge Version:**

35.1.37

**Link to Debug log:**

[debug.log](https://github.com/OreCruncher/DynamicSurroundings/files/6013971/debug.log)

**Description:**
All sounds controlled by the mod are muted, i have begun to use the previous version 1.16.4-4.0.3.9 as it still works for me but would like to update. 
This also is a single player world

**Comment by OreCruncher** [comment]
Looks like this log is for 4.0.3.9.  I need the one for 4.0.3.10.

**Comment by Matt577** [comment]
sorry my bad, i ran the game once again with the 4.0.3.10
[debug.log](https://github.com/OreCruncher/DynamicSurroundings/files/6014102/debug.log)

**Comment by OreCruncher** [comment]
OK - its what I thought.  Apparently the sequence of events during startup are not consistent.  I will have to do more tweaks.

**Comment by OreCruncher** [comment]
Can you load up this JAR to see if it works?  If not I will need the debug.log.  Thanks!  https://github.com/OreCruncher/DynamicSurroundings2/releases/tag/1.16.4-4.0.3.11a

**Comment by Matt577** [comment]
i ran it and with no luck, here is the log
[debug.log](https://github.com/OreCruncher/DynamicSurroundings/files/6014267/debug.log)

**Comment by OreCruncher** [comment]
Strange - for some reason my mod is not getting the world load event.

**Comment by OreCruncher** [comment]
OK - can you redownload the JAR and try it again?  I eliminated the dependency on world load.

**Comment by Matt577** [comment]
OH, everything is is working, thanks for this I really didn't want lose this mod

**Comment by OreCruncher** [comment]
Nice.  Glad it is working.

**Comment by emanuele246gi** [comment]
@OreCruncher This doesn't work even with the newest version :/

**Comment by emanuele246gi** [comment]
I had to downgrade it to the previous version
