### ISSUE TITLE
Bad bug, crashing after some time + possibly slow loading

### ISSUE THREAD

**Issue by ShootToKillSTK** [OreCruncher/DynamicSurroundings#684]
Dynamic Version >   1.16.4-4.0.3.11

Forge 36.0.35

**Link to client log:** Could be not useful log, this is after it loaded proper I think

https://gist.github.com/ShootToKillSTK/45cf5a10cfe643b5c54c1e9e400539b1

**Link to crash log:** 
https://gist.github.com/ShootToKillSTK/d3b925c54a215903e1a11f37d4e877b8

Crash log above is I believe after trying to load the already once crashed world, where I could then finally see some things named 'dynamic' going on and guessed to take out your mod, then loaded and it worked.

**Description:**

Modpack would be slow to load and I think it was much faster and never showed the 'not responding'. Which it has for a while, was not really sure if that is normal since it is heavily modded, 100 ish mods. (I didn't pay a whole lot of attention to its loading but I'm quite sure it was much better)
- After loading world and flying for about a minute and half, maybe 3-4 times it would crash the world. Before I tried loading the same world finally after editing config and crashing, then removing Dynamic surroundings and loading it, and it worked now.

* Did you just add the mod to a pack? No
* Did it just start crashing, or has it always crashed?
^^ I don't think so, but it could of been, it happens after little bit of time but my time was spent minimally on worlds bc modpack testing. Just was recording for video showcasing biomes and flying about then it'd randomly crash. Thought it was other things so I tried that, like 'Improved Mobs' mod something with my configuring

* Did you update any other mods in your pack and it started crashing?  
^^Didn't update forge, mostly editing configs but not dynamics for a long while. Some mods were updated as came out but I'm not sure how long this has been a problem.

* Is the modpack you are using available online somewhere?  If the crash is due to mod interaction having the pack available makes things much easier.  It is much harder to work these types of issues with a private kitchen sink pack containing 250 mods.
- Its my own modpack in development, close to release so I thought, was recording a overview video or trying to for the pack

**Comment by ShootToKillSTK** [comment]
Was using shaders, idk if that would effect anything, I don't think so though?

**Comment by ShootToKillSTK** [comment]
I just found that I had 2 versions of the same mod installed by accident, the 'Dungeons arise mod', not sure if that could be also a cause idk just letting know

**Comment by OreCruncher** [comment]
This does not appear to be related to Dynamic Surroundings.  There is defiantly something strange going on.  The crash log looks like you had a "backup world" prompt, and when told to proceed it eventually failed because it could not find the class net/minecraft/nbt/NBTDynamicOps$NBTRecordBuilder.  I am not familiar with that class.  Did you attach the right crashlog?

**Comment by ShootToKillSTK** [comment]
Ya it's still been crashing now randomly and I've no idea really why, I'm not very good at deciphering errors.

If you want to look here's everything after a crash(Crash, log and debug), without DynamicSurroundings even installed, seems to be related to Guard villager and or villages.

-I can log back into the world after reloading but if I go to the same spot it crashes again with basically the same crash log

https://gist.github.com/ShootToKillSTK/71952be6510f3f3a78da8d06dd16dbf3

**Comment by ShootToKillSTK** [comment]
Found issue to be guard villagers latest update, they draw loot tables to equip armor and it was being incompatible with sneakymagic mod we believe, thanks for your time though and sorry to bother with something unrelated to Dynamics D;
