### ISSUE TITLE
Thunderstorm sounds whenever a player teleports from somewhere and the weather isn't even raining/thunder

### ISSUE THREAD

**Issue by koderian** [OreCruncher/DynamicSurroundings#686]
**Mod Version:**

DynamicSurroundings-1.16.4-4.0.3.12.jar

**Forge Version:**

36.0.43

**Link to crash log:**
There are no crashlogs because nothing has crashed yet. 

**Description:**

Sometimes, when people playing my modpack will hear thunderstorm sounds even when the weather is perfectly clear (seems to occur most often after teleporting somewhere with a Waystone. We are on a multiplayer server) 
* Did you just add the mod to a pack?
* 	No, Dynamic Surroundings has been in my pack for a while
* Did it just start crashing, or has it always crashed?
* 	Nothing is crashing
* Did you update any other mods in your pack and it started crashing?  This includes Forge.
* N/A
* Is the modpack you are using available online somewhere?  If the crash is due to mod interaction having the pack available makes things much easier.  It is much harder to work these types of issues with a private kitchen sink pack containing 250 mods.
 My modpack is publicly available on CurseForge: https://www.modpackindex.com/modpack/27583/wildhalla
 https://www.curseforge.com/minecraft/modpacks/wildhalla

The only other mods I have that alter/add sounds to the game are Charmonium Reforged but the problem has been occurring before that mod was added.

**Comment by OreCruncher** [comment]
That would be weird - DS for 1.16.4 does not generate that sound.  In the past I know that some mods did trigger that sound when teleporting.

**Comment by koderian** [comment]
Oh, now that I think of it. It might be AmbientSounds. Sorry for the trouble

**Comment by OreCruncher** [comment]
No worries :)

**Comment by OreCruncher** [comment]
@koderian BTW, you have MixinBootstrap in the pack.  You shouldn't need it with the Forge version you have.  Forge has Mixin as part of the runtime environment.

**Comment by koderian** [comment]
Will having it installed cause any issues? One mod said `Reccomended: MixinBootstrap`

**Comment by koderian** [comment]
@OreCruncher

**Comment by OreCruncher** [comment]
The Forge version you have (36.0.42) is packaged with Mixin already.  It handles loading and initializing the Mixin subsystem.  As such you do not need MixinBootstrap.  You needed it for earlier versions of Forge for 1.16.4 as well as 1.16.3 and earlier.
