### ISSUE TITLE
Lag more lag. Then crashes. 

### ISSUE THREAD

**Issue by TheRanker** [OreCruncher/DynamicSurroundings#689]
**Mod Version:**
DynamicSurroundings-1.16.4-4.0.3.12.jar  The version that is installed in your pack.

**Forge Version:**
Forge 36.0.46
The actual Forge version - "latest" does not count.

**Link to client log:**
I can link a client log but it's just full of sound processor lagging until I freeze and have to force close 

**Link to crash log:**
No crash    force close by user cause of error and just a gray frozen screen on Mc. 

**Description:**
Whenever I adjust the volume controls with ctrl +v. Or with the individual sounds.   Also when I. World after an hour or more sound processor spits out error. 
[03:51:54] [SoundControl Sound Processor/WARN] [SoundControl/SoundFXProcessor]: SoundControl Sound Processor is lagging; behind 554 msecs   << Dynamic Surrondings.

 I use specialized audio drivers for my Dre beats sound processor. 

* Did you just add the mod to a pack? No
* Did it just start crashing, or has it always crashed? Always
* Did you update any other mods in your pack and it started crashing?  This includes Forge. Yes
* If updating multiple mods did you update one by one or all at once?  Valhelsia 3 3.1.9 to 3.2a
* Is the modpack you are using available online somewhere?  Valhelsia 3

I can gather more info and replicate the freeze anytime I want by opening ctrl v. And adjusting and waiting 1-5 seconds

**Comment by OreCruncher** [comment]
That statement is more for me to understand what is going on.  It's the "lag" that would cause the emission of that statement.  Please link the crash log.

**Comment by OreCruncher** [comment]
@TheRanker Try this updated JAR and let me know if there is a difference. I changed how the handshake works when connecting to a server. https://github.com/OreCruncher/DynamicSurroundings2/releases/tag/1.16.4-4.0.4.1

**Comment by TheRanker** [comment]
> @TheRanker Try this updated JAR and let me know if there is a difference. I changed how the handshake works when connecting to a server. https://github.com/OreCruncher/DynamicSurroundings2/releases/tag/1.16.4-4.0.4.1

this has fixed all issues with dynamic surroundings. tyvm!!!!!!!! had to uninstall . which also avoided the bug that stumped kubejs for weeks lol

**Comment by OreCruncher** [comment]
Yeah - it looks like the the handshake process changed somewhere along the line in Forge which caused a null reference exception in my code.  And that exception is what was causing a lot of issues for some reason.  Going to close as resolved.  Thanks!
