### ISSUE TITLE
Amazing Problem/Bug

### ISSUE THREAD

**Issue by kenijey** [OreCruncher/DynamicSurroundings#69]
DynamicSurroundings-1.11.2-3.3.5.0.jar, forge 2282. NO any sounds until i change any resource pack. Even no click button sounds. It happened after the latest version.
Thanks!

**Comment by OreCruncher** [comment]
When you minimize the window Dynamic Surroundings will mute the sound.  You can disable this by setting "Mute when Background" to false.

As for the resource pack thing that is strange.  Can you post a link to your client log when the problem happens?

**Comment by kenijey** [comment]
oh okay, that's nice.  And ah, when i install dynamic surroundings mod into my modpack, and when the game starts there is no any sound. No even main menu click sounds. But if i change any resource pack (i use 7 resource packs in my modpack) then all sound system comes back. And it happened after the latest version of dynamic surroundings, i was using second latest version(updated at 7 april). 
And here is the logs:
[fml-client-latest.txt](https://github.com/OreCruncher/DynamicSurroundings/files/923585/fml-client-latest.txt)
[latest.txt](https://github.com/OreCruncher/DynamicSurroundings/files/923586/latest.txt)
closed game on from main menu when no hear sound

**Comment by kenijey** [comment]
and you can try installing my modpack [here](https://www.technicpack.net/modpack/magenji.968153), it would be perfect if you find the bug via giving it a try.

**Comment by kenijey** [comment]
sorry, you can not try my modpack because i didn't update it to new version, because of this bug :D

**Comment by OreCruncher** [comment]
Does the 3.3.4.1 version of DS work with your pack?

**Comment by kenijey** [comment]
okay let me try.

**Comment by kenijey** [comment]
yes it works.

**Comment by kenijey** [comment]
i was already using that version, then after update this bug happened.

**Comment by OreCruncher** [comment]
I think this is the culprit:
```
[15:30:04] [Client thread/INFO]: [STDERR]: java.lang.RuntimeException: java.nio.charset.MalformedInputException: Input length = 1
[15:30:04] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.MemoryUtil.decodeImpl(MemoryUtil.java:336)
[15:30:04] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.MemoryUtil.decode(MemoryUtil.java:305)
[15:30:04] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.MemoryUtil.decodeUTF8(MemoryUtil.java:294)
[15:30:04] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.openal.ALC10.alcGetString(ALC10.java:157)
[15:30:04] [Client thread/INFO]: [STDERR]: 	at org.blockartistry.mod.DynSurround.client.sound.SoundEngine.configureSound(SoundEngine.java:161)
[15:30:04] [Client thread/INFO]: [STDERR]: 	at org.blockartistry.mod.DynSurround.client.sound.SoundEngine.onSoundSetup(SoundEngine.java:141)
```

Dynamic Surroundings is trying to get the name of your default sound device and apparently LWJGL is having some heartburn over it.  I am going to make a quick patch for this and make a private JAR for you  to test for me if that's all right.

**Comment by kenijey** [comment]
okay, i'm waiting. Thanks!

**Comment by OreCruncher** [comment]
You can find the test jar here: https://github.com/OreCruncher/DynamicSurroundings/releases/tag/v3.3.5.1TEST

**Comment by kenijey** [comment]
trying

**Comment by kenijey** [comment]
btw, you wrote 1.10.2 in release name :)

**Comment by OreCruncher** [comment]
Oops!  I built the wrong version. ;)  Let me make a 1.11.x real quick

**Comment by kenijey** [comment]
oh, then i shouldn't try it? ok waiting.

**Comment by OreCruncher** [comment]
No, it wouldn't work.  There are enough differences between 1.10.2 and 1.11.x to make it break.  Not sure why they decided to change some method names to cause problems.

**Comment by kenijey** [comment]
ok waiting :D

**Comment by OreCruncher** [comment]
Added a 1.11.x to the release entry.

**Comment by kenijey** [comment]
ok downloading and trying

**Comment by kenijey** [comment]
i don't understand github.com upload speed, it gives me 150kb/sec to download any file..

**Comment by kenijey** [comment]
okay it works. thanks! i can use this version as official, right? can i update my modpack finally? :D

**Comment by OreCruncher** [comment]
I will see about making an official release a little later today.  There are some other things I want to look at before I publish a JAR.  It's possible that this would be a final, but can't rule it out.

**Comment by kenijey** [comment]
hmm... okay i can wait, get luck with!

**Comment by OreCruncher** [comment]
@kenijey Posted a v3.3.5.1 version that has this fix.  Let me know how it goes.

**Comment by kenijey** [comment]
yes it works. thanks!
