### ISSUE TITLE
Game Crashing 

### ISSUE THREAD

**Issue by HassaFelipe** [OreCruncher/DynamicSurroundings#691]
**Mod Version:**
1.12.2 3.6.2.1

**Forge Version:**
14.23.5.2855

**Link to client log:**
https://pastebin.com/qGMwDrDE

**Link to crash log:**
https://pastebin.com/LqejcCDn

**Description:**

My game just crash, I don't known if there is any conflicting mod, I tried search for but I found nothing.

* Did you just add the mod to a pack?
Yes
* Did it just start crashing, or has it always crashed?
Always crashed  
* Did you update any other mods in your pack and it started crashing?  This includes Forge.
No, I added this mod to my modpack and he begin to crash.
* If updating multiple mods did you update one by one or all at once?  To help narrow the problem down adding one by one is helpful.
I haven't updated any mods 
* Is the modpack you are using available online somewhere?  If the crash is due to mod interaction having the pack available makes things much easier.  It is much harder to work these types of issues with a private kitchen sink pack containing 250 mods.
No, this is my personal pack, but he has only 57 mods.

**Comment by OreCruncher** [comment]
Do you have MixinBootstrap installed?

**Comment by HassaFelipe** [comment]
> Do you have MixinBootstrap installed?

No , I should ? I don't know what this mod does.
I'm out of time now but soon i'll can do more tests.

**Comment by HassaFelipe** [comment]
> Do you have MixinBootstrap installed?

I installed this, and it worked. Today I read the mod's main page more carefully and saw this guidance.
