### ISSUE TITLE
[Magma Foundation & client] Unable to launch (DS 3.6.2.1)

### ISSUE THREAD

**Issue by HonzaVinCZ** [OreCruncher/DynamicSurroundings#694]
**Mod Version:**
DynamicSurroundings-1.12.2-3.6.2.1 ( Beta )

**Forge&Magma) Version:**
Server: Magma Dev HEAD-1bc8635
Client: forge:1.12.2-14.23.5.2847

**Link to client log:**
Server:
![image](https://user-images.githubusercontent.com/29098779/111089090-93d0fe00-852a-11eb-95a8-d95469709203.png)

Client:
[latest.log](https://github.com/OreCruncher/DynamicSurroundings/files/6137976/latest.log)

**Description:**
So because of some client crashes in use with Animania 2.0+ I was told to use latest beta version of the Dynamic Surroundings ( I was using latest stable ). 
Animania issue link: [https://github.com/capnkirok/animaniamod/issues/508](url)

The problem comes in when I upload the beta version on my server and then launch the server - It immediately crashes as showed above. No more console output. When I remove the beta and upload latest release back again, server launches normally. 
The exactly same problem is on client.

There is propably some compability with Animania, that's why Animania author wants everyone to use DS beta but actually I can't because of that crash.

**Comment by OreCruncher** [comment]
Did you install MixinBootstrap?

**Comment by HonzaVinCZ** [comment]
I was missing MixinBootstrap, I didn't notice there is requirement of MixinBootstrap in beta. Everything works fine now. Thank you.
