### ISSUE TITLE
[1.12.2] Impossible to return to vanilla walking sounds while mod is installed?

### ISSUE THREAD

**Issue by lazarusgreen** [OreCruncher/DynamicSurroundings#695]
**Mod Version:**

3.6.2.1

**Forge Version:**

14.23.5.2844

**Description:**

I am assembling a pack as a personal project and upon installing this mod and playing around with the config I noticed it appears to be impossible to switch back to vanilla walking sfx for blocks. Disabling all the walking sfx introduced by the mod does not bring back vanilla sounds, it only results in complete silence.
I am not sure if this is an oversight or a feature, but regardless I find it rather frustrating, as I intended to use this mod only for the graphics improvements and new ambience, but there seems to be no easy way to return to original walking sounds without creating a resource pack for the mod, which would be a painfully roundabout method.

**Comment by OreCruncher** [comment]
For 1.12 set the footstep volume level to 0.

**Comment by lazarusgreen** [comment]
> For 1.12 set the footstep volume level to 0.

Thank you so much, that seems to have fixed it. Not a very obvious solution, though! I suggest letting people know somewhere they won't miss it.
