### ISSUE TITLE
Playermovement doesnt work anymore (only on Servers)

### ISSUE THREAD

**Issue by Lord-HaHaHa** [OreCruncher/DynamicSurroundings#696]
**Mod Version:**
DynamicSurroundings-1.16.4-4.0.3.12

**Forge Version:**
forge-1.16.5-36.1.0

**Link to client log:**
i dont have a log

**Link to crash log:**
the game dont crash

**Description:**
If i use the Mod on my Forge Server i am not able to move or jump.
if i destroy the block under the player i dont drop aswell.
But i am able to open the Inventory.

in a Singleplayergame i dont have this problem and everything works fine.

**Comment by OreCruncher** [comment]
Is this a modpack that is available online somewhere?  Folks have been reporting these types of issues and I cannot duplicate on my end.

**Comment by Lord-HaHaHa** [comment]
I made my own private on.
But if i only use the mod i still have the problem.
For Testing I used a new Forge Server / Client installation.

**Comment by SerizawaX** [comment]
I am having the exact same problem on my forge server.
client using forge 36.1.0
server using forge 36.0.48
mod version 4.0.3.12

ps it's not an issue with forge version mismatch.

**Comment by Lychelle** [comment]
This seems to happen if you launch the game through a curseforge profile. It works fine with pure Minecraft launcher.

**Comment by Lychelle** [comment]
Reverting the mod back to 4.0.3.11 fixes the problem but I don't like keeping my mods outdated.

Steps to replicate
- Use the curseforge launcher
- Launch the game through a modpack profile that has Dynamic Surroundings 4.0.3.12 installed.
- Join a forge server.
- Until the player is killed, the Player will be stuck in place but able to destroy blocks and open inventory.

**Comment by Lord-HaHaHa** [comment]
I dont use the Curse launcher

**Comment by Lychelle** [comment]
> I dont use the Curse launcher

I am just providing more info on the issue. You should too.
Maybe you should specify the launcher you're using. You did say "I made my own private on." but I don't know if you're talking about a modpack or something else.

**Comment by OreCruncher** [comment]
I use MultiMC for the packs I play.  The interesting thing is that the difference between *.11 and *.12 are pretty minor - basically code that attempts to detect what server is being connected to in order to decide when to initialize.

**Comment by Ordel** [comment]
Hey, took time to trace the same problem on my server back here to this mod. I couldn't really find much but the stuff I did find is listed in this thread, I hope it helps.

https://www.reddit.com/r/feedthebeast/comments/m5ysm9/cant_movestuck_flying_when_i_spawn_in_1165_forge/

If there's any other info or anything that could possibly help you out @OreCruncher feel free to message me over at reddit, have a good one

**Comment by ghost** [comment]
Here is the problem. I have the same. The log is from my client.

https://pastebin.com/k9hL4YJE

**Comment by kalkafox** [comment]
I can confirm having this issue as well while developing a custom modpack for 1.16.5. I have been able to reproduce this with just using Dynamic Surroundings, as shown in the debug.log [here](https://gist.github.com/kalkafox/91366eba7165a57b42cfe2cebd5e17cb). The relevant error connected to this issue can be found on lines [563](https://gist.github.com/kalkafox/91366eba7165a57b42cfe2cebd5e17cb#file-debug-log-L563-L654) to [654](https://gist.github.com/kalkafox/91366eba7165a57b42cfe2cebd5e17cb#file-debug-log-L563-L654), running only the latest version of Dynamic Surroundings, `4.0.3.12`. It should be noted that this, and the server, were both running the latest current version of Forge as of the date of this post: `36.1.1`. This error has also occurred for me on current 1.16.5 stable (`36.1.0`).

One interesting thing to note is that Dynamic Surroundings had been working for me at least until after around `36.0.48`, which could be an indication that a recent update to Forge must have caused this issue to occur. If there are any updates or clues I can gather on my side I will happily post it here.

**Comment by OreCruncher** [comment]
Try this updated JAR and let me know if there is a difference.  I changed how the handshake works when connecting to a server.  https://github.com/OreCruncher/DynamicSurroundings2/releases/tag/1.16.4-4.0.4.1

**Comment by Lychelle** [comment]
> Try this updated JAR and let me know if there is a difference. I changed how the handshake works when connecting to a server. https://github.com/OreCruncher/DynamicSurroundings2/releases/tag/1.16.4-4.0.4.1

Seems to work perfectly on my curseforge modpack and forge server. I am able to move around after connecting now. Thanks

**Comment by ghost** [comment]
Yes on me to. It works now thank you!

**Comment by ediited** [comment]
when will you push the change to curseforge? or can we just ship the updated jar for now?

**Comment by OreCruncher** [comment]
More than likely this is the JAR that will make it to CurseForge.  Depends on the feedback from others that are having similar issues, though with different server types.

**Comment by gjerm** [comment]
Was confirmed in the Discord for KubeJS as well, still on Forge but another data point: https://github.com/KubeJS-Mods/KubeJS/issues/101

**Comment by OreCruncher** [comment]
@Lord-HaHaHa Have you had an opportunity to try out the latest JAR?

**Comment by OreCruncher** [comment]
I believe this issue to be fixed.  If you continue to have an issue feel free to re-open and add additional latest.log information.

**Comment by KKotik** [comment]
Still happeing to me on the latest version. Even if it only client-side installed.
