### ISSUE TITLE
Crash with Retromagitech

### ISSUE THREAD

**Issue by ThexUniverse** [OreCruncher/DynamicSurroundings#697]
**Mod Version:**
  1.12.2-3.6.1.0
**Forge Version:**
  14.23.5.2855
**Link to client log:**
  https://ghostbin.co/paste/gq47
**Link to crash log:**
  https://ghostbin.co/paste/sqzmsw2
**Description:**
  The issue is that my game crashes while playing during daytime near my base which is located in a plains biome typically when I get near the extreme hills biome that's near my base. I am able to play during the night in this area, and in other areas during the day. Hope you can find whats causing it.
* Did you just add the mod to a pack?
  Yes.
* Did it just start crashing, or has it always crashed?
  It just started crashing.
* Did you update any other mods in your pack and it started crashing?  This includes Forge.
  No.
* If updating multiple mods did you update one by one or all at once?  To help narrow the problem down adding one by one is helpful.
  N/A
* Is the modpack you are using available online somewhere?  If the crash is due to mod interaction having the pack available makes things much easier.  It is much harder to work these types of issues with a private kitchen sink pack containing 250 mods.
  Yes. Link: https://www.curseforge.com/minecraft/modpacks/retro-magitek

**Comment by OreCruncher** [comment]
Use the latest DS 1.12.2 BETA, and install MixinBootstrap.

**Comment by ThexUniverse** [comment]
Appears to work fine now with suggested steps, thank you very much, closing this now, have a good one!
