### ISSUE TITLE
Snowy Tundra biome playing wrong biome sounds

### ISSUE THREAD

**Issue by Lychelle** [OreCruncher/DynamicSurroundings#699]
**Mod Version:** DynamicSurroundings-1.16.4-4.0.4.1.jar

**Forge Version:** 36.1.0

**Link to client log:** https://pastebin.com/C7gFPpY2

**Link to crash log:** The game does not crash.

As title says. minecraft:snowy_tundra biome does not play the appropriate biome sound. It sounds like something that would play in the nether.
Video: https://youtu.be/0fXbEn9byoE

Only this mod is installed, using curseforge client.

**Comment by OreCruncher** [comment]
Not able to view the video - it is marked private for some reason.  To be clear no datapacks involved?

EDIT:  I am not able to duplicate with 4.0.4.1 and Forge 36.1.0.

**Comment by Lychelle** [comment]
Video is fixed. you should be able to view it now. You might want to use a headset.

There are no other mods or datapacks involved. I also did the same test without curseforge launcher and still got the same result.
https://youtu.be/vMxzxom90GE

**Comment by OreCruncher** [comment]
Ok- that is the arctic wind sound which is the correct sound for the biome.  Is your volume sliders are 100%?

**Comment by Lychelle** [comment]
Hmm. they are. maybe it was just me but it sounds sinister and bass heavy. I'll mark this closed

**Comment by OreCruncher** [comment]
I have been looking for a decent replacement for the sound for a while but have yet to find one that I could use.  There are elements to the current sound clip that I am not to keen on.
