### ISSUE TITLE
[1.12.2] Unexpected crash before game can boot

### ISSUE THREAD

**Issue by Robonics** [OreCruncher/DynamicSurroundings#704]
Mod Version 3.6.2.1

Forge Version 14.21.1.2443

MixinBootstrap is 1.0.5 (I simply downloaded the latest file as detailed in one of your replies on the mod page)

Unfortunately, I have no client log, the game crashes before the loading window even opens. I recently updated to the beta because of the incompatibility with the latest version of Animania. I downloaded MixinBootstrap (Although the same thing occurs without it installed) and updated forge. Every time I booted the game however it just immediately closed with Error Code 0.

![](https://i.imgur.com/dgwgtFr.png)

Rolling back to the release version will fix the issue, but obviously then there is the incompatibility with Animania.

It's possible I've just made a dumb mistake, but I don't know what it could be. I'm sorry I don't have any more information about the crash.

**Comment by OreCruncher** [comment]
Which Animania version?  If it's the newest ones you will need the BETA version of DS.  If it is prior to Animania 2.0 you will need the current RELEASE version of DS.  Also, you will need to update Forge - DS requires 2779+.

**Comment by Robonics** [comment]
I just miswrote my forge version ( I accidentally clicked on 1.12 when I went to the site to copy it) I am running 1.12.2 - 14.23.5.2854

as for Animania it is version 2.0.3.28, which is the latest release

**Comment by OreCruncher** [comment]
OK.  Along with MixinBootstrap install this mod as well: https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility.

**Comment by Robonics** [comment]
That seems to have fixed the issue. Thanks for the help.
