### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by zeddybear** [OreCruncher/DynamicSurroundings#705]
**Mod Version:**

4.0.4.1

**Forge Version:**

1.16.4 - forge 35.1.37

**Link to client log:**

[latest.log](https://github.com/OreCruncher/DynamicSurroundings/files/6225601/latest.log)

**Link to crash log:**

N/A

**Description:**

The mod is recognized as working in the game, I.E I can see it in the logs as "working properly" and I can access its in-game menus, I can even hear the sound files when I play them in the ctrl + v menu. 

But other than that I get no ambient sounds in biomes, no sound effects when switching tools, and basically all other sound effects are the vanilla versions. (footsteps, no echo in caves, etc.)

It's driving me mad because I refuse to play without Dynamic Surroundings! The game feels so empty without it!

It was actually working fine and then in the middle of my play it suddenly just stopped. Unfortunately don't have the logs from that time because I've since deleted all of Minecraft and reinstalled to try and fix the issue. Didn't work.

I've tried deleting all the configs, completely uninstalling the entire game and reinstalling, looking through logs, looking through the settings. Found nothing amiss. So I'm wondering if its conflicting with another mod somehow?

here's the list of all mods I'm using.

abnormals core
appleskin
aquaculture
artifacts
autoreglib
citadel
cloth
comforts
cooking for blockheads
create
curios
dungeons plus
dynamic surroundings
endergetic
falling tree
gravestone
ice and fire
JEI
mgui
minecolonies
optifine
pams crops
pams food core
pams food extended
pams trees
quark
quark oddities
repurposed structures
structure gel
structurize
tetra
the undergarden
toro health
traverse
valhesia structures
waystones
xaeros minimap
xaeros world map

Heeeeeelppp meeee pllleaassee!

**Comment by OreCruncher** [comment]
Based on the attached log the login process did not complete for the player (i.e. an event for the player joining the world did not fire).  Because of this DS did not fully initialize.  There are a bunch of errors related to accessing remote servers and I am wondering if you are experiencing other issues.

EDIT:  Also make sure your OptiFine is updated to the latest.  Some of the versions had problems in 1.16.4.

**Comment by zeddybear** [comment]
Thank you for your reply! 

There haven't been any other issues that I've noticed, but that isn't saying much since I honestly refused to play more than a minute without DS lol. 

So are you saying optifine might be causing the issue?

EDIT: currently using optifne 1.16.4 HD U G6. I will update to the latest version and see if that fixes it?

**Comment by OreCruncher** [comment]
OptiFine has been known to affect things that you wouldn't expect, like biome generation.  I would update to the latest to rule it out.

**Comment by zeddybear** [comment]
That did the trick! Thank you! And thank you so much for creating such an awesome mod, it completely changes the experience and make a Minecraft world so much more livelier! Honestly can't play without it anymore ^_^
