### ISSUE TITLE
Weird behavior since update to 3.3.5.0 and 3.3.5.1

### ISSUE THREAD

**Issue by Videonauth** [OreCruncher/DynamicSurroundings#71]
*OS:*
`Linux Ubuntu 16.10 - Kernel 4.8.0-48 generic`

*Java Version:*
```
Java 8
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.10.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```

*Minecraft Version:*
`1.11.2`

*Mod Version:*
`>= 3.3.5.0`

*Forge Version:*
`forge1.11.2-13.20.0.2282`

*Optifine Version:*
`OptiFine_1.11.2_HD_U_B7`

*Link to crash log (if applicable):*
[latest_log_01.txt](https://github.com/OreCruncher/DynamicSurroundings/files/923862/latest_log_01.txt)
[latest_log_02.txt](https://github.com/OreCruncher/DynamicSurroundings/files/923863/latest_log_02.txt)
[latest_log_03.txt](https://github.com/OreCruncher/DynamicSurroundings/files/923864/latest_log_03.txt)
Three different latest log versions created while pinpointing which mod causing the weird behavior described below.

*Description:*
After updating to a version above 3.3.5.0 i saw the following weird behaviour of different other mods (i.e. TechReborn, ExtraUtils2, IronChests, Placable Items, Actually Additions). Many blocks simply turned in different directions (seems to be random) but even after replacing said blocks and then reloading the game they loose again their rotation and turn. Up to that a ton of error messages clogging the log file as you can see above. Reverting to Version 3.3.4.1 made all mods behave like they should. Another symptom I saw is that block of said mods only render if you're really close to them (1-4 blocks) and straight aim at them with the cross-hair.

**Comment by OreCruncher** [comment]
I can see how the exception can be triggered in DS.  I will work on a fix for that.  As for the other symptoms you are seeing I am not sure how they relate to this but since it is occuring during a block update event I guess anything would be possible.

**Comment by Videonauth** [comment]
To add to this the 3.3.5.0 version loaded my world fine first time, but after a restart of Minecraft it became messy (i.e. turned blocks). ExtraUtils2 Magmaic Generator even reverted back to being a MachineChassis (crafting block).

**Comment by OreCruncher** [comment]
DS does not modify world state.  It could be something in the client side world rendering that is causing this problem because of the block update handling.  Could you try out [this jar](https://github.com/OreCruncher/DynamicSurroundings/releases/tag/v3.3.5.2TEST) and let me know if it fixes the issues for you.

**Comment by Videonauth** [comment]
First load of my world with this version seemed fine as far I could see. the following logs have been generated which show no errors:
[betterfoliage.log.txt](https://github.com/OreCruncher/DynamicSurroundings/files/923891/betterfoliage.log.txt)
[CustomNPCs-latest.log.txt](https://github.com/OreCruncher/DynamicSurroundings/files/923892/CustomNPCs-latest.log.txt)
[fml-client-latest.log.txt](https://github.com/OreCruncher/DynamicSurroundings/files/923893/fml-client-latest.log.txt)
[fml-junk-earlystartup.log.txt](https://github.com/OreCruncher/DynamicSurroundings/files/923894/fml-junk-earlystartup.log.txt)
[latest.log.txt](https://github.com/OreCruncher/DynamicSurroundings/files/923895/latest.log.txt)
[ruins_log_dim_0.txt](https://github.com/OreCruncher/DynamicSurroundings/files/923896/ruins_log_dim_0.txt)
[ruins_log_dim_1.txt](https://github.com/OreCruncher/DynamicSurroundings/files/923897/ruins_log_dim_1.txt)
[ruins_log_dim_-1.txt](https://github.com/OreCruncher/DynamicSurroundings/files/923898/ruins_log_dim_-1.txt)
[ruins_log_dim_-2.txt](https://github.com/OreCruncher/DynamicSurroundings/files/923899/ruins_log_dim_-2.txt)
[ruins_log_dim_-3.txt](https://github.com/OreCruncher/DynamicSurroundings/files/923900/ruins_log_dim_-3.txt)
[ruins_log_dim_-9999.txt](https://github.com/OreCruncher/DynamicSurroundings/files/923901/ruins_log_dim_-9999.txt)
[ruins_log_dim_-11325.txt](https://github.com/OreCruncher/DynamicSurroundings/files/923902/ruins_log_dim_-11325.txt)

Second load in of the same world seems to be sane as well. Even restarted Minecraft in between. So yes it seems the issue is fixed :)

**Comment by Videonauth** [comment]
Since its not interfering I will stay on this pre-release build until you publish the final version.

**Comment by OreCruncher** [comment]
Sounds good.  I will be posting a new JAR later today when I have more time.

**Comment by Videonauth** [comment]
Thank you for that quick fix.

**Comment by OreCruncher** [comment]
Pushed a v3.3.5.2 version with this fix to CurseForge.
