### ISSUE TITLE
[1.16.4] Crash with Rising Tides mod

### ISSUE THREAD

**Issue by ghost** [OreCruncher/DynamicSurroundings#712]
**Versions:**
Minecraft 1.16.5
Dynamic Surroundings 4.0.4.1
Rising Tides 1.1.0 [(link to CurseForge page)](https://www.curseforge.com/minecraft/mc-mods/risingtides)
Forge 36.1.4
(latest of everything at the time of writing)

**Link to client log:** https://pastebin.com/c36SNMyY

**Link to crash log:** https://pastebin.com/tEB5yQTS

**Description:** Dynamic Surroundings and Rising Tides don't play nice together. I have no other mods installed. The two mods work when on their own, but the game crashes on startup when both are enabled. I don't know which mod is to blame, but the crash log suggests Dynamic Surroundings is the one at fault.

**Comment by OreCruncher** [comment]
Not sure what is up with the development of the mod.  Links to the Github are non-functional.  Took a look in the JAR and the sounds.json file is malformed and could not be parsed.

**Comment by OreCruncher** [comment]
Pushed 4.0.4.2 to CurseForge.
