### ISSUE TITLE
[1.16.4] Better end and Dynamic surroundings 

### ISSUE THREAD

**Issue by Matusz27** [OreCruncher/DynamicSurroundings#713]
**Mod Version:**

DynamicSurroundings-1.16.4-4.0.4.1.jar

**Forge Version:**

36.1.4

**Description:**
The Dynamic surroundings are really incompatible with the soundscape of BetterEnd mod. forcing itself above it.
If it can't be made to be cantabile is there a way of removing End ambiance overrides?

**Comment by OreCruncher** [comment]
Adding tweak to auto disable the end sound if the mod is loaded.

**Comment by OreCruncher** [comment]
Pushed 4.0.4.2 to CurseForge.
