### ISSUE TITLE
No footsteps besides when wearing armor

### ISSUE THREAD

**Issue by WhiteGuyGaming** [OreCruncher/DynamicSurroundings#718]
Mod version: 1.16.4-4.0.4.2

Forge Version: 1.16.5-36.1.13

**Link to client log:**

https://pastebin.com/FZE5vLiH 

**Link to crash log:**

Mod did not crash

**Description:**

Mod was just added, works great except for missing sounds for footsteps when not wearing armor of any kind. I have seen youtube videos of people testing this mod and have heard both armor sounds and, for example, footsteps on grass. In my game, there are no footsteps in grass sounds, or any footstep-related sounds when not wearing armor. Have tried using ctrl + i to adjust the volume but even at 400% is absent.

**Comment by WhiteGuyGaming** [comment]
I forgot to mention something. I was using sound physics mod, I switched to sound filters mod after looking at one of your old posts saying that sounds physics wasn't really supported. Sound filters seem to have fixed the issue, although sound physics support would be awesome too.

**Comment by OreCruncher** [comment]
You dont need either SoundPhysics or Sound Filters.  DS provides that type of sound enhancement out of the box.  Can you link a copy of your mobeffects-client.toml config file?

**Comment by WhiteGuyGaming** [comment]
I ended up disabling sound filters as well, since I did not realize dynamic surroundings also had similar effects, and in most cases, did it better. How would I find that file?

**Comment by OreCruncher** [comment]
It's in the ./minecraft/config/dsurround folder.
