### ISSUE TITLE
[Enhancement] Add build info stating external ToughAsNails.jar dependency.

### ISSUE THREAD

**Issue by Ristovski** [OreCruncher/DynamicSurroundings#72]
It would be good if it was mentioned anywhere that you need a `ToughAsNails.jar` external dependency to build DynamicSurroundings. 
Likewise, it also wouldn't hurt if the empty `lib` folder and modified `gradle.build` (containing `compile fileTree(dir: 'lib', includes: ['*.jar']) `) were pushed to the repo too, as modifying those manually means trouble since it makes the local git working state unclean - preventing a pull.

**Comment by OreCruncher** [comment]
I went ahead and checked the JAR in the libs directory for now w/the appropriate TAN jar.  I have it on my list to clean up API dependencies a bit.  Some work I have to do.

**Comment by OreCruncher** [comment]
Modified build to pull TaN from maven repository.  Should address this nicely.
