### ISSUE TITLE
[1.12.2] Incompability with VanillaFix(1.0.10-99)

### ISSUE THREAD

**Issue by kibibites** [OreCruncher/DynamicSurroundings#721]
**Mod Version:**

Version 3.6.1.0 for 1.12.2

**Forge Version:**

Version 14.23.5.2855

**Link to client log:**

[here](https://paste.ee/p/2N7b2)

**Link to crash log:**
[here](https://paste.dimdev.org/vuzaqexuhe.mccrash)

**Description:**
Mod works without VanillaFix. Crashes with VanillaFix version 1.0.10-99.

**Comment by kibibites** [comment]
in case that the two links expire, I attached them here
[crashlog.txt](https://github.com/OreCruncher/DynamicSurroundings/files/6412459/crashlog.txt)
[clientlog.txt](https://github.com/OreCruncher/DynamicSurroundings/files/6412460/clientlog.txt)

**Comment by OreCruncher** [comment]
Several things:

* Update DS to use the latest BETA (3.6.2.1)
* Update VanillaFix to the latest version
* Install [MixinBootstrap](https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap).  The 1.16.4 version will do.
* You *may* need to install [Mixin Compat](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility).
