### ISSUE TITLE
1.8.9 Crash

### ISSUE THREAD

**Issue by Triliton** [OreCruncher/DynamicSurroundings#73]
*Mod Version:*DynamicSurroundings-1.8.9-2.0.5.6, and all other 1.8.9

*Forge Version:*
1738

*Link to crash log (if applicable):*https://pastebin.com/gT3BBjWZ

*Description:*
Game crashes right after world loads up.

**Comment by OreCruncher** [comment]
Dynamic Surroundings isn't in the call stack of the crash.  Custom Spawner is, however:

`java.lang.NullPointerException: Ticking entity
    at drzhark.customspawner.EventHooks.onLivingDespawn(EventHooks.java:141)`

**Comment by Triliton** [comment]
Strange.

Heres a new pastebin.

https://pastebin.com/ATm7a9ib

Perhaps if i replace custom spawner with another mod?

**Comment by Triliton** [comment]
Removing Custom mob spawner solved the issue. But its not really solved cause i need custom mob spawner. I wil try and look for replacements

**Comment by OreCruncher** [comment]
IIRC Custom Mob Spawner is needed by Mo'Creatures.  Did a search and [found the same issue someone else had](http://www.mocreaturescommunity.org/forum/m/10615820/viewthread/29101922-crash/post/last).  The recommendation was to adjust a setting in the CMS config to see if it addresses.

**Comment by Triliton** [comment]
Yes i know its needed. I tried some settings. Did not work.
Im gonna post this issue on the forum of Dzhark.

I wil let you know if i get a fix for it. Thanks for your advice and help so far.

**Comment by Triliton** [comment]
Issue is resolved. Best solution after talking to ppl on the More creatures forum.
Remove the CMS. Cause mobs wil spawn without it, you just loose the abillity to control what biomes they should spawn in, and offcourse how many.

Now i can enjoy your great mod :)

**Comment by OreCruncher** [comment]
Glad you like the mod.  And thanks for letting me know the results.  I will close and if you have any other problems with DS let me know.
