### ISSUE TITLE
Clock has Compass Hud / No disable option for Clock Hud

### ISSUE THREAD

**Issue by TDarkShadow** [OreCruncher/DynamicSurroundings#74]
*Mod Version:*
1.11.2 - 3.3.6.0
*Forge Version:*
Forge-13.20.0.2282

*Link to crash log (if applicable):*
N/A
*Description:*
While holding the Clock, you get the Compass bar render like with the regular Compass HUD.
I tried changing the rendering style of the Compass HUD and it only happens with the styles 0 to 3.
The Wind Rose style (4 to 6) doesn't render on the Clock.
I have checked this with the previous version aswell (1.11.2-3.3.5.2) and it is only with the current version.

As a side note, I also noticed there isn't an option to disable the Clock HUD separately.
Would it be possible to have a config option for it?

**Comment by OreCruncher** [comment]
Anything in your shield slot?  And there isn't an option to disable the clock separate.  It is tied to the compass.  I could add it though I am curious as to your thinking on it.

**Comment by TDarkShadow** [comment]
Nope, my offhand slot is empty.
Tested with and without a compass and/or clock in my inventory or offhand.
To be sure, I also created a new instance with only Forge and Dynamic Surrounds.
Same results.

And my reason isn't much special, but I would like to disable the Compass HUD and keep having the Clock HUD.
I have a mod (RPG HUD) in my modpack that renders a compass bar to the top of the screen when there is a compass in your inventory.

**Comment by OreCruncher** [comment]
OK.  Found the bug, and added an option.  Will be in the next BETA.

**Comment by TDarkShadow** [comment]
Thank you so much for the great support!
I really like your mod and I hope more users will use it.

**Comment by OreCruncher** [comment]
Pushed v3.3.6.1 BETA that has a fix.
