### ISSUE TITLE
Incompatibility with Animania - 1.12.2

### ISSUE THREAD

**Issue by jonthemoron** [OreCruncher/DynamicSurroundings#743]
**Mod Version:**

1.12.2-3.6.1.0

**Forge Version:**

14.23.5.2855

**Link to client log:**

https://hastebin.com/idikaruxip.yaml (I had to cut out a lot of the startup stuff since the file was too big)

**Link to crash log:**

https://pastebin.com/Rv0CVSa9

**Description:**

Description of the problem.  In the case of crashes, it is good to know things like the following:

* Did you just add the mod to a pack? Yes
* Did it just start crashing, or has it always crashed? Crashes for everyone only in specific areas
* Did you update any other mods in your pack and it started crashing?  This includes Forge. Nope.
* Is the modpack you are using available online somewhere?  Yes, https://www.curseforge.com/minecraft/modpacks/ooga-booga-caveman-evolution

**Comment by OreCruncher** [comment]
If you are using Animania 2.0 you must update to the latest 1.12.2 BETA.

**Comment by shadowbolt79** [comment]
I just received the same crash - and according to curseforge I am using the latest version of everything. Is the latest animania beta only available in their discord or something? Latest versions are not showing as BETA.

**Comment by shadowbolt79** [comment]
Just going to leave this here: Problem seems to be circumvented by turning off animania badges in dsurround config.

**Comment by OreCruncher** [comment]
Pushed 3.6.3 that has all the accumulated changes and mixin updates.
