### ISSUE TITLE
[Suggestion] Dynamic (Clientside) Lights

### ISSUE THREAD

**Issue by WolfieWaffle** [OreCruncher/DynamicSurroundings#75]
First off, I know that Dynamic Lights is already a mod that exists, but it is server side, meaning it prevents mob spawns and is very laggy. Optifine is what I would want, but Optifine does not support custom light levels and items, and often crashes my game with mods installed.

I don't know how clientside Optifine-like dynamic lighting would work (you hold an item and it visually lights up the area around you but not actually in the game) works so it might be far too much work to implement, but I think it would be a very enjoyable feature that would fit well with the theme of the mod (have it disabled by default even if its too different) and would really help with immersion.

**Comment by OreCruncher** [comment]
Dynamic Lights is laggy because of how it does lighting.  It essentially "fools" Minecraft rendering to render a block at some other light level other than what it really is.  It does a lot of table lookups to make it happen.

If I were to do something it would be the OptiFine approach - purely aesthetic and not affect the actual world light values.  I did look at something like this for other effects but hit a wall due to a lack of knowledge on my part.  I haven't given up on it - I just need to do more research.

**Comment by Blue001** [comment]
WolfieWaffle The Dynamic Lights Mod is Client side only and does nothing server side. And it definitely does not prevent mobs from spawning. Not sure where you got that idea from.

Honestly, I feel there is no need to add this function to this mod as it is present in that mod.

**Comment by OreCruncher** [comment]
If I were to do  something with aesthetic lighting it would be via shaders.  And as @Blue001 points out it would need to offer something more - maybe something like colored lighting (dim red glow when holding redstone torch, etc.)

**Comment by WolfieWaffle** [comment]
Dynamic lighting _has_ to be server side though, there is no way it's _that_ laggy without doing actual lighting updates. Optifine has dynamic lights that don't decrease fps to any noticeable degree and are even smoother, but I can't put optifine in a modpack and it has a lot of bugs with other mods that make it impossible to play even so. Colored lights would be cool, and with configuration as well. Like a brightness and optional color hex code or something.

**Comment by OreCruncher** [comment]
Following up on this.  For 1.12.2 there is the [Albedo](https://minecraft.curseforge.com/projects/albedo?gameCategorySlug=mc-mods&projectID=275300) mod which provides lighting support.  DS 1.12.2 will use Albedo to render light effects around fire flies and when the player is holding a torch.  As for colored  torches there is a mod called [Albedo Torches](https://minecraft.curseforge.com/projects/albedo-torches?gameCategorySlug=mc-mods&projectID=283846).
