### ISSUE TITLE
Crash Rendering Animania Mobs

### ISSUE THREAD

**Issue by uwuscutely** [OreCruncher/DynamicSurroundings#756]
**Mod Version:**

3.6.1.0

**Forge Version:**

forge-14.23.5.2855

**Link to client log:** Log was too long for pastebins. File attached
[latest.log](https://github.com/OreCruncher/DynamicSurroundings/files/7026351/latest.log)

Even of there is a crash log, the client log can provide the necessary context for why the exception occured.  You can use a service like [pastebin](https://pastebin.com) or [hastebin](https://hastebin.com) to upload the log, and paste the link here.  The log file is called latest.txt and can be found in your logs folder.

**Link to crash log:** https://bin.bloom.host/raw/ahemesemef

The callstacks in the log will help pinpoint the actors involved in the crash and give a developer a pointer in the code where to start looking at the problem.  You can use a service like [pastebin](https://pastebin.com) or [hastebin](https://hastebin.com) to upload the log, and paste the link here.

**Description:**

Description of the problem.  In the case of crashes, it is good to know things like the following:

* Did you just add the mod to a pack? No
* Did it just start crashing, or has it always crashed? It is inconsistent but it crashes randomly.
* Did you update any other mods in your pack and it started crashing?  This includes Forge. No
* If updating multiple mods did you update one by one or all at once?  To help narrow the problem down adding one by one is helpful.
* Is the modpack you are using available online somewhere?  If the crash is due to mod interaction having the pack available makes things much easier.  It is much harder to work these types of issues with a private kitchen sink pack containing 250 mods.
Yes https://www.curseforge.com/minecraft/modpacks/creatures-of-sonaria

**Comment by OreCruncher** [comment]
There was a change made to Animania that broke DS.  Give this JAR a try and let me know how it goes: https://github.com/OreCruncher/DynamicSurroundings/releases/tag/3.6.3.0BETA

**Comment by OreCruncher** [comment]
I pushed 3.6.3 to CurseForge.  If it holds up I will move from BETA to RELEASE state.
