### ISSUE TITLE
Damage Pop Off Spacing

### ISSUE THREAD

**Issue by sweetsosweet** [OreCruncher/DynamicSurroundings#76]
*Mod Version:* 1.11.2-3.3.6.0
*Forge Version:* 13.20.0.2282
*Link to crash log (if applicable):* N/A
*Description:* 

The damage pop-offs overlap the critical damage text completely, so it's hard to read either. This has been happening for quite a few versions now. I remember they used to be spaced, as in they'd pop-off in different directions/speeds, but now they pop-off together. Here's a little screenshot (it was kind of hard to take):

[http://i.imgur.com/IkGRklp.png](http://i.imgur.com/IkGRklp.png)

**Comment by OreCruncher** [comment]
I noticed that, too.  I made a tweak to make sure the crit power word is a half block above the damage amount.

**Comment by OreCruncher** [comment]
Pushed v3.3.6.1 BETA that has a fix.

**Comment by sweetsosweet** [comment]
Thanks, works great!
