### ISSUE TITLE
Inconpatablity with Baritone

### ISSUE THREAD

**Issue by Shibva** [OreCruncher/DynamicSurroundings#764]
**Mod Version:**
![image](https://user-images.githubusercontent.com/38770780/132247939-46fe5f70-bfde-432d-bf38-7cb771a0696f.png)

**Forge Version:**
1.12.2
The a
![image](https://user-images.githubusercontent.com/38770780/132248127-6b60139e-f249-4a4d-a74b-d0ec38b8325b.png)

**Link to client log:**
please visit 
https://github.com/cabaletta/baritone/issues/2986

**Descritpon**
The game will refuse to start if this mod is present with baritone, testing has found that this issue will persist even if baritone and Dynamic Surroundings are the only mods present

**Comment by OreCruncher** [comment]
Interesting.  Don't think this is DS either.  I am working on a debug build related to mixin, can you give it a try?  https://github.com/OreCruncher/DynamicSurroundings/releases/tag/3.6.3.0BETA

**Comment by OreCruncher** [comment]
I pushed 3.6.3 to CurseForge.  Let me know if it resolves this issue.

**Comment by Shibva** [comment]
I will when I can

**Comment by Shibva** [comment]
~~its still a instant crash, one way to know is if you add this  version of braitone into the test space
~~
NVM, that seemed to fix it, Thanks!

**Comment by OreCruncher** [comment]
Nice!
