### ISSUE TITLE
Dynamic Surroundings 1.12.2 3.6.2.1 crashing immediately after clicking play.

### ISSUE THREAD

**Issue by willcaddy** [OreCruncher/DynamicSurroundings#770]
DynamicSurroundings-1.12.2-3.6.2.1.jar
Minecraft 1.12.2 Forge 14.23.5.2855

Client Log: https://pastebin.com/A0wExHYt
Crash Log: https://pastebin.com/UiGpNq8q

The game fails to start with an  error that says its an "unknown" mod causing the error. But I have found that after you run the game for the first time after updating to Dynamic Surroundings 3.6.2.1, there is a jar file added called _MixinBootstrap-1.1.0.jar and if I remove this mod and run the game it works flawlessly. Is this file required? or maybe a leftover dev file? Thanks :)

**Comment by OreCruncher** [comment]
The Mixin story for 1.12.2 has been painful to say the least.  Starting with Forge 1.16.5 Mixin is "included" so these issues would not happen.  However, we are dealing with 1.12.2 and Forge never looks back.

I just made a oneoff build of Dynamic Surroundings that I think will address the issue.  Just drop in your mod folder.  Also, you shouldn't need Mixinboostrap.  https://github.com/OreCruncher/DynamicSurroundings/releases/tag/3.6.3.0BETA

Let me know if it works for you.

**Comment by YafavKialie** [comment]
I'm still having the same issue even when I remove all of my previous mods to see if its incompatible with anything

**Comment by OreCruncher** [comment]
Did you try the JAR I linked just above?

**Comment by willcaddy** [comment]
Hello OreCruncher :)

My apologies, I replied to the email not realising it was a copy of what's on here..... Sorry! lol But thanks for the reply!

I gave the version you sent a whirl and on first impressions it works great! I'll keep using it and let you know if I run in to any more issues. Am I OK including this in my modpack or shall I wait for you to release it publicly?

Thanks again, and just wanted to say you are doing great work with the mod :)

**Comment by OreCruncher** [comment]
Wait for an official update please.  I will be pushing to CurseForge in a day or so once I am done validating some other things.

**Comment by willcaddy** [comment]
Ok will do pal, thank you for your hard work! :)

**Comment by OreCruncher** [comment]
Pushed 3.6.3 to CurseForge.
