### ISSUE TITLE
Annoying sound I can not find a way to turn off.

### ISSUE THREAD

**Issue by serkas001** [OreCruncher/DynamicSurroundings#79]
*Mod Version:*
DynamicSurroundings-1.11.2-3.3.3.1.jar
*Forge Version:*
forge1.11.2-13.20.0.2228

*Description:*
Can't find a way to disable an annoying sound that's only played near my base. Already found out it is 
the part of biome sounds by turning on the sounds' settings one by one. It sounds like some kind of a bell or something. I've got a little video showing it off. It is driving me completely crazy!
[The video.](https://www.youtube.com/watch?v=hbxKVNZC1dA) The sound can be heard at 0:07 - 0:10 and 0:34 - 0:37, and also 0:43.

**Comment by OreCruncher** [comment]
The video link is broke.  Are you near a village or have a villager farm nearby?

**Comment by serkas001** [comment]
Sorry, completely forgot to make the video public. And yes, I do have a villager that I cured and locked down in a room. It might be it.

**Comment by OreCruncher** [comment]
That is probably the sound, then.  Internally in Minecraft if you have a villager and a valid door configuration you have a Village.

**Comment by OreCruncher** [comment]
@serkas001 Have you had a chance to block the sound?  Also, I would like to know what you find annoying about the sound - too high pitch, too "clinky", etc.  Would it be better if it were lower in tone?

**Comment by OreCruncher** [comment]
@serkas001 I watched the video and yes that is the village anvil sound effect.

**Comment by serkas001** [comment]
Yeah, I did find a way to turn it off, not a big deal. It was annoying for me, first of all, because I could not find the source of the sound and it wasn't obvious at all. And also because I think it is too frequent, like 5-6 times a minute is too much. 
Thanks! Nevertheless I'm loving the mod, it is really great!

**Comment by OreCruncher** [comment]
Glad to hear you are liking the mod.  I am looking to change how the anvil sound gets played and the feedback helps.  I am going to close out this issue for now.  If you have any further issues let me know.  Thanks!
