### ISSUE TITLE
What's up with lightening

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/DynamicSurroundings#8]
Reported that lightening does not occur.  Need to investigate.

**Comment by OreCruncher** [comment]
To have lightening occur there are several things that need to happen:

It has to be raining. There is a timer for this.
It has to be thundering. There is a timer for this, too.
Rain strength has to be > 90.
So the rain and thunder intervals must overlap, and the rain strength has to be > 90. Storms at the upper end of the scale are more rare because the strength of a storm is based on a bell distribution, with 0 and 100 at either end.

With the current releases (and the unofficial port) you can influence this by setting the minimum rain strength in the dimension to 91. This will result in storms being on the strong end, but it will cause lightening when the thunder is active. I should also point out that this puts the rain at more the vanilla intensity (which is always 100).

**Comment by OreCruncher** [comment]
Added a new setting for the dimension that allows a player to set the rain intensity level where thunder can occur.  By default it is set to 50 meaning that rain with an intensity > 50 can have thunder when the thunder time kicks in.

**Comment by Fortist** [comment]
Was this added to any of the updated 1.7 versions?

**Comment by OreCruncher** [comment]
Currently that change has not been backported.  It's on my list of things to look at.  The 1.10.2/1.11.2 versions are drastically different internally so it's not a matter of simply copying code over.

**Comment by OreCruncher** [comment]
I should also add that this particular option was removed in the 1.10.2/1.11.2 versions as well.  Main reason is that the fundamental way of how Dynamic Surroundings interacts with Minecraft RE: rain/thunder changed so that it was not needed.  Lightning behavior should be normal.
