### ISSUE TITLE
Commands available for vanilla server

### ISSUE THREAD

**Issue by Louis-9902** [OreCruncher/DynamicSurroundings#80]
***Mod Version:*** 3.3.7.0

***Forge Version:*** 13.20.0.2284

***Description:*** 
If you use the commands like /ds or /c on a vanilla server (spigot) it can't execute the command, which makes sens, but maybe you can change this so it also works on vanilla servers. Maybe check if the server is modded and the mod is present and if not catch the command before it is send to the server. Should now be relatively easy because of the new [ClientChatEvent](https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/client/event/ClientChatEvent.java)

**Comment by OreCruncher** [comment]
/ds is a server side command.  It affects server side behavior thus is registered with the server command handler.  In only makes sense to Dynamic Surroundings, meaning it can't affect vanilla behavior.  /calc is purely client side and does not require server side to function, and thus is registered with the client side command handler.  So I am not exactly sure what you are asking for.

**Comment by Louis-9902** [comment]
Never mind, it was a problem with the WorldEdit Mod. 
Sorry for that 😃

**Comment by OreCruncher** [comment]
No worries.  I would rather hear about it than not. :)  Let me know if you have further issues.
