### ISSUE TITLE
[1.11.2] Feature Request or Config Help

### ISSUE THREAD

**Issue by cyberpunkbln** [OreCruncher/DynamicSurroundings#81]
DynamicSurroundings-1.11.2-3.3.3.1
forge-1.11.2-13.20.0.2285

Hello,
i only have a little request. A very good mod but i miss the loudness from the vanilla-rain.

How can i have the vanilla-loudness of the Rain? Copy the sound assets over the mod with a little pack, a special config or some else?

Thx

**Comment by OreCruncher** [comment]
I have to say this is a first. :)  Use the Individual Sound Configuration GUI in the configuration settings for the mod.  Locate "dsurround:rain" and set the slider to the right.  See if that does it for you.

**Comment by cyberpunkbln** [comment]
Yes thx i have made this and another Solution, i have made a sounds.json RessourcePack with the old minecraft sounds. Works very good. Thx.
