### ISSUE TITLE
auroras cause shaders to bug

### ISSUE THREAD

**Issue by Hypsellis** [OreCruncher/DynamicSurroundings#82]
When an aurora is around, if a shader is used, whatever the one which is used, it becomes totally crazy and has multiple displaying bugs until the aurora disappear or the player gets enough away of it. Here is the small video example with BSL Shader.
[https://www.youtube.com/watch?v=gF3Tte9T1wg](url)

**Comment by OreCruncher** [comment]
Which version of DS?  Also, auroras don't work well with the advanced shader packs because the packs want to rule the Minecraft world and stomp other rendering.  See [#68].

**Comment by Hypsellis** [comment]
I use the last one, but any of them still causes the same problem.

**Comment by OreCruncher** [comment]
I dont think this is an OptiFine issue.  I use optifine with the internal shaders.  And there are some smaller shader packs that work fine.

**Comment by Hypsellis** [comment]
Yeah but you, optifine devs, and shader devs reject the fault on the others, and in final nothing advance.

**Comment by OreCruncher** [comment]
I cant help to much if a shader stomps on my sky rendering. :)

**Comment by sp614x** [comment]
Are there any errors/warnings in the error log (game output)?

**Comment by OreCruncher** [comment]
In this particular case not sure.  But in my travels with other shaders nothing shows up in the log.  The aurora in DS was at one time rendered during the weather render phase, but has move to a RenderWorldLast event handler in one of the more recent builds.

**Comment by sp614x** [comment]
The Forge WorldProvider can use a custom SkyRenderer for special effects.

**Comment by OreCruncher** [comment]
Right - can only have 1 sky renderer though.  I've been tripping over mods that hook the sky or weather renderer and the auroras won't display, or the reverse - DS wins the race to hook and another mods feature  stops working.  Would be nice if multiple renders could be registered.

**Comment by sp614x** [comment]
A pre/post-render sky events could be enough

**Comment by OreCruncher** [comment]
The question is I have is whether it will address this particular issue.

**Comment by OreCruncher** [comment]
Didn't find any render sky event hooks. :\

**Comment by Hypsellis** [comment]
It still doesn't work. :(

**Comment by OreCruncher** [comment]
OptiFine has no problem with Auroras.  It the shader packs. :)  The underlying rendering code didn't change.  With the most recent release the aurora is positioned at chunk view distance and can't be approached like previous versions.  They stay at that distance in the northerly sky.  Also, the band is larger with the base being at seal level and stretching up into the sky (height based on chunk render view distance).

**Comment by Hypsellis** [comment]
Opitfine causes some displaying issues when an aurora appears.

**Comment by OreCruncher** [comment]
Which version of OF are you running?

**Comment by OreCruncher** [comment]
@Hypsellis I found the problem.  I rearranged the aurora rendering yet again. :)  Fix will be in the next BETA.  Unfortunately it does not address the broader issue of shader pack compatibility (such as SUES).  The aurora still render's gray at a distance because of the shader pack.

**Comment by OreCruncher** [comment]
Pushed a v3.4.3.0 version with the fix for non-shader OptiFine rendering.  Going to use issue [#68] for tracking the generic "gray render" issue w/shader packs.
