### ISSUE TITLE
Crash on entering server

### ISSUE THREAD

**Issue by applepower34** [OreCruncher/DynamicSurroundings#83]
*Mod Version: 3.4.0.0*

*Forge Version:13.20.0.2227*

*Link to crash log (if applicable): https://pastebin.com/471Rx0Cm*

*Description: Joining a server while holding a nether star apparently crashes the game on join.*

**Comment by OreCruncher** [comment]
:( I can shoot the dev that put that stupid ItemStack.EMPTY into 1.11.x Forge.  It causes more problems than it solves.

**Comment by OreCruncher** [comment]
Pushed v.3.4.1.0 version that has a fix.
