### ISSUE TITLE
explosion problem!

### ISSUE THREAD

**Issue by Moondream15** [OreCruncher/DynamicSurroundings#84]
*Mod Version:*
1.10.2
*Forge Version:*
forge1.10.2-12.18.3.2254

*Link to crash log (if applicable):*

*Description:*
Any type of explosion makes a strange effect like this:

![2017-05-06_17 41 44](https://cloud.githubusercontent.com/assets/26523099/25771274/114412ae-3288-11e7-8e9e-353a3f81aafd.png)

**Comment by OreCruncher** [comment]
Yes.  Its the enhanced explosion.  DS adds additional particles for an explosion.  It only occurs when a large explosion occurs on the client.  You can turn it off in the config if you want.

**Comment by Moondream15** [comment]
thanks for the fast rply! Sorry for calling it a bug! my bad ;P

**Comment by OreCruncher** [comment]
No worries.  I would rather handle these then let true bugs get lost. :)
