### ISSUE TITLE
[1.10.2] Auto-restart of sound system freezing game after some amount of time.

### ISSUE THREAD

**Issue by pPkMnh4to8994h** [OreCruncher/DynamicSurroundings#86]
*Mod Version: 3.4.1.0 (this appears on old versions too)

*Forge Version: 12.18.3.2281 (1.10.2)

*Link to crash log: [https://pastebin.com/V6YCgra9](url) (latest.log)
[fml-client-latest.zip](https://github.com/OreCruncher/DynamicSurroundings/files/988895/fml-client-latest.zip) (log is just too large, i didn't find any site, that might load it)

*Description:*
After auto-restart of sound system, lags begin appears, and after some amount of time game just freeze out.
And, if at this moment look in Task Manager, i see "java.exe" consuming a very small amount of RAM (15-30 MB).
So, how i can avoid this?

**Comment by OreCruncher** [comment]
Actually I think the lag is causing the sound system to crash not the other way around.  This is the reason I put it in.  In my experience when the client gets really laggy the streaming music thread in PaulsCode (the underlying sound system/library) loses it's mind and crashes without recovery.  BTW, I have seen this happen back on 1.7.10 as well as 1.10.2 - haven't seen it yet on 1.11.x.

Questions on the log:
+ This is the extent of the log?
+ The beetroot1/beetroot2 in the log - saw that somewhere and don't recall. :\  Google doesn't show anything worthwhile.

**Comment by pPkMnh4to8994h** [comment]
1. it's full logs.
2. i just look in the log and saw this, omg. i don't know, what causing it.

**Comment by OreCruncher** [comment]
Ok.  For the next BETA I will be adding the following:

+ Option to disable auto-restart of the sound system
+ A crash check will occur every 30 seconds or so
+ If crashed chat messages will be given regarding what it will do (restart, or tell you to manually restart the client) as well as the current FPS of the client

I do think, though, that the lag problem is something other than Dynamic Surroundings.  Unfortunately I can't tell which mod(s) from the log.

**Comment by pPkMnh4to8994h** [comment]
i tried play without dynamic surroundings - it freezed too after 2 hours. after 1 hour of gaming i turned on music in minetunes, that's maybe why it crashed. so, you right - problem in soundsystem.
and in fml-client-latest i've seen that:
`[22:43:03] [Server thread/DEBUG] [FML/]: The world 3ce46ed9 (Mega Leftract 5 44 h) may have leaked: seen 125 times.`

**Comment by OreCruncher** [comment]
Pushed a v3.4.2.0 version that has an option to turn off the auto-restart.  As mentioned I do not think it will affect your situation.  Wish I could be of more help.
