### ISSUE TITLE
ActualMusic compatibility issue

### ISSUE THREAD

**Issue by Synngularity** [OreCruncher/DynamicSurroundings#91]
*Mod Version:*
DynamicSurroundings-1.10.2-3.4.3.0.jar

*Forge Version:*
forge-1.10.2-12.18.3.2297-installer.jar

*Link to crash log (if applicable):*
N/A

*Description:*
[Actual Music](https://minecraft.curseforge.com/projects/actualmusic) replaces Minecraft's in-game music with a configurable soundtrack that plays .mp3s triggered by all sorts of events (entering a new biome, etc.). It pairs up so well with Dynamic Surroundings! But, something in DS 3.4.3 results in the playing of Minecraft's default music even though Actual Music disables it (both play simultaneously). DS 3.4.2 does not do this and gets along just fine with Actual Music. Can DS be fixed so it doesn't re-enable Minecraft's default music when another mod such as Actual Music takes it over?

Thanks for all the fantastic work on Dynamic Surroundings, OreCruncher!

**Comment by OreCruncher** [comment]
DS 3.4.3 replaces the MusicTicker so DS can mute background music when battle music is playing.  Perhaps that is what is going on.  I will have to take a loo at Actual Music source code to see what's up.

**Comment by OreCruncher** [comment]
Confirmed - fighting over the music ticker.  I will see what I can do for compat.

**Comment by OreCruncher** [comment]
OK.  Best I can do ATM is NOT hook the MusicTicker if Actual Music is installed.  Worse thing that would happen is that if DS Battle Music is enabled the music will play over Actual Music.  Battle Music is off by default so "out of the box" a player will not experience a problem.

**Comment by OreCruncher** [comment]
Pushed a v3.4.4.0 that has a fix for this.
