### ISSUE TITLE
Galacticraft Uncompatibility

### ISSUE THREAD

**Issue by kenijey** [OreCruncher/DynamicSurroundings#92]
*Mod Version:*
DynamicSurroundings-1.11.2-3.4.4.0
*Forge Version:*
2299
*Link to crash log (if applicable):*
no crash
*Description:*
DS kills the custom sky feature that made for planets from Galacticraft. here some pictures:(first one with DS)
![2017-05-20_20 30 30](https://cloud.githubusercontent.com/assets/24831406/26278049/a41e0a6c-3d9b-11e7-8cc8-9131342f333c.png)
![2017-05-20_20 33 14](https://cloud.githubusercontent.com/assets/24831406/26278050/a440ccf0-3d9b-11e7-913d-41f6402ba7cc.png)
suggestion: can you add a dimension filter for them? thanks
to help: how can i disable this feature in DS configs? thanks

**Comment by OreCruncher** [comment]
Did this just start or was it always this way?

**Comment by kenijey** [comment]
it was always like this.

**Comment by OreCruncher** [comment]
To be clear it was happening with older versions of Dynamic Surroundings as well?  The reason I am asking is that I made some changes to aurora rendering and trying to establish whether those changes are causing this.

**Comment by kenijey** [comment]
it was happening in older versions (many of them, i think.)

**Comment by kenijey** [comment]
i can try if u suggest a special older version.

**Comment by OreCruncher** [comment]
Try with 3.3.8.0.

**Comment by kenijey** [comment]
ok.

**Comment by OreCruncher** [comment]
If it still happens with the older version, go back to 3.4.4.0 and turn off both biome and desert fog in the config and see if it disappears.

**Comment by kenijey** [comment]
it happens on 3.3.8.0
trying 3.4.4.0 thing

**Comment by kenijey** [comment]
yeah, it worked. (biome-desert fog disabled)

**Comment by kenijey** [comment]
then... i should disable them in my modpack right? or you will develop a fix for it :D ?

**Comment by OreCruncher** [comment]
If you turn those two settings off it turns off ALL fog processing.  You wouldn't get biome fog, like in swamps.  I am going to put in some settings to allow for dimension wide enable/disable of fog processing, and by default for dimensions other than Overworld it will be off (thus addressing this problem).

**Comment by kenijey** [comment]
i love that. thanks.

**Comment by kenijey** [comment]
hey ah, when will you release the new update?

**Comment by OreCruncher** [comment]
May be a couple days.  In the process of testing some things.

**Comment by kenijey** [comment]
today maybe? :D

**Comment by OreCruncher** [comment]
That's my plan.

**Comment by OreCruncher** [comment]
Pushed a v3.4.5.0 version that has a fix for this.

**Comment by kenijey** [comment]
thanks!
