### ISSUE TITLE
[Enhancements] Slush bucket of things for me to keep track of

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/DynamicSurroundings#93]
Slush bucket of ideas and things I want to check into.  May not make it into the mod.

- [-] Sapling tree grow sound (https://clyp.it/p2z2pahr) (Can't do - event is server side)
- [x] Aurora as a shader (v3.4.8.5)
- [x] Red Tail Hawk spot sound (v3.4.5.5)
- [ ] Custom sound slider categories for DS sounds (maybe)
- [ ] Particle effects for footsteps (like little flames/sparks when walking on netherrack) (maybe)
- [ ] Option to use Vanilla rain sound rather than Dynamic Surroundings sound
- [x] Quickset method for turning off Nether weather effects
- [ ] Galacticraft ExtraPlanets support
- [ ] RealWorld support
- [ ] Review aurora alpha calcs to see if it can be tied into the solar angle.  Goal is to fade in/out with sunrise/sunset, and to appear/disappear quickly under certain circumstances.
- [x] Looping spot sounds (waterfalls)

**Comment by darthvader45** [comment]
These sounds are quite amazing, especially the sapling grow sound.  Cannot wait to hear them in Minecraft.
