### ISSUE TITLE
Weird finite water feature in Dynamic Surroundings.

### ISSUE THREAD

**Issue by darthvader45** [OreCruncher/DynamicSurroundings#94]
@OreCruncher 
*Mod Version:* Beta 3.4.5.0 for Minecraft 1.10.2

*Forge Version:* 12.18.3.2185

*Description:* Main feature of Finite Water Control mod, finite water, is in this mod.  Do not have Finite Water Control mod installed.

**Comment by darthvader45** [comment]
It basically means that I cannot have infinite water sources.  Can get quite annoying.

**Comment by OreCruncher** [comment]
Never heard of that mod.  What is the effect you are getting?

**Comment by darthvader45** [comment]
No infinite water sources.  Basically all water is finite.

**Comment by OreCruncher** [comment]
Not sure how - DS does nothing with world gen or affect block states in world.  Take a look at your client log to see if there are any errors being reported.

**Comment by darthvader45** [comment]
Never mind, FFC is a mod maintained by Flaxbeard, and somehow his Gradle setup put that mod's classes in the jar files of Immersive Petroleum, another mod he made.

**Comment by OreCruncher** [comment]
lol.  No worries.  Glad it was sorted.
