### ISSUE TITLE
Potion HUD shows up empty when breaking a block

### ISSUE THREAD

**Issue by phit** [OreCruncher/DynamicSurroundings#95]
*Mod Version:*
DynamicSurroundings-1.11.2-3.4.4.0
TConstruct-1.11.2-2.7.0.12

*Forge Version:*
13.20.0.2298

*Description:*
Breaking a block shows an empty Potion HUD briefly when using a Tinkers Construct tool.
Video: https://phit.link/s/2017-05-23_23-49-02.mp4

**Comment by OreCruncher** [comment]
Hmm....Tinkers must be putting something strange into the potion effect list.  Any buffs on the tool?

**Comment by phit** [comment]
Seems like certain tool parts/traits are necessary, everything else doesn't matter. So for example a full Iron or Cobalt pickaxe works to test this. So that would be the Momentum and Magnetic trait, you can find all of themwhich are indeed implemented as a potion effects [here](https://github.com/SlimeKnights/TinkersConstruct/search?utf8=%E2%9C%93&q=new+TinkerPotion&type=).

Would it be possible to blacklist them from showing in the Potion HUD?

**Comment by OreCruncher** [comment]
I need to see what is going on.  There is a property on a potion effect that says whether to display or not.  It could be lying to the code.

**Comment by phit** [comment]
Looks like they aren't, `shouldRenderInvText` is set to false.
Note the last false [here](https://github.com/SlimeKnights/TinkersConstruct/blob/25a03943276b131e4dcbc74907c887491de343a8/src/main/java/slimeknights/tconstruct/tools/traits/TraitInsatiable.java#L13), which goes [here](
https://github.com/SlimeKnights/TinkersConstruct/blob/1.11.2/src/main/java/slimeknights/tconstruct/library/potion/TinkerPotion.java#L12-L27).

**Comment by OreCruncher** [comment]
That's what the code says.  However, in my debugger it gets down into Potion::shouldRenderHUD(PotionEffect) and returns true. :)  In this case the class is TraitMagnetic$MagneticPotion.

**Comment by OreCruncher** [comment]
Came up with additional checks that should prevent this from happening.  I am still at a lost as to why it's not being reported up properly.  It's like something decided the method could not be overridden.

**Comment by OreCruncher** [comment]
Pushed v3.4.5.1 that has the additional potion hud checks.
