### ISSUE TITLE
[Suggestion][Minor] Customizable Client-Open Sound

### ISSUE THREAD

**Issue by ElvenChaos** [OreCruncher/DynamicSurroundings#96]
*Mod Version:* 3.4.5.0

*Forge Version:* 1.10.2 - 2297

*Description:* I would love to be able to customize the sound that is played at client open and world load to a specific sound, or at least be able to choose the exp. orb sound similar to "Ding!" over the egg pop sound. Unless I missed it, there is currently no way to make these changes in the current configs.

EDIT: Options should be present to allow sound to play on world load as well.

**Comment by OreCruncher** [comment]
No, there isn't a way to configure it.  I was thinking of adding config options so that it could be customized by a pack author.  These changes would be in the next major release train.

**Comment by ElvenChaos** [comment]
Thank you! :D It will be nice to have this when it happens.

**Comment by OreCruncher** [comment]
Pushed v3.4.5.5 that has options to customize startup sound.
