### ISSUE TITLE
Heartbeat sound never stops after death with TAN health reduction

### ISSUE THREAD

**Issue by Efimero** [OreCruncher/DynamicSurroundings#98]
*Mod Version:* 3.3.3.1

*Forge Version:* 2228

*Description:* After taking deadly damage and respawning, the heartbeat sound keeps playing even though the health is maxed (at 10 instead of 20 for Tough as Nails reduction) and no amount of taking damage and healing will stop it, only logging off.
I even set my heartbeat threshold to 6, but it keeps playing. The heartbeat... it never stops... ;w;

**Comment by OreCruncher** [comment]
Try the latest BETA.

**Comment by Efimero** [comment]
ok, yes, it seems fixed in the beta <3

**Comment by OreCruncher** [comment]
Yep.  I fixed a bug where this could happen. :)  Going to mark the issue closed.  If you find anything else let me know.
